### ISSUE TITLE
"background-js" causes issues with events

### ISSUE THREAD

**Issue by OliverJAsh** [guardian/frontend#10005]
I noticed there was a bug whereby the tabs in containers (i.e. most popular on /video) no longer work. This appears to be due to "background-js" (introduced by #9918), because tabs work when this switch is disabled.

Upon closer inspection, I noticed that the `modules:popular:loaded` event is being emitted before we attach any event handlers in `bootstraps/common`.

I believe this is because `background` does not queue itself, which boils down to `upgradeMostPopularToGeo` in `bootstraps/facia` being called before `showTabs` in `bootstraps/common`. I can explain better in person, with diagrams and stuff :smile: 

I've disabled the switch for the time being.

/cc @johnduffell

**Comment by OliverJAsh** [comment]
I wonder if this event issue was causing any other bugs we didn't hear about.

**Comment by ScottPainterGNM** [comment]
@johnduffell are you going to revisit this or safe to close off for now?

**Comment by johnduffell** [comment]
I'll make a decision at some point soon, it's in my mind

**Comment by ScottPainterGNM** [comment]
and heart?

Thanks anyway, just having a cleanse of the issues list
