### ISSUE TITLE
Prerolls do not play when using multiple players in one article

### ISSUE THREAD

**Issue by Calanthe** [guardian/frontend#10034]
On pages with multiple players (like here http://www.theguardian.com/us-news/2015/jul/21/sandra-bland-dashcam-video-arrest-released?adtest=12 - if after few refreshes preroll does not work at all, ask ad-opts to turn the test campaign again) after playing the first video, an ad starts to play as well in the background and it seems to be attached to the second video. It is impossible to turn it off.
![screen shot 2015-08-05 at 12 27 09](https://cloud.githubusercontent.com/assets/489567/9084678/df079c42-3b6d-11e5-8a2c-015425121188.png)
(notice the 'You may skip this advert (...)' button which does not work)

After investigation I noticed that there is something wrong with the `player` object sent by the video.js.ima (https://github.com/guardian/frontend/blob/157d7230cd1dbc1837ddb8d3c2b55de50862234d/static/src/javascripts/components/videojs-ima/videojs.ima.js#L188). After clicking and running the first video on page, the returned player has always wrong scope - second video tag instead of the first one (https://github.com/guardian/frontend/blob/5fa70b691c239b63fdafae290d0cbf2080460f8b/static/src/javascripts/projects/common/modules/video/events.js#L91). The state diagram from https://github.com/videojs/videojs-contrib-ads might be useful as well.

There is a similar (I think) issue raised in the videojs-ima repository - https://github.com/googleads/videojs-ima/issues/89. This needed to be discussed in more details with someone from the sustain team.

There is also a console error while playing the ad:
![screen shot 2015-08-05 at 12 30 23](https://cloud.githubusercontent.com/assets/489567/9084664/c619c03e-3b6d-11e5-8d83-1d9c19984865.png)
But even after fixing it, the same problem occurs.

**Comment by Calanthe** [comment]
This is definitely google ima's issue https://github.com/googleads/videojs-ima/issues/116. Let's wait for their fix.

**Comment by JonNorman** [comment]
Looks the guy who went to fix this ended up not needing it and so abandoned it. Fortunately this was picked up by someone else, so when [this PR](https://github.com/googleads/videojs-ima/pull/215/files) gets accepted, we can have another look.

**Comment by ScottPainterGNM** [comment]
Looks like this is now in [this PR](https://github.com/googleads/videojs-ima/pull/255) instead, fingers crossed!

**Comment by ScottPainterGNM** [comment]
That PR was now accepted so hopefully this might work

**Comment by SiAdcock** [comment]
I guess this is now fixed. Feel free to reopen if you notice any continued strangeness!
