### ISSUE TITLE
Quote block is partially hidden behind image

### ISSUE THREAD

**Issue by Calanthe** [guardian/frontend#10041]
Quote block is partially hidden behind image in this article: http://www.theguardian.com/books/2015/jul/20/are-we-alone-sf-science-fiction-speculative-jeff-vandermeer

<img width="850" alt="screen shot 2015-08-05 at 15 16 32" src="https://cloud.githubusercontent.com/assets/489567/9087916/67608222-3b85-11e5-8fac-627ae6e6c139.png">

**Comment by jennysivapalan** [comment]
Closing as this doesn't follow our design guidelines. Will follow up with Central prod about this specific article to see if the layout can be updated.
