### ISSUE TITLE
special instructions not appearing in cryptics

### ISSUE THREAD

**Issue by desbo** [guardian/frontend#10096]

**Comment by ScottPainterGNM** [comment]
Example - http://www.theguardian.com/crosswords/prize/26645

The R2 version has a special instruction above the grid which is pertinent to solving the crossword clues, currently missing from the Beta.

![screen shot 2015-08-11 at 15 12 31](https://cloud.githubusercontent.com/assets/11922253/9199657/8b72679c-403b-11e5-97b5-babb69287823.png)

![screen shot 2015-08-11 at 15 12 53](https://cloud.githubusercontent.com/assets/11922253/9199660/8dd44e60-403b-11e5-8282-6cfc74ae5f64.png)
