### ISSUE TITLE
croswords: Backspace not working on Android Tablets

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#10136]
When I have entered letters into a clue and want to backspace to clear them the tablet doesn't recognise the backspace key.

**Comment by ScottPainterGNM** [comment]
Fine on Nexus 7 though, super weird

**Comment by ScottPainterGNM** [comment]
Reports from users on other Android tablets that this is also not working

**Comment by OliverJAsh** [comment]
This is a bug in older versions of Chrome I believe: https://github.com/codemirror/CodeMirror/issues/2234#issuecomment-59791445

**Comment by OliverJAsh** [comment]
Updated link: https://code.google.com/p/chromium/issues/detail?id=184812
