### ISSUE TITLE
Crossword grid broken on Windows Phone 8

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#10140]
![wp_ss_20150813_0002](https://cloud.githubusercontent.com/assets/11922253/9248242/07215372-41b2-11e5-90fa-21f3380803fc.jpg)

A decent amount of users have these and they are rolling out Win10 phones so should be fixed.

**Comment by OliverJAsh** [comment]
Apparently 0.5% of our crossword traffic use IE mobile. Is this worth fixing?

It could just be because the SVG isn't honouring the width/height.

**Comment by ScottPainterGNM** [comment]
Possibly not but we could run into issues with the Win 10 phone in the future when its released? Depends on how much work it is to fix?

**Comment by OliverJAsh** [comment]
You probably know better than I do about Windows phones :tongue:

**Comment by ScottPainterGNM** [comment]
@desbo I think you were looking into this one as grid was now displaying but too small? Did it get sorted?

**Comment by desbo** [comment]
No, other things were more important

**Comment by gtrufitt** [comment]
Fix is now on prod.
