### ISSUE TITLE
Sticky nav breaks nav on mobile

### ISSUE THREAD

**Issue by OliverJAsh** [guardian/frontend#10148]
You can no longer scroll when you expand the nav.

**Comment by kaelig** [comment]
I just noticed this issue.

FYI I'm running iOS9.

**Comment by Calanthe** [comment]
Sticky nav is now turned off on mobile and I don't know when and if it will be turned on again. Should we close this issue and raise another one if necessary in the future?

**Comment by ScottPainterGNM** [comment]
Having discussed with @stephanfowler - as we will reimplement mobile before it coming back on, this bug is closed for now but needs to be considered for when we revisit this.
