### ISSUE TITLE
Fullscreen icon broken

### ISSUE THREAD

**Issue by Pearson82** [guardian/frontend#10169]
On article with wide image...

![screen shot 2015-08-17 at 11 50 48](https://cloud.githubusercontent.com/assets/3416696/9303490/4055c728-44d6-11e5-9915-47a67538eefb.png)

http://www.theguardian.com/cities/2015/aug/17/no-cafe-pub-doctor-londons-most-isolated-suburb-barking-riverside

**Comment by NataliaLKB** [comment]
Hello!

I will look into this now.

Best,
Natalia

**Comment by NataliaLKB** [comment]
@Pearson82 This should now be fixed. Thanks :).


![image](https://cloud.githubusercontent.com/assets/8774970/9307074/fac182c4-44f3-11e5-849d-b699309d0443.png)
