### ISSUE TITLE
[sticky] broken search with adblocker enabled

### ISSUE THREAD

**Issue by desbo** [guardian/frontend#10197]
1. visit a page with ad blocking on
2. enter a search term, click a result
3. with the search menu open, scroll

the list of search results doesn't scroll with the page, and the content overlaps the page body if you scroll to the top

![aug 19 2015 15 05](https://cloud.githubusercontent.com/assets/1064734/9358387/a823961a-4683-11e5-91a8-a737d2b27e61.gif)

@Calanthe @uplne 

(found by an ad-blocking friend :stuck_out_tongue_winking_eye:)

**Comment by paperboyo** [comment]
Duplicate/related: https://github.com/guardian/frontend/issues/10030

**Comment by desbo** [comment]
ah! my bad, yours covers it.
