### ISSUE TITLE
Sidebar sticky ad jumping

### ISSUE THREAD

**Issue by davidrapson** [guardian/frontend#10190]
I've been seeing some odd jumping behaviour recently with sticky sidebar adverts where the ad overlays other content in the sidebar.

<img width="393" alt="screen shot 2015-08-18 at 16 31 56" src="https://cloud.githubusercontent.com/assets/123386/9334471/ef6667ea-45c6-11e5-9430-0161152528fc.png">

![ad-jump mov](https://cloud.githubusercontent.com/assets/123386/9334561/55db20b0-45c7-11e5-855c-8c32e1ab039b.gif)

**Comment by Calanthe** [comment]
Can you give the example link, please?

**Comment by davidrapson** [comment]
Of course, I was seeing it on this page: http://www.theguardian.com/environment/2015/aug/18/1000-sq-miles-england-opened-up-fracking-new-round-licences

(It's obviously not a major issue, just a little jarring)

**Comment by paperboyo** [comment]
Hmm... at above URL, the whole page jumps left-right for me when reloading/loading (much faster in Chrome, but more noticeably in FF on 10.9.4). Can you see it too? Is that what the issue is describing, or should I open a new one?

**Comment by paperboyo** [comment]
The jump happens because there is a flash of a second slider on the right hand side (just left to the normal slider).

**Comment by Calanthe** [comment]
This has been fixed.
