### ISSUE TITLE
crosswords: word separators appearing where they shouldn't

### ISSUE THREAD

**Issue by desbo** [guardian/frontend#10200]
e.g. 15 down on http://www.theguardian.com/crosswords/cryptic/26650
the clue is `4, 5` so it should only have one spacer (after the 4th character) but it shows two (after the 4th and 7th)

@rich-nguyen

**Comment by ScottPainterGNM** [comment]
@OliverJAsh Pretty sure the fix you made to ensure separators are split out correctly with grouped clues has fixed this, can you close off this issue if you agree?

**Comment by OliverJAsh** [comment]
Yup it has!
