### ISSUE TITLE
Unused Images?

### ISSUE THREAD

**Issue by NataliaLKB** [guardian/frontend#10241]
As some of you may know, to reduce the size of the css we are loading we are inlining as much of our svgs as possible. While going through the images I have found quite a lot that are only being used in the css associated with a class (example: `.i-clock-yellow`), but I can't find where that class is used anywhere in the code.

Before I submit a PR deleting these images. Please let me know if there is anything here that I should keep. 

**Here is the list of some of the images** (located in [`static/src/images/global/`](https://github.com/guardian/frontend/tree/master/static/src/images/global))

- camera-black-large.svg 
- camera-white-large.svg 
- camera-yellow-large.svg
- left-arrow.svg
- play-icon-gold.svg
- play-icon-grey.svg
- right-arrow.svg
- share-android--white.svg
- share-android.svg

**Deleted:**
- clock-light-blue
- clock-light-pink
- clock-white
- clock-yellow
- quote-black.svg
- profile-small.svg
- quote-light-pink.svg
- quote-orange.svg
- rss-black.svg
- rss-white.svg
- quote-white.svg
- location-gps.svg
- video-icon-black.svg
- video-icon-grey.svg
- video-icon-white.svg
- comment-white.svg
- comment-yellow.svg
- comment-light-blue.svg
- comment-light-pink.svg
- quote-grey.svg
- quote-mask.svg
- download-black.svg
- download-white.svg
- arrow-black-right.svg 
- arrow-blue-right.svg
- arrow-grey-large.svg
- arrow-left-grey.svg 
- arrow-light-blue-right.svg
- arrow-up-grey.svg
- arrow-up-white.svg
- share-facebook--blue-dark.svg
- share-gplus--red.svg
- share-gplus--red-dark.svg
- share-link.svg
- share-linkedin--blue.svg
- share-linkedin--blue-dark.svg
- share-pinterest--red-dark.svg
- share-twitter--blue-dark.svg
- download-black.svg
- download-white.svg
- reply-white.svg
- plus-blue.svg

cc @sndrs @stephanfowler

**Comment by NataliaLKB** [comment]
Starting tomorrow morning I will start experimenting with deleting some of the images (only a few at a time). Will be asking people who know the site a bit better to take a second look and make sure these images are definitely not being used...

**Comment by Jholder112233** [comment]
Deleted some here: https://github.com/guardian/frontend/pull/10677

**Comment by NataliaLKB** [comment]
Closing down this issue for now, as most of these icons have been addressed.
