### ISSUE TITLE
Sidebar ad forever sticky

### ISSUE THREAD

**Issue by davidrapson** [guardian/frontend#10252]
![sidebar-forever-sticky mov](https://cloud.githubusercontent.com/assets/123386/9445155/87b00a46-4a82-11e5-8a45-05e9b3e40303.gif)

This is happening on all articles in my testing so far…

But first seen at http://www.theguardian.com/football/2015/aug/24/the-fiver-anyone-but-chelsea

**Comment by Calanthe** [comment]
This is now fixed.

**Comment by davidrapson** [comment]
Confirmed. Thanks for sorting it!
