### ISSUE TITLE
Sisyphusian labours in the editorial config tool

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#10278]
So I'm on code trying to make a duplicate of the uk front.
Consistently when I create containers in my front and pressing save the containers are being forgotten and disappear from the face of the earth.

![sisyphus](https://cloud.githubusercontent.com/assets/7239344/9491338/2026bd24-4be6-11e5-9c3d-c349c93e6103.gif)

**Comment by michaelwmcnamara** [comment]
@piuccio  I hear you are looking into this.

**Comment by piuccio** [comment]
yes, I'm on it, I wrote a unit test to reproduce the issue, now working on the cause.
Love your gif :smile: 

Btw works fine if you do it quick
