### ISSUE TITLE
Problems with video tracking when user has adblocker active

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#10281]
We just discovered a major issue with video tracking, which appears to be connected to the problem with the number of pre-roll completes exceeding the number of pre-rolls starting we found a couple of weeks ago.

In a nutshell,
- the tracking issue happens when the user has an adblocker enabled: the player doesn't send any video events to Omniture OR Ophan, except for video request
- the issue doesn't seem to happen if the video is one that expressly prohibits ads from showing beforehand (there's a CAPI flag that tells this to the video player)
- the issue doesn't happen when the user doesn't use an adblocker, BUT sometimes the player sends pre-roll end when no pre-roll has been shown (which probably explains the issue we brought up 2 weeks ago)

As a consequence of that new issue, we could be under-reporting our video traffic by up to 12% (since half our video views are on desktop, and about a quarter of our desktop traffic is adblocked). Talking to the data team, this issue should to be relatively new as they know it wasn't happening a few months ago.

Can somebody look into this issue? I had an initial discussion with Rich who suggested I reach out and/or send to sustain.

**Comment by jbreckmckye** [comment]
We've been doing a lot of work on Adblock detection recently in Commercial; I'm happy to talk about its current state to anyone who's interested.

**Comment by johnduffell** [comment]
I'm pretty sure I fixed this
