### ISSUE TITLE
Short articles don't de-dupe 'save for later' button

### ISSUE THREAD

**Issue by Jholder112233** [guardian/frontend#10309]
The sharing buttons are de-duped on short articles, but the save for later button still shows up.

If I recall, the decision to hide the second set of sharing icons was because it felt odd for both sets to be visible at the same time, so I'm sure the same applies here?

Easy fix in: https://github.com/guardian/frontend/blob/29c6dc4acd92d5530ae9565fda95c46b57c82d5f/common/app/views/fragments/submeta.scala.html

![screen shot 2015-08-28 at 10 26 08](https://cloud.githubusercontent.com/assets/2236852/9543248/54f88a2a-4d6f-11e5-8e82-f94e5fcc6edb.png)

**Comment by NathanielBennett** [comment]
I actually started working on this 11 and a half minutes ago. I good 4 minutes before you raised it. You can OK my PR when i'm done, if you like

**Comment by Jholder112233** [comment]
Great minds think alike @NathanielBennett. Happy to +1 once it's done!

**Comment by Jholder112233** [comment]
Fixed with https://github.com/guardian/frontend/pull/10312
