### ISSUE TITLE
Slideshows on fronts broken

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#10333]
Hello,

Just seen on a Network front (FF 41, Chrome 45 on Win 10).

This may all be changed by https://github.com/guardian/frontend/pull/10325, but it may not be, so here it goes anyway.

Slideshow looks broken: upon visiting the page there is a flash of an image that lasts as long as the page still loads. Then, it’s immediately replaced by another image (no standard transition). That second one stays there for far-too-long-a-time. After that, there is a broken transition. Only after all that slideshow goes back to how it should look in the first place.

GIF worth a thousand words (observe the reload page button):
 
![slideshow_broken](https://cloud.githubusercontent.com/assets/6032869/9593159/270ea186-5043-11e5-9132-f42a1f29d02b.gif)

Regards
Mateusz

**Comment by OliverJAsh** [comment]
Fixed by https://github.com/guardian/frontend/pull/10325

**Comment by paperboyo** [comment]
Seems fixed in https://github.com/guardian/frontend/pull/10325 & https://github.com/guardian/frontend/pull/10341. Still some comments in https://github.com/guardian/frontend/pull/10325 to sort out, I think (not loading all images where slideshow is not active?). Thanks!
