### ISSUE TITLE
crosswords: completed clue in list highlight not distinct

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#10348]
This has been amended already but the distinction between the completed clue and others is not very clear, it did used to be a lighter grey but that caused accessibility issues so another design needed?

**Comment by ScottPainterGNM** [comment]
Is this good to close down now or still need looking at?

**Comment by gtrufitt** [comment]
I still think it's an issue actually, I suggested the crossing about but it was mentioned that this wouldn't work as the clues still need to be read - probably needs a designer to have a gander.

**Comment by ScottPainterGNM** [comment]
@zeftilldeath @Pearson82 Not sure which of you is on loyalty but could we maybe have a quick chat about this issue?

**Comment by Pearson82** [comment]
Can you explain what the problem is? @ScottPainterGNM

**Comment by ScottPainterGNM** [comment]
As we have just discussed, closing the issue and leaving this as is.
