### ISSUE TITLE
crosswords: Check All Button not functioning

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#10351]

**Comment by OliverJAsh** [comment]
Seems to work for me. Are users not noticing they need to click the button twice to confirm?

**Comment by ScottPainterGNM** [comment]
I've asked for some feedback from users to see if we can pinpoint whether they used to confirm button or not

**Comment by ScottPainterGNM** [comment]
First user to respond had actually not clicked confirm, seems to be working here so will close unless anything definitive comes back to suggest it isn't from users.
