### ISSUE TITLE
crosswords: Missing Clue

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#10366]
Same cryptic! http://www.theguardian.com/crosswords/cryptic/26666

Clue 21 across (part of the grouped clue) is missing on NGW, other clues in the same group are displaying correctly

**Comment by ScottPainterGNM** [comment]
Related to #10365

**Comment by OliverJAsh** [comment]
Fixed by https://github.com/guardian/frontend/pull/10372
