### ISSUE TITLE
Showcase videos are showing a blue border

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#10379]
Raised by Mariana from central production.
We have been testing how to showcase videos in the main media in composer.
Here is an example:

https://composer.gutools.co.uk/content/55cb16b6e4b0891b23e59e48

As you can see in the above URL, the video has a blue border around it. I checked and the video on Youtube doesn't seem to have it: 

https://www.youtube.com/watch?v=gTpZFRUdZ3U

However when going in the the Guardian's Youtube Channel the blue border shows up in the thumbnails which may be what is causing it:

![image](https://cloud.githubusercontent.com/assets/7239344/9655945/bdc09db0-522c-11e5-9a3d-fb062cf9b150.png)

**Comment by Jholder112233** [comment]
This is baked into the YouTube embed, definitely not coming from Frontend.

**Comment by johnduffell** [comment]
oh yeah sorry I found that out myself at the time
