### ISSUE TITLE
Image background wrong colour on cards

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#10375]
Hello,

As seen on Opinion front just now:

![opinion tone card](https://cloud.githubusercontent.com/assets/6032869/9640066/773d5f34-51a7-11e5-85c4-626fb9e87fe6.gif)

No that I like all that empty space below image, but that’s another matter entirely...

Regards
Mateusz

**Comment by ScottPainterGNM** [comment]
Which browser did you see this on?

**Comment by paperboyo** [comment]
Any? :laughing: Just now: Opinion front on FF 40.0.3 & CH 44. I presumed it's a CSS issue, so haven't specified browser, sorry.

**Comment by ScottPainterGNM** [comment]
Ah yeah got it now!

**Comment by paperboyo** [comment]
[This is a general observation. I do not expect this to be fixed along the above issue.]

There is a problem with the cards backgrounds that trail images are shown over. See e.g. https://github.com/guardian/frontend/issues/8963. Also slideshow transitions have different "colours" for similar reasons.

**Comment by paperboyo** [comment]
Oh, and the main issue does not affect only the opinion tone:

![backg tone](https://cloud.githubusercontent.com/assets/6032869/9777002/8f814920-5756-11e5-87a0-5bb51ac7fa26.JPG)

**Comment by gtrufitt** [comment]
Hi @paperboyo - Is this fixed?

![colour1](https://cloud.githubusercontent.com/assets/638051/10191560/c7ce7764-676c-11e5-8061-0a9ce4fa9faf.gif)
![colour2](https://cloud.githubusercontent.com/assets/638051/10191561/c9d00014-676c-11e5-9b27-30a3b316a3f9.gif)

**Comment by paperboyo** [comment]
Hi, @gtrufitt!

Main issue looks fixed :-) (haven't noticed the PR with fixes, sorry).

The issue of a background colour spilling over the image on hover still present (noticeable on white in your second GIF).

Closing, though.
