### ISSUE TITLE
crosswords: missing group clue ordering

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#10407]
In R2 for a clue where grouped clues need to be done in a specific order, you see the list of clue numbers on the first clue to make sure the user knows in which order to enter the clues.

Example URL: http://www.theguardian.com/crosswords/cryptic/26666 

For the mega clue on R2 the clue states "2, 10, 23, 21across..."

![image](https://cloud.githubusercontent.com/assets/11922253/9689192/5022ff2c-532c-11e5-8fc7-321fd34d1752.png)

On Beta this is missing and has caused some user complaints

![image](https://cloud.githubusercontent.com/assets/11922253/9689196/5a81d646-532c-11e5-970e-8ed75b94fb71.png)

**Comment by ScottPainterGNM** [comment]
@OliverJAsh FYI

**Comment by NathanielBennett** [comment]
@ScottPainterGNM https://github.com/guardian/frontend/issues/10407
