### ISSUE TITLE
crosswords: double text entry on clues while on Android

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#10428]
When typing clues on Android you pick up double text while typing in a clue cell, need to check iOS but currently only experienced with Android.

Found internally and a user has reported with the image below:

![image](https://cloud.githubusercontent.com/assets/11922253/9733729/a89a6a22-5625-11e5-94ef-1fd6c0bb5c1c.png)

**Comment by ScottPainterGNM** [comment]
@OliverJAsh FYI - as discussed earlier

**Comment by OliverJAsh** [comment]
Did the user report how this happened? Where they typing fast?

On Tue, 8 Sep 2015 at 13:34 Scott Painter <notifications@github.com> wrote:

> @OliverJAsh <https://github.com/OliverJAsh> FYI - as discussed earlier
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/10428#issuecomment-138546722>
> .
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by ScottPainterGNM** [comment]
I've emailed them to ask (and BCC'd you in)

On 8 September 2015 at 14:34, Oliver Joseph Ash <notifications@github.com>
wrote:

> Did the user report how this happened? Where they typing fast?
>
> On Tue, 8 Sep 2015 at 13:34 Scott Painter <notifications@github.com>
> wrote:
>
> > @OliverJAsh <https://github.com/OliverJAsh> FYI - as discussed earlier
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/guardian/frontend/issues/10428#issuecomment-138546722>
> > .
> >
>
> --
>
> ------------------------------
> Visit theguardian.com. On your mobile and tablet, download the Guardian
> iPhone and Android apps theguardian.com/guardianapp and our tablet
> editions
> theguardian.com/editions. Save up to 57% by subscribing to the Guardian
> and Observer - choose the papers you want and get full digital access.
> Visit subscribe.theguardian.com
>
> This e-mail and all attachments are confidential and may also be
> privileged. If you are not the named recipient, please notify the sender
> and delete the e-mail and all attachments immediately. Do not disclose the
> contents to another person. You may not use the information for any
> purpose, or store, or copy, it in any way. Guardian News & Media Limited
> is not liable for any computer viruses or other material transmitted with
> or as part of this e-mail. You should employ virus checking software.
>
> Guardian News & Media Limited is a member of Guardian Media Group plc.
> Registered
> Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.
> Registered
> in England Number 908396
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/10428#issuecomment-138560107>
> .
>



-- 
Scott Painter
QA Analyst | Dotcom

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by OliverJAsh** [comment]
According to the user, this happens even when they are typing slowly. I am unable to reproduce on various Android tablets.

**Comment by gtrufitt** [comment]
This occurs on the 'internet' browser of Samsung galaxy tab. It is due to the browser not supporting the 'autocomplete' attribute on input elements, therefore the input event fires sporadically and sometime contains several characters in the event data. This issue is not seen in Chrome on samsung tablets.

Testcase: http://jsbin.com/vimamigato/

I have raised a PR for preventing double letters, which masks the visual error, but does not fix the underlying problem: #10594

This issue is also on the R2 crossword, marking as low priority.

**Comment by ScottPainterGNM** [comment]
Closing off issue as per comments above, will monitor user feedback
