### ISSUE TITLE
crosswords: older crosswords contain false special instruction with print link

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#10434]
http://www.theguardian.com/crosswords/quick/12001

![image](https://cloud.githubusercontent.com/assets/11922253/9740502/f9b08b0e-564c-11e5-86e7-689517e028ff.png)

Not sure how many this covers but from Quick 13000 onwards that I have looked at it doesn't appear

**Comment by paperboyo** [comment]
Very loosely related (similar cleanup job): https://github.com/guardian/frontend/issues/8129

**Comment by ScottPainterGNM** [comment]
Fixed by #10442

**Comment by ScottPainterGNM** [comment]
https://groups.google.com/a/guardian.co.uk/forum/#!topic/crosswords.beta/WSl1F0XMbns - this is still getting reported as an error on older crosswords

**Comment by JonNorman** [comment]
Do these "special instructions" only appear on older crosswords? I think the fix is quite simple and am happy to put it in, but it would be good to know what else might be affected first...
