### ISSUE TITLE
Only first 5 tweets "enhanced"

### ISSUE THREAD

**Issue by theefer** [guardian/frontend#10496]
![image](https://cloud.githubusercontent.com/assets/36964/9847073/6f8c5968-5ace-11e5-8a97-ebb3a27e869d.png)

e.g. http://www.theguardian.com/politics/2015/sep/13/tory-theme-corbyn-threat-national-security-criticised
on desktop

I swear we used to enhance all the tweets as you scrolled down. It doesn't seem to be happening anymore?

**Comment by gtrufitt** [comment]
Tweets sometimes load, sometimes don't, but they throw 'Uncaught TypeError: Illegal invocation' on a .load which is probably related to passing something other than a string to [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent). Investigating.

**Comment by gtrufitt** [comment]
On Prod. The reliability of enhanced tweets loading should now be.. enhanced.

**Comment by theefer** [comment]
Nice, thanks! :+1:
