### ISSUE TITLE
Sticky nav obscures live blog key events

### ISSUE THREAD

**Issue by Jholder112233** [guardian/frontend#10495]
When you scroll up a live blog the nav expands. This causes the nav to overlap the key events panel and the title of cards.

![stickynav](https://cloud.githubusercontent.com/assets/2236852/9846065/921f6850-5ac7-11e5-9b5d-132cd14a0c61.gif)

**Comment by rich-nguyen** [comment]
Think this is the same as #9917

**Comment by Jholder112233** [comment]
@rich-nguyen Seems to be! Almost 2 months old though, is there a plan for any of these..?
