### ISSUE TITLE
Crosswords: Desktop Layout on core

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#10590]
When a user is in core then the crosswords page is a bit of a mess on desktop, it still functions though so maybe some tweaks could be made to the page so it displays more nicely?

Fine on tablet and mobile breakpoints

![image](https://cloud.githubusercontent.com/assets/11922253/10015676/c2dc1df0-6119-11e5-92c9-0b88a1f7faab.png)

**Comment by desbo** [comment]
fixed by 397bf165d9a841d4949af8df7ee096b4d600d144
