### ISSUE TITLE
Related content images not showing in Safari

### ISSUE THREAD

**Issue by gtrufitt** [guardian/frontend#10610]
"Just a heads up that, for whatever reason, I’m unable to view thumbnail photographs linked to “related content”. All other similar material is per normal. 

Using the latest version of Safari; have also tried other user agents.

Best."

![image](https://cloud.githubusercontent.com/assets/638051/10041974/51503690-61e0-11e5-80f9-b20c667c57df.png)

**Comment by gtrufitt** [comment]
Related content images are now showing on Safari (picturefill runs on the lazy loaded related content container)

**Comment by davidrapson** [comment]
:gem:
