### ISSUE TITLE
Offline page and ServiceWorker out of sync

### ISSUE THREAD

**Issue by OliverJAsh** [guardian/frontend#10667]
* SW caches /app-1.js
* /offline-page requests /app-2.js

This happens because, since the last deploy, /offline-page has been revalidated but /service-worker.js has not.

We need to find a way to lockstep these two files, to guarantee users will be caching the same version of assets requested by /offline-page.

Here is our current cache setup:

```
/service-worker.js
< Cache-Control: max-age=3600, stale-while-revalidate=360, stale-if-error=864000, private

/offline-page
< Cache-Control: max-age=60, stale-while-revalidate=6, stale-if-error=864000, private
```

**Comment by OliverJAsh** [comment]
Crazy idea to circumvent the need for synchronisation (don't do this):

1. fetch offline page
2. parse the response to find asset versions (somehow)
3. fetch those assets
4. cache the fetched offline page + assets

**Comment by jakearchibald** [comment]
You could version the offline page, eg /offline-page-contenthash/, then do a serviceWorker upgrade to fetch it during install.

Or, similar to your conment above, create a manifest.json that lists the assets needed and update them when that changes.

**Comment by OliverJAsh** [comment]
Thinking out loud here.

> You could version the offline page, eg /offline-page-contenthash/, then do a serviceWorker upgrade to fetch it during install.

If we did that, we would need to continue to serve old versions of the offline page and assets, because the cached service worker will continue to request these after a deploy has created new versions. We already do this for assets, because content pages cached by our CDN (and elsewhere on the internet) will continue to request these. Doing this for the offline page is a bit harder.

**Comment by jakearchibald** [comment]
Back from leave, are you still blocked on this?

Had it bouncing around my head, and thinking that a manifest is the right answer. If the manifest is served from the same place as `/offline-page/` it would be in sync. Eg:

```json
{
  "toCache": [
    "//cdn/script-v123456.js",
    "//cdn/styles-v876543.css",
    "/offline-page/"
  ]
}
```

Then in your sw:

```js
function updateStaticPage() {
  return fetch(manifestURL).then(r => r.json()).then(data => {
    return caches.open('offline-page-' + todaysDate).then(cache => {
      return cache.addAll(data.toCache);
    })
  }).then(_ => {
    // delete older caches
  });
}
```

**Comment by OliverJAsh** [comment]
> If the manifest is served from the same place as /offline-page/ it would be in sync

Not sure I follow how this will guarantee the manifest and the offline page will be in sync. Both will be cached by the CDN separately, and thus revalidated at different times. There might be an obvious solution to this but I'm not seeing one. :crying_cat_face: 

Essentially I want to say "cache this page and all its assets". The problem here is the service worker needs to know which assets to cache up front and that depends on which version of the offline page is currently cached by the CDN.

**Comment by OliverJAsh** [comment]
Accidentally closed.

**Comment by jakearchibald** [comment]
Hmm, ok. Yeah, your original parsing idea sounds like the best way.

If parsing feels unreliable, you could have a header describe the resources needed. The preload header might be a good bet https://w3c.github.io/preload/ - then read those in the SW.

Alternatively the body could contain

```html
<script type="cache-manifest">{"some":"JSON"}</script>
```

…as this would be easier to parse.

**Comment by rich-nguyen** [comment]
Thanks @jakearchibald, we can definitely get the parsing approach working. It actually makes more sense to swap things around, so that rather than parse resources from html, we could make an endpoint that provides a well-formatted json with everything we need, so `theguardian.com\offline.json` would respond with something like:

```
{
    pageId: '/offline-page'
    page : '<html>...</html>',
    resources : [ '/version/1/app.js', '/version/1/offline.css' ]
}
```

This way, we always know that the html content and it's resources are locked together.
