### ISSUE TITLE
iOS9 Deep Linking - Twitter App adding '+' instead of spaces

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#10668]
Reported by user, when they try and share an article in iOS9 when the twitter app opens up the tweet has replaced the spaces with '+' - fine when sharing on the web but now deep linking takes you to the app if its installed this could do with a look.

![img_0017](https://cloud.githubusercontent.com/assets/11922253/10137818/60f7f300-65f3-11e5-991d-467cc5640660.PNG)

**Comment by gtrufitt** [comment]
Looks as if the response from CAPI contains the '+'s. It doesn't do for the other social shares, so maybe there's a historical issue - however, testing the intents with encoded spaces instead pluses with the url: https://twitter.com/intent/tweet?text=test+my%20spaces gets the following:

![image](https://cloud.githubusercontent.com/assets/638051/10188643/c576546e-6758-11e5-9acb-49f26420d1a8.png)

We could replace the pluses with spaces in https://github.com/guardian/frontend/blob/master/common/app/model/ShareLinks.scala but not sure if required in CAPI. Will talk to the team.

**Comment by gtrufitt** [comment]
Now on prod.
