### ISSUE TITLE
Popular video trail block not working on video article pages

### ISSUE THREAD

**Issue by JustinPinner** [guardian/frontend#10670]
Occasionally videos fail to show up. @jennysivapalan did some digging and said;

So the most popular videos are listed again. I was able to do a bit more debugging during the time the most popular videos were not showing. Ophan is returning the information fine. It looks like the refreshing in the memory list of videos on dotcom seems to take some time populate but there isn't enough logging information to suggest why. As it does eventually resolve I guess that this likely to occur when there is a dotcom deployment.

What can we do:
- Add more logging / alerting when videos (and other popular lists?) are not returning results to see how often this occurs.
- Not show the Popular videos heading when dotcom has an empty list of most popular videos.

**Comment by jennysivapalan** [comment]
Thanks @JustinPinner. My digging also found that the code that fetches from Ophan uses agents and can be found in `MostViewedVideoAgent` and the call to render the most popular videos is `MostViewedVideoController`.

**Comment by JustinPinner** [comment]
This should be patched up now. Re-open if the problem returns.
