### ISSUE TITLE
Special Characters not displaying correctly when user signed in

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#10689]
See - https://github.com/guardian/frontend/issues/4012#issuecomment-72757249

Looks like in tags and on profile pages it displays correctly but not so when displaying a signed in users name on the nav bar

![image](https://cloud.githubusercontent.com/assets/11922253/10160331/b0935c3c-6694-11e5-874c-f1d8673f4fec.png)

![image](https://cloud.githubusercontent.com/assets/11922253/10160346/c3da2ef6-6694-11e5-999e-dd7b71aa3f8f.png)

**Comment by ScottPainterGNM** [comment]
@paperboyo FYI

**Comment by gtrufitt** [comment]
I've raised this with the identity team, and it's scheduled to be fixed as part of their Q3 work, as well as being able to register with diacritics as part of a username (which is currently not possible, so made it difficult to test the original issue!)

**Comment by paperboyo** [comment]
That's great, thąnks, @gtrufitt!

**Comment by nlindblad** [comment]
Fixed in https://github.com/guardian/frontend/pull/12364 and on the Identity side.

<img width="574" alt="screen shot 2016-04-05 at 12 39 29" src="https://cloud.githubusercontent.com/assets/164991/14280594/9e636cba-fb2b-11e5-8049-066eb90e5cce.png">
