### ISSUE TITLE
Crosswords - Need to add message to advise crosswords are auto saved

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#10717]

**Comment by NathanielBennett** [comment]
@ScottPainterGNM Have we got a design for this?

**Comment by andreajez** [comment]
@NathanielBennett Going to put something together now!

**Comment by andreajez** [comment]
@ScottPainterGNM am on it. :)

**Comment by andreajez** [comment]
@NathanielBennett @ScottPainterGNM 

I did this really quickly in the browser. Small message near where people might be looking for save buttons. Uses the same font styling as the date and time stamp, but italicised. 

Chris and I are happy with it - thoughts?

![screen shot 2015-09-30 at 12 36 57](https://cloud.githubusercontent.com/assets/6411232/10191890/14a0ea6a-6770-11e5-96c2-f4416c2bcbe8.png)
![screen shot 2015-09-30 at 12 37 21](https://cloud.githubusercontent.com/assets/6411232/10191891/1782cab4-6770-11e5-8f63-aa6b332995b5.png)

**Comment by ScottPainterGNM** [comment]
Looks good to me!

**Comment by andreajez** [comment]
Cool, let's do it!

(Need to get my machine set up so I can add it myself next time.)

**Comment by NathanielBennett** [comment]
There's a PR out for this .

**Comment by ScottPainterGNM** [comment]
Fixed by #10736
