### ISSUE TITLE
iOS - Peace Content Blocker blocks search

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#10731]
Peace is blocking the Google Search Ajax API - could potentially be Ghostery related as Peace is powered by them and on desktop this comes up as an option.

**Comment by michaelwmcnamara** [comment]
From Grant:
The plot thickens...

There are actually ads in there but they are hidden due to the width we force the component to.

If I make the box larger you can see them.

This is actually against Google's T&Cs (and they know we are doing it).

Grant



Inline images 1

**Comment by michaelwmcnamara** [comment]
See email chain for more info on this - its possible that the content blocker is behaving correctly

**Comment by gtrufitt** [comment]
@ScottPainterGNM @michaelwmcnamara What would we expect to do with this? Put a message up? I can't see what else we can do if the the API is blocked...

**Comment by ScottPainterGNM** [comment]
I think maybe this is worth closing for now, there's not much we can do and if users complain we can advise its this specific content blocker which is now off the app store anyway
