### ISSUE TITLE
Twitter icon misaligned

### ISSUE THREAD

**Issue by Jholder112233** [guardian/frontend#10791]
The tweet icon is misaligned on mobile under the byline. Pops out the left of the box.

Maybe one for @zeftilldeath if you have chance?

![img_0134](https://cloud.githubusercontent.com/assets/2236852/10333708/958ef262-6cdd-11e5-874f-2b64f93d93a5.PNG)

**Comment by zeftilldeath** [comment]
Sure I'll take a look.
