### ISSUE TITLE
Video icons displaced on video end slate

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#10823]
Hello,
All browsers, OSes. Icons are showing in the wrong place on the video end slate (note, how they are showing correctly in Popular videos at the right):

![video end slate icons](https://cloud.githubusercontent.com/assets/6032869/10381341/e3b17a66-6e11-11e5-8faa-f4a842e24972.PNG)

Regards
Mateusz

**Comment by zeftilldeath** [comment]
I'll take a look at this.

**Comment by zeftilldeath** [comment]
Fix is live now.

**Comment by paperboyo** [comment]
Thank a lot, @zeftilldeath! Closing.
