### ISSUE TITLE
Showcased images in the new Immersive template are being requested at too low a resolution

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#10947]
Hello,

In the new Immersive template the showcased in-article images are requested at smaller resolution that they are shown at (at 100% zoom). This results in unnecessarily blurry images. As far as I can tell, this affects all breakpoints (they are requested 20px smaller in width, maybe because Immersive template has a wider text column?).

Related to (all fixed): https://github.com/guardian/frontend/issues/9482, https://github.com/guardian/frontend/issues/9278, https://github.com/guardian/frontend/issues/10467, https://github.com/guardian/frontend/issues/10493.

Regards
Mateusz

**Comment by sammorrisdesign** [comment]
This should be fixed in https://github.com/guardian/frontend/pull/11044

**Comment by paperboyo** [comment]
Thanks, @sammorrisdesign!
