### ISSUE TITLE
Unstyled tweet embed

### ISSUE THREAD

**Issue by gidsg** [guardian/frontend#10959]
Not sure if it is a production issue, but the embedded tweet in this article appears completely unstyled. (In Chrome/Safari/Firefox)

Steps to reproduce
===============
Go to: http://www.theguardian.com/music/2015/oct/25/ryan-adams-1989-album-taylor-swift-like-shakespeare-interview

Actual Results
===========
Tweet appears unstyled:
<img width="627" alt="screen shot 2015-10-26 at 09 47 52" src="https://cloud.githubusercontent.com/assets/1764158/10725822/cab681a6-7bc6-11e5-9d37-ba4c7aa67c34.png">

Expected Results
==============
Tweet appears styles as per other pages e.g. http://www.theguardian.com/tv-and-radio/2015/oct/07/nadiya-jamir-hussain-great-british-bake-off-favourite

**Comment by mchv** [comment]
@gidsg I have fixed this. The reason was that the tweet had not been embedded correctly in composer.
