### ISSUE TITLE
AMP pixel not secure

### ISSUE THREAD

**Issue by stephanfowler** [guardian/frontend#10965]
We have:
```<amp-pixel src="http://hits.theguardian.com...```

but surely we need: 
```<amp-pixel src="https://hits-secure.theguardian.com...```

because AMPs always serve on https, so the pixel request always errors.

@johnduffell @NataliaLKB

**Comment by NataliaLKB** [comment]
This has been fixed by this PR: https://github.com/guardian/frontend/pull/10985
