### ISSUE TITLE
Chrome: some images in text columns are not being displayed

### ISSUE THREAD

**Issue by OliverJAsh** [guardian/frontend#10977]
![image](https://cloud.githubusercontent.com/assets/921609/10763938/cddc6c26-7cc3-11e5-8c47-40227f7af8d3.png)

http://www.theguardian.com/us/sustainable-business

This appears to be a bug in Chrome.

Isolated test case and bug report: https://code.google.com/p/chromium/issues/detail?id=548223

**Comment by sndrs** [comment]
closed by #11116
