### ISSUE TITLE
Render quiz content atoms in frontend

### ISSUE THREAD

**Issue by chrisfinch** [guardian/frontend#10982]
I'm creating this issue to keep track of the tasks that need completing in order to get the new quiz content atoms rendering in frontend.

- [x] Styling for no-js quiz in content body ([in-prog](https://github.com/guardian/frontend/tree/quiz-atom))
- [ ] Javascript to enhance no-js quiz with interactive features ([in-prog](https://github.com/guardian/frontend/tree/quiz-atom))
    - [x] Request quiz data from onward endpoint using provided id
    - [x] Enhance share text
    - [ ] Solution for tweeting share text
    - [x] Solution for responsive images in quiz rendering
    - [x] Display revealText on correct answers
- [ ] Output responsive images from quiz builder as default
- [ ] Changes to capi data parsing in frontend to allow access to quiz atom data and switching for js package ([in-prog](https://github.com/guardian/frontend/tree/quiz-atom))
- [ ] Update [content-api-client](https://github.com/guardian/content-api-scala-client) to pass through new content-atom/quiz data
- [ ] Update frontend project [content-api-client](https://github.com/guardian/content-api-scala-client) dependancy version from 6.10 to ^7.3 to allow use of new data
    - [ ] New onward endpoint for requesting structured quiz data
        - [x] Stub out
        - [ ] Integrate with new output from content-api-client
    - [ ] Relevant booleans inserted in to page config for use by js bootstraps loader (in prog)

cc @paulmr @clloyd @rich-nguyen @NickPapacostas - Please edit this if you think I've left anything out.

**Comment by chrisfinch** [comment]
Current Enhanced Quiz styling...
![quiz_](https://cloud.githubusercontent.com/assets/1170410/10913630/b1684118-8246-11e5-9998-948540aa643d.png)

**Comment by rich-nguyen** [comment]
We've got this tracked as part of the Health team. The "no-javascript" implementation is adequate for quiz migration, with bells and whistles to be added at a later date.
