### ISSUE TITLE
Jobs link shows up in sticky nav on international edition

### ISSUE THREAD

**Issue by Jholder112233** [guardian/frontend#11017]
Only happens on the international edition, at tablet breakpoints and above.

![screen shot 2015-10-29 at 17 14 33](https://cloud.githubusercontent.com/assets/2236852/10826223/9427d850-7e60-11e5-9fd2-99b734637459.png)

**Comment by paperboyo** [comment]
Fixed by https://github.com/guardian/frontend/pull/11086?

**Comment by Jholder112233** [comment]
Sure is!
