### ISSUE TITLE
On fronts, Video play event does not send to omniture when viewed with adblocker

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#11043]
If I play a video on a front and have and adblocker (ie adblock plus) active, the "video play" event is not sent to omniture.

This only happens if I am on a front - in a video page the events all send fine, even with an ad-blocker active.

If there is no adblocker active all works well so it seems like we are losing a request somewhere on fronts when adblockers are running.

**Comment by michaelwmcnamara** [comment]
Main difference seems to be that - on a front, selecting a video actually requests and loads the player rather than simply pressing play.

Normally this results in the following chain of omniture requests:
front without adblock
- video request
- preroll request
- video play
- (if ad present - preroll play followed by preroll end)
- some kind of event after ad finishes and actual content starts playing

However if I have adblocker active, the chain of omniture requests is as follows:
front with adblock
- video request
-  other calls - ie 25% completion etc as normal 

the initial video play omniture event does not trigger.
If I pause and play the video however the play event does send so it seems to be the initial chain that is broken.

Suspect that when we lose the preroll request, we are also breaking the chain that results in the videp play request being sent

**Comment by michaelwmcnamara** [comment]
a full comparison of the omniture calls sent on video page and fronts when adblocker is active or inactive follows:

video page without adblock
- video request
- preroll request
- video play
- (if ad present - preroll play followed by preroll end)
- some kind of event after ad finishes

front without adblock
- video request
- preroll request
- video play
- (if ad present - preroll play followed by preroll end)
- some kind of event after ad finishes


video page with adblock
- video request
- video play
- etc
(play does send if I pause and play again)

front with adblock
- video request
no initial video play
-  other calls as normal - play does send if I pause and play again

**Comment by ScottPainterGNM** [comment]
PR #12006 should hopefully fix this
