### ISSUE TITLE
Redundant secondary nav only on International edition

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#11054]
Hello,

All other editions look like:

![all other editions](https://cloud.githubusercontent.com/assets/6032869/10938022/65b80530-82f7-11e5-95f2-1f6004082a20.PNG)

International edition looks like (FF & CH on Win10):

![international edition](https://cloud.githubusercontent.com/assets/6032869/10938048/7c9c5314-82f7-11e5-9f2b-e8ef849865ca.PNG)

I would expect International edition to not have a redundant secondary nav containing the home link just beside a home icon that does the same thing.

Regards
Mateusz :palm_tree:

**Comment by crifmulholland** [comment]
Yes, I spotted this - that's hardcoded to disappear on network fronts. We should make it a bit more dynamic and hide it when there are no subsections.

**Comment by paperboyo** [comment]
Problem will disappear with the new nav, so closing...
