### ISSUE TITLE
AB testing framework sampling isn't even

### ISSUE THREAD

**Issue by Jholder112233** [guardian/frontend#11148]
I've had problems now with numerous tests that ran on the 0-2% sample, where the variant was receiving around half the page views of the control. So I investigated and set up a dummy test which did nothing and always returned true. 

The result:
<img width="958" alt="screen shot 2015-11-18 at 14 33 16" src="https://cloud.githubusercontent.com/assets/2236852/11243682/5858d800-8e01-11e5-995b-eab5f86491c1.png">

The tests which had problems on that sample worked perfectly on a different sample.

Whoever picks this up, come grab me to chat about it!

**Comment by rich-nguyen** [comment]
Very alarming! Let's investigate this together tomorrow, we've had problems like this in the past but thought we'd fixed them.

**Comment by Jholder112233** [comment]
Seems to have been fixed by https://github.com/guardian/frontend/pull/11156
