### ISSUE TITLE
Outbrain on IE10

### ISSUE THREAD

**Issue by Jholder112233** [guardian/frontend#11164]
Outbrain is incredibly broken on IE10. 

![screen shot 2015-11-20 at 15 03 16](https://cloud.githubusercontent.com/assets/2236852/11302933/e8be2be2-8f97-11e5-97a9-3d96a04bfcd5.png)

**Comment by jbreckmckye** [comment]
Is this still an issue? I couldn't replicate in Edge's emulator.

My understanding is that this component is styled by the third party, so we'll have to raise issues with Outbrain themselves.

**Comment by ScottPainterGNM** [comment]
Replicated this in Browserstack so think this is still an issue.

**Comment by ScottPainterGNM** [comment]
I've emailed JB @ Outbrain to take a look

**Comment by ScottPainterGNM** [comment]
This has now been fixed by Outbrain, tested over a VM running IE10
