### ISSUE TITLE
Immersive articles don't print correctly

### ISSUE THREAD

**Issue by Jholder112233** [guardian/frontend#11233]
Saw a commenter complaining about this, and they're right. Paragraphs get cut off:

![screen shot 2015-12-01 at 10 10 21](https://cloud.githubusercontent.com/assets/2236852/11497880/da6627fa-9813-11e5-8d72-4e1853ab7526.png)
![screen shot 2015-12-01 at 10 10 27](https://cloud.githubusercontent.com/assets/2236852/11497884/dcb1980a-9813-11e5-8f23-1c3db76d240a.png)

**Comment by Jholder112233** [comment]
@sammorrisdesign

**Comment by sammorrisdesign** [comment]
This header is actually injected with javascript, so was a bit of a hack.

The proper version that I've added it in [this PR](https://github.com/guardian/frontend/pull/11268) means this error won't appear any more.

**Comment by paperboyo** [comment]
Works much better now, although there is still room for improvements. Bylined authors are blank, huge blank spaces where images used to be, cut-off drop caps, some junk at the end.

**Comment by ScottPainterGNM** [comment]
@sammorrisdesign any thoughts on the above comments or can we close this off?

**Comment by michaelwmcnamara** [comment]
Closing - too many competing issues with higher priority.
