### ISSUE TITLE
Share counting on twitter is broken

### ISSUE THREAD

**Issue by mchv** [guardian/frontend#11286]
The [current code](https://github.com/guardian/frontend/blob/master/static/src/javascripts/projects/common/modules/social/share-count.js#L100) was using an [unofficial twitter API](https://twittercommunity.com/t/is-http-urls-api-twitter-com-1-urls-count-json-a-valid-way-to-get-the-tweet-count-for-a-url/13369):

```javascript
                    url: 'https://cdn.api.twitter.com/1/urls/count.json?url=' + url,
```

The endpoint has [now been turned off](https://twittercommunity.com/t/a-new-design-for-tweet-and-follow-buttons/52791) (16 days ago) so every request got a `410` response and result in an error in the browser console.

cc @mattosborn

**Comment by gtrufitt** [comment]
FYI,

**Comment by gtrufitt** [comment]
Yeah, we need a decision on what we're going to do with this...

cc/ @Jholder112233

**Comment by OliverJAsh** [comment]
There's no easy alternative to the API. We need to treat this as a new
feature and potentially consider replacing it with some other metric.

On Fri, 11 Dec 2015 at 17:04 Gareth Trufitt <notifications@github.com>
wrote:

> Yeah, we need a decision on what we're going to do with this...
>
> cc/ @Jholder112233 <https://github.com/Jholder112233>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/11286#issuecomment-163991554>
> .
>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by paperboyo** [comment]
Twitter share count was removed in https://github.com/guardian/frontend/pull/11424. Safe to close? (although :cry:)

**Comment by brugeman** [comment]
There are several easy alternatives to the API, the one I'm involved with is newsharecounts.com, maybe it can suit your needs.

**Comment by mchv** [comment]
Closing the issue as the feature has been removed.
