### ISSUE TITLE
“Popular” shows just one item of content (The far right is coming...)

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#11287]
Hello,

All editions, all browsers:

![the far right takes over](https://cloud.githubusercontent.com/assets/6032869/11621038/1a1e54d0-9cb0-11e5-8a1b-fa98dc285510.JPG)

Regards
Mateusz

**Comment by paperboyo** [comment]
Must have been a temporary hiccup, sanity prevailed, closing...

**Comment by OliverJAsh** [comment]
This has come up several times in the last 7 days. :confused:
