### ISSUE TITLE
Crosswords can’t be Saved for laterz

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#11316]
Hello,

All OS/browsers. Steps:

1. Log in
2. Note the number of your saved items
3. Save for later any crossword
4. Go to your saved items

Notice how the number of saved items increases, but the crossword doesn’t show in saved for later list.

Also, Save for later button on a crossword pages lacks a tooltip which makes it harder to discover.

Ideally, the **contents** of a half-solved crossword would travel between devices/browsers when saved for later.

Regards
Mateusz

**Comment by crifmulholland** [comment]
It looks like it does save it, but the order of saved for later items has been messed up. They should be ordered by date.

(saving the contents would be great, but that's a fair bit of work - so a feature request rather then bug!)

**Comment by paperboyo** [comment]
> It looks like it does save it,

The number of saved items goes up but they do not show for me at all (I have 9 in total, so just one page and the crosswords are not there at all). Just checked by adding another one - same result.


> a feature request rather then bug!

Most obviously!

**Comment by gtrufitt** [comment]
> Save for later button on a crossword pages lacks a tooltip which makes it harder to discover.

This was intentional to avoid confusion that the crossword's contents was being saved to a user's account (not just the browser's localstorage). 

> Ideally, the contents of a half-solved crossword would travel between devices/browsers when saved for later.

*Ideally* :)

**Comment by paperboyo** [comment]
> This was intentional to avoid confusion that the crossword's contents was being saved to a user's account (not just the browser's localstorage).

Ok (although...). But if there is a button, the crossword (not the content) should save to the user's account and be visible there. It isn't - I've checked on two different accounts. So keeping it open, unless instructed otherwise.

> Ideally :)

What would the life be without dreams... :unicorn_face: :wink:

**Comment by paperboyo** [comment]
In my dreams there is a :unicorn_face: on github! For real!

**Comment by gtrufitt** [comment]
> But if there is a button, the crossword (not the content) should save to the user's account and be visible there

Yeah, sure, that's a bug :horse:

**Comment by ScottPainterGNM** [comment]
I do think that at the very least you should be able to SFL the actual crossword if not the contents, users report this issue from time to time. 

@michaelmcnamara FYI

**Comment by paperboyo** [comment]
Fixed in https://github.com/guardian/frontend/pull/14550. Thanks, @rjmk!
