### ISSUE TITLE
AMP redirect fails for BAFTA noms article

### ISSUE THREAD

**Issue by ndarville** [guardian/frontend#11505]
<http://www.theguardian.com/film/2016/jan/08/baftas-2016-full-list-of-nominations>
`=>`
<https://www.theguardian.com/film/2016/jan/08/baftas-2016-full-list-of-nominations/amp>

The first article works, the second doesn’t.

(Previously: #11425.)

**Comment by NataliaLKB** [comment]
@ndarville the second link appears to work just fine for me. Could you expand on the problem?

Regarding the issue you mentioned, live blogs are not yet available in an AMP format. Thus the `404`. Most articles are however. The article for Bafta Nominations should work just fine.

**Comment by ndarville** [comment]
The link didn’t work during the time of submission. Dunno what your CMS looks like nor how fast it renders the AMP versions, but maybe a changelog has the answer.

**Comment by NataliaLKB** [comment]
@ndarville it should work immediately, and it is good to know if it didn't. Do let us know if you find a problem like this again.

Thanks!
