### ISSUE TITLE
Double dotted line on immersive articles

### ISSUE THREAD

**Issue by Jholder112233** [guardian/frontend#11512]
Dotted line under the article meta and then another dotted line at the start of the article.

![screen shot 2016-01-11 at 11 54 56](https://cloud.githubusercontent.com/assets/2236852/12232873/2f2870ac-b85a-11e5-967e-6e3bd38f25a6.png)

cc @sammorrisdesign

**Comment by sammorrisdesign** [comment]
Yeah I know it's gross. Trying to get sbt working now to change it

**Comment by paperboyo** [comment]
Can’t reproduce at the (not) given URL. Safe to close?

**Comment by ScottPainterGNM** [comment]
Looks good to me as well, closing
