### ISSUE TITLE
Broken links in profile.theguardian.com

### ISSUE THREAD

**Issue by thomaska** [guardian/frontend#11521]
Steps to reproduce:
1. Visit <a href="https://profile.theguardian.com">profile.theguardian.com</a>
2. Click on any link under the instruction "Please follow one of the links below to continue exploring."

Expected:
According to the link clicked go to the corresponding section

Reality:
A 404 is returned.
This must be because the relative path is concatenated to the base url, in which case is not theguardian.com but a subdomain (profile.theguardian.com).

**Comment by ScottPainterGNM** [comment]
I can't replicate this, in fact when I go to profile.theguardian.com I just get a 404. Is this still causing an issue for you?

**Comment by thomaska** [comment]
Yes I am also getting a 404 when I go to profile.theguardian.com. Maybe it became obsolete...?

**Comment by ScottPainterGNM** [comment]
I checked with Identity and it shouldn't link to anything now so think this is now good to close?

**Comment by thomaska** [comment]
Ok, yes please!
