### ISSUE TITLE
Quiz not working on HTTPS

### ISSUE THREAD

**Issue by adamnfish** [guardian/frontend#11531]
If you opt in to https using @desbo's nice little tool, you'll find this quiz doesn't work.

https://www.theguardian.com/film/2016/jan/12/ceiling-good-match-the-room-to-the-movie-quiz

I get the following error

    Mixed Content: The page at 'https://www.theguardian.com/film/2016/jan/12/ceiling-good-match-the-room-to-the-movie-quiz' was loaded over HTTPS, but requested an insecure script 'http://gdn-cdn.s3.amazonaws.com/quiz-builder/535a2e46-804c-4318-8e4b-6677b889aae6/app.js'. This request has been blocked; the content must be served over HTTPS.

It works great without the secure opt-in, of course.

**Comment by ScottPainterGNM** [comment]
@desbo do you think this is something for tools to look into or our end?

**Comment by desbo** [comment]
looks like it's one for quiz-builder, we need to update the call to `app.js` in https://gdn-cdn.s3.amazonaws.com/quiz-builder/535a2e46-804c-4318-8e4b-6677b889aae6/boot.js

**Comment by ScottPainterGNM** [comment]
@clloyd Would you be the man for the job? If not do you know who we should ask?

**Comment by clloyd** [comment]
The plan for these quizzes is to migrate them to the new atom-style quizzes, with full HTTPS support. We don't plan to further update the interactive-style quizzes.

**Comment by ScottPainterGNM** [comment]
Chris advised that, it’s a known limitation of the old interactive style-quizzes (the Berry variety), once they are migrated into the new tool they will support https

**Comment by johnduffell** [comment]
sounds like nothing to do here then!
