### ISSUE TITLE
Our 404 freeze Firefox

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#11547]
Hello,

This is a long-standing thing. Guardian's 404s make my Firefoxen (many, many versions) unresponsive. Console prints (FF 43.0.3 on 10.9.5 hangs for 7s):
```
17:37:10.446 too much recursion
anonymous/s.c_w() omniture.js line 746 > Function:1
anonymous() omniture.js line 536 > Function:1
anonymous() omniture.js line 524 > Function:1

[...repeated many times...]

1 omniture.js line 746 > Function:1:3087
```

Chrome (46.0.2490.86 on 10.9.5, no freeze):
```
Uncaught RangeError: Maximum call stack size exceeded
encodeURIComponent	@	(program):281
s.ape	@	VM109:3
s.c_w	@	VM109:3
(anonymous function)	@	VM142:3
(anonymous function)	@	VM141:3
(anonymous function)	@	VM142:3
(anonymous function)	@	VM141:3
(anonymous function)	@	VM142:3
(anonymous function)	@	VM141:3
(anonymous function)	@	VM142:3
```
Regards
Mateusz

**Comment by gidsg** [comment]
I think I have worked out what is going on here, this page calls a *very* old version of omniture at https://static.guim.co.uk/omni/omniture.js I will try and update this file which should fix the issue.

**Comment by paperboyo** [comment]
Thanks!

**Comment by gidsg** [comment]
Fixed by updating https://static.guim.co.uk/omni/omniture.js this has been verified OK from a tracking point of view by @mkopka. H/T @troydias for making the change.
