### ISSUE TITLE
Whatsapp Share Button not working on Google Search app

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#11562]
As above, when using the iOS Google Search app to browse the site, the whatsapp share button doesn't open the app (other share buttons seem to function fine).

Reported by Sophie Zeldin-O'Neill

**Comment by Jholder112233** [comment]
Not sure this is fixable on our end, seems like the Google app isn't recognising it. Buzzfeed's WhatsApp sharing button has the same issue

**Comment by ScottPainterGNM** [comment]
Going close this off as don't think there is much we can do/how much usage that google app gets
