### ISSUE TITLE
Broken Twitter images in source

### ISSUE THREAD

**Issue by dracos** [guardian/frontend#11588]
Browser: Safari
OS: OS X 10.10.5
URL: http://www.theguardian.com/sport/live/2016/jan/16/south-africa-v-england-third-test-day-three-live (but any live blog)

Looking at the HTML source, if there's not an associated picture, an `img` is still inserted with a `src` of the Tweet HTML, so displays as a broken image. I guess it should be the profile image? If there's a picture associated with the tweet, then it's okay, as that image is used in the source rather than a profile image.

I had JavaScript on, but updates that were being pulled into the page post first load were displaying this broken image, which is how I spotted it. For example, from that page:
```
<figure class="element element-tweet" data-canonical-url="https://twitter.com/Ian_Bell/statuses/688388391495450624">
<blockquote class="js-tweet tweet">
<img src="https://twitter.com/Ian_Bell/statuses/688388391495450624" alt="" rel="nofollow" class=" js-tweet-main-image tweet-main-image"/>
<span class="tweet-user">— Ian Bell (@Ian_Bell)</span>
<a href="https://twitter.com/Ian_Bell/status/688388391495450624" data-link-name="in body link" data-component="in-body-link" class="tweet-date">January 16, 2016</a>
```

![screen shot 2016-01-17 at 19 37 55](https://cloud.githubusercontent.com/assets/154364/12379402/e835744a-bd51-11e5-8e31-5a43c58ea023.png)

**Comment by rich-nguyen** [comment]
Thanks for the report, @dracos . This should be fixed now, I upgraded our library `content-api-client` to 7.27, which has a fix for this. https://github.com/guardian/frontend/pull/11996
