### ISSUE TITLE
Modern HTML doesn't work in comments

### ISSUE THREAD

**Issue by mattandrews** [guardian/frontend#11590]
Come on folks, let's drag Discussion kicking and screaming into 2010! 

I posted [this comment](http://www.theguardian.com/tv-and-radio/2016/jan/18/15th-anniversary-of-popworld#comment-66953010) just now (it's a great comment, feel free to recommend it) and the `<em>so</em>` HTML I wrote in the textarea now shows—embarrassingly—as raw HTML. Presumable the ancient `<i>` and `<b>` tags work fine.

Maybe you could parse `<em>`/`<strong>` tags too?!

Also: when I posted the comment and the preview appeared, the HTML didn't show up (but the italics did)...

**Comment by ScottPainterGNM** [comment]
@nicl any plans to implement this feature request in the future? Just wondering whether we want to keep this issue or not (sorry if not @mattandrews !)

**Comment by mattandrews** [comment]
Nic promised me this was going to happen just a week or so ago (admittedly, in a pub...)

**Comment by ScottPainterGNM** [comment]
Oh well that is basically gospel in which case, Nic sounds like this is a goer...

**Comment by nicl** [comment]
@ScottPainterGNM @mattandrews it's in our Trello!!! But seriously it is, we just haven't prioritised it yet. I'm hoping we can fix this in the next few weeks but can't guarantee anything.

**Comment by michaelwmcnamara** [comment]
tracked by discussion card
