### ISSUE TITLE
This is the NHS (special project) tone overwrites liveblog background colour

### ISSUE THREAD

**Issue by Jholder112233** [guardian/frontend#11661]
![screen shot 2016-01-22 at 10 15 09](https://cloud.githubusercontent.com/assets/2236852/12507987/1871dcbe-c0f1-11e5-9e9a-b392613f5101.png)

Seems like it's not getting the tonal--tone-live class and the tonal---tone-special-project class would overwrite the background colour anyway.

**Comment by paperboyo** [comment]
Also, it overrides background on media (or, at least, video) pages, e.g.: http://www.theguardian.com/society/video/2016/jan/22/the-great-british-booze-problem-epidemic-nhs-video

Some of the furniture (Save for later especially) looks quite surprised:

![sfl on special report tone](https://cloud.githubusercontent.com/assets/6032869/12526758/de3a27ea-c168-11e5-8e89-cd79bae65db3.PNG)

**Comment by piuccio** [comment]
Interested in what @janua has to say, articles are modelled to have only one tone, they can't be `special-report` and `live` (or `comment`) at the same time.

**Comment by janua** [comment]
Yes, they can only have one tone; and `special-report` has higher precedence than `live`. It's not possible for things to have two tones, it doesn't make sense conceptually right now unless it was designed. Special tone needs to be fixed here or the `live` tone needs to come out instead.

**Comment by NataliaLKB** [comment]
I think this was fixed by @zeftilldeath ! Closing. Please open if this is still happening.
