### ISSUE TITLE
comments sorted by recommended don't load

### ISSUE THREAD

**Issue by piuccio** [guardian/frontend#11735]
go to any article with comments. sort them by `recommendations` and refresh the page, comment won't load.

**Comment by JonNorman** [comment]
I've just tried to reproduce this, with no luck; suggest we close the issue.

I tried the following articles:
http://www.theguardian.com/tv-and-radio/2016/apr/01/tv-characters-vote-for-election-2016
http://www.theguardian.com/commentisfree/2016/apr/01/germany-refugee-crisis-invited-into-my-home-welcoming-spirit-divided

**Comment by piuccio** [comment]
true, seems to be working now
