### ISSUE TITLE
Liveblog toast ab test - toast notifications do not display for IE

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#11832]
Running IE - even the latest version, while opted into the "remove stickynav" and "toast" ab tests.
When I am viewing a liveblog and am scrolled down the page, if a new block is added to the liveblog, I should see a notification pop-up informing me there is an update availble to be viewed.

This is the case on Chrome

On IE11 or older, the block is just inserted with no notification - this is the case even if I am scrolled to the bottom of the page.

**Comment by sndrs** [comment]
is this still true?

**Comment by OliverJAsh** [comment]
Nope, this is fixed now
