### ISSUE TITLE
Sponsored content for Amp pages

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#11935]
Currently the sponsorship badges on amp pages are not enhancing. The underlying text is visible, but it doesn't enhance to the relevant company logo.

example: compare standard sponsored article page:
https://www.theguardian.com/sustainable-business/2016/feb/09/social-media-networks-child-protection-policies-facebook-twitter-instagram-snapchat:
badge shown: 
![image](https://cloud.githubusercontent.com/assets/7239344/12976529/a853634a-d0bc-11e5-8ec2-503641272b68.png)

and amp version of the same page
https://amp.theguardian.com/sustainable-business/2016/feb/09/social-media-networks-child-protection-policies-facebook-twitter-instagram-snapchat
badge shown:
![image](https://cloud.githubusercontent.com/assets/7239344/12976541/c1baf730-d0bc-11e5-8133-a0d7189a3dee.png)

**Comment by NataliaLKB** [comment]
This isn't in the page source, without JS I don't think I can display this. Closing unless @stephanfowler has any ideas?

**Comment by stephanfowler** [comment]
We might be able to load the badge, which is actually an ad served by DFP. We'll speak to commercial about it. But for now, it's out of scope.
