### ISSUE TITLE
Football match reports are not showing score results widget or match stats widgets

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#11948]
Example page
http://www.theguardian.com/football/2016/feb/10/peterborough-united-west-brom-fa-cup-fourth-round-replay-match-report
vs
http://amp.theguardian.com/football/2016/feb/10/peterborough-united-west-brom-fa-cup-fourth-round-replay-match-report

In the www page there is a large graphic below the headline giving the scores and below the body of the text is another graphic showing a range of match stats.
These are missing in the amp page.

eg:
scores graphic in www version of the page
![image](https://cloud.githubusercontent.com/assets/7239344/12985021/6bb060a6-d0e8-11e5-8141-1312fcb3111b.png)

match stats in www version of the page:
![image](https://cloud.githubusercontent.com/assets/7239344/12984999/51833abe-d0e8-11e5-9c1f-6fbfc17bdb74.png)

**Comment by TBonnin** [comment]
Score and match stats are loaded asynchronously at the moment. I am not sure how we want to handle this scenario. @stephanfowler @NataliaLKB?

**Comment by stephanfowler** [comment]
It'd be nice to have them. However, they're currently injected dom fragments, not iframe-able docs. So  no quick solution for this yet. Let's see how amp goes before we take this one further.
