### ISSUE TITLE
Quizzes serve an amp page but no page body

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#11946]
Currently quizzes serve an amp page, but the questions and answers are not injected. Need to either fix this or consider whether we want to serve quizzes on amp at all. 
eg: https://amp.theguardian.com/football/2016/feb/11/football-quiz-ticket-prices
![image](https://cloud.githubusercontent.com/assets/7239344/12984436/9dac5efa-d0e5-11e5-815d-24774482c60c.png)

**Comment by NataliaLKB** [comment]
Quizzes are not supported on AMP yet. Made a PR to make sure they are not "AMPed"

**Comment by NataliaLKB** [comment]
Closed via commit 11946
