### ISSUE TITLE
Video's embedded into article pages as main media do not load and are not playable

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#11949]
When an article has a video as main media it does not load for the amp page - in fact we dont even get a place-holder image, just a big black box.

Ideally want to get the video, but if this isn't possible at least the placeholder image would make the page look less broken.

Example: 
https://www.theguardian.com/uk-news/2016/feb/11/port-talbot-100ft-flames-at-steelworks-blaze
vs
https://amp.theguardian.com/uk-news/2016/feb/11/port-talbot-100ft-flames-at-steelworks-blaze

video does not load on amp page leaving big black box:
![image](https://cloud.githubusercontent.com/assets/7239344/12985377/2cd01078-d0ea-11e5-903e-1f7d2a935e97.png)

**Comment by NataliaLKB** [comment]
This is because there are not any https sources for this video. Is this the only one you have found? I will report this to CAPI and james in the mean time.

**Comment by NataliaLKB** [comment]
The problem is actually the video is being served with the wrong source.

Videos should be served from this CDN:
https://cdn.theguardian.tv

But this one is being served from:
http://multimedia.guardianapis.com

@michaelwmcnamara if you find other videos please document them here :)

**Comment by michaelwmcnamara** [comment]
Chasing this up with content platforms. Will update when I know more.

**Comment by michaelwmcnamara** [comment]
Other examples
https://amp.theguardian.com/science/2015/oct/27/the-force-awakens-tractor-beam-becomes-a-reality
(offending video is in article body - one at top of page plays ok)

**Comment by michaelwmcnamara** [comment]
Andy Gallagher has volunteered to look into this on Monday. 
"... - will need to get a certificate generated for multimedia.guardianapis.com and then it should be a fairly simple change.
Under normal circumstances videos should source from cdn.theguardian.tv but will fallback to using auto-resolves from multimedia.guardianapis.com if the update process in Flex fails for any reason.  We appear to have had more of those failures recently.

This problem will go away once videos are atomised."

**Comment by NataliaLKB** [comment]
@michaelwmcnamara any news on this? Can you follow up first thing tomorrow?

**Comment by jamesgorrie** [comment]
Working:
https://amp.theguardian.com/science/2015/oct/27/the-force-awakens-tractor-beam-becomes-a-reality

> This problem will go away once videos are atomised.

This will be a while in the making.

[While looking at this](https://amp.theguardian.com/uk-news/2016/feb/11/port-talbot-100ft-flames-at-steelworks-blaze) - it seems that there is not sources within the video tag - is this because AMP omits any http content (the redirects would be http, but redirect to https)?

**Comment by jamesgorrie** [comment]
In short there has been trouble between Pluto and Flex talking to each other so the links are `http`. @fredex42 is going to be looking at getting the `multimedia.` URLs to have `https` versions and we will look at how we could update these URL in flex too (which would then update here).

**Comment by NataliaLKB** [comment]
@jamesgorrie thanks for the update!

**Comment by jamesgorrie** [comment]
@NataliaLKB - are you replacing http://cdn.theguardian.tv URLs manually to https?

**Comment by NataliaLKB** [comment]
The `https` urls come from a `secureFile` field in CAPI

**Comment by NataliaLKB** [comment]
Look here: https://github.com/guardian/frontend/blob/f896262c903f2c73af7369d513e876b5fe273c80/common/app/model/Asset.scala#L85

**Comment by NataliaLKB** [comment]
@jamesgorrie did we get the ssl cert working?
