### ISSUE TITLE
amp Politics articles - promoted content containers are taken from section front instead of network front

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#11972]
On content with a section tag ie politics or technology, the last three recommended content containers are being taken from the relevant section front.
This is incorrect. The third last container should be from the section front, but the bottom two containers should be sourced from the network front.

**Comment by NataliaLKB** [comment]
@TBonnin is working on this now :smile:

**Comment by TBonnin** [comment]
https://github.com/guardian/frontend/pull/12000 :smiley_cat:
