### ISSUE TITLE
AMP - images have no right padding 

### ISSUE THREAD

**Issue by Jholder112233** [guardian/frontend#11995]
![screen shot 2016-02-17 at 10 06 38](https://cloud.githubusercontent.com/assets/2236852/13106074/47ab801c-d55e-11e5-80f7-ac2f98a4f96e.png)

https://amp.theguardian.com/music/2015/nov/12/prince-interview-paisley-park-studios-minneapolis

Is this intended?

@zeftilldeath @NataliaLKB

**Comment by zeftilldeath** [comment]
@Jholder112233 As far as I I'm aware this is connected to the image sizing issue.

**Comment by Jholder112233** [comment]
Ah this one: https://github.com/guardian/frontend/issues/11943

Let's close this then as that will fix this issue. Lovely.
