### ISSUE TITLE
AMP - twitter bird blue on feature tone 

### ISSUE THREAD

**Issue by Jholder112233** [guardian/frontend#11994]
![screen shot 2016-02-17 at 10 05 39](https://cloud.githubusercontent.com/assets/2236852/13106051/2bf4b168-d55e-11e5-8696-488dc39cb0ac.png)

Just doing my bit in the run up to launch :wink: 

https://amp.theguardian.com/music/2015/nov/12/prince-interview-paisley-park-studios-minneapolis

@NataliaLKB @zeftilldeath

**Comment by zeftilldeath** [comment]
@Jholder112233 No excuse for that :smile: Will take a look.

**Comment by NataliaLKB** [comment]
@Jholder112233 thanks for the find, that is great!

@zeftilldeath I have assigned you, I hope that is okay :blush:

**Comment by Jholder112233** [comment]
Fixed by #11998
