### ISSUE TITLE
Comment functionality broken on HTTPS sections in Firefox 44+

### ISSUE THREAD

**Issue by OliverJAsh** [guardian/frontend#12012]
Steps to reproduce:

1. Go to https://www.theguardian.com/crosswords/quick/14282
2. Refresh to activate the service worker
2. Sign in
3. Open up the network panel
4. Search for a request beginning with https://discussion.theguardian.com/discussion-api/profile/me

Expected:
This request should return 200 and the response should have a status of “success”.

Actual:
The request returns 200 and the response has a status of “error”.

![image](https://cloud.githubusercontent.com/assets/921609/13143594/e1376ad2-d63c-11e5-81e6-d59370b3f7ed.png)

--

After chats with Ben Kelly who works on the service workers implementation inside of Firefox, we discovered that there is a bug on their end. When making a JS request (`<script>` i.e. JSONP), Firefox’s service worker will forward the request but drop cookies if the request is cross origin. The expected behaviour is it should send the cookies in the forwarded request. This bug can be tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1248994.

Fix to follow.

**Comment by TBonnin** [comment]
Nice catch @OliverJAsh
