### ISSUE TITLE
Should Outbrains be suppressed if any of legally sensitive, suppress related content, or should hide adverts are set?

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#12026]
Currently outbrains ignores the 
shouldHideAdverts, showInRelatedContent, and legallySensitive flags in CAPI and just displays anyway.
Is this correct?
example: http://www.theguardian.com/australia-news/2016/feb/05/church-ethos-of-easy-forgiveness-failed-to-stop-child-sex-abuse-says-peter-jensen

![image](https://cloud.githubusercontent.com/assets/7239344/13154162/86647ac2-d66f-11e5-8b98-18dddae12f45.png)

**Comment by ScottPainterGNM** [comment]
Might be worth pinging this question to Jamie Morrison to investigate?

**Comment by regiskuckaertz** [comment]
Outbrain is not shown when either `shouldHideAdverts` is true (it is false in this example) or the page belongs to the children's books section (here it is australia news). You can see other ads showing up too.

I couldn't find any reference to a `legallySensitive` flag in the global config, not anywhere. Is this something that should be added? In this case it currently does not apply, neither to Outbrain nor any other ad.

/cc @ScottPainterGNM @JonNorman

**Comment by JonNorman** [comment]
I believe that `legallySensitive` is a new flag being introduced - Huma pointed me to this [Useful Links](https://docs.google.com/document/d/1iqCgyKaLepXKDOWQ12FYipwqyeLHYPUpFmsZTHKScHk) doc which, on the second page, details these flags.

**Comment by NataliaLKB** [comment]
@michaelwmcnamara I think this is okay to close, what do you think?

**Comment by ScottPainterGNM** [comment]
@NataliaLKB pretty sure this can be closed off now!
