### ISSUE TITLE
installation wiki page has wrong link to nginx setup

### ISSUE THREAD

**Issue by domdorn** [guardian/frontend#12045]
# ISSUE
https://github.com/guardian/frontend/wiki/Installation-steps has a link on how to setup nginx for the guardian projects. however, the linked page does not exist. 
## Steps to Reproduce
go to the url, click the link
## URL
https://github.com/guardian/frontend/wiki/Installation-steps
https://github.com/guardian/frontend/wiki/nginx/README.md

## OS and Browser details

- Device:
- Browser (inc version):
- OS:

*Please add relevant labels*

**Comment by ScottPainterGNM** [comment]
Thanks for raising this issue, I have now amended the wiki page to correct this link
