### ISSUE TITLE
In recommended containers, &Amp is being read literally instead of displayed as "&"

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#12040]
There's a problem with "&Amp" on Amp pages (sorry, couldn't resist)
Seen on Chrome and Safari
The bug has been seen in the "highlights" containers, but is likely to apply to all the recommended content containers below the article body.
When the headline of a recommended story contains "&Amp" it should be rendered as "&". Instead it is rendered as is.

![image](https://cloud.githubusercontent.com/assets/7239344/13181149/7dd2177a-d723-11e5-8641-520cc2884129.png)

**Comment by NataliaLKB** [comment]
@michaelwmcnamara the amp team got back to us, I will clean these out today :smile:

**Comment by NataliaLKB** [comment]
Closing this, as we don't normally encode ampersands anyway.
