### ISSUE TITLE
Adverts brake videos

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#12048]
Hello again,

Where there are pre-rolls, the videos either do not play after an advert (or after skipping it) or take eons to start. Throbber GIF is shown for minutes after which sometimes there is “The media could not be loaded, either because the server or network failed or because the format is not supported.” info accompanied, for an unknown reason, by an intriguing “This is a modal window.” one.

URL: http://www.theguardian.com/world/video/2016/feb/21/fire-destroys-german-refugee-shelter-video
URL: http://www.theguardian.com/politics/video/2016/feb/21/david-cameron-warns-boris-johnson-not-join-brexit-campaign-video

Some strange Console output from Edge 25 (vpaid videojs error is common to all browsers but firefoxen, the rest - specific to Edge):

![videojs ads](https://cloud.githubusercontent.com/assets/6032869/13206136/3d06b4f2-d8f0-11e5-925d-101aad3e9349.PNG)

Browsers tested: Opera 35, Chrome 49, FF 45&47, IE11 and Edge 25 on Windows 10. With and without AdBlocks+ whenever possible. None work correctly.

Videos without ads play as expected.

Regards
Mateusz

**Comment by paperboyo** [comment]
Hmm. This includes videos playable on fronts. The first of above URLs is currently in pictures & video container. Do we really want to play adverts for videos on fronts?!

**Comment by jamesgorrie** [comment]
Looking into this.
> Do we really want to play adverts for videos on fronts

Ultimately, yes, but I think we need to look at who watches where first.

**Comment by jamesgorrie** [comment]
This is due to us receiving timeouts from the redirection on the multimedia server.

e.g. https://multimedia.guardianapis.com/interactivevideos/video.php?octopusid=11263712&format=video/mp4

CC @fredex42 - do you know why this might be happening?

**Comment by jamesgorrie** [comment]
> Videos without ads play as expected.

Red herring, it's the video file that's causing this.

**Comment by paperboyo** [comment]
You call me red haired?! 

![maxresdefault](https://cloud.githubusercontent.com/assets/6032869/13219382/a4088b5e-d967-11e5-85d1-3b1766f05ac9.jpg)

or red herring?

![s5000705](https://cloud.githubusercontent.com/assets/6032869/13219581/d45be6f6-d968-11e5-89fb-75480ed5e1dd.JPG)

From the POV of a reader, if there are no adverts - videos work, if there are - they do not :D

> Ultimately, yes, but I think we need to look at who watches where first.

Yeah, and into who stops watching for good when they see we stuff pre-rolls on fronts ;-)

**Comment by jamesgorrie** [comment]
> From the POV of a reader, if there are no adverts - videos work, if there are - they do not :D

 Not true, I can break them in both instance.

**Comment by paperboyo** [comment]
My bad, sorry, I have checked only two of each :-( Thanks for taking a look, @jamesgorrie! :tulip:

**Comment by jamesgorrie** [comment]
Fixed.
Waiting for the cache to clear on the first one.
