### ISSUE TITLE
Amp - Recommended content does not run on firefox

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#12053]
On amp content recommended content containers are not displaying - scroll below the content and you are left with a screen of loading "..."'s (see screenshot).
In the last month firefox has accounted for 0.8% of mobile phone visits (1 million out of 132 million).
In terms of usage this is very small, but the visual impact is pretty ugly - one to fix when we get to it.

Example url: https://amp.theguardian.com/us-news/2016/feb/21/bill-clinton-monica-lewinsky-hillary-president

screenshot:
![image](https://cloud.githubusercontent.com/assets/7239344/13225186/acb134c4-d983-11e5-9b0f-9253fb09d6ef.png)

**Comment by TBonnin** [comment]
FYI errors in console :(
![screen shot 2016-02-23 at 10 18 40](https://cloud.githubusercontent.com/assets/233326/13248516/acd65072-da16-11e5-8f8c-7e38c43782f6.png)

**Comment by NataliaLKB** [comment]
This has been fixed:

![image](https://cloud.githubusercontent.com/assets/8774970/13603297/170dfd3c-e534-11e5-8819-45511e3e881c.png)
(on firefox)
