### ISSUE TITLE
Amp pages need to respect edition cookie for recommended content

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#12050]
Amp pages are loading recommended content that corresponds to geographic location (or proxied location), but ignores the setting in the Edition cookie. 

To reproduce
Load network front
Select location other than current location
Confirm in settings that GU_Edition is set to expected value
Load an amp page amp.theguardian.com/foo
Confirm the stories in headlines and highlights match those on the front for the selected edition.
Result: They do not.

Repeat test for story in amp carousel - again they do not

Summary: Recommended content is being served according to geolocation without taking edition cookie into account.
Fail

**Comment by michaelwmcnamara** [comment]
Note: links on navigation bar do seem to respect edition cookie - ie with us edition set, nav shows "sports" and navigates to US sports front, even though location is UK so its just the recommended content thats broken.

**Comment by NataliaLKB** [comment]
@stephanfowler @michaelwmcnamara this should now be working!!! :tada: 

Please check for yourselves though and reopen if it is still not working
