### ISSUE TITLE
If a legally sensitive article is in on a front, we will serve it as a content recommendation on Amp

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#12088]
Just been reading through the document on sensitive and legally sensitive articles:
https://docs.google.com/a/guardian.co.uk/document/d/1BvDwS3oEU5lR5ZB0Us6FlTzx31B6dtzrnD3JXgSpYfI/edit?usp=sharing

"In the not so distance future, we will be experimenting with content recommendation. Like related content, we will be filtering out legally sensitive articles from these engines so we don’t serve articles that may put us in hot water"

We have a small problem in that currently we serve the contents of some containers from the network and relative section fronts at the bottom of AMP content.

This means that if a legally sensitive article is placed on the front, then we will serve it as recommended content at the bottom of AMP articles.

Question is, given we hide legally sensitive articles from related content recommendations, does it follow that we should also be hiding it in any other content recommendation we serve on articles?

**Comment by NataliaLKB** [comment]
Closing as we are not affected by this. We just have to obey the hideAds and showRelatedContent flags :)
