### ISSUE TITLE
Liveblogs: Toast incorrectly fixing

### ISSUE THREAD

**Issue by OliverJAsh** [guardian/frontend#12111]
# Steps to reproduce
1. Go to an archive page for a live liveblog
2. Stay at the top of the page and wait for updates
# Expected

Toast should appear in the correct place.
# Actual

Toast appears in its fixed position. When I scroll, it fixes itself and moves to the correct position
# Screenshot

<img width="1680" alt="toast bug archive page no scroll after js" src="https://cloud.githubusercontent.com/assets/921609/13393466/96f7d2ea-ded9-11e5-9fe5-3e39c7f3c201.png">

**Comment by SiAdcock** [comment]
I believe this was fixed in #17040, but feel free to re-open if you see more weirdness!
