### ISSUE TITLE
Can't go to my profile

### ISSUE THREAD

**Issue by kaelig** [guardian/frontend#12175]
# ISSUE

## Steps to Reproduce

On any page, tap the profile icon in the left hand side of the header. 

## Actual Results (include screenshots)

Nothing happens

## Expected Results (include screenshots)

It opens my profile page or shows me a menu. 

## OS and Browser details

- Device: iPhone 6
- Browser (inc version): Safari
- OS: iOS 9.2.1

**Comment by paperboyo** [comment]
:wave: Kaelig! It works for me in IE11, Opera, Chrome, Edge, Firefox on Win10 and in Opera, Firefox, Android Browser and Chrome on Android. Could you check in a different browser? Oh, forgot you can’t :stuck_out_tongue_winking_eye:

**Comment by gtrufitt** [comment]
Replicated on iPhone 6 plus, immediately after logging in, navigating to a new page causes the feature to work as expected

**Comment by ScottPainterGNM** [comment]
I have been having issues with this on Chrome Desktop today also, when I opened up an article from Saved for Later I cannot click on the profile drop down menu unless I refresh or navigate to another page

**Comment by kaelig** [comment]
Looks like it was fixed. Thank you!
