### ISSUE TITLE
Jankiness in liveblogs due to content embeds when I click on a key event

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#12212]
When I click on a key event I am taken to the block  want to read, then a short time after the block is bounced down the page.
Looks to be a result of embeded items being enhanced above the block I am navigating to.
Also may be caused by MPU's injecting above key event block, but this is tracked in a seperate issue

**Comment by ScottPainterGNM** [comment]
I believe @regiskuckaertz was going to look at the impact of the new ads within the liveblog work to see if this might be a cause of this jump

**Comment by regiskuckaertz** [comment]
Yeah both are problematic actually. This is an easy fix (at least for ads): only items located below the viewport should be loaded. I'll card this up.

**Comment by ScottPainterGNM** [comment]
Thanks!

**Comment by ScottPainterGNM** [comment]
@regiskuckaertz did you get a chance to look at this or still carded up at the moment?

**Comment by regiskuckaertz** [comment]
Nope, I'll try to slip in asap.

**Comment by ScottPainterGNM** [comment]
![image](https://cloud.githubusercontent.com/assets/11922253/14275714/2b882880-fb11-11e5-95c8-3dfb0582da0f.png)

**Comment by Calanthe** [comment]
This should be fixed now (https://github.com/guardian/frontend/pull/12544). There is still a little jump visible but it's because of the images loaded on top.

**Comment by sndrs** [comment]
closing in that case
