### ISSUE TITLE
HTTPS - Audio page wont play while opted in to https

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#12256]
The audio player on https://www.theguardian.com/technology/audio/2016/mar/10/the-tinder-illuminati-tech-weekly-podcast
would not load and play. console shows a host of 403 forbidden errors and at least one mixed content error:
Most relevant errors in console seem to be:

- Failed to load resource: the server responded with a status of 403 (Forbidden)

- Fetch API cannot load https://audio.guim.co.uk/2016/03/09-56789-gdn.tech.160309.sb.tinder-illuminati.mp3. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.theguardian.com' is therefore not allowed access. The response had HTTP status code 403.
Included screenshot of full error log below though.

-The source of the resource - https://audio.guim.co.uk/2016/03/09-56789-gdn.tech.160309.sb.tinder-illuminati.mp3 loads and plays ok if pasted into a fresh browser tab.
- Deleting the https opt-in cookie and reloading in http the page and player worked ok

console errors:
![image](https://cloud.githubusercontent.com/assets/7239344/13784018/91e43d00-eac5-11e5-9f8f-d37ff65721f2.png)

**Comment by michaelwmcnamara** [comment]
Example here in the science section - better example as it doesnt need the https opt-in to generate the error

**Comment by jamesgorrie** [comment]
@fredex42 are we going to have to setup https for this too?

**Comment by fredex42** [comment]
I think that setting access-control-allow-origin: * as a header at Fastly should do the trick, that's what we did for video.  I have made the change as configuration version #6 to audio.guim.co.uk, please let James and I know if the error recurs.

**Comment by ScottPainterGNM** [comment]
Hey @fredex42 I've just retried that podcast and seeing the same issue:

![image](https://cloud.githubusercontent.com/assets/11922253/14278403/67aad89a-fb1f-11e5-8d5f-7e9dcb9c5e75.png)

**Comment by johnduffell** [comment]
working now
