### ISSUE TITLE
"Show N more replies" button clicks are not tracked correctly due to DOM removal of button

### ISSUE THREAD

**Issue by dominickendrick** [guardian/frontend#12252]
# ISSUE

We cannot track clicks on the "Show more Comments" button is the comment area.
## Steps to Reproduce

Click on the "Show N more replies" button
## Actual Results (include screenshots)

<img width="1255" alt="screen shot 2016-03-15 at 11 44 50" src="https://cloud.githubusercontent.com/assets/1289259/13776646/3a963930-eaa3-11e5-96df-50e70ecf2add.png">
## Expected Results (include screenshots)

No errors, link tracked correctly
## URL

http://www.theguardian.com/world/2016/mar/15/russian-planes-preparing-to-leave-syria-defence-ministry-putin#_=_
## OS and Browser details
- Device: Macbook Pro (Mid 2014)
- Browser (inc version): Chrome:  48.0.2564.116 (64-bit)
- OS: OSX 10.10.4,

_Please add relevant labels_

**Comment by michaelwmcnamara** [comment]
@nicl  @NathanielBennett  This will make some of our tests difficult.

**Comment by SiAdcock** [comment]
Looks like this has since been fixed, feel free to reopen if not
