### ISSUE TITLE
Post Comment button styling text is mis-aligned

### ISSUE THREAD

**Issue by gidsg** [guardian/frontend#12308]
# ISSUE
Post Comment button styling text is mis-aligned

## Steps to Reproduce
* Sign in
* Go to http://www.theguardian.com/money/commentisfree/2016/mar/21/fear-cashless-world-contactless#comments

## Actual Results (include screenshots)

Post your comment button text is mis-aligned
<img width="820" alt="screen shot 2016-03-21 at 17 00 50" src="https://cloud.githubusercontent.com/assets/1764158/13926911/5688bcac-ef86-11e5-9a12-5e69ca3832cb.png">

## Expected Results (include screenshots)

Text is centred in button

## URL
http://www.theguardian.com/money/commentisfree/2016/mar/21/fear-cashless-world-contactless#comments

## OS and Browser details

Can reproduce in Firefox and Chrome

**Comment by mattandrews** [comment]
Yep, I spotted this too! Culprit is this CSS:

`padding: 0.6875rem 0.625rem`

**Comment by rich-nguyen** [comment]
Fixed in https://github.com/guardian/frontend/pull/12338
