### ISSUE TITLE
Missing poster images on AMP pages.

### ISSUE THREAD

**Issue by cramforce** [guardian/frontend#12358]
# ISSUE

Videos in AMP docs are missing a poster image.

## Steps to Reproduce

Visit AMP page with video.

## Actual Results (include screenshots)

Videos show a black poster frame.

## Expected Results (include screenshots)

Have a meaningful poster frame

## URL

https://amp.theguardian.com/world/2016/mar/26/man-charged-brussels-terror-attacks-faycal-c-belgian-barack-obama

## OS and Browser details

All

**Comment by gtrufitt** [comment]
Looks like there's a poster there now 👍 Cheers @cramforce
