### ISSUE TITLE
Comment permalink urls don't always jump to the correct comment

### ISSUE THREAD

**Issue by TBonnin** [guardian/frontend#12678]
# ISSUE
Permalink urls don't always jump to the correct comment, especially on the first load 

## Steps to Reproduce
1. Load permalink to a specific comment ex: `https://www.theguardian.com/technology/2016/apr/12/how-we-analysed-70m-comments-guardian-website#comment-72211137`

## Actual Results (include screenshots)
The page loads but doesn't jump to the comment

## Expected Results (include screenshots)
The page load and jump to the comment section

## URL
https://www.theguardian.com/technology/2016/apr/12/how-we-analysed-70m-comments-guardian-website#comment-72211137

## Note: 
If you hit return it tends to work the 2nd time, so probably a race condition related to how javascript loads

Thanks to @gidsg for reporting the issue.

**Comment by paperboyo** [comment]
Duplicate of https://github.com/guardian/frontend/issues/10471 and, probably, many more before it...

**Comment by gidsg** [comment]
Seems to be completely broken in Safari (not intermittently working)
This was reported by users and I have reproduced

**Comment by nicl** [comment]
@TBonnin any progress/update on this? User Help are still getting a lot of emails about this.

**Comment by TBonnin** [comment]
I haven't made this my priority at all to be honest. I am happy to revisit though

**Comment by ScottPainterGNM** [comment]
@gtrufitt is this closable now or still an issue?

**Comment by gtrufitt** [comment]
Still getting some reports, but I'm no longer able to replicate. Apparently on `http` pages the comments jump doesn't work for some users.

This url works for me on Safari: https://discussion.theguardian.com/comment-permalink/75097820

Does it work for you @ScottPainterGNM?

These specific urls were reported:

http://www.theguardian.com/us-news/2016/may/27/chelsea-manning-six-years-prison-whistleblowing
http://www.theguardian.com/commentisfree/2016/may/27/acned-letter-teenage-self-acne-philippa-perry
http://www.theguardian.com/commentisfree/2016/may/27/obama-apologise-hiroshima-lessons-bombed
http://www.theguardian.com/cities/2016/may/27/isis-palmyra-3d-technology-copy-rebuild-city-venice-biennale

**Comment by ScottPainterGNM** [comment]
That url you sent me didn't work at all on Safari, it just took me straight to the article

**Comment by gtrufitt** [comment]
What Safari?

**Comment by ScottPainterGNM** [comment]
9.0.1

**Comment by gtrufitt** [comment]
I'm re-closing this unless someone can show me this happening without any other discussion problems causing it. 💥  cc/ @paulbrown1982

**Comment by gidsg** [comment]
Re-opening as I can reliably reproduce this in Safari, if using this link: https://t.co/p9RUEm9FcS (seems to lose the `#` somewhere along the way) see also: https://twitter.com/rooreynolds/status/746971609366466561

**Comment by gtrufitt** [comment]
Ok. So I can replicate this on http:

http://www.theguardian.com/politics/live/2016/jun/25/brexit-live-emergency-meetings-eu-uk-leave-vote#comment-77205935

but not with

https://www.theguardian.com/politics/live/2016/jun/25/brexit-live-emergency-meetings-eu-uk-leave-vote#comment-77205935

@ScottPainterGNM Can you confirm that you're seeing the same? Odd that the http link is even being shared, I thought we were https everywhere now, how/why is someone sharing http?

Looks like the redirect is stripping the hash though which would be a back-end issue, not in the client-side JS I believe.

@JustinPinner @TBonnin - Anyone able to look at and confirm that going to http://www.theguardian.com/politics/live/2016/jun/25/brexit-live-emergency-meetings-eu-uk-leave-vote#comment-77205935 redirects to the https but strips the hash (and fix :))?

**Comment by gtrufitt** [comment]
Hmm.. Ok, apparently we are not on HTTPS yet on politics. Will investigate further.

**Comment by gtrufitt** [comment]
For reference: Some bug reports that sound eerily related:

- https://bugs.webkit.org/show_bug.cgi?id=24175
- https://bugs.webkit.org/show_bug.cgi?id=158420

**Comment by gidsg** [comment]
Arrgh, if this is a Safari problem there's not a simple fix but I guess we could for example:
* Stop using the permalink URLs and instead provide directly the link to the article with the `#`?
* Use frontend routing to create a URL with `/` instead of a hash which is resolvable

**Comment by gtrufitt** [comment]
Checking http://www.redirect-checker.org/index.php we see a 301 redirect without the hash:

```
https://discussion.theguardian.com/comment-permalink/77205935
302 Found
https://www.theguardian.com/politics/live/2016/jun/25/brexit-live-emergency-meetings-eu-uk-leave-vote#comment-77205935
301 
http://www.theguardian.com/politics/live/2016/jun/25/brexit-live-emergency-meetings-eu-uk-leave-vote
200 OK
```

```
https://discussion.theguardian.com/comment-permalink/77205935

HTTP/1.1 302 Found
Access-Control-Allow-Origin: *
Cache-Control: max-age=60
Content-Type: application/json; charset=UTF-8
Location: https://www.theguardian.com/politics/live/2016/jun/25/brexit-live-emergency-meetings-eu-uk-leave-vote#comment-77205935
Server: Jetty(9.2.z-SNAPSHOT)
Strict-Transport-Security: max-age=0
Via: 1.1 varnish
Fastly-Debug-Digest: 9767d0cb5904d6e1de37d25b254726cde6c498e7d7b13a859558f0db7247eba4
Content-Length: 0
Accept-Ranges: bytes
Date: Mon, 27 Jun 2016 11:06:23 GMT
Via: 1.1 varnish
Age: 7
Connection: keep-alive
X-Served-By: cache-lcy1121-LCY, cache-jfk1046-JFK
X-Cache: HIT, MISS
X-Cache-Hits: 1, 0

https://www.theguardian.com/politics/live/2016/jun/25/brexit-live-emergency-meetings-eu-uk-leave-vote#comment-77205935

HTTP/1.1 301 
Retry-After: 0
Content-Length: 0
Location: http://www.theguardian.com/politics/live/2016/jun/25/brexit-live-emergency-meetings-eu-uk-leave-vote
Accept-Ranges: bytes
Date: Mon, 27 Jun 2016 11:06:23 GMT
Via: 1.1 varnish
Connection: close
X-Served-By: cache-jfk1024-JFK
X-Cache: HIT
X-Cache-Hits: 0
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy-Report-Only: default-src https:; script-src https: 'unsafe-inline' 'unsafe-eval'; style-src https: 'unsafe-inline'; img-src https: data:; font-src https: data:; connect-src https: wss:; report-uri https://beacon.guim.co.uk/csp-report

http://www.theguardian.com/politics/live/2016/jun/25/brexit-live-emergency-meetings-eu-uk-leave-vote

HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
ETag: W/"hash-5077943309597271607"
Expires: Mon, 27 Jun 2016 10:11:22 GMT
X-Gu-Backend-App: article
Via: 1.1 varnish
Fastly-Debug-Digest: 5cacfb267e0bf76514cc08d02707fc2e57c2e623d1b538c9017f7b77b8dc8921
Content-Length: 656334
Accept-Ranges: bytes
Date: Mon, 27 Jun 2016 11:06:23 GMT
Via: 1.1 varnish
Age: 3361
Connection: keep-alive
Set-Cookie: GU_mvt_id=177493; expires=Sun, 25 Sep 2016 11:06:23 GMT; path=/; domain=.theguardian.com
X-Served-By: cache-lcy1133-LCY, cache-jfk1026-JFK
X-Cache: HIT, HIT
X-Cache-Hits: 1, 1
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-GU-Edition: us
Cache-Control: max-age=60, stale-while-revalidate=6, stale-if-error=864000, private
Vary: Accept-Encoding,User-Agent
X-GU-Platform: next-gen-router
Set-Cookie: GU_geo_continent=NA; path=/;
```

**Comment by gidsg** [comment]
Looks like according to this spec, the user agent is supposed to append the fragment from the original URL. https://www.w3.org/TR/cuap#uri so I think this points to an issue of Safari failing to do this.

**Comment by gtrufitt** [comment]
Yeah, you're right. Almost definitely the Safari bug then. We'll have to discuss workarounds with @nicl and someone from dotcom that knows more of the history about your suggestions @gidsg. In the meantime I'll update that webkit bug with our usecase
