### ISSUE TITLE
Add save-for-later to top of long reads

### ISSUE THREAD

**Issue by sndrs** [guardian/frontend#12700]
## Steps to Reproduce

see https://www.theguardian.com/technology/2016/apr/27/how-uber-conquered-london for example. it's not much use down there.

we should add it to the top of the article too.

**Comment by paperboyo** [comment]
+1 My thoughts exactly.

While I understand the general, if silent, consensus that our byline area is super-busy and prevents one from reaching the important content quickly and a general, if under the radar, tries to slim it down with every new design idea, I find some of these tries lacking (e.g. image caption/credit missing on immersive template). Just sayin’.

**Comment by paulrobertlloyd** [comment]
+1, as I mentioned here: https://twitter.com/paulrobertlloyd/status/725275047393419265

It is strange that a reader can save a wire story for latter yet for original, long-form content, this functionality is hidden:

<img width="660" alt="screen shot 2016-04-28 at 14 35 25" src="https://cloud.githubusercontent.com/assets/813383/14887677/c3f3c9b8-0d4e-11e6-9af9-8d38f263e739.png">

<img width="660" alt="screen shot 2016-04-28 at 14 35 53" src="https://cloud.githubusercontent.com/assets/813383/14887698/d514aed8-0d4e-11e6-8c1e-9ea2ad824f8b.png">

Oh, and if you’re worried about having a crowded byline, feel free to remove the ~~malware~~ sharing links ;-)

**Comment by sammorrisdesign** [comment]
Can we look at how often people use Save For Later. I understand if we're going to support it we should do it everywhere. But I'd be curious to know of people that save articles and go back to read them.

If not, next to the share icons makes sense. Maybe we should remove Pinterest, LinkedIn, Google+ (again dependent on use maybe).

**Comment by paperboyo** [comment]
Maybe they should all be rolled into one share icon that expands on click/tap?

**Comment by mchv** [comment]
@paperboyo @sammorrisdesign @chriswilk we are monitoring share icons performance and we are planning to tidy up in the future. please don't remove any of them in the meantime.

**Comment by paperboyo** [comment]
+ @piuccio, just-in-case ^

**Comment by piuccio** [comment]
@paperboyo  I don't see myself implementing this in the nearest future 😁

**Comment by paperboyo** [comment]
@piuccio "Just-in-case: meant "just in case of implementing the removal", not the feature! 😆

**Comment by ScottPainterGNM** [comment]
@michaelmcnamara

**Comment by paperboyo** [comment]
Fixed _via_ https://github.com/guardian/frontend/pull/14914. Safe to close?
