### ISSUE TITLE
New video container UI bug

### ISSUE THREAD

**Issue by regiskuckaertz** [guardian/frontend#12819]
I see this on the network front:
<img width="1038" alt="screen shot 2016-05-09 at 08 03 55" src="https://cloud.githubusercontent.com/assets/629976/15105825/c492d578-15bc-11e6-994d-4887270706bc.png">

The navigation arrows won't let me click to play the video.

**Comment by paperboyo** [comment]
Oh, never seen this. Mind sending browser, OS and window size details, pls?

**Comment by paperboyo** [comment]
No nevermind. Confirmed in Firefox, Chrome; Win10. Maybe it’s because of the Nest takeover (or whatever this thing is called)?

**Comment by regiskuckaertz** [comment]
Yeah the pageskin is squeezing everything in tablet mode 😨

**Comment by ScottPainterGNM** [comment]
This has been fixed
