### ISSUE TITLE
Media type icon shown on headlines within immersive headers is too small

### ISSUE THREAD

**Issue by paulrobertlloyd** [guardian/frontend#12848]
# ISSUE
The type icon shown on headlines within immersive headers is shown too small.

## Steps to Reproduce
Icon appears too small across all breakpoints. Suspect the article I’ve seen is the first example of the gallery article type with the immersive header.

## Actual Results (include screenshots)
<img width="230" alt="screen shot 2016-05-11 at 11 18 48" src="https://cloud.githubusercontent.com/assets/813383/15177906/6d5dd3ac-176a-11e6-9cb1-15f340d8bcf3.png">

## Expected Results (include screenshots)
(I’d expect the icon to match the size of the headline)

## URL
http://www.theguardian.com/us-news/gallery/2016/may/10/george-w-bush-september-11-pictures-gallery

**Comment by paulrobertlloyd** [comment]
Oh wait, is this is a new header style used across all gallery articles? Was getting it confused with the featured articles that show a poster image above the fold… which is possibly a separate issue ;-)

**Comment by NataliaLKB** [comment]
@paulrobertlloyd is this still an issue? If not, can I close this?

**Comment by jamesgorrie** [comment]
@NataliaLKB I would say no through a few tests.

**Comment by NataliaLKB** [comment]
Okay closing this, but please reopen if you still see any issues @paulrobertlloyd

**Comment by paulrobertlloyd** [comment]
Yep, this appears fixed now. Thanks!
