### ISSUE TITLE
"More from" a video series doesn't stack correctly

### ISSUE THREAD

**Issue by Jholder112233** [guardian/frontend#12912]
# ISSUE

<img width="376" alt="screen shot 2016-05-16 at 09 42 59" src="https://cloud.githubusercontent.com/assets/2236852/15284684/bec9ecec-1b4a-11e6-89f6-3168370194cb.png">
Potentially seems one of the stories is missing a trail image and so the the grid breaks down.

Note: that story is also missing a trail image in the endslate:
<img width="711" alt="screen shot 2016-05-16 at 09 46 33" src="https://cloud.githubusercontent.com/assets/2236852/15284732/21a3641a-1b4b-11e6-89b9-9baf1bd03410.png">
## URL

http://www.theguardian.com/global-development/video/2016/may/16/why-do-women-still-die-in-childbirth-asks-emily-watson-video
## OS and Browser details
- Browser (inc version): Chrome 50
- OS: OS X 10.11

cc @jamesgorrie

**Comment by ScottPainterGNM** [comment]
@jamesgorrie Did this move into prod or has the test now closed?

**Comment by jamesgorrie** [comment]
It's not a test anymore.
The problem here is that those bits of content don't have holding images - potentially worth thinking about a fallback UI.

**Comment by jamesgorrie** [comment]
p.s. Nothing to do with the "more from" test - this has always been the case.

**Comment by SiAdcock** [comment]
Looks like this layout has changed and this is no longer a problem.. perhaps we can close this. @michaelmcnamara @ScottPainterGNM are you able to confirm?

**Comment by ScottPainterGNM** [comment]
@SiAdcock I think we are good to close here.
