### ISSUE TITLE
Video disabled on Opera Mini for Android "high" data savings mode

### ISSUE THREAD

**Issue by ressawyj** [guardian/frontend#13016]
# ISSUE
New versions of Opera Mini on Android include a new "high" data savings mode where web content is rendered by an Android WebView rather than using the Opera Mini server-side rendering. I am no web developer, but I believe an over-zealous feature detection script may be disabling video for users of Opera Mini using the "high" data savings mode. WebKit on Android 4.2+ should support HTML5 video and users of Android 5+ have auto-updated Chromium rendering WebViews, currently at version 50. If you press the video player controls before the player and it's associated scripts have fully loaded, Opera Mini has no problem at all playing back video, albeit, behind a "your browser is not supported" message. Opera Mini is a very useful browser even in the UK due to the speed of rural 3G and 2G connections.

## Steps to Reproduce
Load any video on guardian.co.uk using the "high" data savings mode in Opera Mini on Android.

## Actual Results (include screenshots)
Without user intervention, the video is disabled and replaced with a "your browser is not supported" message. Tapping the player controls before the page has fully loaded can start and successfully play the video, behind the "your browser is not supported" message.

Initial state before full page load.
![Initial state before full page load.](https://cloud.githubusercontent.com/assets/12541776/15447918/00d4114c-1f49-11e6-919b-8ae9f3cf59a2.png)

Video disabled.
![Video disabled.](https://cloud.githubusercontent.com/assets/12541776/15447919/00d9b73c-1f49-11e6-91f8-b917b5a86c60.png)

Video playing behind message.
![Video playing behind message.](https://cloud.githubusercontent.com/assets/12541776/15447920/00da5962-1f49-11e6-8646-3c78fa507fc6.png)

Screen capture video of succesful playback behind message.
https://drive.google.com/file/d/0B4uT6GnMN--hdDlETy1sdmRyWU0/view?usp=sharing

## Expected Results (include screenshots)
Expected result is that the video plays normally (like in Chrome for Android) as the rendering engine can fully support playing the video.

## URL
http://www.theguardian.com/world/2016/may/20/egyptian-military-says-debris-from-egyptair-flight-ms804-found-in-sea

## OS and Browser details

- Device: Sony Xperia Z2
- Browser (inc version): Opera Mini Android 16.0.2.2168.103662, Chromium 50
- OS: Android 6.0.1

*Please add relevant labels*

**Comment by jamesgorrie** [comment]
Thanks for reporting this @ressawyj - this should all be working now.
