### ISSUE TITLE
Play icon not optically centered

### ISSUE THREAD

**Issue by regiskuckaertz** [guardian/frontend#13098]
In the new video container, the icon is geometrically centered giving the illusion of leaning on the left:

<img width="358" alt="screen shot 2016-05-26 at 21 05 00" src="https://cloud.githubusercontent.com/assets/629976/15588600/98fa9e0a-2386-11e6-87ac-84a4b1c835b4.png">

**Comment by ScottPainterGNM** [comment]
@akash1810 @jamesgorrie

**Comment by akash1810** [comment]
reminds me of this cool project - http://javier.xyz/visual-center/

**Comment by regiskuckaertz** [comment]
nice! bookmarked 😃 🔖

**Comment by jamesgorrie** [comment]
@blongden73 - Do you want to catch up about this?

I am thinking the solution might be to not use the "sometimes makes politicians look like lollipops" play button, and potentially sync up with the app design.

**Comment by ScottPainterGNM** [comment]
This was fixed Zef so closing off.
