### ISSUE TITLE
Greedy CSS rule

### ISSUE THREAD

**Issue by regiskuckaertz** [guardian/frontend#13286]
# ISSUE

## Steps to Reproduce

The `.from-content-api h2` rule has side-effects in components it should not touch, one of which is [the inline merchandise](http://m.code.dev-theguardian.com/politics/2016/apr/12/dont-judge-politicians-by-their-tax-returns-says-william-hague?google_preview=hLruxlaTqk4YgLv_ugUwgNe0wgWIAYCAgKCzqKnqbQ&iu=59666047&gdfp_req=1&lineItemId=123216807&creativeId=93009006567).

I suggest using the child selector instead, `.from-content-api > h2`.

## Actual Results (include screenshots)

![picture 2](https://cloud.githubusercontent.com/assets/629976/16039856/340002d6-3224-11e6-9d3a-3a2f0969ea45.jpg)

## Expected Results (include screenshots)

![picture 3](https://cloud.githubusercontent.com/assets/629976/16039872/50960f62-3224-11e6-83cb-eea875b2a35b.jpg)

**Comment by sndrs** [comment]
child selector massively ties it the to the underlying HTML structure. ideally, you could move the logic to the template and give it a unique class

**Comment by regiskuckaertz** [comment]
The thing is `.from-content-api` is added to the `DIV` surrounding all the
content, giving it a large scope. As a consequence, shouldn't it take care
not to target unwanted elements?

On Tue, 14 Jun 2016 at 11:53 Alex Sanders <notifications@github.com> wrote:

> child selector massively ties it the to the underlying HTML structure.
> ideally, you could move the logic to the template and give it a unique class
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/guardian/frontend/issues/13286#issuecomment-225846893>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAmc2OfY4P0NIFWgsIChuEiTge-bGR_jks5qLogdgaJpZM4I1LzW>
> .
>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by katebee** [comment]
Found this occurring on the GLabs ad component; think it is the same issue.

<img width="478" alt="" src="https://cloud.githubusercontent.com/assets/8607683/16149044/e558dc66-3485-11e6-8cfb-600826d1466e.png">

**Comment by regiskuckaertz** [comment]
Hello. Any hope this might get solved?

We've had another example in immersive articles:

![unnamed](https://cloud.githubusercontent.com/assets/629976/16199321/092fb862-3701-11e6-8322-e0724b44725a.jpg)

If that's too much of a hassle, we can typeset titles inside ads, but I'd prefer not to (we'd be tied to every `.from-content-api` update).

**Comment by regiskuckaertz** [comment]
@sndrs pinging you on this one. I really feel like it's the responsibility of `.from-content-api` to only target elements it wants to target and nothing more.
