### ISSUE TITLE
Font rendering

### ISSUE THREAD

**Issue by garrilla** [guardian/frontend#13334]
# Issue

Web Font not rendering cleanly

## Steps to reproduce
View website 

## Actual Results (include screenshots)

![image](https://cloud.githubusercontent.com/assets/5795139/16171217/604b11a6-3561-11e6-89fc-8c86f69fc39a.png)

## Expected Results (include screenshots)

clean rendering of anti-aliased fonts

## URL
http://www.theguardian.com/uk

## OS and Browser details

- Device: Laptop
- Browser (inc version): Chrome Version 51.0.2704.103 m (64-bit) 
- OS:  Windows 10 Home (1511 - 10586.420 64bit)

*Please add relevant labels*

**Comment by sndrs** [comment]
cc @paperboyo

**Comment by paperboyo** [comment]
Hi, @garrilla. It looks like your font smoothing settings (and/or ClearType) are turned off. They need to be on to allow for better font rendering. E.g. http://www.isunshare.com/windows-10/choose-whether-to-smooth-edges-of-screen-fonts-in-windows-10.html & http://www.isunshare.com/windows-10/turn-off-or-on-clear-type-text-in-windows-10.html. Please let us know whether it worked for you.

Regards
Mateusz

**Comment by paperboyo** [comment]
This is safe to close. As far as I know, there are two reasons for something like that or similar to happen, both Windows only:
- Smooth edges of screen fonts switched off in Advanced system settings>Performance (all but Microsoft browsers)
- Firefox with not working/switched off Hardware Acceleration

In the first case, thanks to @sndrs, we have a clever mechanisms that will switch off webfonts altogether for a period of time (and then - re-check).
In the second case, we may look into introducing a similar sniffing mechanism, see https://github.com/xodigital/Firefox-HWA

Irrespectively, we may also want to surface the webfonts on/off switch in User accessibility preferences.
