### ISSUE TITLE
'undefined' appearing in euro 2016 round of 16 results

### ISSUE THREAD

**Issue by regiskuckaertz** [guardian/frontend#13412]
<img width="251" alt="screen shot 2016-06-25 at 20 01 15" src="https://cloud.githubusercontent.com/assets/629976/16358312/b7877b9a-3b0f-11e6-8fe1-f3a2765e3568.png">

**Comment by michaelwmcnamara** [comment]
moved to bugs trello board https://trello.com/c/OcLwzffd/3-undefined-appearing-in-euro-2016-round-of-16-results
