### ISSUE TITLE
video embeds on a page should not load fully until user selects to play video

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#13422]
# ISSUE

The page weight of pages with many videos is far too high. 
the gifs that keep on giving series is a good example of this - 
this page https://www.theguardian.com/sport/2016/jun/25/gifs-giving-roy-keane-diving-football-baseball
weighs 8.3MB on both mobile and desktop without ads. 
The reason for this is that all of the videos download their full content with the page, instead of waiting for the user to click play. As a result the user is paying to download content that he doesn't actually want.

This is also a problem on article pages that happen to have one of our videos,  but is especially annoying on the .gifs that keep on giving pages because someone has gone to all the effort of converting these gifs into videos, however, because we then load the whole video on the page, we lose the benefit of their efforts.

On fronts we use a placeholder for the video and only load the video when the user clicks play. This keeps the page light and allows large numbers of videos to be present without a performance hit.
We should do the same with video embeds on content pages.
## Steps to Reproduce

Go to https://www.theguardian.com/sport/2016/jun/25/gifs-giving-roy-keane-diving-football-baseball
or another page with a guardian video embedded somewhere. Do not do anything with the page or press play on the video
Open debugging tools - network tab - sort by size and marvel at the size of these things!
## Actual Results (include screenshots)

![image](https://cloud.githubusercontent.com/assets/7239344/16386954/92da1308-3c8a-11e6-871b-a5a95c55f6b7.png)
## Expected Results (include screenshots)

Video content should not be downloaded on content pages that are not video pages until the user presses play. This is the behaviour for 3rd party video embeds - ie youtube, and we should follow suit for the same reasons. 
## URL

https://www.theguardian.com/sport/2016/jun/25/gifs-giving-roy-keane-diving-football-baseball
## OS and Browser details

All of the browsers and devices, but chrome gives best debugging info so use that.

**Comment by jamesgorrie** [comment]
These are actually something different - they're not video embeds but rather normal embeds with HTML in them.

I will have a chat with Paul C to see if he can make sure he puts `preload="metadata"` on the videos to get around this.

I have updated that article with that - see what you think?

**Comment by michaelwmcnamara** [comment]
@jamesgorrie 
Hi mate, 
Thanks for looking at this. At the moment I cant see any difference on the article. It still downloads the full weight of the videos.

**Comment by michaelwmcnamara** [comment]
This still needs to be fixed.
mobile pages such as http://www.theguardian.com/sport/2016/jul/16/gifs-giving-cristiano-ronaldo-olivier-giroud-football are weighing in at 14.5MB with no ads - this is without the user pressing play on anything, just hitting the page.
Currently this would cost a user in the US just under a dollar on a postpaid mobile plan and US$1.46 on a prepaid plan. Just for landing on the page

**Comment by SiAdcock** [comment]
I've retested this: the full video download behaviour is no longer occurring, and the total file size of videos is way smaller than it was 2 years ago! I only tested on Chrome desktop, please let me know if you spot this behaviour happening on any specific browser.

Going forward, most videos will be hosted on YouTube using YouTube's player, which is very good at optimising page weight.

**Comment by paperboyo** [comment]
> YouTube's player, which is very good at optimising page weight

Hmmmmmmm.

**Comment by SiAdcock** [comment]
Haha! I must admit, I just assumed YouTube would be doing something clever around optimisation, like Vimeo does. If it doesn't now, then surely at some point... it will do? I mean, it's more likely they'll fix this before we do... right?
