### ISSUE TITLE
Lightbox opening icon broken

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#13452]
Hello,

Helmut Kohl does not seem entirely happy about the extra dark innercircle in the below icon that appeared recently on the site (Brexit is enough of a worry):
![kohl not happy](https://cloud.githubusercontent.com/assets/6032869/16502527/27481360-3f0f-11e6-8edb-4b55e89fa478.PNG)
[all platforms, URL: https://www.theguardian.com/world/2016/jun/30/slovakia-foreign-minister-eu-support-measure-stop-brexit]

Maybe we could take this opportunity to revisit the icon itself? It recently disappeared from gallery pages. While I totally understand that it obstructs images, unfortunately the lack of it also makes the Lightbox less discoverable. And that goes against my sick plan to turn the Lighbox into an app that will provide a whole new parallel way to browse all Guardian content through multimedia and make us loadsamoney.

No rush on making money, though, we can just remove the extra dark circle :wink:

Regards
Mateusz

**Comment by NataliaLKB** [comment]
@thanks @paperboyo and @sndrs for originally noticing this. I have a PR open to fix it now.

**Comment by paperboyo** [comment]
Thanks a lot, @NataliaLKB!

**Comment by NataliaLKB** [comment]
Yay! If you check:

http://router-prod.gu-web.net/world/2016/jun/30/slovakia-foreign-minister-eu-support-measure-stop-brexit

It is all fixed

![image](https://cloud.githubusercontent.com/assets/8774970/16619711/39e33546-4387-11e6-9dc1-efc58076dc11.png)
