### ISSUE TITLE
config.page.isSSL is always false

### ISSUE THREAD

**Issue by regiskuckaertz** [guardian/frontend#13535]
Even on HTTPS pages. We have [a condition](https://github.com/guardian/frontend/blob/7c72f21c629df2c6608078d0dd92abe13cbcb022/static/src/javascripts/projects/common/modules/commercial/commercial-features.js#L20) where all DFP advertising is disabled if the page is secure, but the flag is always false so we never had to remove that test.

I'm removing it, but you might want to fix the flag too.

**Comment by rich-nguyen** [comment]
That's a bit of legacy confusion. For servers which are wholly secure, like identity, `config.page.isSSL`. This config doesn't indicate anything userful about servers that render pages as 'secure', in the sense of theguardian.com's https migration.

**Comment by regiskuckaertz** [comment]
I see. Closing this issue then.
