### ISSUE TITLE
Users confuse username and password fields when signing up

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#13548]
There are a number of complaints from users who believe their password is visible after signing up.
Upon investigation, it turns out that they have confused the username and password fields on the signup form. 
We need to revisit the design of this page and make it clearer to users which field is which

**Comment by ScottPainterGNM** [comment]
This is definitely true but don't identity manage the sign up pages? Might need to be raised with them and not on frontend itself.

**Comment by ScottPainterGNM** [comment]
Closing this as this is an issue in identity-frontend not the main frontend site but looking at possible solution now.
