### ISSUE TITLE
Cannot get janus credentials for frontend

### ISSUE THREAD

**Issue by irukukagika** [guardian/frontend#13691]
I am following the steps to setup on my local server, but I cannot get credential since the link gives me  a 404.

**Comment by johnduffell** [comment]
Are you working at the guardian? If not,  Janus is an internal tool for accessing our accounts, unfortunately you would need to set up your own AWS account with the right files in S3 to get things running yourself.

**Comment by irukukagika** [comment]
Oh, I see, sorry and thanks for the feedback.

**Comment by johnduffell** [comment]
No problem, unfortunately we don't have the dev time to make it properly open source, more "working in the open".  However if you really want to try, you can just about get it running to view Articles if you sign up for a Content API key http://open-platform.theguardian.com/access/  However it's not really documented too well!

**Comment by irukukagika** [comment]
Thanks, I will try that

**Comment by goonux** [comment]
Hi @johnduffell,  in present, does your app public as open source software?
I want try to install the front-end on my local computer but it doesn't work.
![guardian-error](https://user-images.githubusercontent.com/8654203/65417558-87338400-de24-11e9-8be3-70179e5d03b8.png)
Could you take a look at this and give me an advice?
