### ISSUE TITLE
Layout issues on the profile page when using mobile or tablet

### ISSUE THREAD

**Issue by katebee** [guardian/frontend#13717]
# ISSUE

Layout issues on the profile page when using a narrow device.
## Steps to Reproduce

Navigate to https://profile.theguardian.com/membership/edit on a tablet or mobile device (or use dev tools)
## Actual Results (include screenshots)

<img width="355" alt="picture 128" src="https://cloud.githubusercontent.com/assets/8607683/17106027/96e81064-5281-11e6-976e-219c574acab8.png">
## Expected Results (include screenshots)
- Margins between submit buttons
- Consistent tab height
- Membership text should not overflow the tab

<img width="351" alt="picture 130" src="https://cloud.githubusercontent.com/assets/8607683/17106599/d0314ce4-5283-11e6-883f-ca0c0942b2ca.png">
## OS and Browser details
- Device: Nexus 5X
- Browser (inc version): Google Chrome 51
- OS: Android 6.0.1

**Comment by ScottPainterGNM** [comment]
Have referred to the Membership team (which now encompasses identity-frontend work also)

**Comment by SiAdcock** [comment]
This has now been fixed 🎉 

<img width="632" alt="screen shot 2018-08-01 at 22 00 17" src="https://user-images.githubusercontent.com/5931528/43548655-64c1c0cc-95d6-11e8-9053-8eebd2cbf42f.png">
