### ISSUE TITLE
No compatible source was found for this video

### ISSUE THREAD

**Issue by zenonp** [guardian/frontend#13782]
Since about a month more or less, all new videos on the Guardian display "No compatible source was found for this video" in Firefox ESR 45.2.0 on Centos7. Screenshot attached. 
![no-compatible-source](https://cloud.githubusercontent.com/assets/10004285/17273288/5bd8f192-56b8-11e6-8923-c6cd84b227b5.png)

This is a Guardian-specific problem (and Twitter has the same, reporting along the lines of "your browser is not compatible with this video format"). I have not encountered it on any other sites. I suspect that both sites are trying to be too smart in their choice of video format they serve to the browser and, when an unknown combination of OS and browser comes along, they lack a failsafe fallback. 

In any case, for the past five years and up to about a month ago this problem did not exist. Whatever you changed in the meanwhile was a bad move and the obvious quick and easy fix is to revert the change until you can figure out the root cause of the problem.

**Comment by gidsg** [comment]
@akash1810 maybe this is related to the webm removal?

**Comment by akash1810** [comment]
@gids webm still exists, we removed 3gp. I don't think 3gp removal would cause this as we weren't setting the correct mime-type on these assets, so the browser didn't understand it anyway.

This may have something to do with the multimedia api? Or maybe the issue fastly contacted us about?

**Comment by gidsg** [comment]
@zenonp can you still reproduce this issue? Does it happen consistently for videos linked from: https://www.theguardian.com/video ?

**Comment by zenonp** [comment]
> can you still reproduce this issue? Does it happen consistently for videos linked from: https://www.theguardian.com/video ?

Yes to both questions. Here's a fresh example: 

![no-video-20160831a](https://cloud.githubusercontent.com/assets/10004285/18127351/895103c4-6f88-11e6-8235-f6bc493abe87.png)

It now also goes [back to a time](https://www.theguardian.com/video?page=100) when video (flash, I suspect) did work - but now does not. 

See also FF bugzilla [1233335](https://bugzilla.mozilla.org/show_bug.cgi?id=1233335) and [1233429](https://bugzilla.mozilla.org/show_bug.cgi?id=1233429); they might be related. Note that media.fragmented* no loger exists in FF ESR 45.3.0, while media.mediasource.webm*.enabled=true makes things even worse: it doesn't play webm and it prevents flash from being served instead (e.g. at youtube).

**Comment by zenonp** [comment]
>  webm still exists, we removed 3gp.

But it seems that you also removed flash. We can all agree that it's an obsolete proprietary format that should be removed in the long run, but if its removal coincides with a firefox bug that cripples HTML5 video, it was premature.

**Comment by akash1810** [comment]
Hi @zenonp, are you still experiencing this issue? Sadly, we have not been able to reproduce it.

**Comment by zenonp** [comment]
Since firefox 45.7 ESR was released a few weeks ago *and* I uninstalled flash at the same time, I no longer have the problem.

**Comment by akash1810** [comment]
@zenonp thank you for the update, its interesting that you've had to uninstall flash (though this is a good thing anyway!). I'll close this for now. Please comment/raise a new issue if you encounter this problem again.
