### ISSUE TITLE
Missing from the docs

### ISSUE THREAD

**Issue by rjmk** [guardian/frontend#14272]
I've had a think, but it's not apparent to me exactly where to put the following in the docs:
- `etc/gu/install_vars` is needed and needs to contain `STAGE=DEV`
- The `aws` cli needs to be installed. When installed via `pip`, I also needed to add `/Library/Frameworks/Python.framework/Versions/Current/bin` to my `$PATH`

Any advice, @TBonnin?

**Comment by TBonnin** [comment]
@johnduffell why creating `install_vars` has been removed from `setup.sh` https://github.com/guardian/frontend/commit/69359123081a850773b5c00075b7fe2326b73e5e#diff-6aa367da3fdfc952b15def7759aa5f0b

**Comment by johnduffell** [comment]
not needed locally afaik, it should default to dev - having said that, maybe I didn't quite test that properly and perhaps it errs now.  If so, then it should be fixable as that was the intention.

**Comment by rjmk** [comment]
We attempt to read the properties from `etc/gu/install_vars` both in the class `GuardianConfiguration` and its companion object. The class guards the non-existence of the file nicely, but the object does not. Only `stage` appears to be checked in the class. Perhaps it would be possible to replace the logic in the object with that in the object. Then we could drop the reading in the class and only read the stage variable from the class?

**Comment by johnduffell** [comment]
yes, I must have missed the additional check, and also missed that the class is also using the same file.  So if you fix them as you say hopefully everything will be good!

**Comment by rjmk** [comment]
I have the fix locally, just working on stripping out the duplication :)

**Comment by johnduffell** [comment]
great, thanks very much for spotting it and fixing it up!

**Comment by jfsoul** [comment]
@rjmk is this now resolved?

**Comment by rjmk** [comment]
I'll raise a PR adding the AWS CLI info, and then should be good to close
