### ISSUE TITLE
Bad colour contrasts in advertisement features

### ISSUE THREAD

**Issue by regiskuckaertz** [guardian/frontend#14283]
# ISSUE

## Steps to Reproduce

https://www.theguardian.com/savour-the-moment/2016/sep/09/seven-film-noir-classics-for-you-to-savour

## Actual Results (include screenshots)

![picture 1](https://cloud.githubusercontent.com/assets/629976/18483268/3b50da52-79db-11e6-8ef2-bdec64444740.jpg)

**Comment by lps88** [comment]
I noticed this one too, it make my eyes hurt:
https://www.theguardian.com/leffe-rediscover-time/ng-interactive/2016/jul/08/15-ways-to-have-a-slow-summer-interactive
![image](https://cloud.githubusercontent.com/assets/6290008/18592030/f85728d8-7c2c-11e6-9332-fbade7905e6c.png)

**Comment by ScottPainterGNM** [comment]
Pretty sure this is now fixed, it was a bug because related content was incorrectly pulling editorial content and has now been switched back. Closing off unless anybody sees a new instance of this.
