### ISSUE TITLE
Multiple containers broken with page skin

### ISSUE THREAD

**Issue by regiskuckaertz** [guardian/frontend#14865]
As seen [here](https://www.theguardian.com/us?adtest=6) (might disappear soon, seen on FF 49)

First the contribution message:
![picture 6](https://cloud.githubusercontent.com/assets/629976/19961933/32d9fd1e-a1ad-11e6-82aa-d2dc0a89d114.jpg)

Then, the Counted ad:
![picture 5](https://cloud.githubusercontent.com/assets/629976/19961945/3f6cc6ba-a1ad-11e6-8edf-c6fc6f477f51.jpg)

Then, the Minute ad:
![picture 4](https://cloud.githubusercontent.com/assets/629976/19961955/4a9d540a-a1ad-11e6-9087-77f66f9025ab.jpg)

And finally, on the left-hand side here:
![picture 3](https://cloud.githubusercontent.com/assets/629976/19961978/5422ab60-a1ad-11e6-8116-922fa6b9739b.jpg)

Aaaand forgot this one at the top:
![picture 7](https://cloud.githubusercontent.com/assets/629976/19962033/a9dce318-a1ad-11e6-8d9e-ff834fcc5659.jpg)

**Comment by regiskuckaertz** [comment]
Checking it to see if anything is in the pipe here? There is a HPTO on the UK front and the contributions banner is still broken.

**Comment by regiskuckaertz** [comment]
... meanwhile, it has been removed. Problem solved 😆

**Comment by duarte** [comment]
Just saw this thread — last week on the day this broke I updated the thrashers in the UK front.

See https://github.com/guardian/thrashers/commit/c89d7c2ac3a3e99a53d519a10fe0363841f5afc5 & https://github.com/guardian/thrashers/commit/5debdb829d7af23c4852c5de2ceb453293e85875

This involved tweaking the wide breakpoint CSS when the .has-page-skin class is present. I think there might be a way to automate this a bit more, but am not sure exactly how…

CC @gtrufitt

**Comment by gtrufitt** [comment]
@duarte Is this handled in thrashers now?

**Comment by SiAdcock** [comment]
I guess these thrashers are no longer used, so are unlikely to cause us further problems? 

We probably do need a better system for reporting issues in thrashers. At the moment the best strategy is to let Dotcom Platform know so we can track down the specific developer or designer who worked on the problematic thrasher.
