### ISSUE TITLE
Missing properties on RSS media enclosures

### ISSUE THREAD

**Issue by misja** [guardian/frontend#15053]
# Missing properties on RSS media enclosures

Some media properties are missing from RSS feed enclosures, most notably `height`and `type`.

## Steps to Reproduce

Any feed with media enclosures will have some missing properties, e.g. a sample enclosure from feed url  [https://www.theguardian.com/video](https://www.theguardian.com/video/rss):

```xml
<media:content width="140" url="https://i.guim.co.uk/img/media/9b7e597a1e77c3fc959f9d0f70eed2eb2c04c952/0_0_1800_1080/master/1800.jpg?w=140&q=55&auto=format&usm=12&fit=max&s=4867df5330d3ffcf203a233547e03677">
<media:credit scheme="urn:ebu">Photograph: Guardian</media:credit>
</media:content>
```

## Expected Results

Expected output for the given sample above would be:

```xml
<media:content width="140" height="84" type="image/jpeg" url="https://i.guim.co.uk/img/media/9b7e597a1e77c3fc959f9d0f70eed2eb2c04c952/0_0_1800_1080/master/1800.jpg?w=140&q=55&auto=format&usm=12&fit=max&s=4867df5330d3ffcf203a233547e03677">
<media:credit scheme="urn:ebu">Photograph: Guardian</media:credit>
</media:content>
```

**Comment by TBonnin** [comment]
Thank you @misja for your report.

`height`, `type` and several other attributes are [optional](http://www.rssboard.org/media-rss#media-content). Therefore it is not required to always provide them all.

**Comment by misja** [comment]
Thanks for looking into this. Pity though, would have made life easier on the client side :)
