### ISSUE TITLE
Youtube atoms missing caption icon

### ISSUE THREAD

**Issue by gidsg** [guardian/frontend#15253]
# ISSUE

## Steps to Reproduce
Go to: http://www.theguardian.com/science/grrlscientist/2012/aug/07/3

## Actual Results (include screenshots)
No icon next to caption
<img width="677" alt="screen shot 2016-12-07 at 14 03 49" src="https://cloud.githubusercontent.com/assets/1764158/20970582/32963db0-bc86-11e6-8683-98a4956a302e.png">

## Expected Results (include screenshots)
Icon next to caption (as per other content types)
@zeftilldeath please can you advise what class to use here if we need to change it?

## URL
http://www.theguardian.com/science/grrlscientist/2012/aug/07/3
CC @markjamesbutler @zeftilldeath

**Comment by paperboyo** [comment]
Isn't this fixed and safe to close, @gidsg?

**Comment by gidsg** [comment]
Yes looks like this is fixed.
