### ISSUE TITLE
Sticky ad banner doesn't reliably prevent page jump

### ISSUE THREAD

**Issue by OliverJAsh** [guardian/frontend#15438]
Hey all! :-)

Just found a small bug in the sticky ad banner and thought it was worth raising here!

You can see in the recorded gif below that, when a large banner ad loads (it takes awhile), the page jumps and, as a user, I lose my reading position.

I recall we used `window.scrollTop` to offset the scroll position when loading larger banner ads. Is that still the case? Note that this does seem to work some of the time.

![untitled](https://cloud.githubusercontent.com/assets/921609/21459680/622fe260-c938-11e6-99d0-f907f8b6db96.gif)

**Comment by gtrufitt** [comment]
Looks fixed! 💃
