### ISSUE TITLE
Weather widget predicts midnight sun in Australia

### ISSUE THREAD

**Issue by zenonp** [guardian/frontend#15566]
Instead of using local time for each weather location, the widget seems to use British time or perhaps UTC or the user's computer's local time (there's no telling which). This introduces a skew that is hard to detect and even harder to correct. It also returns very silly results for locations many time zones away. Example: 
![unlocal-time](https://cloud.githubusercontent.com/assets/10004285/21964614/261b6cc2-db58-11e6-8d13-6e8d743b7244.png)
A better way to do this would be to use the local time of each weather location, showing the weather for London in GMT/BST, for Berlin in CET/CEST, for Adelaide in ACT/ACDT etc, and to add the current local time to "Now" so that it is perfectly clear which time is being used.

**Comment by SiAdcock** [comment]
Hi @zenonp, thanks for reporting. The weather widget now uses the local time of the weather location 🎉 

![screen shot 2018-10-24 at 14 18 42](https://user-images.githubusercontent.com/5931528/47434296-304ba780-d79a-11e8-8664-ae590ee52dfa.png)
