### ISSUE TITLE
Confirm programmatically constructed module names work

### ISSUE THREAD

**Issue by sndrs** [guardian/frontend#15591]
there are `require`s that construct the names of the files they load, which webpack can't handle:

- https://github.com/guardian/frontend/blob/master/static/src/javascripts-legacy/projects/commercial/modules/dfp/apply-creative-template.js#L97
- https://github.com/guardian/frontend/blob/master/static/src/javascripts-legacy/projects/commercial/modules/creatives/template.js#L86

**Comment by sndrs** [comment]
actually, this looks like it's managed by webpack just fine. need to confirm with commercial that they're seeing what they'd expect, easier in prod

**Comment by SiAdcock** [comment]
All good in the Webpack hood 👍
