### ISSUE TITLE
Recommended for you layout bug

### ISSUE THREAD

**Issue by sndrs** [guardian/frontend#15650]
# ISSUE

the cards in the slice are not evenly spaced above mobile bp

## Steps to Reproduce

just load the page above mobile

## Actual Results (include screenshots)

<img width="965" alt="screen shot 2017-01-23 at 08 04 23" src="https://cloud.githubusercontent.com/assets/867233/22195994/b838367c-e142-11e6-9dea-1e1d4e3d4789.png">

## Expected Results (include screenshots)

they'd be even

## OS and Browser details

- Device: mac
- Browser (inc version): safari 10
- OS: macOS 10.12.2

*Please add relevant labels*

**Comment by SiAdcock** [comment]
@sndrs Any idea if this is still happening? I haven't even been able to find a "Recommended for you" container... do they still exist?

**Comment by SiAdcock** [comment]
This is container is toast, I'll close this issue
