### ISSUE TITLE
Comment counts display bug in safari below desktop

### ISSUE THREAD

**Issue by sndrs** [guardian/frontend#15793]
# ISSUE

comment counts sporadically appear off the screen in safari below desktop BP

## Steps to Reproduce

visit any article with comments, reload till you see it

## Actual Results (include screenshots)

![screen shot 2017-02-09 at 10 53 03](https://cloud.githubusercontent.com/assets/867233/22780301/2773862e-eeb6-11e6-9963-870a8d958464.png)

## Expected Results (include screenshots)

![screen shot 2017-02-09 at 10 54 58](https://cloud.githubusercontent.com/assets/867233/22780308/379ec81a-eeb6-11e6-8a50-6e3d6e8aea42.png)

## OS and Browser details

- Device: n/a
- Browser (inc version): safari 10 (at least)
- OS: iOS, macOS

**Comment by SiAdcock** [comment]
@sndrs I haven't noticed this post-Garnett. Do you think it's safe to close?

**Comment by sndrs** [comment]
yeah could be – i'll keep an eye out and reopen if need be
