### ISSUE TITLE
clear up after removing requirejs

### ISSUE THREAD

**Issue by sndrs** [guardian/frontend#15854]
- [x] remove everything flagged `#wp-rjs`
- [x] update loaders to use wp config properly (not text!etc)
- [x] uninstall requirejs/text with yarn

**Comment by sndrs** [comment]
+ uninstall `requirejs/text` with yarn

**Comment by gustavpursche** [comment]
@sndrs 👏 ❤️

**Comment by SiAdcock** [comment]
Good point @sndrs! I think now we've removed videojs (I think??), we should probably remove [the last weird alias](https://github.com/guardian/frontend/blob/d359f5c7d9ca1a5351e95dbc561764d978261c69/webpack.config.js#L76) from the webpack config (and delete the last `#wp-rjs` comment!)

**Comment by sndrs** [comment]
oh no i looked for them! was looking for an unrelated issue elswhere and
saw this, searched and github gave me nothing. sorry – please do reopen!

**Comment by SiAdcock** [comment]
No, I think in spirit this issue ought to be closed. We’ve done everything we set out to achieve. I can no longer remember what this codebase looked like under AMD!
