### ISSUE TITLE
Image zoom icon broken in glabs galleries

### ISSUE THREAD

**Issue by regiskuckaertz** [guardian/frontend#15865]
Just saw this [here](https://www.theguardian.com/ashes-australia-travel/gallery/2017/feb/15/the-natural-splendour-and-urban-cool-of-sydney-in-pictures):

![picture 2](https://cloud.githubusercontent.com/assets/629976/23063813/6e87fbb8-f504-11e6-9d96-eb3e14f82cbf.jpg)

The bottom-left icon does not look right.

**Comment by ScottPainterGNM** [comment]
Fixed as part of the super new galleries!
