### ISSUE TITLE
Manually enter Amazon configuration

### ISSUE THREAD

**Issue by tienhv** [guardian/frontend#16756]
Hello, I am not working for guardian. So what should I do to enter the Amazon credential information to make the application run on my dev machine?

Thank you

**Comment by shtukas** [comment]
Hi @tienhv 
Even though our code is available online, the credentials you are looking for are only available to Guardian developers. So you won't actually be able to _run_ frontend at this time. I hope this answers your question :)
Cheers,

**Comment by tienhv** [comment]
Thanks @shtukas, I mean what and where to enter my personal amazon credentials to make the app work. I do not which files to hold the credentials.

**Comment by shtukas** [comment]
@tienhv I should have been more detailed in my answer :)

The amazon credentials are used to access some of our backed/cloud services (hosted in AWS). Unless you reproduce the same backend infrastructure in your own AWS account (which you can't), it simply won't work. 

That having been said I can still better answer your original question. Assuming you had the correct credentials, then you would register them using the AWS command line interface: http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html 

When and where do this is then explained here: https://github.com/guardian/frontend/blob/master/docs/01-start-here/01-installation-steps.md

Cheers,
