### ISSUE TITLE
Multiple problems with one-off contributions

### ISSUE THREAD

**Issue by zenonp** [guardian/frontend#17089]
This is a report of multiple issues, some technical and some of policy. They all regard the one-off contribution mechanism, so they belong together in one report. 

The contribution mechanism involves two embedded frames and one pop-up. Each of them has its own problems.

Frame 1 asks for the amount, while the currency is fixed by previous geolocation and is impossible to change. I, for example, live in Greece and have my bank account in the UK, in sterling. If I pay in euro, which is the only option that the system gives me, my bank will charge me a foreign exchange fixed fee on top of a very bad currency conversion rate and you will get a lesser amount than if I was allowed to pay the same sum in pounds.

Suggestion: make the currency selectable. You can still use geolocation to suggest, but not enforce, the apparently appropriate currency for the user.

Frame 2 contains a form that asks for my name (mandatory), e-mail address (mandatory) and postcode (optional). The form is embedded in a Guardian page and it is completely unclear whether these data are only used by the payments processing company to carry out the credit card transaction, or are shared with and retained by the Guardian. Your privacy policy does not make this clear either.

I would like to make an anonymous contribution. Faced with the choice to either give up my anonymity or not make a contribution, I choose the latter. I suspect there are more people out there who think the same way.

The name on the credit card is indispensable for payments, but it only has to be provided to the payment processor, not to the Guardian. The e-mail address is completely unnecessary for the payment. The fact that it is mandatory on the form raises a very valid suspicion that it will be used for future fund-raising campains, and not only. This idea i reinforced by the request for postcode, which is a pretty sure method to determine a person's social class and financial standing, at least in the UK.

I have a very aggressive stance on spam and I regard all unsolicited commercial mail as such. Thus, rather than risk placing my name and e-mail address on a potential spam list, I abstain from making a contribution to the Guardian.

Suggestion: Make the name and e-mail address fields optional. Decouple the contributing user's name from the name on the credit card and let the latter be requested by and only passed to the payment processor. As an extra bonus this would also allow people to pay with company credit cards or prepaid anonymous debit cards.

Frame 3 (the pop-up box) requests the user's credit card data. By all visible signs it appears to be part of the Guardian website, and it was only by sniffing the network that I could see that it actually comes from stripe.com, your US-based payments processor. This still doesn't allow me to see where my credit card data will be sent - to Stripe, to the Guardian or to both - unless I dig deep in the source code, which I can't be bothered to. Thus, this is the third hurdle that puts me off from making a contribution.

Payment systems, like all systems that handle sensitive data, must be absolutely transparent as to who gets which data and for what purpose. The industry-standard way to create such transparency with regard to payments is to redirect the user to a bank-operated website which verifies itself with its own EVO SSL certificate and handles the payment and all its details. The way that the Guardian has implemented its payment mechanism (a) by embedding third-party forms into its own website and (b) by completely disguising the identity of the payments processor (thereby also disguising the payment processor's country and privacy policy), is a textbook example of how not to process payments.

Suggestion: redo the whole system. Drop stripe.com and use a reputable UK bank (OK, I know that this comes across as an oxymoron) as your credit card payments processor. Ensure that it is crystal-clear to the user where his personal and credit card details are going and what exactly they will be used for.

The contributions page offers Paypal as an alternative to credit card payments. It redirects to Paypal, where the user is prominently notified that "We don’t share your financial details with the merchant." In other words, they do share the non-financial details of the user with the merchant, such as name, postal address and e-mail address. That makes Paypal a non-alternative to the flawed credit card payment mechanism.

Finally, there is a bug somewhere in the selection of payment method. If I choose credit card, proceed to the 2nd and 3rd stage, and then back to the first page and try Paypal instead, the system replies "Sorry, an error occurred" or something similar. Clearing all cookies solves the problem, hence it is a problem in the logic of cookie setting and unsetting.

**Comment by dominickendrick** [comment]
Hi @zenonp. Thanks for taking this time to provide us with this detailed feedback. We will look into the both the technical and policy issues within the team, and update this issue when we implement any changes.

**Comment by njwgh** [comment]
great! In total agreement with this (and have not yet donated because of) . One final point, can you make it clear by way of some text on the screen that although you can pay in your local currency, the bank processing the donation will not be in your country. This has implications for Australian contributors who are required to pay foreign transaction fees  even on $AUD currency transactions if the processing bank is located overseas.

**Comment by SiAdcock** [comment]
c/c @guardian/contributions @guardian/reader-revenue 

Is anyone able to confirm whether these concerns have been addressed by recent changes?

**Comment by njwgh** [comment]
Thanks for follow up
regarding the AUD transaction fees, there is still no mention of the location of the processing bank

Until I see a statement on the screen (or in a terms & conditions screen) then I have to assume that I will be charged fees (and hence not donate)

**Comment by SiAdcock** [comment]
Thanks @johnduffell. 

There's a few interesting points here, but I don't think this is the correct forum to resolve them. As John says, userhelp will definitely offer better support and will know how to move forward with any actionable suggestions. Hence I'm going to close this issue.

**Comment by zenonp** [comment]
> There's a few interesting points here, but I don't think this is the correct forum to resolve them.

I would argue that this is the **only** forum to resolve technical issues. 

None of the issues that I reported just over a year ago has been solved. It is still impossible to select a currency other than the one pre-determined by geolocation. A name and e-mail address are still mandatory (@johnduffell: the system accepts "Donald Duck, nobody@example.com" without verification and the money can be traced by the payment processor and the credit card issuer, so the argument against 'flows of untraceable and anonymous money' is doubly invalid). And the complete lack of transparency regarding regarding the payment processor and their privacy policy persist. 

Thus, effectively, the sole response to my report was to let it lie dormant for a year and then close the issue without any action. This neither encourages reporting bugs, nor making contributions to the Guardian. 

As for the suggestion of contacting userhelp, I mailed my full bug report to Katharine the same day that I filed it here. I received a reply from Natalie Hanman two weeks later, where, among other things, she said 

> I’ve spoken with the team handling contributions to discuss your other
> questions and to pass on the cookie issue. They are aware of the extra
> charges incurred when people aren’t able to pay in their country’s currency
> and have assured me this is something they intend to resolve.

What happened with your assurances to her?

**Comment by njwgh** [comment]
I also contacted userhelp prior to my original post here. It took  2 - 3 emails before they understood what I was asking and then the reply was 
"I am sorry to have to go back and forth with this, I understand you need to know the address of the bank but unfortuantely I do not have that information"

@johnduffell  says:
> Regarding AUD, we now have an Australian registered credit card account due to the problem with transaction fees. This is used for our systems for AU, and this seems to have cleared up as an issue

This is great - but your potential donors don't know this as the information doesn't appear on the donation form nor in the terms & conditions

@zenonp says:
> It is still impossible to select a currency other than the one pre-determined by geolocation

I did find an option to choose the currency when I went back to relook at the payment issue. It was on the top left of the screen - not an obvious place though, in relation to where you're filling in the money amount. 7 different currencies are offered.

**Comment by zenonp** [comment]
> I did find an option to choose the currency when I went back to relook at the payment issue. It was on the top left of the screen

Ah, you're right! And I take back my criticisms regarding this part. Nevertheless, if I missed the currency selection while checking this very issue, most people are bound to miss it while only trying to make a contribution. Why can't the currency selector go immediately above the "Monthly/Just once" button?

**Comment by AWare** [comment]
As the engineer who implemented that currency selector for contributions the first time, I'd like to apologise for missing this issue. 

I took an existing currency selector that we had in use. I'm no longer on the team responsible for this component, but I'm sorry that you were both unable to use it to select an appropriate currency. 

Regarding Australian users being charged transaction fees, had I known about this github issue I would have commented on it in October when I was part of the effort to prevent this from happening again in https://github.com/guardian/frontend/pull/17891. @zenonp while I can only apologise for not having passed this on to you, these assurances have been met.

It would not be appropriate for us to comment on any policy complaints here, but our user help team userhelp@theguardian.com are aware of this issue, and request that you email them directly about it. 

Also, while we regret not being able to respond more promptly our github issue pages are monitored by engineers, and not by our user help team- and so responses will unfortunately be delayed and may not reach the right people.
