### ISSUE TITLE
New navigation has a horizontal scroll in the expanded menu

### ISSUE THREAD

**Issue by designbysoil** [guardian/frontend#17400]
The new navigation has a horizontal scroll in the expanded menu. Not that it is a big issue as it isn't hiding any information.

Screenshot of the horizontal scroll:
http://dl.dropbox.com/u/450152/guardian_new-navigation_horizontal-scroll.jpg

Test URL:
https://www.theguardian.com/artanddesign/gallery/2017/jul/03/mattia-micheli-friendly-fire-in-pictures-italian-photographer-gun-lovers-firearms-italy

Tested on:
- On Mac OS X Capitan 10.11.6
- Chrome Version 59.0.3071.115

**Comment by gustavpursche** [comment]
@designbysoil Thanks a lot for the report. We were able to reproduce the issue and will work on a fix asap. 👍

**Comment by zeftilldeath** [comment]
Thanks @designbysoil, the bug has now been fixed [here](https://github.com/guardian/frontend/pull/17407).
