### ISSUE TITLE
Social Icon Height Bug

### ISSUE THREAD

**Issue by thiagodebastos** [guardian/frontend#17744]
# ISSUE

Social Icons within inline interactives appear cut off at the bottom.
This looks strangely familiar to Issue [#9090](https://github.com/guardian/frontend/issues/9090) from 2015. By this, I mean that the social icons appear to have the same incorrect height now as they did in issue #9090.

It looks like the `.social` container should consist of a `3rem` height, instead of `2rem`.

Note: When social icons 'expand' button is clicked and social icons expand, the height bug is no longer present and all icons can be seen without cut-off.

## Steps to Reproduce
Embed this interactive into Composer:
https://content.guardianapis.com/atom/interactive/interactives/2017/08/glabs-specsavers-eyemonth-quiz

## Actual Results (include screenshots)
Social links cut off

## Expected Results (include screenshots)
Social links not cut off

![social-icon-height-bug](https://user-images.githubusercontent.com/6151341/30010155-0ff862e0-9171-11e7-8de0-e1128d1e73f2.jpg)

## URL
https://www.theguardian.com/specsavers-eyes-on-health/ng-interactive/2017/sep/04/eyes-on-health-quiz#/

### Temporary github repo for this project:
https://github.com/thiagodebastos/glabs-specsavers-eyemonth-quiz

## OS and Browser details
- Device: MacBook Pro 
- Browser (inc version): Chrome 62
- OS: MacOS 10.12.6

*Please add relevant labels*
bug, css, styling

**Comment by katebee** [comment]
@thiagodebastos are there other Interactives affected? I've had a look at some on the non-GLabs interactives and the Specsavers page appears to be applying slightly different CSS rules.

The difference appears to be that on this page, [the Interactive](https://github.com/thiagodebastos/glabs-specsavers-eyemonth-quiz/blob/37f44d193408348e9ba842c76fbdde8afade0061/src/components/App.js#L21) is overriding the default box-sizing of the `.meta-social` element:

```
* {
    box-sizing: border-box;
  }
```

Would it be possible to scope this style rule to only the Interactive?

**Comment by katebee** [comment]
I think I would rather update the interactive css than the frontend css. However, I am going to close this since I think it is no longer occurring (post Garnett) and remaining layout issues with paidfor templates will hopefully be caught during other maintenance work.
