### ISSUE TITLE
Guardian homepage pausing iOS background audio

### ISSUE THREAD

**Issue by PeterHarbigan** [guardian/frontend#17791]
# ISSUE
If playing audio on an iPhone, visiting the Guardian homepage with Safari will immediately pause the audio. The problem persists after successfully (and temporarily!) installing an adblocker, leading me to believe it might be the Documentaries video element that is responsible rather than a rogue advert.

## Steps to Reproduce
1. Play audio through music, podcast, etc app
2. Use Safari to visit theguardian.com
3. Audio stops

## OS and Browser details
- Device: iPhone 7
- Browser (inc version): Safari
- OS: IOS 10.3.3

**Comment by gtrufitt** [comment]
I've seen this too @guardian/dotcom-platform @guardian/interactive-team

**Comment by SiAdcock** [comment]
Hi @PeterHarbigan. Hi @gtrufitt

I’ve been unable to reproduce this issue following the steps provided. It’s likely the issue has been fixed, but please reopen if you notice it happening again.

Many thanks for reporting
