### ISSUE TITLE
GitHub organization member request?

### ISSUE THREAD

**Issue by YoginthS** [guardian/frontend#19311]
Hey,

I am really excited about the active development and wanted to be a part of the **guardian** organization on GitHub. In this regard, how can I become a member and would love if somebody would add me to it?

My GitHub username is YoginthS

Thanks, Yoginth

**Comment by sndrs** [comment]
sorry, only staff are members, and anyway... 

![screenshot-2018-3-12 yoginths yoginth 1](https://user-images.githubusercontent.com/867233/37279971-551e6c04-25e4-11e8-9dbf-c0724142e1f2.png)
