### ISSUE TITLE
Q&A component button always renders outside its container

### ISSUE THREAD

**Issue by mattandrews** [guardian/frontend#19324]
I've seen this for a long time now:

![image](https://user-images.githubusercontent.com/394376/37333176-8e8f78c2-26a0-11e8-82b1-f47d0eba5d49.png)

(from [this article](https://www.theguardian.com/cities/2018/mar/13/buyer-funded-development-scandal)

The button is always outside of the box (looks to be the `transform: translate(0, 50%)` which is doing it) – possibly it needs to be rendered outside of the element it's currently in?

**Comment by SiAdcock** [comment]
Hi @mattandrews, thanks for reporting, however I believe this is a deliberate design decision.

@regiskuckaertz @benwuersching are you able to clarify?

**Comment by benwuersching** [comment]
@mattandrews @regiskuckaertz  Nothing wrong with the button. We're simply thinking outside the box here. :)

**Comment by mattandrews** [comment]
Ahhh! I feel terrible now! Sorry Ben (and 👋, hope all's well!).

**Comment by benwuersching** [comment]
No worries Matt. Glad you're still reading the Guardian. All the best!
