### ISSUE TITLE
Fonts update and stuff

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#19550]
_Issue just tracks the deployment and provides a description, I will close it as soon as the work is done._

This describes new quality standard of web and app fonts we use. Currently to roll out there are new versions of Text Egyptian and Text Sans. Scope of rollout:
- [x] dotcom (https://github.com/guardian/frontend/pull/20466)
- [x] AMP
- [ ] Pasteup 2.0
- [x] [iOS app](https://theguardian.atlassian.net/browse/GLA-870) 
- [X] Android app - _fixed since 6.8_
- [X] [Apps template](https://github.com/guardian/mobile-apps-article-templates/pull/812)
- [x] [apps-rendering](https://github.com/guardian/apps-rendering/pull/123)
- [x] Tools (Composer: https://github.com/guardian/flexible-content/pull/3355)
- [x] Interactives
- [x] Support-frontend (https://github.com/guardian/support-frontend/pull/634, https://github.com/guardian/support-frontend/pull/1439)
- [x] dotcomponents
- [x] emails (https://github.com/guardian/frontend/pull/20628)
- [x] Everything else I forgot

New versions of these two families benefit from optimisations and fixes described below (similar to recently deployed GH Guardian Headline) and also:
- Have new vertical metrics, so will cause reflows and have to be carefully checked by Design before rolling out
- Have consistent naming scheme for both web and app fonts (old dotcom schema minus ‘Web‘ at the end)
- Three subsets:
  - Full,
  - **NoAlts** (main one everywhere),
  - Latin 1
- Two hinting options:
  - **no hinting** (main one everywhere),
  - autohinting (minority of dotcom Win clients).
  
Webfonts:
- **WOFF2** (main one, wherever supported)
- WOFF (minority)
- TTF (legacy)

App fonts:
- **TTF** (identical to webfonts, but with PS names intact for iOS)

Historical context and current situation
-----------------------------------------

Last time we updated our fonts, we optimised them to be half the size by e.g. removing `LTSH`, `VDMX`, `hdmx` and redundant legacy `kern` tables. We were also quick to appreciate the savings offered by WOFF2. We have also used [different mixes](https://github.com/guardian/frontend/blob/master/tools/__tasks__/compile/fonts/index.config.js) of character set subsets depending on font file format to minimise the payload. Unfortunately, this last decision meant we’ve had to live with occasional ugly font substitutions and faux styles (even though we’ve tried to minimise the impact with [clever fallbacks](https://github.com/guardian/frontend/pull/5190)). This has grown increasingly at odds with our ambition to spell correctly whatever the language and our appreciation of good typography (faux italics in antiqua!).

![accents](https://user-images.githubusercontent.com/6032869/27998007-dee82a10-64fb-11e7-8716-355ce73e115a.jpg)

Because fixing it permanently using our current fonts would mean increasing the payload by various amounts depending on font format and charset mix used (e.g. WOFF2: 196KB→362KB; TTFautohint: 753KB→1782KB), we resorted to [patching it here and there](https://github.com/guardian/frontend/pull/9411) where the visual impact was deemed too much.

Lastly, we serve various flavours of hinting to [different Windows clients](https://github.com/guardian/frontend/blob/master/common/app/templates/inlineJS/blocking/loadFonts.scala.js#L19) and hinting substantially increases the payload.

Intent to implement
------------------

We’ve worked hard with our font provider – [Commercial Type](https://commercialtype.com/) – and thanks to their expertise, invaluable help and patience (special thanks go to Mark Record, who did all the work!), been able to reduce the fonts file sizes by ~half again. This issue is meant to document the optimisations, bug fixes and changes, and to outline outstanding fixes. Lastly, we also list ideas for future optimisations which are outside the scope of this update.

With this update we hope to be able to greatly reduce or even eliminate (in WOFF2 at least) all faux styles and ugly glyph substitutions. It should eliminate the need for most or all hinting flavours reducing logic complexity. It also introduces some unrelated fixes.

Changelog
----------
1. _[main optimisation – ~27–45% smaller]_ Removed OpenType features and corresponding glyphs that we weren’t using anyway. Removed and “flattened” when necessary: `frac`, `dnom`, `numr`, `sinf`, `sups`, `lnum`, `onum`, `ordn`, `case`, `tnum`, `pnum`, `ss01`, `ss02`, `salt`.
2. _[~10% smaller]_ Used [Raph Levien’s Fontcrunch](https://github.com/googlefonts/fontcrunch/) to optimise font outlines.
3. Added a Unicode codepoint for non-breaking hyphen and for no-break space to fix rendering in some browsers (incl. [this beauty](https://github.com/guardian/frontend/issues/17506)):

![u2011](https://user-images.githubusercontent.com/6032869/27998023-3230dd7a-64fc-11e7-86ac-82b63292ef75.png)

4. Added a U+2010 Unicode codepoint to existing U+002D glyph. [Harfbuzz only falls back](https://github.com/behdad/harfbuzz/issues/517) from U+2011>U+2010, not from U+2010>U+002D. Browsers should have our back, but they don’t.
 
5. While “flattening” OT features, settled on Proportional Oldstyle figures style (instead of Tabular) as default for Text Egyptian to match other fonts and for better-looking text:
![proprtional vs tabular](https://user-images.githubusercontent.com/6032869/27998026-3907f4b2-64fc-11e7-9511-e690f0d73e70.gif)

6. Adjusted Vertical metrics, so that baselines match between different families on Windows and Windows matches Mac rendering:
![text rendering -mac win current vs mac win - new](https://user-images.githubusercontent.com/6032869/27998031-40e1ef8a-64fc-11e7-96ac-c3e8dffe8ae1.gif)
[note how kickers line up better, ignore changes in hinting]

7. _[~10% smaller]_ Changed `post` tables to be version 3. And, yes, we are fine with a [slight regression on a Mac](http://typedrawers.com/discussion/1945/truetype-based-fonts-and-post-table-version-3-0) (haven’t checked iOS, but unlikely to be there; it’s even less of an issue on HiDPI screens), maybe Apple will fix it one day:

![post2_vs_post2_mac_rendering](https://user-images.githubusercontent.com/6032869/28017873-ef0e0bea-6572-11e7-8a8e-407ca49d4dc6.gif)

8. Fixed `gasp` table to only allow `Version 1: Grid Fit, Anti-Alias, Symmetric-Smoothing, Grid Fit w/ Symmetric-Smoothing` (value `15`) for all sizes to fix Windows rendering of non-hinted (and ClearType-hinted) fonts under some circumstances (e.g. Chrome<37 and any Firefox with OS set ClearType off, any Chrome on XP set to Standard).
9. Added short `prep` program according to [this recommendation](https://github.com/googlefonts/tools/blob/master/bin/gftools-fix-nonhinting.py) attributed to Vern Adams (thank you!) to all unhinted fonts to fix Windows rendering (e.g. Chrome<37, any Win XP set to ClearType and all Firefoxes without hardware acceleration):
![current-unhinted-vs -gasp -prep-adjusted](https://user-images.githubusercontent.com/6032869/27998032-4bf72c78-64fc-11e7-8ef3-e4896d8ece92.png)
[illustrates both pts. 8, 9]
10. Compressed all WOFFs using latest sfnt2woff-zopfli.
11. Applied [Palettize-kerning](https://github.com/justanotherfoundry/font-production/tree/master/palettize%20kerning) from [Just Another Foundry](https://github.com/justanotherfoundry) for different amount of GPOS optimisation. Thank you! 
12. Encoded diacritical marks with codepoints from Combining Marks Unicode block, so browsers less sophisticated than Chrome can compose decomposed forms correctly too (Chrome seems to very cleverly compatibility- compose, and decompose, even when just one glyph is present from the needed combination. Should be zero, but hey).
![composed diacritics firefox vs chrome](https://user-images.githubusercontent.com/6032869/27998033-56804436-64fc-11e7-9d46-19511adc366c.png)

[old versions of the fonts without Combining, just with spacing marks, decomposed form called for; Firefox – left, Chrome – right]

13. Bumped version numbers to  2.001 (the same as GH Guardian Headline).

Future…
---------
…is bright! I suspect possible further savings could exceed another 50%, by when, according to my math skillz, the fonts weight should be… negative :stuck_out_tongue_winking_eye:

14. Look into trying to productionise the idea behind Adam Twardoch’s super-clever [ttfdiet](https://github.com/twardoch/ttfdiet). If only all [other browsers](https://bugzilla.mozilla.org/show_bug.cgi?id=1425711) would be as flexible as Chrome when doing composition and decomposition, maybe the whole hack wouldn’t even be necessary?
This requires impeccable Mark Positioning whenever it may provide result identical to precomposed forms (including kerning!) with alternate designs for cap marks working and all the goodness. The idea is for the fonts to be indistinguishable from the ones with precomposed forms. 

15. Embrace OpenType 1.8 Variable Fonts. New format should provide file savings for current fonts, but should also help to combine Text and Headline families for even more radical savings!

-   Layman’s take: The (relatively?) easy step would be just to combine whatever styles we already use as masters, italics and roman separately. Harder would be to roll-in sans serif italics into a variable roman font. Harder still, would be to try to remove some masters whenever we use more than two and let browsers use instances there. Harder again, would be to combine Text and Headline families (contrast axis yay!). Because to roll in serif italics into roman sounds a bit too crazy, right? (although I think I’ve heard it [mentioned](https://www.typotalks.com/videos/monotypes-way-of-producing-opentype-variations/)). Interesting that with VF the savings will provide a way to bring back some of the features that we have removed in this here very update, so the dance between aesthetics and performance will continue, even though they are one: poor performance forces compromises that result in poor aesthetics. Maybe one day it will be solved by streaming font data?

16. Look into subsetting fonts on the fly to minimise loading for when component/projects cannot use dotcom’s fonts directly and there is no way to message them through.

17. Look into expanding (and standardising: Guardian Headline contains e.g. π & μ which are missing from other families) our Latin charset to cover more languages (e.g. Vietnamese!), so that we won’t have to be ashamed of [ugly substitutions](https://www.theguardian.com/global-development/2017/aug/26/ready-married-kidnapped-brides-vietnam-china), won’t have to spend hours shaping individual glyphs for print manually and we won’t be hitting browser bugs ([as rewarding as this is :-)](https://bugs.chromium.org/p/chromium/issues/detail?id=758380)). Hopefully, this should be helped by pt. 11 to avoid inflating font file sizes:

![ugly vietnamese](https://user-images.githubusercontent.com/6032869/31727705-2f98524e-b422-11e7-9de7-f3526defcb0b.png)

---
Fixes https://github.com/guardian/frontend/issues/17506 and properly fixes https://github.com/guardian/frontend/issues/8158 (pts. 3, 4). Properly fixes: https://github.com/guardian/frontend/issues/7630 and https://github.com/guardian/frontend/pull/7373 and https://github.com/guardian/frontend/pull/7912 and https://github.com/guardian/frontend/pull/7654 (pts. 8, 9; wrong `gasp` was causing jaggies in Blink browsers and wrong rendering of ClearType-hinted fonts). Properly fixes https://github.com/guardian/frontend/pull/7545 (pt. 6; Vertical metrics consistent between environments). Properly fixes: https://github.com/guardian/frontend/pull/5190 and https://github.com/guardian/frontend/issues/3253 (file-size should allow for serving full charsets, clever fallbacks were only so clever). And, most probably, a bunch of others.

**Comment by mchv** [comment]
Thanks for the summary and details level, this is very educative.
 Anyone wondering what a good bug report is, should read @paperboyo 's [one on google chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=758380) 💎

**Comment by SiAdcock** [comment]
Font usage in emails is pretty inconsistent:

- [Email fronts](https://github.com/guardian/frontend/blob/master/static/src/stylesheets/email/_front.scss#L14-L30) use Guardian Headline (medium and bold), pointing to the URLs on interactives.guim
- [Email articles](https://github.com/guardian/frontend/blob/master/static/src/stylesheets/email/_article.scss#L12-L28) use Guardian Text Egyptian Web (regular and regular italic), pointing to the URLs on pasteup.guim

We should think about consolidating these.

**Comment by paperboyo** [comment]
> We should think about consolidating these.

Yes. But proper consolidation can happen only after we set up pasteup 2.0, right?

Until this happens, I would point to interactives.guim, where @Jholder112233 recently placed latest versions of Text Sans and Egyptian (and latest Guardian Headline was there before).

**Comment by SiAdcock** [comment]
Okay, thanks @paperboyo. I have updated the URLs to point to interactive.guim in #20628, and stripped out non-woff fonts as advised by [this Litmus blog post](https://litmus.com/blog/the-ultimate-guide-to-web-fonts).

**Comment by paperboyo** [comment]
Thanks everybody for their effort! Let’s look to the future update!
