### ISSUE TITLE
Android: "added to home screen" always opens /uk

### ISSUE THREAD

**Issue by kaelig** [guardian/frontend#19746]
# ISSUE

## Steps to Reproduce

Using Chrome on Android (Oreo)

1. Go to theguardian.com/us
2. Add to home screen 
3. On the homescreen, open the guardian shortcut

## Actual Results

/uk is loaded 

## Expected Results

/us is loaded

## OS and Browser details

- Device: pixel 2 XL
- Browser (inc version): Chrome 66
- OS: Android 8.1.0

**Comment by NataliaLKB** [comment]
Thanks @kaelig ! Looking into this now

**Comment by kaelig** [comment]
Any updates on this?

It's excessively annoying as a US Guardian reader. I'm almost tempted to download the app instead of loading the website.

**Comment by SiAdcock** [comment]
Hi @kaelig, thanks for chasing this.

In #19746 we removed the `start_url`, so now adding to the home screen should always add the current page to the home screen, regardless of whether you are on an article, a front or the network front.

Please could you retest and let us know if you have any further thoughts or notice other issues?

**Comment by kaelig** [comment]
Amazing, it works! Thanks for fixing this.
