### ISSUE TITLE
Cannot sign into account using Google Auth

### ISSUE THREAD

**Issue by turkeyphant** [guardian/frontend#20365]
https://github.com/guardian/frontend/issues/19252#issuecomment-369604422

# ISSUE

## OS and Browser details

- Device:
- Browser (inc version):
- OS:

*Please add relevant labels*

**Comment by turkeyphant** [comment]
More than six months on STILL unfixed.

**Comment by turkeyphant** [comment]
Screenshot from version 6.8.1784 taken 2018-09-17 11:01 on LG G5 trying to use a Google account that is currently signed in without issue on dekstop.

![capture _2018-09-17-11-01-54](https://user-images.githubusercontent.com/8129583/45617166-5ed2b600-ba69-11e8-87e8-c7724b4634d3.png)

**Comment by rahilb** [comment]
Hi @turkeyphant thanks for reporting the error. 

If possible could you report the error at https://www.theguardian.com/info/tech-feedback

This will allow us to look into the issue further; please be sure to include the email address of the account that you are unable to log in to. If possible please submit the feedback form using the same device and browser that you see the error in.

**Comment by rahilb** [comment]
cc @guardian/android-developers

**Comment by turkeyphant** [comment]
@rahilb I already did that back in February. Got a reply asking for a screenshot which I already provided. No response since 28 Feb.

**Comment by turkeyphant** [comment]
************ ***************** ***********
************  Diagnostic info  ***********
************ ***************** ***********
Build type: RELEASE
App version: 6.8.1784.1784
Installed: 26 Feb 2018 13:46:47
Last updated: 14 Sep 2018 01:47:00

Device: LGE LG-H850
Android version: 7.0
Rooted: false
Region format: GB
Language: English
Timezone: 0

Edition: UK
Signed In: false
Subscription Type: Free
Membership Type: none
Is Online: true
Connection Type: 4g

And Live news app (QW5kIExpdm)


************ ***************** ***********
************ ***************** ***********
************ ***************** ***********
Your feedback category: QW5kIExpdm

Same issue on wifi/4g/3g unsurprisingly.

**Comment by turkeyphant** [comment]
Different error today - "Access denied".

**Comment by turkeyphant** [comment]
Back then I couldn't sign into the app _nor_ via the website. Now I can sign in via the mobile website as it no longer seems to redirect.

To clarify, _neither then nor now_ am I able to sign in using the app with the method you describe.

**Comment by SiAdcock** [comment]
Okay thanks for clarifying. I’m glad you’re able to sign into the website on mobile. Redirection errors are very difficult to diagnose! 

I’ll pass this over to the Android team

**Comment by turkeyphant** [comment]
Issue still persists with 6.8.1813. Going to Settings > Sign In / Register and tapping Google results in "Google auth failed" error.

**Comment by SiAdcock** [comment]
Hi @turkeyphant. I have spoken to the user help team and they have said they are helping you with this issue via email. Thanks for your patience

**Comment by turkeyphant** [comment]
Please reopen. This issue is still ongoing regardless of email support.

**Comment by SiAdcock** [comment]
@turkeyphant this board is for issues with the Guardian website, I'm afraid it is not the appropriate forum for the login issue you're having with the Android app. The user help team are better placed to help you with this.

**Comment by turkeyphant** [comment]
Are you saying the app doesn't render using the same frontend?

**Comment by SiAdcock** [comment]
That is correct, it’s a different codebase
