### ISSUE TITLE
Layout bug

### ISSUE THREAD

**Issue by sndrs** [guardian/frontend#21399]
# ISSUE

main image overlapping right hand column on some stories

## Steps to Reproduce
- https://www.theguardian.com/lifeandstyle/2019/apr/10/harry-nuriev-russian-architect-fantasy-office-furniture-designer 
- `leftCol` breakpoint

## Actual Results (include screenshots)

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/867233/57583335-6b5bc100-74c7-11e9-9101-cd998ee6d8e0.png">

## URL
- https://www.theguardian.com/lifeandstyle/2019/apr/10/harry-nuriev-russian-architect-fantasy-office-furniture-designer 

## OS and Browser details

- Device: Mac
- Browser (inc version): firefox 66 + safari
- OS: 10.14.14

**Comment by gtrufitt** [comment]
❤️  Thanks @sndrs 

❤️ @GHaberis https://github.com/guardian/frontend/pull/21448

**Comment by gtrufitt** [comment]
💊 fixed
