### ISSUE TITLE
More people in %%COUNTRY_NAME%%...

### ISSUE THREAD

**Issue by zenonp** [guardian/frontend#21591]
See attached screenshot. It looks as if there is no default fall-back for the event that the user's IP cannot be geolocated. In this case the "More people in %%country_name%% (support the Guardian)" message should be dropped in favour of a more generic "More people support the Guardian". 

Note: IPv6 compounds the problem.

![country_name](https://user-images.githubusercontent.com/10004285/60127168-34e8b580-9798-11e9-9824-99afe9043967.png)

**Comment by tomrf1** [comment]
thanks for reporting, this was fixed this morning [here](https://github.com/guardian/frontend/pull/21592)
only some users should be opted into this variant
