### ISSUE TITLE
Article page scrolls horizontally in Android

### ISSUE THREAD

**Issue by piuccio** [guardian/frontend#22170]
# ISSUE

## Steps to Reproduce

Go to any article page, for instance https://www.theguardian.com/business/2019/dec/24/boeing-737-max-new-troubling-communications-faa

## Actual Results (include screenshots)

The page scrolls horizontally

![Screenshot_20191224-190253](https://user-images.githubusercontent.com/680284/71422168-0765c180-2680-11ea-89c4-b18eea1be896.png)

![Screenshot_20191224-185732](https://user-images.githubusercontent.com/680284/71422153-eac98980-267f-11ea-807f-ab4cd9d0d45e.png)

## Expected Results (include screenshots)

The page shouldn't be larger than the viewport

## OS and Browser details

- Device: pixel 3
- Browser (inc version): chrome 79
- OS: Android 10

I believe I opted in the react rendered version by clicking on the link in the dev blog post.

**Comment by piuccio** [comment]
By the way, there's a tall white space, I guess it's the placeholder for the first ad, it never loads...

**Comment by paperboyo** [comment]
Hi, @piuccio! Long time no see, I hope it’s all amazing! Happy New Year. When are you coming back? ;-)

I can’t reproduce on latest Chrome beta on Android on old frontend, but indeed by adding `dcr=true`, I can…

> I believe I opted in the react rendered version by clicking on the link in the dev blog post.

This is the repo: https://github.com/guardian/dotcom-rendering. You can tell by the “beta” appearing in the footer.

**Comment by oliverlloyd** [comment]
Hey @piuccio, thanks for raising this. I've recently made a fix to horizontal scrolling that _may_ have fixed this issue but when I went to test it I hit another horizontal scrolling problem. It looked like this:

![Screenshot 2020-01-08 at 17 28 21](https://user-images.githubusercontent.com/1336821/72000960-4c6f2380-323c-11ea-89f9-84bdad782ea1.jpg)

I think this is a different issue but if not, please let us know.

Regarding the white space. You're right, this is another problem and I've raised that separately with Commercial

Finally, it's possible that none of these things will fix your original scrolling problem 😞but  I'll have a clearer idea what's going on once the main issues are addressed

**Comment by oliverlloyd** [comment]
The original issue raised in this issue should now be fixed by https://github.com/guardian/dotcom-rendering/pull/1066. There is an element inside Outbrain with a hard coded width of >1000 pixels which causes the viewport to explode horizontally. The same issue is present on frontend and is fixed using `overflow: hidden;` on the outbrain container. This PR replicates this solution on DCR, preventing the overflow.

**Comment by piuccio** [comment]
I don't know if this is related to the other issue you mentioned, but things got worse for some pages.
Take this one https://www.theguardian.com/world/2020/feb/03/world-celebrates-palindrome-day-on-02022020

The actual width is considerably higher than the viewport.

![Screenshot_20200203-181029](https://user-images.githubusercontent.com/680284/73640033-e649b500-46b0-11ea-9747-312bee1db724.png)
