### ISSUE TITLE
Links on special container are blue on blue when selected

### ISSUE THREAD

**Issue by piuccio** [guardian/frontend#22182]
# ISSUE
 This might be hard to explain, but don't worry there's a screenshot.

## Steps to Reproduce

On the special container on the landing page, scroll the page by tapping down on the sublinks of the first story.
(Same if you long press on the sublinks)

## Actual Results (include screenshots)
The story background changes colour. The link, which starts from dark blue on light blue, becomes dark blue on a similarly dark blue, hence impossible to read.

![Screenshot_20200104-163052](https://user-images.githubusercontent.com/680284/71767843-07cc4b00-2f11-11ea-91b6-a143b8fc07bf.png)

## Expected Results (include screenshots)
I expect nothing special to happen

![Screenshot_20200104-164456](https://user-images.githubusercontent.com/680284/71767904-993bbd00-2f11-11ea-9653-1bc15e0b6930.png)

## URL
https://www.theguardian.com/international

## OS and Browser details

- Device: pixel 3
- Browser (inc version):  chrome 79
- OS: android

**Comment by gtrufitt** [comment]
Thanks @piuccio - my fault, will look today!

**Comment by mchv** [comment]
Thanks @piuccio for reporting 💎

**Comment by jfsoul** [comment]
This should be fixed by #22952
