### ISSUE TITLE
Front end upload error

### ISSUE THREAD

**Issue by ShayanAhmedd** [guardian/frontend#22679]
When i tried to upload a file from my [site](www.easisol.com). it gets error. that file is not upload. Due to exceeded limit.
Please help

**Comment by katebee** [comment]
Hello 👋  Could you share a little more information in this issue, as much of the following as possible would be helpful:

1. Steps to Reproduce
2. Actual Results (include screenshots)
3. Expected Results (include screenshots)
4. URL of the page the error is appearing on
5. OS and Browser details

**Comment by katebee** [comment]
I am going to close this issue for now as more information is needed before we can properly triage.
