### ISSUE TITLE
TCFv2 test results very low

### ISSUE THREAD

**Issue by sndrs** [guardian/frontend#22860]
### CCPA test

https://github.com/guardian/frontend/blob/f7184238b8c9cd3112fbd81942774b7fe1b08e32/common/app/experiments/Experiments.scala#L52-L58

https://github.com/guardian/frontend/blob/f7184238b8c9cd3112fbd81942774b7fe1b08e32/static/src/javascripts/projects/commercial/modules/cmp/ccpa-ab-test.js#L1-L15

https://github.com/guardian/frontend/blob/f7184238b8c9cd3112fbd81942774b7fe1b08e32/static/src/javascripts/boot.js#L34-L37

see also [full PR](https://github.com/guardian/frontend/pull/22687/files#diff-89c79c0e096c91961ee0ad11bd007482)

### Current TCFv2 test:

https://github.com/guardian/frontend/blob/5b60cb4369aa86a00d9fec16299477ba4196b53f/common/app/experiments/Experiments.scala#L45-L51

https://github.com/guardian/frontend/blob/5b60cb4369aa86a00d9fec16299477ba4196b53f/static/src/javascripts/projects/commercial/modules/cmp/tcfv2-test.js#L1-L17

https://github.com/guardian/frontend/blob/5b60cb4369aa86a00d9fec16299477ba4196b53f/static/src/javascripts/boot.js#L35-L41

**Comment by mxdvl** [comment]
https://github.com/guardian/ab-testing/blob/d908567fa95d113a01f915c319ed27268e394eb1/packages/ab-core/src/ophan.ts#L106-110

**Comment by mxdvl** [comment]
I think the problem lies in DCR:

https://github.com/guardian/dotcom-rendering/blob/6adf7c6e9ec96c757bb0a51327fce3ab891d3e9b/src/web/browser/ophan/ophan.ts#L134

**Comment by mxdvl** [comment]
After discussion, it seems most (all but 20%) server-side tests `variant` buckets/cohorts overlap with the 50% test `variant` bucket/cohort
