### ISSUE TITLE
Text wrapping bug on Android Firefox with text enlarged

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/frontend#24649]
reported by: Paul Brown
via: Chat
on: 15 Feb 2022

> Morning. A reader has reported that the website looks broken in Android Firefox when they increase the font size. I can reproduce this. They have provided a screenshot of their accessibility settings.

![Screenshot 2022-02-15 at 08 15 01](https://user-images.githubusercontent.com/31692/154234680-714fb8ce-97d6-48b7-8965-d540f03bf50d.png)
![Screenshot 2022-02-15 at 08 23 03](https://user-images.githubusercontent.com/31692/154234684-9af7384c-3dfe-4e2e-8dbd-8f3571c24a3e.png)

https://chat.google.com/room/AAAAG9rU0m0/kWrZxsB2JTU [not public]

**Comment by OllysCoding** [comment]
@jamesgorrie to add info
