### ISSUE TITLE
Pressed article with embed can't be previewed

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/frontend#24675]
reported by: Simon Adcock
via: chat P&E Dotcom https://chat.google.com/room/AAAAG9rU0m0/DUHLk4XsIrk (internal)
on: 21 Feb 2022

We had an issue last week trying to update this interactive page by changing to a new atom: https://composer.gutools.co.uk/content/58dd107be4b007e8557f1170 - the preview renders a blank page. We flagged it to Editorial Tools and they couldn’t resolve it but its not issue with Preview / Composer.

The issue may be because the page is a "pressed" Interactive. Any chance you could:
 - outline how “pressed” pages work (or point to some docs on this if they exist)
 - let us know how we can update a previously pressed page to use a new content (in this case, a new version of the interactive) and whether we should expect this to work with Preview in Composer or not?

For reference, the capi for the new interactive we want to put on the page is https://content.guardianapis.com/atom/interactive/interactives/2022/02/sign-up-for-the-bookmarks-email/default

**Comment by OllysCoding** [comment]
@jamesgorrie to follow up
