### ISSUE TITLE
Discrepancy between inferred data for CAPI & Facia-press/frontend

### ISSUE THREAD

**Issue by DavidLawes** [guardian/frontend#24703]
An issue occurred on 21/02/2022 where a card (pictured) on the /uk front in the opinion container, did not have the byline or quoted headline as enabled in the fronts-tool.

![image (1)](https://user-images.githubusercontent.com/45561419/155560970-244f3c64-9511-45b5-a4fc-61aa3c275fbd.png)

Further investigation showed that on the /uk/commentisfree front (opinion) the same article did have byline and quoted headline for its card.

It turned out that the data for these two properties were missing in the facia-tool-store S3 bucket (cms-fronts S3 account) - which is where facia tool stores front data.

There appears to be a discrepancy between how frontend and fronts tool was treating that lack of data.

This discrepancy likely comes from facia scala client ([guardian/facia-scala-client](https://github.com/guardian/facia-scala-client)), where some defaults are defined

A default of interest is: [ResolvedMetaDataTest.scala](https://github.com/guardian/facia-scala-client/blob/a4532823df344c84e8f4ff764806283a1743386b/fapi-client/src/test/scala/com/gu/facia/api/utils/ResolvedMetaDataTest.scala#L54).

It's worth investigating if frontend and fronts tool are using differing versions facia-scala-client, or if there is another reason that this discrepancy exists.

A short term solution of switching both buttons off, saving, and switching both buttons back on was used which forced fronts-tool to be explicit about the data removed the discrepancy, however having differences between the tools and what frontend shows is not ideal and we should investigate this.

It would be worthwhile working with tools (Jonathon Herbet was involved on the tools side) on this investigation

Fixed:
![image (2)](https://user-images.githubusercontent.com/45561419/155561059-4f517553-b9ac-445c-9d47-a9f4f13cc093.png)

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team and we can't address them all. With so many tickets we are potentially missing things that are high-impact so we're reorganising.
