### ISSUE TITLE
Scala Upgrade 2.13

### ISSUE THREAD

**Issue by DavidLawes** [guardian/frontend#24740]
**What is the context for the card?(this could be a user story or bug description)**

We'd like to migrate Frontend from Scala 2.12 to 2.13.

This brings compiler perf benefits and keeps up close to the latest version (3) rather than 2 off as we currently are (2.12). Our [department recommendations](https://github.com/guardian/recommendations/blob/master/scala.md) suggest you should only be 1 major version off head.

The main challenge here is to publish the various Guardian dependencies that don't yet exist for 2.13. You can see which ones by updating the Scalaversion to 2.13.6 and attempting a compile. 

**any useful URLs**

Version is set here: https://github.com/guardian/frontend/blob/main/project/ProjectSettings.scala#L35.

**What is the expected outcome?**

(Frontend migrated!)

- [x] scala-uri
- [x] content api client aws
- [ ] identity model
- [x] play google auth
- [x] scanamo
- [x] redis client
- [x] json4s native
- [x] nscala time
- [x] play json joda
- [x] lift json
- [x] box 2.13 (??)
- [ ] scalatest
- [ ] scalacheck
- [ ] scalatestplus

**Comment by jamesgorrie** [comment]
This has been done
