### ISSUE TITLE
'Today in Focus' only works when there is 1 entry for a day

### ISSUE THREAD

**Issue by OllysCoding** [guardian/frontend#24879]
https://www.theguardian.com/news/series/todayinfocus

Recently there was an issue in editorial that led to a podcast being mis-published on the wrong day ~ resulting in CAPI returning 2 podcasts for the same day 

When this happened on the todayinfocus page, only 1 of the podcasts showed up.

This isn't really a priority as we wouldn't expect more than 1 article to be published per day for todayinfocus, but having it documented here will be useful if there any future cases where this happens.

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team. With so many tickets we are potentially missing things that are high-impact so we're reorganising the board - if we can get through all our high-impact tickets we can re-open these lower impact ones.
