### ISSUE TITLE
CODE Environment - Images don't work when pointed at CAPI CODE

### ISSUE THREAD

**Issue by OllysCoding** [guardian/frontend#24989]
e.g:

When displaying CODE fronts, the host frontend uses for images is: `media-origin.test.dev-guim.co.uk`. This URL no longer exists and does not work,

The correct host would be: `i.guimcode.co.uk/img/media`, e.g https://i.guimcode.co.uk/img/media/e56404a7eeb2e510cb4a85c2e36f575ab9fd8418/0_98_3500_2100/master/3500.jpg

However for this to work, Frontend CODE would need to add the signature (`?s=XXX`) to the URL, which it also currently doesn't do!

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team and we can't address them all. With so many tickets we are potentially missing things that are high-impact so we're reorganising.
