### ISSUE TITLE
Facia Press Preview - Only fetch published articles for backfill requests

### ISSUE THREAD

**Issue by OllysCoding** [guardian/frontend#24988]
Johnathon Herbet:

Morning dotcom! ☀️ I've just had a conversation with @Gabriel Smith about the behaviour of the fronts press. At the moment, when backfilling for preview, it seems to draw content from preview CAPI, sorting by last modified date across all content.

In conversations with editorial, Gabriel notes that this presents a difficulty: it's difficult to set up a new automated front and know that you've got it right because you see all the unpublished content there.

I suppose previewing with backfills never looks all that representative – you'll see whatever is last modified. For example, there's an entirely blank article currently in preview on this training front: https://preview.gutools.co.uk/responsive-viewer/https://preview.gutools.co.uk/cp-test-matt because it happened to be the last thing touched as the front was pressed.

----

Task: Update facia-press app so that when we're requesting backfill CAPI data for preview, we still use regular capi, rather than preview!

**Comment by OllysCoding** [comment]
@jonathonherbert Has expressed interest in pairing with us on this one!

**Comment by jlieb10** [comment]
I think this sounds like a bigger project than a rota task. Going to move it to the backlog but if it gets discussed again, would be a good thing to bring up in planning.

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team and we can't address them all. With so many tickets we are potentially missing things that are high-impact so we're reorganising.
