### ISSUE TITLE
Labs front inconsitent behaviour when `adFree`

### ISSUE THREAD

**Issue by ioannakok** [guardian/frontend#25101]
> I've been experiencing an issue today and cannot figure out why. This link https://www.theguardian.com/guardian-labs-australia is showing two different fronts for me. The right one, when I am not logged in to the Guardian site and when I am logged in, it shows a stale front (articles from 2018).

**Comment by ioannakok** [comment]
https://user-images.githubusercontent.com/19683595/173323675-7dee4d03-4a73-4237-baa5-e6e93afaba22.mov

**Comment by mxdvl** [comment]
This looks like a bug, as the following are working as expected even if signed-in:
- https://www.theguardian.com/guardian-labs
- https://www.theguardian.com/guardian-labs-us

**Comment by mxdvl** [comment]
Ongoing research to identify why the paid containers are skipped for this page. Potential areas of interest are :

- https://github.com/guardian/frontend/blob/main/common/app/views/fragments/containers/facia_cards/container.scala.html#L30
- https://github.com/guardian/frontend/blob/main/common/app/layout/FaciaContainer.scala#L163-L166
- https://github.com/guardian/frontend/blob/main/common/app/model/facia/PressedCollection.scala#L37-L43

**Comment by ioannakok** [comment]
@mxdvl Please leave a comment if there's anything else to add. Putting this back to TODO

**Comment by OllysCoding** [comment]
Picking this up to try and figure it out!

**Comment by OllysCoding** [comment]
I believe the start of the issue could stem from here: https://github.com/guardian/frontend/blob/main/facia/app/controllers/FaciaController.scala#L194

This logic says that if there are no collections in the 'ad free' variant of a front (which is prioritised for an ad-free user), then fall back to the normal variant.

The https://www.theguardian.com/guardian-labs-us has no collections: 

![Image](https://user-images.githubusercontent.com/9575458/174330300-7a265cef-d02a-43fd-97de-96a81cd78721.png)

Whereas the aus version does:

![Image](https://user-images.githubusercontent.com/9575458/174330339-2ae2e45a-4ec4-4680-b734-d7f2bbe01b05.png)

We can also see that the ad-free variant of the aus version is _still_ being pressed: 

![Image](https://user-images.githubusercontent.com/9575458/174330476-4e4281a8-a453-428c-8031-4bdc4656e465.png)

So it's likely that either in the configuration, history, or pressing of the article, something is wrong or misconfigured that's causing the ad-free variant of the article to be pressed with content we don't want.

**Comment by jlieb10** [comment]
Hi all, has this been merged/is there an associated PR?
