### ISSUE TITLE
Investigation in Schema.org on DCR vs Frontend

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/frontend#25237]
If you compare DCR vs Frontend schema.org values on liveblogs you get:
https://gist.github.com/jamesgorrie/68644cb0d7e439e35ccc70e8fcbbe4e6

A couple of notes:
- `@id` is the amp url
- `@id` is missing a trailing slash after the host
- the structure is a bit odd - where from the docs (https://schema.org/LiveBlogPosting) I think it should be 1 LiveBlogPosting with multiple BlogPostings in the liveBlogUpdate prop

This feels like a relatively important thing to fix as it's related to SEO.

**Comment by bryophyta** [comment]
- the `amp` issue is slightly unclear, opening a new issue for this: #25262
- the trailing `/` issue was resolved by #25255
- I believe that the `LiveBlogPosting` structure was found to be okay as it is.
