### ISSUE TITLE
Sport: Fixture removed from PA API isn't removed from our Fixtures.

### ISSUE THREAD

**Issue by AshCorr** [guardian/frontend#25248]
# ISSUE

When a fixture is removed from PA's sport API we don't remove it from our Sport cache. This can cause pages like https://www.theguardian.com/football/premierleague/fixtures to have Fixtures on it that are duplicated or don't actually exist.

I was able to resolve the problem by redeploying frontend (thus clearing the memory cache), but ideally we should fix the underlying issue.

Seems like this is being caused by this line here https://github.com/guardian/frontend/blob/995d8b9037575306d9038d4c1413fff3f89259c3/sport/app/football/feed/agent.scala#L131 It seems like we only ever add new data and never remove old data.

**Comment by jlieb10** [comment]
I think we should put this on backlog as we have a current workaround. It's not ideal and if it is a quick fix, let's take it out of the backlog.

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team. With so many tickets we are potentially missing things that are high-impact so we're reorganising the board - if we can get through all our high-impact tickets we can re-open these lower impact ones.

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team. With so many tickets we are potentially missing things that are high-impact so we're reorganising the board - if we can get through all our high-impact tickets we can re-open these lower impact ones.
