### ISSUE TITLE
Remove badging from youthjustice tag

### ISSUE THREAD

**Issue by ioannakok** [guardian/frontend#25325]
https://www.theguardian.com/society/youthjustice

**Comment by jlieb10** [comment]
For pairing: 

- Remove: https://github.com/guardian/frontend/blob/e06ce983e2119552ae7c73f2c0e492bb781352ef/common/app/model/Badges.scala#L74
- Remove: https://github.com/guardian/frontend/blob/e06ce983e2119552ae7c73f2c0e492bb781352ef/common/app/model/Badges.scala#L142
- Delete: https://github.com/guardian/frontend/blob/e06ce983e2119552ae7c73f2c0e492bb781352ef/static/public/images/badges/childrenInTheDocks-Icon1.svg

I think that's it? But let's check it out when you're free
