### ISSUE TITLE
DCR has the data it needs to decide when to show a second most viewed tab

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/frontend#25448]
The container data sent to DCR to render the `news/most-popular` container is simply a list of trails, similar to other containers. But this component often has two tabs where each tab has a heading string and the second tab has an additional list of trails

![Image](https://user-images.githubusercontent.com/1336821/187860262-bc4b44b5-9be0-49c6-b412-c23427e384b6.png)

**Comment by bryophyta** [comment]
I think that this is completed in our MostViewed PRs, unless there's some existing business logic that we need to recreate but have overlooked? @jamesgorrie @OllysCoding

**Comment by VDuczekW** [comment]
we believe this can be closed - as other tickets have addressed this
