### ISSUE TITLE
Bug: AU news curated content collection doesn't exist

### ISSUE THREAD

**Issue by bryophyta** [guardian/frontend#25453]
We fetch curated content for 'Onwards' containers using a hard-coded list of collection ids. This includes `au-alpha/news/regular-stories`. But there is no collection with that id in the current PROD fronts config, so no data is fetched for  Australian news articles.

## UK edition has two containers, as it should

![Image](https://user-images.githubusercontent.com/37048459/188452336-d72a92e1-8938-4e48-b39f-b8692ca31988.png)

https://www.theguardian.com/australia-news/2022/aug/31/federal-icac-independents-want-safeguards-to-ensure-body-cannot-be-politicised

## AU edition only has one container, when it should have two

![screenshot of page with no curated content loaded](https://user-images.githubusercontent.com/37048459/188450407-6b314c6f-d2ab-4b75-8ead-fa61232c85fd.png)

This collection id _does_ exist in the CODE fronts config, so my guess is that it has been removed from PROD at some point (rather than it  being a typo  or  something). If this is correct, we probably need an editorial decision about which collection  to use instead for AU/News curated content.

**nb.** This is a bug both in the existing site and in the new  curated  content agent that's being created at the moment. If we get a new id, it should just be a one-line change in either codebase, however.

If we're going to talk to editorial about this, it may also be worth exploring whether there are any options which would allow us to avoid relying on a hard-coded list of ids altogether.

**Comment by Georges-GNM** [comment]
@AshCorr think you mentioned in a recent tools catchup you were looking at this?

**Comment by bryophyta** [comment]
@AshCorr sorry I can't believe that when we were pairing on this the other day I'd totally forgotten I'd opened this issue! 🤦

**Comment by AshCorr** [comment]
This is fixed now!

**Comment by Georges-GNM** [comment]
Hey both, not familiar enough with onwards to have a sense of how much work there might be in improving it, but I'm inclined to suggest creating a new ticket (or maybe an rfc/doc) for that, and this one can be closed?

**Comment by bryophyta** [comment]
@Georges-GNM sounds good! Tbh there are a few different issues in this area. I don't think we've got a ticket for the issue which underlies this particular bug though, so I'll create one now.

**Comment by Georges-GNM** [comment]
Thanks @bryophyta! Will close this ticket then.

**Comment by bryophyta** [comment]
new issue created here: https://github.com/guardian/dotcom-rendering/issues/6732
