### ISSUE TITLE
Rotate adops AWS key

### ISSUE THREAD

**Issue by mxdvl** [guardian/frontend#25516]
@OllysCoding to provide context

**Comment by jlieb10** [comment]
@mxdvl could you share some more information about this? Do we have instructions documented somewhere?

**Comment by jlieb10** [comment]
Notes:

- Key can be found here: https://security-hq.gutools.co.uk/iam/frontend
- Joshua emailed adops to see if the key is still required or can be deprecated.
- @jamesgorrie is currently the only 'admin' on the team who will have permission to actually reissue a new key. This can be changed if we want to distribute admin permissions more widely.
