### ISSUE TITLE
Pressed articles and interactives in AMP

### ISSUE THREAD

**Issue by ioannakok** [guardian/frontend#25566]
Some work needs to be done in how we handle articles and interactives that have been pressed but are requested via AMP. Currently:

* `ArticleController` [does a redirect to s3](https://github.com/guardian/frontend/blob/main/article/app/controllers/ArticleController.scala#L124-L125) but router and gives a 500. e.g. https://amp.theguardian.com/world/2018/apr/26/lynchings-sadism-white-men-why-america-must-atone

* `InteractiveController` [serves them via frontend](https://github.com/guardian/frontend/blob/main/applications/app/controllers/InteractiveController.scala#L128). e.g. https://amp.theguardian.com/environment/ng-interactive/2019/oct/11/guardian-climate-score-how-did-your-mp-do

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team and we can't address them all. With so many tickets we are potentially missing things that are high-impact so we're reorganising.
