### ISSUE TITLE
Update `FaciaPicker` to reject paid and rss pages

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/frontend#25593]
The [FaciaPicker](https://github.com/guardian/frontend/blob/main/facia/app/services/dotcomrendering/FaciaPicker.scala) file is:

1) incorrectly listing /rss fronts as supported by DCR
and
2) incorrectly showing some paid for content as supported by DCR

There is an [existing PR](https://github.com/guardian/frontend/pull/25502) to solve both of these but it has merge conflicts

**Comment by VDuczekW** [comment]
@jamesgorrie & @jamesgorrie the existing PR is now merged - can this ticket be moved to done?

**Comment by VDuczekW** [comment]
this done
