### ISSUE TITLE
Investigate whether TaggedContentController is still used

### ISSUE THREAD

**Issue by OllysCoding** [guardian/frontend#25606]
It's listed as an 'experimental' in the [onwards route file](https://github.com/guardian/frontend/blob/main/onward/conf/routes#L63)

It seems like all it does it, for 3 supported tags, it fetches the 3 pieces of content for that tag (I'm guessing most recent content?)

The code was written in a way which suggested Editions mattered, however this parameter was actually not used.

I've searched frontend & DCR and can't find any references to the route it exposes.

Example: https://api.nextgen.guardianapps.co.uk/tagged.json?tag=tone/minutebyminute

Tearing it down would involve removing 
- [TaggedContentController.scala](https://github.com/guardian/frontend/blob/main/onward/app/controllers/TaggedContentController.scala) & references in Frotend
- [Removing it from router](https://github.com/guardian/platform/blob/main/router/files/router.conf#L443)

First we should check logs, etc to ensure this endpoint isn't being queried

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team and we can't address them all. With so many tickets we are potentially missing things that are high-impact so we're reorganising.
