### ISSUE TITLE
Amazon ElastiCache for Redis 2 End Of Life

### ISSUE THREAD

**Issue by ioannakok** [guardian/frontend#25626]
We have received an email from AWS notifying us that 

> ElastiCache for Redis version 2, originally released in September 2013, will reach its End Of Life (EOL) on January 13, 2023. We are providing you with a fourth reminder to give you sufficient time to upgrade your Redis cluster(s). We recommend that you upgrade your cache cluster(s) to the latest available ElastiCache for Redis version before January 13, 2023

More details here: https://mail.google.com/mail/u/0/?ui=2&view=btop&ver=15lpbc819enuh&q=aw&search=query&th=%23thread-f:1746554585944325101&cvid=1

This ticket is to make the upgrade.

**Comment by Jakeii** [comment]
@OllysCoding Yep we've got rid of it
