### ISSUE TITLE
Review some footer links?

### ISSUE THREAD

**Issue by Georges-GNM** [guardian/frontend#25758]
In the Australian footer there is a link to the general ['about' page ](https://www.theguardian.com/about) but this doesn't appear in the US/Int editions. 

The Australian footer also includes a link to the [vacancies page](https://www.theguardian.com/info/2015/aug/04/guardian-australia-job-vacancies), which should probably be changed to the ['work for us'](https://workforus.theguardian.com/) (like the UK/US/INT editions)

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team. With so many tickets we are potentially missing things that are high-impact so we're reorganising the board - if we can get through all our high-impact tickets we can re-open these lower impact ones.
