### ISSUE TITLE
Spike of errors around the hourly in admin app

### ISSUE THREAD

**Issue by ioannakok** [guardian/frontend#25785]
Spike of errors around the hourly mark looks like its coming from the admin app with the error:
`Tag without alpha index, being shoved into 1-9: `

https://logs.gutools.co.uk/s/dotcom/goto/36e4df50-7c8f-11ed-b75f-7fd0fcc4ddb8

Taken from this list: https://docs.google.com/document/d/1-m5VDi1iZVgVbRUgLtz3IJqwqPsq8y33GRPDbWeiy2o/edit

**Comment by bryophyta** [comment]
I've looked into this a bit and I _think_ that at least some of the errors are coming from contributor tags where the `lastName` field is an empty string. If I've understood correctly, [the `orElse` chain here](https://github.com/guardian/frontend/blob/d0c9a749294b7204cd3b869b8a9b75c3743d83ab/admin/app/jobs/RebuildIndexJob.scala#L99) will let an empty string pass through, which then triggers [the error logging](https://github.com/guardian/frontend/blob/4127510b39923a3492cd9a7c5a09dcd2ee74c2d5/admin/app/indexes/TagPages.scala#L94) when it gets to the `alphaIndexKey` method.

## Unanswered questions:

1. There are >2k contributors with empty strings for last names. But it looks like we're getting more like 8k errors. Where are the rest coming from?
2. We seem to only be getting these errors in CODE, but there are contributors with empty last names in PROD CAPI, too. Are the errors not arising in PROD for some reason? Or are we failing to log the errors from PROD?

**Comment by VDuczekW** [comment]
mob? @bryophyta @Georges-GNM @ioannakok

**Comment by VDuczekW** [comment]
done

**Comment by ioannakok** [comment]
Fixed by: https://github.com/guardian/frontend/pull/25834
