### ISSUE TITLE
Investigate sass-lint PR on Frontend

### ISSUE THREAD

**Issue by bryophyta** [guardian/frontend#25806]
What's happening with this PR? https://github.com/guardian/frontend/pull/25690

**Comment by VDuczekW** [comment]
and this one https://github.com/guardian/frontend/pull/24887 

mobbing re vulnerabilities on Tuesday 17th Jan 23

**Comment by VDuczekW** [comment]
@ioannakok  is improving the process and we will do this

**Comment by bryophyta** [comment]
closed as it's included in our vulnerabilities epic
