### ISSUE TITLE
Fix Dependabot PRs in frontend

### ISSUE THREAD

**Issue by ioannakok** [guardian/frontend#25815]
Currently the snyk action is consistently failing on Dependabot PRs, due to an auth issue, e.g. https://github.com/guardian/frontend/actions/runs/3845586820/jobs/6549901836

**Comment by VDuczekW** [comment]
needs to be done

**Comment by rhiannareechaye** [comment]
@ioannakok did we fix this?

**Comment by shesah** [comment]
Closing the ticket - we don't think it is an issue anymore. is that okay @ioannakok
