### ISSUE TITLE
Fix issue with Prout taking a long time to notify for frontend

### ISSUE THREAD

**Issue by ioannakok** [guardian/frontend#25828]
After updating prout and frontend to ensure it hits actual production instances as part of an [incident action item](https://github.com/guardian/dotcom-rendering/issues/6796), it is now taking a long time to notify developers their changes are in production. This ticket is to fix the delay.

Previous PRs that introduced a better check for frontend but introduced the delay:
* Exposes the git commit id it into our http endpoints so that Prout knows exactly what commit id we're running in prod: https://github.com/guardian/frontend/pull/25795
* Prout checks for commit id: https://github.com/guardian/prout/pull/79

**Comment by VDuczekW** [comment]
to be worked on with Roberto. it is in flight but was cut short in finishing

**Comment by ioannakok** [comment]
Two PRs have been merged:
* https://github.com/guardian/prout/pull/91
* https://github.com/guardian/prout/pull/92

The issue seems to have been fixed. Let's keep the ticket in progress for a few more days to keep an eye!

**Comment by ioannakok** [comment]
It seems it takes Prout about 15 minutes to add the seen on prod labels so closing this ticket

![image](https://user-images.githubusercontent.com/19683595/217779078-4fcf49e4-7892-416f-ad79-886430ba4832.png)

![image](https://user-images.githubusercontent.com/19683595/217779162-26518228-124f-45f2-897f-d1df700a5064.png)

![image](https://user-images.githubusercontent.com/19683595/217779239-45d92fec-a530-4f97-8931-5b52caf2c9e2.png)
