### ISSUE TITLE
Bug: Right-hand column on nav bar overflows

### ISSUE THREAD

**Issue by bryophyta** [guardian/frontend#25918]
The right-hand column on the main nav bar has a couple of layout bugs at medium-sized breakpoints.

The list is a flex container with `flex-wrap: wrap;` set on it. But when the links wrap into a second column they get clipped by the browser window. The odd vertical spacing is also caused by a strange interaction between the flex-wrap layout algorithm and the text layout algorithm within the list items. (It looks like the flex container is allocating vertical space based on the assumption that text will be wrapping inside the flex children, but then the child is not actually wrapping/breaking its contents, leaving an empty space within the child.)

This bug only affects Frontend; perhaps the DCR approach could be copied here?

![Image](https://user-images.githubusercontent.com/37048459/220577225-e38f8088-91c2-4771-8af6-5542ad5cfe1c.png)

![Image](https://user-images.githubusercontent.com/37048459/220577258-8b629804-5842-4f73-9364-642a2670b920.png)

**Comment by rhiannareechaye** [comment]
Moving to won't fix as we'll address this with the upcoming DCR migration (it's not a DCR issue) and our team is focusing on vulnerabilities at the moment
