### ISSUE TITLE
"All today's stories" link on UK edition home front has wrong destination

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/frontend#26068]
On the UK edition home front (https://www.theguardian.com/uk?INTCMP=CE_UK) there is a "All today's stories" link above the footer.
Currently this points to `https://www.theguardian.com/tone/letters/all` which is incorrect. It should point to `https://www.theguardian.com/uk-news/all` instead.

Please update CP when this is resolved.

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team. With so many tickets we are potentially missing things that are high-impact so we're reorganising the board - if we can get through all our high-impact tickets we can re-open these lower impact ones.

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team. With so many tickets we are potentially missing things that are high-impact so we're reorganising the board - if we can get through all our high-impact tickets we can re-open these lower impact ones.
