### ISSUE TITLE
Investigate if we can remove `handleMembershipAccess` from `standard/main.js`

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/frontend#26341]
Some articles have a field `membershipAccess` of type `MembershipTier`:

https://github.com/guardian/frontend/blob/5288bfd78b4c649c65266542d872af9ff958e81b/static/src/javascripts/bootstraps/standard/main.js#L212-L221

implying that they can only be viewed by members (sometimes specifically paid members). The code to check whether a user has this status is here:

https://github.com/guardian/frontend/blob/5288bfd78b4c649c65266542d872af9ff958e81b/static/src/javascripts/bootstraps/standard/main.js#L61-L99

and the `membershipAccess` flag comes from the CAPI response for the article: https://github.com/guardian/content-api-models/blob/9c936e11ec5ec7bdda4f522cd9fee93b6474cf6d/models/src/main/thrift/content/v1.thrift#L1113

Are there still articles that fall into this category, or was this feature removed? If it was removed, can we also remove the above code that refers to it?

**Comment by VDuczekW** [comment]
@JamieB-gu could we have an update - is this in hand or does it need to be handed over?

**Comment by JamieB-gu** [comment]
> @JamieB-gu could we have an update - is this in hand or does it need to be handed over?

Opened the PR above to make this change. We're waiting on RR to confirm whether this can be done.
