### ISSUE TITLE
What should we do with pre-existing Okta code in Frontend?

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/frontend#26344]
There's some pre-existing Okta-related code in the codebase that performs functionality such as refreshing the Okta session. Should this be updated or removed now that we're using the `identity-auth` library to handle Okta interaction?

For example:

https://github.com/guardian/frontend/blob/22c84f55d331cfefd707b27f79adfeecad2a0828/static/src/javascripts/projects/common/modules/identity/cookierefresh.ts#L26-L45

The Identity team may be able to answer this.

**Comment by georgeblahblah** [comment]
The functionality in [`cookierefresh.ts`](https://github.com/guardian/frontend/blob/22c84f55d331cfefd707b27f79adfeecad2a0828/static/src/javascripts/projects/common/modules/identity/cookierefresh.ts) keeps the user logged in by refreshing both the Okta session and IDAPI cookies.

We should keep this functionality, as well as introducing it to DCR. @coldlink will look into adding it to [`@guardian/identity-auth`](https://github.com/guardian/csnx/blob/main/libs/%40guardian/identity-auth), so the functionality can be introduced to both platforms.

**Comment by coldlink** [comment]
PR https://github.com/guardian/csnx/pull/754
