### ISSUE TITLE
Migrate all remaining usages of `isUserLoggedIn` in `identity/api.ts` to Okta

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/frontend#26347]
We created a temporary function here to handle the Okta version of this: https://github.com/guardian/frontend/pull/26311/files#diff-f1363c4e3904fccf2fa18daf855bd2ffda72af106b83f546c3a09d9b92b07e66L171-L172

We want to move all usages of `isUserLoggedIn` to this, and then remove the old function and rename the new one.

Example of this in #26337.

```[tasklist]
### Remaining
- [ ] https://github.com/guardian/frontend/issues/26424
- [ ] https://github.com/guardian/frontend/issues/26423
- [ ] https://github.com/guardian/frontend/issues/26415
- [ ] https://github.com/guardian/frontend/issues/26428
- [ ] https://github.com/guardian/frontend/issues/26430
- [x] Rename `isUserLoggedInOktaRefactor` => `isUserLoggedIn`
```

**Comment by VDuczekW** [comment]
what was the outcome? clarify what is outstanding on this ticket? - as some items have been done - however some outstanding
