### ISSUE TITLE
Refactor `setConsent` in `identity/api.ts` to Okta

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/frontend#26351]
Refactor usage of `fetch` to use either Okta or cookies depending on the experiment variant. Example of this here:

https://github.com/guardian/dotcom-rendering/pull/8211/files?diff=unified&w=1#diff-ae460a81df60e9adb882cddbba675359ef3ef98f869a762f3598024fd1fa55a4L132-R160

New functions added in https://github.com/guardian/frontend/pull/26311 may be useful for this.

https://github.com/guardian/frontend/blob/22c84f55d331cfefd707b27f79adfeecad2a0828/static/src/javascripts/projects/common/modules/identity/api.ts#L405-L414

**Comment by VDuczekW** [comment]
we may be able to remove the method and may be able to close this one

**Comment by georgeblahblah** [comment]
Done in #26397

**Comment by georgeblahblah** [comment]
Won't do. See #26397
