### ISSUE TITLE
Deprecate Article Share Counts

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/frontend#26568]
Frontend supports some routes and features around article share counts, behind a feature switch. The switch is currently off, and the routes are returning errors due to errors from the underlying APIs.

## Questions for discussion

- Should we keep share counts code in Frontend (and DCR), or is it time to remove it?
- Are we likely to re-enable this feature? 
- What motivated the switch to be turned off?
- Are the errors from the underlying API possible to resolve? 
- Should we continue to implement new features (like articles for apps in DCR) assuming share counts will come back at some point?

## Code

Feature switch: https://github.com/guardian/frontend/blob/c62bcca75dbf8f6336ecc3459e6778e71209f761/common/app/conf/switches/FeatureSwitches.scala#L10-L17

https://github.com/guardian/frontend/blob/c62bcca75dbf8f6336ecc3459e6778e71209f761/applications/app/controllers/ShareCountController.scala#L8-L27

https://github.com/guardian/dotcom-rendering/blob/8bc360e6fdd5bd4c5d18b55a9e95c29abdc266dc/dotcom-rendering/src/components/ShareCount.importable.tsx#L65-L104

**Comment by rhiannareechaye** [comment]
I think we should simply deprecate. If this switch is off and the feature is broken, we should deprecate and it can be rebuilt if deemed necessary. Should this go into 'pick me ups'?
