### ISSUE TITLE
Stale / old articles appearing in Most Viewed component

### ISSUE THREAD

**Issue by mattandrews** [guardian/frontend#26607]
# ISSUE

Hello, Guardian folks! Apologies if this is the wrong repo to raise this, my Guardian-fu is a bit rusty...

I've noticed that the "Most viewed" component currently seems to have frozen:
![image](https://github.com/guardian/frontend/assets/394376/1d497d2c-2a1a-4b4b-8053-7125547afe38)

Every link in there currently points to an article from 22 September (writing this on 26th). The "Games" tab seems to show newer stuff, though.

## Steps to Reproduce

Visit an article and scroll to the bottom. Confirm the "Most viewed" component shows a set of stale results.

## Actual Results (include screenshots)

See above

## Expected Results (include screenshots)

I would expect a more recent/fresh article to appear

## URL

https://www.theguardian.com/games/2023/sep/26/mortal-kombat-1-review-johnny-cage-and-co-return-with-the-same-old-moves

## OS and Browser details

- Device: Macbook Pro
- Browser (inc version): Chrome v116
- OS: MacOS

**Comment by mattandrews** [comment]
... I'm now seeing fresh articles in this list:

![image](https://github.com/guardian/frontend/assets/394376/402214a8-8922-4da1-bfaa-8a0171320a07)


So maybe a temporary glitch?!

**Comment by georgeblahblah** [comment]
Thanks so much for raising this @mattandrews!

Frontend uses an agent to periodically update the list of most viewed articles, but the agent had been failing silently following a seemingly unrelated change. https://github.com/guardian/frontend/pull/26606 fixed the underlying cause of the failing agent, and so the Most Viewed list is showing up to date articles again.
