### ISSUE TITLE
Use the new facia SNS topic for facia-press SQS queue

### ISSUE THREAD

**Issue by ioannakok** [guardian/frontend#26790]
### Current architecture

<img width="1317" alt="image" src="https://github.com/guardian/frontend/assets/19683595/e0b54615-d9ac-48e1-bca3-189a0a86f05b">

More about the fronts architecture [here](https://github.com/guardian/frontend/blob/main/docs/02-architecture/02-fronts-architecture.md)

1. Fronts tool sends a PressJob to the facia-press queue
2. Facia-press presses the front and stores JSON to the bucket
3. facia-purger lambda [gets triggered](https://eu-west-1.console.aws.amazon.com/lambda/home?region=eu-west-1#/functions/facia-purger-lambda-PROD-Lambda-190WIIV8979JL?tab=configure) when a new front gets stored in the bucket and purges the front. Example [logs](https://logs.gutools.co.uk/s/dotcom/goto/0a848ec0-aaeb-11ee-9200-935cda9b1c3e).

### New architecture

<img width="1578" alt="image" src="https://github.com/guardian/frontend/assets/19683595/cf172808-dd90-47e5-8c1e-ffe7b4546a96">

### Useful links
* [frontpress.sqs.tool_queue_url](https://github.com/guardian/frontend/blob/85fccaf6d3489c972437afe5a28074e5733eece8/common/app/common/configuration.scala#L589) =  URL
* Related [facia-tool PR](https://github.com/guardian/facia-tool/pull/1534)
* facia-press [cloudformation](https://github.com/guardian/platform/blob/main/provisioning/cloudformation/frontend.yaml#L1082)
* mobile account set up: https://github.com/guardian/mobile-fastly-cache-purger

**Comment by alinaboghiu** [comment]
Moving to this sprint as Tom suggested a pairing session on this

**Comment by abeddow91** [comment]
https://github.com/guardian/platform/pull/1569 <- Platform PR that subscribes the SQS to the SNS topic

**Comment by ioannakok** [comment]
Ticket completed
