### ISSUE TITLE
Video articles: add article age indicator

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/frontend#26853]
## Description

On DCR-rendered articles, we show an "age warning" on articles depending on their publication date. Given the nature of news to be published this year, we should include an age warning on video articles which are still rendered by Frontend.

Thanks to @SiAdcock for the idea!

## Useful links

- [Age Warning component from DCR](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/components/AgeWarning.tsx)
- [Age warning logic](https://github.com/guardian/dotcom-rendering/blob/0fadeb92c8e66a37412ae369f617f43c1218cba5/dotcom-rendering/src/lib/age-warning.ts)

**Comment by shesah** [comment]
One to do after video pages have been migrated to DCR

**Comment by abeddow91** [comment]
closing as this was resolved by the migration to DCR
