### ISSUE TITLE
Upgrade To AWS SDK v2 For Some AWS Libraries

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/frontend#27368]
https://github.com/guardian/frontend/pull/27315#issuecomment-2228603319

```[tasklist]
### Tasks
- [ ] Upgrade to `"software.amazon.awssdk" % "dynamodb"` latest version - required for the `scanamo` upgrade
- [ ] Upgrade to `"software.amazon.awssdk" % "sdk-core"` latest version - required for the `com.gu:kinesis-logback-appender` upgrade
```

**Comment by ioannakok** [comment]
Draft PR for using dynamoDB AWS SDK v2: https://github.com/guardian/frontend/pull/27380
For the 2nd task it might be preferable to migrate `kinesis-logback-appender` to `devx-logs`: https://github.com/guardian/platform/issues/1558
