### ISSUE TITLE
Add solutions to the accessible version of crosswords

### ISSUE THREAD

**Issue by ioannakok** [guardian/frontend#27462]
@bryophyta has raised this in the WebX chat: https://chat.google.com/room/AAAAG9rU0m0/iP6ru3P4Xfg?cls=12

> We publish an [accessible version](https://www.theguardian.com/crosswords/accessible/quick/16951) of our crosswords on the website, which is currently (along with the rest of the crossword pages) [rendered in Frontend](https://github.com/guardian/frontend/blob/33f95ece905702c9874dca8fcc0aff7c973c9912/applications/app/controllers/CrosswordsController.scala#L123). On the `digital.crosswords` mail list we received a message via Userhelp from a reader who asked if we could add solutions to the accessible version. (CP has reported that they've had similar requests before.)

**Comment by shesah** [comment]
We will ping Nerwsroom res to see if they can pick this up or not

**Comment by ioannakok** [comment]
Closing this as @bryophyta from the News Resilience team has picked it up
