### ISSUE TITLE
UEFA Champions League Table "lines" incorrect

### ISSUE THREAD

**Issue by rowannekabalan** [guardian/frontend#27515]
The "promotion lines" in this table are incorrect"
![Image](https://github.com/user-attachments/assets/0de076d4-e167-4171-97b0-5e45d899b588)

The correct ones appear here in the BBC table:

https://www.bbc.co.uk/sport/football/champions-league/table

**Comment by Sanjai451** [comment]
I have reviewed the issue can I get assigned to work with this project?

**Comment by rowannekabalan** [comment]
More requests:

The sport desk has now raised more issues with football tables. 

They've said that as well as the qualification lines being placed incorrectly, the following is also incorrect for the [champions league table](https://www.theguardian.com/football/championsleague/table):
Last year's Group E is rendering at the bottom
The green/red markers on the right to signify form are wrong, with some teams having last season's results included. 

There also appear to be issues with the [Europa League table](https://www.theguardian.com/football/uefa-europa-league/table) regarding the qualifying lines and the green/red markers.
