### ISSUE TITLE
Duplicated comments in discussions

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#4058]
That must be the worst bug report ever, since I cannot find a way to reproduce it, but it happened to me at least 4 times in the last week or so. Always on FF 29, Win 8.1.
After expanding discussions, some comments and replies are duplicated. After duplicating the browser tab and following exactly the same clicks, it doesn't happen again... until the next time.
![discussion bug](https://cloud.githubusercontent.com/assets/6032869/2848872/4389995c-d0c8-11e3-97b0-e192f926b0fb.GIF)

**Comment by jamesgorrie** [comment]
When sorting by newest first, the `page` pointer lands up being unreliable i.e. Page 9's contents will change dependant on the activity of the discussion.

There are multiple solutions to this - one being [cursored pagination](https://dev.twitter.com/overview/api/cursoring). The problem with this is that the cache is very easily broken.

Another would be to always use `sortBy: "oldest"` and have the order of the comments rendered in reverse. This way a page reference would always point to the same place.

**Comment by michaelwmcnamara** [comment]
cleanup: currently with Discussion folks so keeping open

**Comment by johnduffell** [comment]
closing as it's not been fixed so far so in all likelyhood it won't be fixed in future

**Comment by paperboyo** [comment]
> closing as it's not been fixed so far so in all likelyhood it won't be fixed in future

Love the reasoning :laughing:!

If that's any consolation, I haven't seen that in a while...

**Comment by johnduffell** [comment]
We're going to start triaging things properly and only having things in the
list if we're working on.  Discussion isn't great, but we don't seem to
care too much about it (I'm sure we should though)  If we do decide to fix
it, we won't need a list as we can find the bugs easily...

On 8 July 2015 at 11:42, Mateusz <notifications@github.com> wrote:

> closing as it's not been fixed so far so in all likelyhood it won't be
> fixed in future
>
> Love the reasoning [image: :laughing:]!
>
> If that's any consolation, I haven't seen that in a while...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/4058#issuecomment-119537908>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396
