### ISSUE TITLE
Video item without an image shouldn't be considered 'no image'

### ISSUE THREAD

**Issue by ironsidevsquincy** [guardian/frontend#4225]
If a video item doesn't have an image, we use a place holder, but the rest of the item still looks like it's a no-image item (larger headline, standfirst displayed)

![screen shot 2014-05-14 at 14 05 29](https://cloud.githubusercontent.com/assets/74132/2971311/e79dc9aa-db68-11e3-90fe-7ba334b9d196.png)

**Comment by michaelwmcnamara** [comment]
cleanup: closing - noone seems to be showing any interest. Will reopen if becomes necessary.
