### ISSUE TITLE
[Live blog] Blank embedded Tweets in ‘Oldest’ order

### ISSUE THREAD

**Issue by Smylers** [guardian/frontend#4464]
## Steps to reproduce

1. View a liveblog with an embedded Tweet in it, such as [the 9th over of England's innings yesterday](http://www.theguardian.com/sport/2014/may/28/england-v-sri-lanka-third-odi-live#block-5386085de4b0f6774a4ff2c9). Note the blog is in the default reverse-chronological ordering.
2. Go to the top of the page and click on ‘Oldest’ so it changes to ‘Latest’.
3. Scroll down to find the block with the embedded Tweet (pressing `Enter` in the URL bar should jump to it). It's disappeared — there's an empty box with a shadow where the Tweet's content was:

![guardian_beta_missing_tweet](https://cloud.githubusercontent.com/assets/598534/3115573/8203f026-e70a-11e3-90f8-c81d5a57567c.png)

## Environment

Device: laptop
Browser: I checked both Firefox and Chrome
OS: Linux (Firefox) and Windows (Chrome)

And, let's put the word ‘Twitter’ in this bug report, just in case anybody is searching by that.

**Comment by jennysivapalan** [comment]
@ScottPainterGNM I can't reproduce this. Which browser / device did you see this on?

**Comment by Smylers** [comment]
@jennysivapalan I still experience the problem on all of Firefox and Chromium on Ubuntu Linux, and Firefox, Chrome, and IE on Windows 7 (on some of which I was logged in to Twitter, and some not, in case that made a difference).

It's still cropping up in new content; here's [an example from the weekend](http://www.theguardian.com/sport/live/2015/aug/08/ashes-2015-england-v-australia-fourth-test-day-three-live#block-55c5dffee4b0901d8d6f24db) — change the order to ‘oldest first’, then in ‘Key Events’ click on ‘BREAKING NEWS: PIERS MORGAN IS ELECTED POPE’.

The effect has changed slightly since the bug was reported: there's now just an empty space where the missing Tweet should be; the curved border and shadow of the above screen shot no longer show.

**Comment by jennysivapalan** [comment]
Thanks @Smylers, I can see this happening too. I'll keep this issue open and will take a look at complex this is to fix.

**Comment by ScottPainterGNM** [comment]
The Live Blog format has been changed to remove a change to the ordering of blocks (due to the new pagination we have implemented). Have closed off issue unless we need to revisit in the future.
