### ISSUE TITLE
Discussion: Viewing paginated comments goes back to page1 on reload

### ISSUE THREAD

**Issue by glockett** [guardian/frontend#4534]
Issue when viewing comments - When clicking on a link in the pagination to page 3 - When you reload the page is redirected to page 1

View an article with over 200 comments in the pagination of comments choose page '3'
Now reload the page. The page you will be on next is page 1
But - but you should be page 3 the page you were on originally.

**Comment by michaelwmcnamara** [comment]
Still occuring. Guys is a fix coming for this? 
If not, please close as de-prioritised.

**Comment by johnduffell** [comment]
closing as it's not been fixed so far so in all likelyhood it won't be fixed in future
