### ISSUE TITLE
[interactives] Embeds duplicate the main navigation

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#4617]
Hello,
I am not sure I should report it here. If not, fell free to direct me somewhere else (to go climb a tree?:).

Windows 8.1, all browsers.
Steps to reproduce:
- go to an interactive here: http://www.theguardian.com/world/ng-interactive/2014/jun/09/born-out-of-the-ussr-the-children-of-the-revolution
- click on any face, then click on 'Read country profile' link at the bottom of person's story

Result:
The whole of the Guardian page is being embedded where the interactive was, including the main navigation.

Expected result:
Embed just the article area.

Plaese see screenshot:
![double nav](https://cloud.githubusercontent.com/assets/6032869/3216708/72218bbc-efd6-11e3-80b5-b4eb3266db56.JPG)

Regards
Mateusz

**Comment by johnduffell** [comment]
this is an interactive bug so can't be fixed by frontend, perhaps talk to the interactive team to see if they'll maintain old interactives.

**Comment by paperboyo** [comment]
Happens on the new ones too, if they use the same template... @andymason @fcage @seanclarkeguardian
