### ISSUE TITLE
Discussion: Unable to Pick a comment in CODE environment

### ISSUE THREAD

**Issue by glockett** [guardian/frontend#4954]
Steps to reproduce:
When signed in as a Staff user (IdentityCodeMonkey ) I am unable to select to PICK a comment to be featured in the CODE environment.  The link to 'Pick'  is missing.  I have extended the commenting period on the test article to expire in 2015 but still not seeing the link. 

Environment: 
GUCODE
Device: Macbook Pro
Browser: Chrome
OS: OSX 10.9.1
URL: http://m.code.dev-theguardian.com/science/grrlscientist/2012/aug/07/3

**Comment by ScottPainterGNM** [comment]
@glockett - is this still an issue? If so could you ping me the login details for that Staff User so I can try and reproduce possibly?
