### ISSUE TITLE
Hover state for play button is broken on video player

### ISSUE THREAD

**Issue by sammorrisdesign** [guardian/frontend#4999]
This is a screenshot of the hover state for the play button on the new video player. There's a thin row of pixels on the left hand side of the circle that doesn't change state. This is on the latest version of Chrome (35.0.1916.153) and on OS/X 10.8.4

![screen shot 2014-07-05 at 12 28 53](https://cloud.githubusercontent.com/assets/1607666/3486436/12a8b1ee-0438-11e4-8cd5-df69298793da.png)

**Comment by ScottPainterGNM** [comment]
Tested across Chrome, IE, Firefox and Safari and appears to be fixed. Closing issue unless it reappears and needs reopening.
