### ISSUE TITLE
[embed] Inline embeds not showing on NGW

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#5000]
Hello,
On a PC, Mac and Android in all browsers:
http://www.theguardian.com/society/2014/jul/04/nhs-patients-waiting-longer-for-routine-operations-under-coalition?view=mobile
is not showing an embedded SVG graphic that shows up fine on
http://www.theguardian.com/society/2014/jul/04/nhs-patients-waiting-longer-for-routine-operations-under-coalition?view=classic

Just to test, I've copied the embed code for that object from R2 and pasted it into a Composer article where it previewed fine, just fine...

Also, here is the 30% smaller version of the graphic, just because: http://static.guim.co.uk/ni/1404585060694/WAITING-TIMES_WEB_svgoptim.svg.

And I would finish here, but then!
http://www.theguardian.com/world/2014/jun/19/injured-explorer-rescued-germany-deepest-cave?view=mobile
is not showing two PNG graphics that are present in the R2 version. They are also of a type 'embed', the ones I could find of a type 'image' work fine...

Also, any embeds for articles created in Composer from scratch work in both environments.

Suspicious... Is this a known issue?

Regards
Mateusz

**Comment by ScottPainterGNM** [comment]
So @gidsg just to check from the related issue, am I right in thinking that the graphic isn't being served to us by CAPI?

**Comment by mchv** [comment]
@ScottPainterGNM yes that's right.

**Comment by ScottPainterGNM** [comment]
Excellent, thanks @mchv that's handy to know. Will close this off as well on that basis as not an item for frontend, thanks for clarifying.
