### ISSUE TITLE
Stale content on home page

### ISSUE THREAD

**Issue by rmurphey** [guardian/frontend#5001]
When visiting the Guardian home page, I sometimes see stale content:

![screenshot 2014-07-04 13 42 40](https://cloud.githubusercontent.com/assets/58987/3487798/ec741510-04a3-11e4-966f-6da0212380bb.png)

Note that the home page date is in the past, though the actual date in the screenshot is July 4. This has happened many times to me in the past several weeks; indeed, until recently, I wasn't able to get a fresh home page at all unless I used Chrome's incognito mode. 

## Steps to reproduce

I can reproduce this by visiting http://www.theguardian.com/us (via guardiannews.com) after visiting it in the past. If I reload even with the dev tools open -- when cache should be disabled -- I have observed the issue still happen. However, if I enter guardiannews.com into the location bar when the dev tools are already open, the content on http://www.theguardian.com/us is as expected, and subsequent reloads and navigations are fine. *However*, even though I thought I had finally gotten around some weird cache issue today by navigating to the page in a fresh window with dev tools open, I just visited the page again and the issue re-appeared. 

## Environment

Device: Retina MBP
Browser: Google Chrome 35.0.1916.153
OS: OS X 10.9.3
URL: http://www.theguardian.com/us

## Additional information

Please let me know if there's anything else that would be helpful. This seems something of a Heisenbug, I apologize I can't give you better steps to repro or more information off the top of my head.

**Comment by piuccio** [comment]
is this still an issue?

**Comment by ScottPainterGNM** [comment]
Looking to clear off old issues where possible, is this still an issue or ok to close?
