### ISSUE TITLE
User Bower to install stripe

### ISSUE THREAD

**Issue by ironsidevsquincy** [guardian/frontend#5030]
Looks like the stripe lib was just added to our [`components`](https://github.com/guardian/frontend/tree/master/common/app/assets/javascripts/components) dir directly. It should use bower to install, i.e. add it to [`bower.json`](https://github.com/guardian/frontend/blob/master/common/app/assets/javascripts/bower.json)

cc @chrisfinch

**Comment by ScottPainterGNM** [comment]
Looks to have been dealt with under #5578 , issue closed
