### ISSUE TITLE
Tags displaying strangely at top and bottom of article pages (Chrome)

### ISSUE THREAD

**Issue by theresamalone** [guardian/frontend#5095]
Some tags are breaking onto two lines, both above the headline (in the case of series tags) and at the bottom of the page in Chrome 33.0.1750.152 (MacBook Air). See screengrabs, taken from these pages:

http://www.theguardian.com/film/filmblog/2014/jul/16/why-the-manic-pixie-dream-girl-must-never-return?view=mobile

http://www.theguardian.com/film/filmblog/2013/jan/09/clip-joint-manic-pixie-dream-girls?view=mobile

![picture 25](https://cloud.githubusercontent.com/assets/5167463/3600283/e0e98eea-0cf6-11e4-8952-c19a67cda192.png)
![picture 23](https://cloud.githubusercontent.com/assets/5167463/3600285/e739c47c-0cf6-11e4-89a6-5c02b898e0d2.png)
![picture 22](https://cloud.githubusercontent.com/assets/5167463/3600301/fa09c93a-0cf6-11e4-82bb-e8786d9f48c6.png)

**Comment by ScottPainterGNM** [comment]
This appears to be fixed now, are you happy for the issue to be closed?? Checked on Chrome 42.0.2311.90 on OSX 10.10.3.
