### ISSUE TITLE
Profile > Comments shows pagination

### ISSUE THREAD

**Issue by kaelig** [guardian/frontend#5125]
This user: https://profile.theguardian.com/user/id/13543217

Posted only one comment. The expected behaviour of the page would be to have no pagination links.

![screen shot 2014-07-19 at 19 13 41](https://cloud.githubusercontent.com/assets/85783/3635429/8172a06a-0f70-11e4-935c-184a4b9b3e23.PNG)

**Comment by johnduffell** [comment]
closing as it's not been fixed so far so in all likelyhood it won't be fixed in future

**Comment by kaelig** [comment]
:person_frowning:

**Comment by johnduffell** [comment]
I think half the issues can be summed up as "discussion needs love"!  but the list of issues wasn't helping us
