### ISSUE TITLE
#start-of-comments ID missing

### ISSUE THREAD

**Issue by Smylers** [guardian/frontend#5126]
Page anchor links to `#start-of-comments` are broken, because Beta uses `id=comments` instead (which is a better name, since anchors generally jump to the start of something).

There's an instance of a broken link in [yesterday's restaurant review](http://www.theguardian.com/lifeandstyle/2014/jul/18/the-reliance-leeds-restaurant-review): see how ‘interactions with the city's restaurant fans’ (second sentence) links directly to http://www.theguardian.com/lifeandstyle/2014/jun/06/shears-yard-leeds-restaurant-review#start-of-comments, and that anchor doesn't work on Beta.

Keeping these links working would require one of:

* Changing `id=comments` to `id=start-of-comments`, and accepting the less-good name.
* Putting `id=start-of-comments` on either the parent or the first child of `<div id=comments>`, which will scroll to the same place. On that page at least, both of those elements are currently `id`-less, so are available for doing this.
* Rewriting content to find instances of `#start-of-comments` and changing them to `#comments`. But that will only work for links from other places on the site; links from other sites (and email, Tweets, and so on) would still be broken.

**Comment by johnduffell** [comment]
closing as it's not been fixed so far so in all likelyhood it won't be fixed in future
