### ISSUE TITLE
Share buttons not given enough space in Firefox when early image is 'showcased'

### ISSUE THREAD

**Issue by rcrphillips** [guardian/frontend#5224]
http://www.theguardian.com/cities/2014/jul/28/-sp-williston-north-dakota-people-oil-workers-photography-in-pictures

In chrome, there's enough padding afforded to the image in order to avoid overlapping the share buttons. 
![screen shot 2014-07-28 at 10 51 27](https://cloud.githubusercontent.com/assets/2051501/3719074/d408d9e6-163e-11e4-95ed-3462b77d0145.png)

**Comment by ScottPainterGNM** [comment]
This appears to be sorted now so closing off
