### ISSUE TITLE
Drop cap spacing broken

### ISSUE THREAD

**Issue by Pearson82** [guardian/frontend#5233]
Should be 1 less line of space below the drop cap. ie text should wrap 1 line tighter.

http://www.theguardian.com/world/shortcuts/2014/jul/27/white-privilege-worth-crowdfunding-race-relations-yaya-m

![screen shot 2014-07-28 at 15 05 23](https://cloud.githubusercontent.com/assets/3416696/3721417/4d68780c-1660-11e4-838f-3cc69b5da52c.png)

**Comment by ScottPainterGNM** [comment]
Appears to be fixed, closed unless issue reoccurs.
