### ISSUE TITLE
[Video player] General critique (long)

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#5237]
Hello!

I am not even sure it belongs on github, there are definitely some bugs here, but mostly these would be suggestions/UX musings, so feel free to close whenever. I wanted to reach all potentially interested, though. Also, it's all low priority and only my humble opinions, as always, so fell free to replace 'should' with 'could/would be nice' and 'shit' with 'subprime/award-winning'.

They are in no particular order, but I've tried to keep the "bugs" first...

1. Just before the video starts most browsers show their native controls for a moment and the poster frame is being resized/jumps - can we hide all that ugliness?

2. The interaction with the volume bar is unsatisfactory - it provides misleading feedback: the bar that signifies the current volume level can be dragged out of view at extremes.

3. At the end of the video when clicking on any item on an end plate while in full screen, video exits full screen, browser loads another video page and then the user has to click full screen again and press play to enjoy the next video. Instead, the next video should load and auto play all while in full screen mode and the underlying video page should (probably) change without the interruption in user’s experience. Maybe, it should work that way also when not in full screen?

4. When end plate is reached, the play icon should change to a replay icon.

5. If you are watching any of Popular videos, it’s also shown in Popular videos again (and sometimes is also shown in myriads of other containers:)

6. Currently in full screen, the control bar disappears when there is no user interaction wherever over the full screen, I think the control bar should stay open when the mouse is over the control bar (this is how Youtube works), but should close when the mouse is at the very bottom edge of the screen (not how Youtube works) - while I am not sure about this one, there are alternatives which are still better than the current behaviour (like the fade out to be MUCH longer while the cursor is over the control bar)…

7. With Youtube, BBC iPlayer, all browser’s native video players and many more, a video can be brought in and out of full screen by double clicking on it. I would then consider it a bug rather than the lack of a feature, that our videos do not work that way.

8. What’s the status of custom skins/controls on mobile? Isn’t Chrome on Android ready to use them?

9. Can we wrap all (also, third party, embedded) videos in our customized controls/skin?

10. In general, I think that for some types of content there are some metadata information that should be made available to the user as soon as possible - sometimes right along the thumbnails (like date for news, authorship for comment pieces etc.). That very important piece of info for videos is the length of the clip. I think it should be visible over video item thumbnails in all contexts. But at the very least, it should be available when user opens the video page. Currently, only the poster frame pic and the play icon is visible.

11. Some browsers (all but IE?) offer ‘Show/Hide controls’ functionality in the context menu of the video. Currently, this shows a duplicated native controls under ours. Isn’t there a way to hook it up to ours, so that it shows/hides it instead of the native one, just as Mute is nicely hooked up?

12. We should think about the first lined up item from the end plate to be set for autoplaying, but with the timer and the ability for the user to stop it before it starts (and maybe even to switch off that behaviour entirely - part of user preferences as an incentive for logging in?). In general, I think there are loads of possibilities to build upon the current end plate design/functionality that can increase engagement and help discovery.

13. Just as there are two ways to enter a gallery (through the gallery page when clicking on an item’s title or bypassing the gallery page and going straight to the lightbox overlay when clicking on an item’s thumbnail) and they are differentiated by the gallery icon changing state when bypassing a gallery page and not changing it when not, there, maybe, should be two ways to open a video: through a video page and by bypassing it and going straight to the video (either full screen or letterboxed (not sure about letterbox, though...)).

14. Our videos should be playable inline in articles and on fronts (just as galleries should). They should be embeddable on third party websites and shareable from within full screen video player containing the whole lineup of content if we want (just as galleries should). Externally they should offer the minimal functionality, the rest of functionality (and a clickable, vector, not-burned-in logo) should take the user to the Guardian/Observer’s site (where the balance should be here depends on if the video could carry advertising with it while presented externally (just as galleries :)

Sorry for the length, I've kept most to myself :) Thinking about something relatively easy/quick, I vote for no. 7.

Regards
Mateusz

**Comment by ScottPainterGNM** [comment]
As we're having a clear up of the issues list I will close this one off, interesting points though!
