### ISSUE TITLE
sharing: mailto - escaping of quotes

### ISSUE THREAD

**Issue by bernhardriegler** [guardian/frontend#5380]
Sharing via Mail uses mailto.
It uses the title of the article as a subject for the generated mail.
Quotes are not escaped properly (%E2%80%99 ==> %u2019)

i.e. http://www.theguardian.com/politics/2014/aug/05/lady-warsi-resigns-government-gaza-stance
--> share via mail:

NOW:
<li class="social__item" data-link-name="email">
    <a class="social__action social-icon-wrapper" data-link-name="top" href="mailto:?subject=Lady%20Warsi%20resigns%20over%20UK%E2%80%99s%20%E2%80%98morally%20reprehensible%E2%80%99%20stance%20on%20Gaza&amp;body=http%3A%2F%2Fwww.theguardian.com%2Fpolitics%2F2014%2Faug%2F05%2Flady-warsi-resigns-government-gaza-stance">
        <span class="u-h">Share via Email</span>
        <span class="social-icon">
<i class="i-share-email i"></i>
</span>
    </a>
</li>

FIXED ESCAPING:
<li class="social__item" data-link-name="email">
    <a class="social__action social-icon-wrapper" data-link-name="top" href="mailto:?subject=Lady%20Warsi%20resigns%20over%20UK%u2019s%20%u2018morally%20reprehensible%u2019%20stance%20on%20Gaza&amp;body=http%3A%2F%2Fwww.theguardian.com%2Fpolitics%2F2014%2Faug%2F05%2Flady-warsi-resigns-government-gaza-stance">
        <span class="u-h">Share via Email</span>
        <span class="social-icon">
<i class="i-share-email i"></i>
</span>
    </a>
</li>

**Comment by ScottPainterGNM** [comment]
Is this still an issue or can it be closed off?

**Comment by janua** [comment]
It's probably still an issue, I couldn't recreate though.

**Comment by bernhardriegler** [comment]
still an issue for my testsetup:
Win7, 
Outlook 14.0.7145.5000 (part of MS Office Proffesional Plus 2010),
Chrome 42.0.2311.90

The subject in the Mail looks like this:
```
Lady Warsi resigns over UKâ€™s â€˜morally indefensibleâ€™ stance on Gaza
```

**Comment by johnduffell** [comment]
closing as it's not been fixed so far so in all likelyhood it won't be fixed in future

GMail does seem to be able to back calculate the original, but I'd imagine we're basically treating UTF-8 as ascii.

however... feel free to go in and do a github Pull request with a fix! =)
