### ISSUE TITLE
Relative times are not accurate on live blogs

### ISSUE THREAD

**Issue by alastairjardine** [guardian/frontend#5455]
![screen shot 2014-08-08 at 11 27 01](https://cloud.githubusercontent.com/assets/4292469/3855532/a91fd1a2-1ee6-11e4-8cf3-97fca2f973e7.png)

For live blogs, the relative time stamps don't seem to get updated. Safari 7.0.5  on 10.9.4. 

In the attached screenshot, the time says 36s ago/11:18. The time on my machine was 11:27.

It should read "9 minutes ago" (or something closer to that).

**Comment by paperboyo** [comment]
Dulicate of https://github.com/guardian/frontend/issues/4956. Seems fixed. Safe to close?
