### ISSUE TITLE
Preview login redirects to humans.txt

### ISSUE THREAD

**Issue by rrees** [guardian/frontend#5559]
I thought after logging in I would go to the page I was trying to preview. Not sure if this is just something with my setup or universal.

**Comment by ScottPainterGNM** [comment]
@rrees is this still an issue or can it be closed off? If it is could you provide an example please?

**Comment by rrees** [comment]
For posterity the redirect that the authentication does is based on the last url it receives. So I had the Humans Chrome extension installed so the last url seen is the request fro `humans.txt`.

As most people won't have these kind of extensions installed it's not a big issue.
