### ISSUE TITLE
Navigation: force desktop width in IE <= 8

### ISSUE THREAD

**Issue by kaelig** [guardian/frontend#5649]
In old IEs, the global layout is locked at a width 12 columns, but the nav is fluid. It would probably make sense to lock the nav to this width in these browsers.

**Comment by ScottPainterGNM** [comment]
Unable to reproduce issue in IE8, nav and containers seem to be aligned. previous version of IE are no longer supported though also don't seem to be able to replicate this issue so closed unless someone can re-produce.
