### ISSUE TITLE
Television &amp; Radio in video end slate

### ISSUE THREAD

**Issue by robertberry** [guardian/frontend#5651]
![screen shot 2014-08-20 at 10 01 02](https://cloud.githubusercontent.com/assets/1001642/3978542/10e2cb94-2849-11e4-8bdf-6b3e050e9616.png)

You can see in the Content API that the &amp;amp; is part of the webTitle of the section. 

http://content.guardianapis.com/tv-and-radio

Which feels wrong to me ... that field should only contain text, not arbitrary HTML. We've had to do things to turn it back into a normal string on Mobile, too, which feels ugly. It's probably like that due to something in R2 though. Do we document anywhere which fields should contain what?

**Comment by paperboyo** [comment]
Seems fixed. Safe to close?

![tv radio endslate](https://cloud.githubusercontent.com/assets/6032869/5988641/bd4726ee-a960-11e4-82db-85020d22bab5.PNG)

**Comment by robertberry** [comment]
Yup :+1:
