### ISSUE TITLE
Empty related content block for legally sensitive content

### ISSUE THREAD

**Issue by gidsg** [guardian/frontend#5733]
Steps to reproduce
================
Go to: http://www.theguardian.com/uk-news/2014/aug/26/rebekah-brooks-hacking-trial-costs-news-uk?view=responsive
Actual Results
===========
Empty related content block
![screen shot 2014-08-26 at 17 12 04](https://cloud.githubusercontent.com/assets/1764158/4047619/ca500fb4-2d3b-11e4-8f61-1e0572e06c60.png)
Expected Results
=============
Don't show related content block if ```show-related=true``` returns no results as in this case http://content.guardianapis.com/uk-news/2014/aug/26/rebekah-brooks-hacking-trial-costs-news-uk?show-related=true (typically when the content is legally sensitive)

**Comment by paperboyo** [comment]
Can’t reproduce at the given URL. Do not know how to test others like that, though.

**Comment by gidsg** [comment]
Thanks for triaging this @paperboyo looks like it is fixed as Related Content container no longer appears/
