### ISSUE TITLE
Twitter image tag on content pages is incorrect

### ISSUE THREAD

**Issue by crifmulholland** [guardian/frontend#5769]
See: view-source:http://www.theguardian.com/football/2014/aug/28/the-fiver-england-captain-wayne-rooney

This is incorrect (should have http:) at start, but can be removed.
<meta property="twitter:image:src" content="//i.guim.co.uk/w--/h--/q-95/sys-images/Football/Pix/pictures/2014/8/28/1409236960039/Mr-Roy-cracks-wise-012.jpg"/>

As this has the correct url:
<meta property="og:image" content="http://static.guim.co.uk/sys-images/Football/Pix/pictures/2014/8/28/1409236960039/Mr-Roy-cracks-wise-012.jpg"/>

**Comment by ScottPainterGNM** [comment]
Hi @crifmulholland did this ever get resolved??

**Comment by crifmulholland** [comment]
Yes, it looks sorted. You can check urls on https://cards-dev.twitter.com/validator

**Comment by ScottPainterGNM** [comment]
Awesome thanks!
