### ISSUE TITLE
Colour management issue causes images to look ugly, inconsistent

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#5780]
Hello,

Not sure it is a frontend problem, but some image specific issues were discussed here... and maybe someone could direct me/issue where appropriate.

All platforms; different symptoms depending on OS/browser colour management support (not on the actual system's colour calibration state!):
URL: http://www.theguardian.com/world/2014/aug/31/eu-leaders-summit-ukraine-russia-war-fears

Thumbnail image appears unsaturated compared to main image (FF 32b on Win 8.1, here).

Image thumbnail displays wrong colours:
![thumb](https://cloud.githubusercontent.com/assets/6032869/4100650/39d58fca-30a8-11e4-9ea1-514e9567044d.PNG)

Main media displays correct colours:
![main](https://cloud.githubusercontent.com/assets/6032869/4100651/3d54b7b6-30a8-11e4-8c2b-f35e7e3e7e36.PNG)

The reason for this behaviour is that the main media has an embedded colour profile (ProPhoto RGB) but the thumbnail image, having the same RGB values, has no embedded profile. Whatever mechanism created the thumbnail(s) just disregarded the profile and haven't done any colour conversion.

On systems/browsers (e.g. all my Android browsers) where there is no colour management, both images would appear unnaturally unsaturated, being either assumed sRGB (most common) or just displayed as is (in the display's colour space).

Given the current state of colour management (poor on mobile platforms), the most correct/safest behaviour would be for the images to be converted from whatever embedded profile to sRGB and the profiles stripped afterwards.

The less incorrect behaviour (but the desirable one in the ideal world) would be for the algorithm to not do any colour conversion, merely embed the correct colour profile in any child images.

This particular instance is but one example of errors that might result from dumb, colourblind systems.

Regards
Mateusz

**Comment by ScottPainterGNM** [comment]
@paperboyo I'm having trouble working out how best to replicate this issue, could you advise?

**Comment by paperboyo** [comment]
This is still very much an issue, but the work is ongoing to address it. The solution for frontend imagery is two-pronged:
- make sure media service deals with colours correctly
- make sure the new resizer will

Currently both are wrong, but we are working on it. I think it's safe to close this issue, I won't let it rest until it's fixed anyway :laughing:
If you would still like to see how these kind of problems may look - I can bore you to death with it and I have a wide gamut monitor to prove it :wink:

Regards
Mateusz
