### ISSUE TITLE
Print page formatting broken on Safari

### ISSUE THREAD

**Issue by Pearson82** [guardian/frontend#5971]
A staff member (through help desk) has flagged this. Page formatting means you can't print the page from Safari.

![screen shot 2014-09-16 at 15 45 38](https://cloud.githubusercontent.com/assets/3416696/4289018/61fba8f8-3db0-11e4-822e-180924a4bb33.png)

**Comment by johnduffell** [comment]
this was fixed a while ago 
![image](https://cloud.githubusercontent.com/assets/7304387/8569156/5add7d04-256c-11e5-8f3d-a5d5d9ba3036.png)
