### ISSUE TITLE
Media player unusable without images

### ISSUE THREAD

**Issue by ironsidevsquincy** [guardian/frontend#5972]
* Turn off images, e.g. remove `svg` class from body
 * Player controls have no text fallback - unusable

![screen shot 2014-09-16 at 15 48 43](https://cloud.githubusercontent.com/assets/74132/4289079/e72f9804-3db0-11e4-840e-78836eda1861.png)

**Comment by ScottPainterGNM** [comment]
Reproduced - the area where the player images should be are selectable in Chrome to use the media player but there is no indication of how these would be selected.

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
