### ISSUE TITLE
[Gallery] History woes

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#6144]
Hi

An extended version of https://github.com/guardian/frontend/pull/5934#issuecomment-55925018.

There is an unneeded step in history while using galleries. The lightbox is not completely disconnected from history.

Steps to reproduce:
1. open a gallery page
2. click on an image to enter the lightbox
3. click ‘previous’ button to get to the end slate
4. click on any galleries from an end slate
5. on a new gallery page, click on any image to enter lightbox

Now use the history to go back in time. The actual result is:
1st click on a back button takes you to 2nd gallery page
2nd - opens the first lightbox **(this should not happen as the lightbox should be completely disconnected from history)**
3rd - opens the first gallery page
4th - **does nothing** (sic!)
5th - the beginning

The expected result would be not to have steps no. 2 & 4. Unless someone decides (wrongly:) that step no. 2 is no biggie, then at least we should not have step no. 4.

Regards
Mateusz

p.s. I still cannot find a reproducible case of me having to tap back button twice on mobile to exit the lightbox :(

**Comment by paperboyo** [comment]
Hi,

Also, what may be related, every page reload while in a lightbox registers a step in history.

Regards
Mateusz

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future

**Comment by paperboyo** [comment]
![watching you](https://cloud.githubusercontent.com/assets/6032869/8570547/f9c03d38-2578-11e5-8b85-3d7b04ebe3ce.gif)

**Comment by johnduffell** [comment]
:fearful:
