### ISSUE TITLE
iPad, iPad-mini, Nexus 7 (landscape) display problem with first 2 stories in fixed-small-fast-VIII containers

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6204]
Display of fixed-small-fast-VIII containers on the http://m.code.dev-theguardian.com/all-new-containers page have a display issue when shown on ipad portrait mode.

The issue is that the length of the first two cards is stretched out of proportion leaving an area of whitespace that stretches across almost a third of the visable length of the page.

Issue has been seen on iPad and iPad-mini in portrait mode and also on the Galaxy Nexus 7 in landscape mode.

(screenshot is from iPad Air in portrait mode)

![img_0001](https://cloud.githubusercontent.com/assets/7239344/4491373/34bb6150-4a38-11e4-9860-dc5ba1af3ed0.PNG)

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
