### ISSUE TITLE
Page tags overflow at tablet breakpoint

### ISSUE THREAD

**Issue by tudorraul** [guardian/frontend#6261]
![screen shot 2014-10-02 at 17 57 20](https://cloud.githubusercontent.com/assets/1492162/4494806/6e00a796-4a55-11e4-98e0-4b0577c9a5d5.png)

**Comment by paperboyo** [comment]
Can’t reproduce. Safe to close?

**Comment by tudorraul** [comment]
might have been fixed in the meantime :+1:

**Comment by ScottPainterGNM** [comment]
Appears to be fixed, closed
