### ISSUE TITLE
New football tables should have blue colour on heading links

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6275]
On tables currently in prod, heading links are coloured blue which highlights that they can be clicked or selected (especially for phones and tablets where there is no mouseover to change icon)
Currently the fixtures in our new snaps have these headings coloured black. There is nothing to indicate to the user that they can select these headings to navigate to the related page.

Can we make them blue like they currently are in prod?

example:
The current football snaps in PROD:

![current snap](https://cloud.githubusercontent.com/assets/7239344/4506620/8b3ae10a-4b04-11e4-82a3-dff4e066482f.png)

vs 

The new snaps - currently in CODE:

![new snap](https://cloud.githubusercontent.com/assets/7239344/4506633/b0fcb436-4b04-11e4-95f4-f682467cdb06.png)

- [ ] Heading links in new snaps containing football fixtures should have the same colour as headings links in the current live snaps.

- [ ] View all fixtures should also be this colour, indicating it too can be selected.

**Comment by ScottPainterGNM** [comment]
This looks to be resolved in CODE from what I can see, closed unless you disagree @michaelwmcnamara
