### ISSUE TITLE
Missing padding below caption of main video

### ISSUE THREAD

**Issue by theefer** [guardian/frontend#6309]
Captions from main videos seem to be lacking bottom margin/padding to space it from the text. Looking at the CSS, it's missing the `caption--main` class that introduces the space with main images.

![screen shot 2014-10-06 at 20 17 35](https://cloud.githubusercontent.com/assets/36964/4531816/8741c650-4d8d-11e4-97ec-c513df420b64.png)

**Comment by paperboyo** [comment]
Seems fixed. Safe to close?

![video embed caption](https://cloud.githubusercontent.com/assets/6032869/5988710/82910788-a963-11e4-8e29-515305c21e79.PNG)

**Comment by theefer** [comment]
Indeed, seems fixed
