### ISSUE TITLE
Related content on interactive page shows double-border on some stories

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6337]
Related content section on http://www.theguardian.com/reader-events/ng-interactive/2014/oct/03/the-observer-presents-observer-ideas-a-festival-for-the-mind shows a double line on top border and missing line on bottom border on some of the stories in this container..

![screen shot 2014-10-07 at 17 37 53](https://cloud.githubusercontent.com/assets/7239344/4546153/15bc82a4-4e41-11e4-9261-80647c2ce16c.png)

**Comment by ScottPainterGNM** [comment]
This appears to be working fine now, closed issue.
