### ISSUE TITLE
Comment submission text formatting is a bit broken in IE9

### ISSUE THREAD

**Issue by mattandrews** [guardian/frontend#6351]
I've reproduced this myself.

Comments can't be posted:

![image](https://cloud.githubusercontent.com/assets/394376/4560480/7151d466-4ef5-11e4-8d19-d8ef97e65186.png)

Formatting buttons dump code in the wrong place:

![1](https://cloud.githubusercontent.com/assets/394376/4560493/8cc74384-4ef5-11e4-8377-3a5527337315.gif)

Recommending comments doesn't work (can't do a screencapture for some reason but it seems to be 403ing when making the request)

Lots of users moaning about it in the business blog threads.

**Comment by ScottPainterGNM** [comment]
Bold formatting bug reproduced

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
