### ISSUE TITLE
Title of commercial components is overlapping action button on mobile screens

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6370]
Display of commercial components on mobiles.
Where a component has an action button on the same line as the title, any medium to long title (eg "guardian masterclasses", "guardian holiday deals") will overlap the button on mobile devices.

![screen shot 2014-10-09 at 12 12 57](https://cloud.githubusercontent.com/assets/7239344/4575495/11aec100-4fa8-11e4-85bc-b429a6373e9c.png)

![screen shot 2014-10-09 at 12 13 16](https://cloud.githubusercontent.com/assets/7239344/4575498/1770ef28-4fa8-11e4-8230-1c0d2b733444.png)

**Comment by ScottPainterGNM** [comment]
Fixed in linked PR, closed
