### ISSUE TITLE
Space under video

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/frontend#6380]
I'm not sure which is right so not fixing.
If you let me know I can.

[Article](http://www.theguardian.com/environment/2014/oct/09/lego-ends-shell-partnership-following-greenpeace-campaign)

---

![nospace](https://cloud.githubusercontent.com/assets/31692/4577601/e1931730-4fbd-11e4-9e54-6a05b4212336.png)

---

![space](https://cloud.githubusercontent.com/assets/31692/4577602/e1951d1e-4fbd-11e4-991c-9b1e0f2ca3ae.png)

**Comment by paperboyo** [comment]
Seems fixed. Safe to close?
