### ISSUE TITLE
Articles using new containers - css not loaded for items at bottom of page

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6392]
This is to track the issue with broken containers at bottom of articles using new formats.
Example http://www.theguardian.com/travel/2014/oct/09/thomson-airways-flights-family-couples-seating.

Bottom containers show with no css:

![screen shot 2014-10-09 at 17 15 06](https://cloud.githubusercontent.com/assets/7239344/4579718/7a14f68e-4fcf-11e4-8813-d6fcdfc9406c.png)

**Comment by ScottPainterGNM** [comment]
Looks to be fixed, closed.
