### ISSUE TITLE
Opinion column on uk frontend - cutout images appearing below comment count and time of publishing

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6445]
Visible on uk home page.
cutout images - eg on editorial pieces are appearing below the comment count and time of publish.
this adds a large amount of whitespace and breaks the display.

![screen shot 2014-10-13 at 12 33 55](https://cloud.githubusercontent.com/assets/7239344/4612789/1e9dacbe-52cd-11e4-9987-811194b96a20.png)

**Comment by ScottPainterGNM** [comment]
Tidying up issues and closed this off as looks to be resolved.
