### ISSUE TITLE
Sublinks should appear on mobile

### ISSUE THREAD

**Issue by crifmulholland** [guardian/frontend#6474]
All the same sublinks should as on desktop should appear on mobile.

![image](https://cloud.githubusercontent.com/assets/796176/4627915/5dc5a3a6-5390-11e4-8b02-6b89c6b5064a.png)

![image](https://cloud.githubusercontent.com/assets/796176/4627921/69aeccf6-5390-11e4-98a4-d5d7b8ffb252.png)

@sammorrisdesign @sndrs

**Comment by ScottPainterGNM** [comment]
I think this appears to be resolved, multiple sublinks within the same container on the network front today are displaying on mobile breakpoints. Happy for me to close off? @crifmulholland

**Comment by crifmulholland** [comment]
sure.
