### ISSUE TITLE
Icon apocalypse on old Android phones

### ISSUE THREAD

**Issue by theefer** [guardian/frontend#6491]
All icons appear to be completely broken on the site on the stock browser on an Android 2.3.6 phone.

This includes the logo, the top nav, the "read more" and share icons, etc, as per the screenshots (photos) below.

I think it started happening a week or so ago, so @phamann reckons it may be related to @ironsidevsquincy's refactoring of the icon.

![img_20141015_083822](https://cloud.githubusercontent.com/assets/36964/4643432/751a93a8-544f-11e4-8c3c-c00ee507a351.jpg)
![img_20141015_083809](https://cloud.githubusercontent.com/assets/36964/4643431/73d0442a-544f-11e4-8a81-18a133a1bb1f.jpg)
![img_20141015_083943](https://cloud.githubusercontent.com/assets/36964/4643429/727e6228-544f-11e4-96bc-9bc0bd75d163.jpg)

PS: My QA assistant also noted another bug whereby "the fonts are bold everywhere", although I gather that I may not be asked to open an issue for that?

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
