### ISSUE TITLE
When defaults set in config tool clash with defaults from article type, both options are shown as selected in tool

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6505]
Relates to https://github.com/guardian/frontend/pull/6496 - raised to track as it will not be fixed in that pull request.

When you have the config for a container set to show section-kicker on all content within it, and you drag in a podcast (which shows tag kicker by default), the tool shows both of these as selected, even though they should be mutually exclusive. 
(NB: If you leave it this way and launch the container, the section kicker is displayed, not the tag kicker - this last is correct as the user has manually chosen section kickers as a default in the config and manual choice should win over system defaults)

config setting for collection miketest:
![screen shot 2014-10-15 at 14 54 05](https://cloud.githubusercontent.com/assets/7239344/4646399/d025af76-5472-11e4-9690-0fef3269dfa9.png)

Editorial tool display when podcast dragged into miketest:
![screen shot 2014-10-15 at 14 53 40](https://cloud.githubusercontent.com/assets/7239344/4646404/ec14a994-5472-11e4-9b6d-cc8eb2f604b4.png)

**Comment by ScottPainterGNM** [comment]
@michaelwmcnamara Trying to replicate this issue but the kickers now seem to be more specific for each podcast, any ideas?
