### ISSUE TITLE
Fronts / view more button - colour update

### ISSUE THREAD

**Issue by Vilderness** [guardian/frontend#6509]
The new view more button is great, so much better - however easily overlooked in practice. Can we please update the colour language (same is in comments area) - white text out of blue lozenge - cheers!

![showmore](https://cloud.githubusercontent.com/assets/6472162/4646934/664d921c-5477-11e4-901d-6c356051b63e.png)

![blue](https://cloud.githubusercontent.com/assets/6472162/4646876/0d3ccb98-5477-11e4-81e9-f0a775d91d44.png)

**Comment by ScottPainterGNM** [comment]
This change looks to have been implemented, closing issue.
