### ISSUE TITLE
Live scores page looks broken when no matches are underway

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6548]
"Live scores" is shown as the first link on the football nav which is a quite prominent position.
However if I click this when there is no matches underway, I am taken to a page that is empty apart from the most popular container.

Could we either have a message when this page is empty - something like:
"There are no matches currently underway. Check the fixtures page for the next match"  
or just hide the link on the front when there are no matches?

![screen shot 2014-10-16 at 15 44 46](https://cloud.githubusercontent.com/assets/7239344/4664390/a7a4970c-5543-11e4-9877-a9935036f3a6.png)

**Comment by ScottPainterGNM** [comment]
This has been resolved and now shows upcoming fixtures, issue closed.
