### ISSUE TITLE
Link hover targets are weird in popular tab box

### ISSUE THREAD

**Issue by mattandrews** [guardian/frontend#6576]
This is making links feel a bit odd, like they're not clickable:

![fixed](https://cloud.githubusercontent.com/assets/394376/4680213/1074a716-5609-11e4-814b-464c5ed18bfd.gif)

I suspect changing the order of the HTML so the `<a>` is the outermost element here would help:

    <h2 class="fc-item__title fc-item__title--quoted">
        <a href="http://www.theguardian.com/commentisfree/2014/oct/17/midlife-crisis-lie-motorbike" class="fc-item__link" data-link-name="article">
            <span class="headline-list__body">The ‘midlife crisis’ is a lie – now go and buy yourself a motorbike</span>
        </a>
    </h2>

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
