### ISSUE TITLE
Video - Windows 7 IE9 & Windows 8 - IE10 - unable to fullscreen video

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6595]
When I play video on IE9 in Windows 7 or IE10 on Windows 8, I am unable to display the video in fullscreen.
This is not the case in other browsers on the operating systems listed above or when running IE11 on Windows 8.

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
