### ISSUE TITLE
Image for interactive gets case of gigantism on commercial front

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6657]
Giant image on http://www.theguardian.com/us/sustainable-business : 
Image is for "business structures & sustainability, how are they connected?" in the "in case you missed" section.

Container is fixed-medium-slow-VI

Seems to have coincided with this editorial front disappearing from the editorial part of the facia-tool (it was there earlier as I was looking at it) and appearing in the commercial fronts portion of the tool.
Comparing it to an old tab I had open, the image was looking correct and normal size this afternoon. However when i re-opened it again this evening in a new browser, it has grown to giant size (see screenshot)

Item in question is an interactive so possible commercial fronts is not handling these.
Otherwise something funny might be taking place when fronts are deleted and recreated like this.
screenshot: (OMG its huuuge!!!!)
![screen shot 2014-10-21 at 18 00 55](https://cloud.githubusercontent.com/assets/7239344/4723159/702b3b0e-5945-11e4-9713-48208e8ccaf4.png)

details of front in commercial part of facia tool:
![screen shot 2014-10-21 at 18 18 41](https://cloud.githubusercontent.com/assets/7239344/4723301/b02e8c46-5946-11e4-829f-5745ecb47d72.png)
No image boost or any other settings

**Comment by ScottPainterGNM** [comment]
Can't replicate this issue - likely due to time passed but will close of unless it reappears.
