### ISSUE TITLE
Incorrect url in request on sustainable business front

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6662]
Guardian us sustainable business front - console shows error: 
"GET http://api.nextgen.guardianapps.co.ukus/sustainable-business/front-index.json net::ERR_NAME_NOT_RESOLVED"
Seems to be a reccurring query with incorrect url in get request. 
Might simply need a '/' in the url between the domain and "us"

![screen shot 2014-10-22 at 10 52 04](https://cloud.githubusercontent.com/assets/7239344/4734249/8b173756-59d1-11e4-837b-e76288cc8267.png)

**Comment by ScottPainterGNM** [comment]
Cannot re-produce, issue closed.
