### ISSUE TITLE
Collapse container option not working for nav/media-list container

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6697]
nav/media-list containers show an expand/collapse option, but selecting this has no effect on container display.
Examples can be found on live site on us/sustainable-business front.

![img_0016](https://cloud.githubusercontent.com/assets/7239344/4751623/507b3b2c-5aa0-11e4-95dd-2d6922794e7a.PNG)

**Comment by ScottPainterGNM** [comment]
Appears to be fixed, issue closed.
