### ISSUE TITLE
Nexus 7 - any front - expand container then rotate device. expanded stories show blank

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6716]
On a Nexus 7, load a front (eg /uk/sustainable-business) in landscape mode.
Expand a container to show extra stories
Rotate to portrait view.
Result:
Page redraws but stories that were displayed by expanding container display as blank boxes (see screenshot):

![screenshot_2014-10-23-16-04-05](https://cloud.githubusercontent.com/assets/7239344/4755904/3a64f9b2-5ac9-11e4-8ec5-e5709b6692e6.png)

**Comment by ScottPainterGNM** [comment]
When re-testing I couldn't reproduce this on the Nexus7 or emulating it on BrowserStack, will close off issue unless someone has this occur again.
