### ISSUE TITLE
Edition selection sometimes ignored

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6729]
I am in the US edition and navigate to an editionalised front - say "culture".
If I decide to see whats happening in the uk and so change the edition selector from us to uk,
I am occasionally being shown the uk front but with the edition selector still displaying us.

When it gets into this funny state - to make things even more confusing - selecting an editionalised front (eg - culture) will give me the us content but with the edition selector now showing "uk" as the selected edition! 

![screen shot 2014-10-24 at 13 04 57](https://cloud.githubusercontent.com/assets/7239344/4769235/e364d624-5b76-11e4-9b24-bb4c8f7476a7.png)

Issue is not systematic. Seems to only happen sometimes.
I am using macbook pro running Mavericks. Browser is Chrome 37.0.2062.94

Workaround:
Clicking home resolves it and I get uk (my selected edition) content with the correct display in the edition selector, however this isn't obvious.

**Comment by ScottPainterGNM** [comment]
Unable to reproduce this issue, closed off unless it reappears
