### ISSUE TITLE
Image sizes on Chrome 39 beta are showing too large

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6748]
Fronts viewed on Chrome 39.0 (beta version) are showing images that are too large

![screen shot 2014-10-24 at 20 11 35](https://cloud.githubusercontent.com/assets/7239344/4774867/cb70a62a-5bb1-11e4-924b-4f86645802d8.png)

**Comment by ScottPainterGNM** [comment]
Cannot reproduce this bug, closed.
