### ISSUE TITLE
IE9 - Commercial components display vertically

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6752]
IE9 - Commercial components display vertically

this is an issue on any page where the comercial components are mixed in with content 
- eg /books

![image](https://cloud.githubusercontent.com/assets/7239344/4775390/753f264a-5bb7-11e4-9d1e-a6cbfe9a442a.png)

**Comment by ScottPainterGNM** [comment]
This looks to be sorted now, closing issue.
