### ISSUE TITLE
IE11 - opinions section - "in case you missed" container - headline displays below image instead of next to it

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6754]
Looking at US cif page - container is "in case you missed" (fixed-medium-slow-VI)
The first image in the container is right justified, leaving a large amount of greyspace to the left. - no settings on the story beyond the default.

Issue is that headline has dropped below image instead of displaying next to it.
Issue occurs on all breakpoints, except mobile breakpoint.

![image](https://cloud.githubusercontent.com/assets/7239344/4775452/08276f4e-5bb8-11e4-9ac3-629b46d17576.png)

**Comment by ScottPainterGNM** [comment]
Cannot reproduce on IE11, closed issue.
