### ISSUE TITLE
/film - movies 930' width window - First story in container is far too long

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6759]
First story in "movies" container on film page is too long.
All items in container are video items. Page is a tag page as far as I can tell (no front for it in editor tool or config).

![image](https://cloud.githubusercontent.com/assets/7239344/4775529/e37b7a2c-5bb8-11e4-9e3d-3baa3c1590d7.png)

**Comment by paperboyo** [comment]
No longer applies - no such container/problem; front now curated? Safe to close.
