### ISSUE TITLE
US cif page - stories are not placed below mpu in "global view" container

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6762]
Another issue for http://www.theguardian.com/us/commentisfree
On the 813' screen width breakpoint,looking at the "talking points" container, no stories are showing below the MPU. Theres just a big column of whitespace

![image](https://cloud.githubusercontent.com/assets/7239344/4782617/4eee7494-5cfe-11e4-94c0-902ae4d11133.png)

[Update: issue used to happen on "global view" but they have changed the container type. Now it happens on "talking points" (see below for updated screenshot) type: Fixed-small-slow-V-mpu.

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
