### ISSUE TITLE
IE8 - sprites not displaying correctly - eg guardian logo and others

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6780]
Sprites not displaying correctly in IE8 - means some of the core features of the front such as the guardian logo do not display correctly:

![screen shot 2014-10-27 at 17 23 19](https://cloud.githubusercontent.com/assets/7239344/4795766/22919ca8-5dff-11e4-9f27-456bb529d86e.png)
(the guardian logo - by Francis Bacon)

**Comment by ScottPainterGNM** [comment]
This appears to be resolved, other IE8 bugs are tracked separately for sustain team to look into.
