### ISSUE TITLE
When I select the show or hide button, the button stays highlighted, but highlight is partially cut off.

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6797]
When I select the show or hide button on chrome, the button stays highlighted

![screen shot 2014-10-28 at 10 52 30](https://cloud.githubusercontent.com/assets/7239344/4807333/9c1a3406-5e93-11e4-9da6-9e7c03da3e9a.png)

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
