### ISSUE TITLE
config tool - It is possible to create a container without assigning a container type

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6800]
This has happened on live.
In the commercial components config tool, users created a number of pages and saved the container without specifying a type.

We either need to force the user to select a type or have a default container type that prepopulates this field in the config tool.

When type is empty it breaks the "show more" button:

![screen shot 2014-10-28 at 12 28 36](https://cloud.githubusercontent.com/assets/7239344/4808216/08f2b8b4-5e9e-11e4-9b4d-8b6cdd7f19f8.png)

**Comment by piuccio** [comment]
type and title are now mandatory. It's not possible to create a container without those. Closing
