### ISSUE TITLE
IE11 - when you play video, you either get no ad, or video hangs 

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6806]
In Windows 8 running IE11
Navigate to a video page eg: http://www.theguardian.com/film/video/2013/feb/15/side-by-side-video-review
Either video plays with no ads, or video attempts to play ad and freezes.

![screen shot 2014-10-28 at 15 24 38](https://cloud.githubusercontent.com/assets/7239344/4810979/43de3d0e-5eb7-11e4-8a80-86fee957e5d9.png)

**Comment by paperboyo** [comment]
Hi,

Not sure what would be the expected behaviour, but on Win 8.1 IE11 now there is no ad, no autoplay, and when clicked, the video plays without errors.

Regards
Mateusz

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
