### ISSUE TITLE
iphones, Android 4.4 - video playables on fronts open article rather than playing

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6813]
Phone running android 4.4 - either native browser or chrome:
when you navigate to a tag/non curated front that has a video on it - eg: /video or /film or a curated front such as /sport selecting play,  the content page containing the video is opened. Instead the playable should play on the front.

**Comment by ScottPainterGNM** [comment]
Fixed in linked PR, issue closed.
