### ISSUE TITLE
Safari - on smaller breakpoints line break on container title occurs in middle of word

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6842]
On content pages viewed with Sarafi browser at width 1200':
The "related content" container title is displayed as:
               related con-
               tent
with newline occurring in the middle of the word.

On other browsers - ie Chrome, the newline happens between words  - ie:
                related
                content
Which looks much better.

Can we please make safari do this also?

![screen shot 2014-10-29 at 13 05 34](https://cloud.githubusercontent.com/assets/7239344/4826089/5034f966-5f6c-11e4-9b99-de10b865e7be.png)

**Comment by ScottPainterGNM** [comment]
Appears to be resolved, issue closed
