### ISSUE TITLE
Safari & Firefox - Accessibility issue: seting a minimum font size >12 in browser preferences causes site to not fit the screen

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6850]
When font size for browsers is increased it breaks the display of the fronts and can make content inaccessible.
example:
There is a setting in the Safari Preferences -> Advanced tab called "Never use font sizes smaller than"
which sets a minimum font size for the browser.
If this is set to a high value - eg 24, stories in containers start to be cut off from view without even a scrollbar to find them.

![screen shot 2014-10-29 at 16 54 44](https://cloud.githubusercontent.com/assets/7239344/4830237/5c4af208-5f8c-11e4-9174-30f915b79d45.png)

On content pages the article is unaffected but related content containers are truncated:

![screen shot 2014-10-29 at 16 58 02](https://cloud.githubusercontent.com/assets/7239344/4830349/3cefbf32-5f8d-11e4-8997-d848bc01327b.png)

**Comment by michaelwmcnamara** [comment]
Came across this issue again in firefox.
- In preferences->content->advanced set minimum font size to 24
- Reload network front

Page should reformat to appropriate breakpoint, however it continues to show at largest breakpoint.
Consequently many stories are cut-off

![image](https://cloud.githubusercontent.com/assets/7239344/5835586/64e675fa-a162-11e4-8cc0-205634ed2214.png)

**Comment by ScottPainterGNM** [comment]
Closed off as comments in linked PR seem to address the specific bugs with firefox
