### ISSUE TITLE
Opera 25 -  1270' width - top ten shows small banner ad instead of MPU

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6875]
Opera 25 -  1270' width - popular container on network front shows small banner ad instead of MPU. Refreshing page does not change this.

![screen shot 2014-10-30 at 16 42 04](https://cloud.githubusercontent.com/assets/7239344/4847587/1c0a2a42-6054-11e4-8edc-4893396a3441.png)

**Comment by ScottPainterGNM** [comment]
This appears to be resolved now, MPU displaying at the correct site
