### ISSUE TITLE
Opera 25 - Mobile breakpoint on fronts - ads are left justified

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6877]
Opera 25 - Mobile breakpoint on fronts - ads are left justified

![screen shot 2014-10-30 at 17 03 43](https://cloud.githubusercontent.com/assets/7239344/4847997/f5294626-6056-11e4-9ad9-9714253bbf50.png)

**Comment by ScottPainterGNM** [comment]
Issue doesn't seem to reproduce now, issue closed.
