### ISSUE TITLE
Opera 25 - ads on tag pages showing as 2 split ads in mpu container

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6878]
Opera 25
Really screwy ad display on non-curated pages.
On http://www.theguardian.com/film in the "news" container I can see half of 2 ads (ie 2 ads split down the middle trying to fit into the MPU space).

![screen shot 2014-10-30 at 17 06 57](https://cloud.githubusercontent.com/assets/7239344/4848050/67a4f5d8-6057-11e4-8579-5f91dbcf0d5b.png)

Also seen on page2 of boxing tag page: http://www.theguardian.com/sport/boxing?page=2
![screen shot 2014-10-30 at 17 12 44](https://cloud.githubusercontent.com/assets/7239344/4848142/3202ebe6-6058-11e4-8060-de0010031891.png)

**Comment by ScottPainterGNM** [comment]
Cannot reproduce - MPU looks fine in both instances. Issue Closed
