### ISSUE TITLE
Time last updated and show/hide toggle clash on 890' screen width

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6927]
Looking at network front on code.
On screenwidths around 890' the last updated time jumps up from the left column to the righthand side of the top of the container.

The problem with this at the moment is that is overlaps the show hide toddle. A display issue we should tidy up. 

Screenshot:
![screen shot 2014-11-03 at 17 43 42](https://cloud.githubusercontent.com/assets/7239344/4887045/65f7c76a-6381-11e4-8edd-9a4f89267fa5.png)

**Comment by uplne** [comment]
I think this functionality is being deprecated.

**Comment by ScottPainterGNM** [comment]
Closed off as per comments above, this is no longer present on the containers
