### ISSUE TITLE
Managed macs - OSX Lion - Safari 6.0 & Firefox 26 - "The big picture" container on network front display broken

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6937]
Managed macs run - OSX Lion - Safari 6.0 & Firefox 26 
When the network front is viewed on these "The big picture" container display is broken - see screenshots:

![bpsaf6 2](https://cloud.githubusercontent.com/assets/7239344/4899528/f248eec4-641c-11e4-8a1c-635404a9106c.jpg)

![bpsaf6 0 5](https://cloud.githubusercontent.com/assets/7239344/4899530/f5bef3fa-641c-11e4-92bf-9ce4938c9468.png)

**Comment by ScottPainterGNM** [comment]
Fixed by linked issue number so closing off
