### ISSUE TITLE
IE9 - display cut off on smaller browser widths - display scrollbar if we don't support breakpoints

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6950]
On smaller browser widths, the display of the fronts is cut off.
Problem is that we are not adjusting for breakpoints but neither are we displaying a scrollbar for the user.

Solution 
1 - incorporate breakpoints - may not be flexible as flex containers not supported on this browser
or

2 - display a scrollbar for user on browsers where we are not supporting breakpoints

![screen shot 2014-11-04 at 15 34 44](https://cloud.githubusercontent.com/assets/7239344/4902310/8b311c36-6438-11e4-97b3-00c431d27cb9.png)

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
