### ISSUE TITLE
iPad - portrait view - cutout image and comment count display are overlapping on "Opinion" front

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6953]
When viewed on iPad or iPad mini  - cutout image and comment count display are overlapping on "Opinion" front.
(See Jessica Valentini story in screenshot)

Issue also occurs in Related content container in the article pages.

![img_0007](https://cloud.githubusercontent.com/assets/7239344/4903473/a76bc4b6-6440-11e4-9fee-33e75c25c74a.PNG)

**Comment by ScottPainterGNM** [comment]
I think we discussed this last week that there may not be a way to win with the cutouts, Justin is working on something under a newer PR so closing this issue off.
