### ISSUE TITLE
Mobile refresh button - needs positioning tweak

### ISSUE THREAD

**Issue by Vilderness** [guardian/frontend#6965]
The refresh button on mobile needs nudging down a little so it doesnt touch into the ad area above. Also the text inside the lozenge can bump up a couple of pixels. Aim for container title and button text to share the same baseline. Cheers!

Current look - iPhone 5 Chrome screen grab:

![img_6477](https://cloud.githubusercontent.com/assets/6472162/4911852/84497362-6494-11e4-930e-45b5758cf033.jpg)

The dream...

![img_6477_edit](https://cloud.githubusercontent.com/assets/6472162/4911854/89ebe3e0-6494-11e4-8246-104501e02e67.jpg)

**Comment by ScottPainterGNM** [comment]
I'm having trouble reproducing this issue, would you be able to advise whether this is still occurring please?

**Comment by crifmulholland** [comment]
The feature's dead so we can kill this.

**Comment by ScottPainterGNM** [comment]
Excellent! Closed
