### ISSUE TITLE
Upvote / pagination buttons are tough to press accurately on touch devices

### ISSUE THREAD

**Issue by mattandrews** [guardian/frontend#6982]
eg. these:

![screen shot 2014-11-05 at 15 14 49](https://cloud.githubusercontent.com/assets/394376/4919969/90254e08-64fe-11e4-8487-b98d6a86cd38.png)

I was browsing on my phone this morning and it took me several taps to actually click any of these. Might be worth upping the click area for touch devices?

**Comment by ScottPainterGNM** [comment]
@mattandrews Could you possibly confirm your device/OS so I can see if I could reproduce possibly?

**Comment by mattandrews** [comment]
This was on Firefox mobile for Nexus 5.

**Comment by ScottPainterGNM** [comment]
Thanks @mattandrews tried on a Samsung S3 and get similar issue #9003 with unresponsive selections to close Breaking News and the app drop down

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
