### ISSUE TITLE
Share counter overlaps container where podcast has sponsored badge & long left hand column

### ISSUE THREAD

**Issue by gidsg** [guardian/frontend#6989]
Where a podcast has a long left hand column caused by a long byline and sponsor badge the date stamp and share counter can overlap the popular container e.g. http://www.theguardian.com/books/audio/2014/nov/04/podcast-books-going-going-gone-al-kennedy
![screen shot 2014-11-05 at 16 42 09](https://cloud.githubusercontent.com/assets/1764158/4921508/cf484dd6-650a-11e4-8ea4-13d6ea2bbb58.png)
![screen shot 2014-11-05 at 16 49 55](https://cloud.githubusercontent.com/assets/1764158/4921572/2d39e9f4-650b-11e4-8142-ab6b1be32000.png)

**Comment by paperboyo** [comment]
Can’t reproduce on Win 8.1, FF, Chrome, IE11. Fixed? Safe to close?

**Comment by gidsg** [comment]
Not sure it this is fixed as the sponsor's badge no longer appears on the content. So will leave open for the time being.

**Comment by paperboyo** [comment]
Obviously! :facepalm:

**Comment by ScottPainterGNM** [comment]
To reduce down the issue list for the sustain team I will close off for now but will keep an eye out for a new sponsorship and see whether the same occurs.
