### ISSUE TITLE
[Luxembourg feature] Video player fail

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#6999]
Hello,

URL http://www.theguardian.com/business/2014/nov/05/-sp-luxembourg-tax-files-tax-avoidance-industrial-scale

Video player is unskinned (also, cropped on Firefox, so that the volume adjustments are unusable) and there is to much padding to it on latest Chrome, Firefox, Opera (padding: fine) an IE (no controls by default, so it's not clear it's a video at all) on Win 8.1.

![capture](https://cloud.githubusercontent.com/assets/6032869/4934606/116968ba-65a3-11e4-8746-a7cd79750601.JPG)

Also in IE, the How it works interactive is missing the text:

![capture2](https://cloud.githubusercontent.com/assets/6032869/4934630/4ddc71ca-65a3-11e4-8426-5d4dc3906dcd.JPG)

Regards
Mateusz

**Comment by johnduffell** [comment]
this is an interactive, so it's probably one for those guys to look at if it's a problem @mattosborn anyone down there able to pick this up before this dropps into a black hole?
