### ISSUE TITLE
Long tag name in left hand column clips at 1140 Breakpoint

### ISSUE THREAD

**Issue by gidsg** [guardian/frontend#7035]
Steps to reproduce
==============
Go to http://www.theguardian.com/football/2014/nov/07/bolton-wanderers-wigan-athletic-championship-match-report
Resize to 1140px width

Actual Results
===========
Tag name clips (tested in Chrome and Firefox)

![screen shot 2014-11-10 at 09 58 14](https://cloud.githubusercontent.com/assets/1764158/4974054/77f1b442-68bf-11e4-9aa4-9bf9e73ef47e.png)

Expected Results
=============
Tag name doesn't clip

**Comment by paperboyo** [comment]
Can’t reproduce on Win 8.1, FF, Chrome, IE11. Fixed? Safe to close?

**Comment by gidsg** [comment]
Thanks for triaging @paperboyo looks like this is fixed.
