### ISSUE TITLE
Vertical divider rule between shares / comments colour wrong 

### ISSUE THREAD

**Issue by Pearson82** [guardian/frontend#7067]
Border left on comment count should be #484848.

Currently #f1f1f1. Can we change back.

![screen shot 2014-11-11 at 17 10 58](https://cloud.githubusercontent.com/assets/3416696/4997336/c23ed76c-69c5-11e4-9531-f8170f3f141d.png)

**Comment by ScottPainterGNM** [comment]
@OliverJAsh I know that you were looking at comments yesterday, any chance you could check this issue out and see whether it still needs work?

**Comment by Pearson82** [comment]
This was resolved some time ago. Thanks for picking it up though. @ScottPainterGNM @OliverJAsh
