### ISSUE TITLE
Commercial CAPI component shows duplicated time stamp icon and date stamp overlaps headline

### ISSUE THREAD

**Issue by gidsg** [guardian/frontend#7073]
Steps to reproduce
===============
Go to: http://www.theguardian.com/lifeandstyle/2012/feb/01/top-five-regrets-of-the-dying?view=mobile
Scroll to bottom of page

Actual Results
==============
Commercial CAPI component has duplicated time stamp icon and timestamp overlaps headlines that go on to two lines.
![screen shot 2014-11-12 at 09 56 55](https://cloud.githubusercontent.com/assets/1764158/5008246/bfc010fe-6a52-11e4-9e85-97aaa0f2c9e6.png)

Expected Results
==============
Headlines shouldn't overlap timestamp
Only one timestamp icon

**Comment by ScottPainterGNM** [comment]
Haven't been able to reproduced this issue so closed off unless it reappears.
