### ISSUE TITLE
Chrome in Windows 8.1 - Fonts not loading

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7084]
When using Chrome V39 (latest chrome) in Windows 8.1, fronts appear to be using Georgia font. Also colours are not correct.
I have confirmed Flash player is installed. Not sure what's causing this.
... Weirdly IE11 is displaying correctly (must be the first ever case of IE doing a better job than Chrome!)

![screen shot 2014-11-12 at 15 34 57](https://cloud.githubusercontent.com/assets/7239344/5012892/86dcd586-6a81-11e4-9fd0-c8fe9a8504e4.png)

**Comment by paperboyo** [comment]
Hello,

Original issue non-existent. Safe to close. Some comments worthwhile, though. Thanks for all participating!

Of course the last https://github.com/guardian/frontend/issues/7084#issuecomment-63976863 still very much an issue, even though closed multiple times: https://github.com/guardian/frontend/issues/5372, https://github.com/guardian/frontend/issues/5201. This may seem closed only to the French and the Swiss when they are served Latin 1 ;-)

I believe there is a way to fix it while (substantially?) improving webfonts initial loading times...

Regards
Mateusz

**Comment by ScottPainterGNM** [comment]
As comment above, closing off this particular issue to remove from outstanding work.
