### ISSUE TITLE
IE9 - IE8: width 880 - Tag pages - story section does not resize to fit window

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7112]
On IE8 or IE9 resize the window to roughly 880' then load a tag page (eg /progile/charliebrooker).
Result:

The containers on the page do not resize to fit the available window space.

![screen shot 2014-11-13 at 18 06 11](https://cloud.githubusercontent.com/assets/7239344/5045551/9d547690-6bf6-11e4-9c7a-5fba4a576e6d.png)

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
