### ISSUE TITLE
iphone - Selecting  "Less" button on container also selects the ad beneath it

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7126]
On an iphone, navigate to a container with an MPU or banner ad immediately below it.
Press more to expand the container
Scroll to the bottom of the container and select "Less"

Result: 
The less button shows as selected.
Despite not clicking on it, a new tab opens and takes over and you are taken away from the front to the ad-site (as though you had selected the ad)
When you make your way back to the tab containing our front, the container has been reverted to normal size.

Issue is that selecting the less button seems to also select the clickable area of the ads.

**Comment by ScottPainterGNM** [comment]
This appears to be resolved, issue closed
