### ISSUE TITLE
When you click less on an expanded container, you lose your place!

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7128]
Any browser or device:
Expand a large container.
Scroll down to the "Less" button.
Select it.

Result:
The container reverts to normal size, but your view does not come with it. You seem to stay at the same position on the front while it shrinks around you. As a result, you wind up much further down the page than you were possible missing one or two containers.

This effect is very disorienting and quite frustrating if you are trying to get a feel for what stories are on the front.

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
