### ISSUE TITLE
Cannot select text on iOS

### ISSUE THREAD

**Issue by alastairjardine** [guardian/frontend#7136]
## Steps to reproduce
On iOS, I am unable to select text using any method. It means I cannot copy/paste snippet to email or tweet.

## Environment

Device: iPhone, iPad
Browser: iOS 8
OS:  iOS 8
URL: any guardian URL

**Comment by ScottPainterGNM** [comment]
This appears to be resolved from testing today, closing issue unless i can be reproduced.
