### ISSUE TITLE
Firefox - display issues at tablet breakpoints

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7147]
Problem occurring with display of fronts at tablet breakpoints.
eg: http://www.theguardian.com/cities/series/resilient-cities

"On this site" (fixed-large-slow-XIV) container shows excessive whitespace and first story is pushed off the screen.

![screen shot 2014-11-17 at 17 53 38](https://cloud.githubusercontent.com/assets/7239344/5074554/6832f5ce-6e83-11e4-8bf5-9f8bd0ea2109.png)

**Comment by uplne** [comment]
This should be fixed. If you can double check it would be awesome. Thanks.
