### ISSUE TITLE
When a user is the first to post a comment - clicking "post your comments" does not display their handiwork

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7164]
Seen this a few times, although it is tricky to get a reliable reproduction.
If a user is the first to enter a comment on a piece of content, when they press "post your comment", nothing is displayed.
The comment only displays after you press refresh.

Screenshots:
1) Just after I post my comment:

![screen shot 2014-11-18 at 17 03 35](https://cloud.githubusercontent.com/assets/7239344/5092264/af9f5e9e-6f45-11e4-9796-2f310b23888e.png)

2) After I refresh the page:

![screen shot 2014-11-18 at 17 04 00](https://cloud.githubusercontent.com/assets/7239344/5092278/c0c7f0e6-6f45-11e4-9385-cd373df82aa6.png)

**Comment by johnduffell** [comment]
we get a lot of complaints about this, and double posts also, so we should fix this

**Comment by johnduffell** [comment]
this was introduced in [this commit](https://github.com/guardian/frontend/commit/bd26412c5ff0d4e6f4e75e1c4207c2f1ec11d308#diff-4e460503ca7bf2c20da06a73805589e4L48)
