### ISSUE TITLE
Liveblog - expanded liveblog has bottomless scrolling after update

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7182]
If a user has selected the '+' expand button at the bottom of the liveblog content, to see all liveblog updates and if a susequent update occurs, the page suddenly scrolls for ever with infinite whitespace at the bottom.

1) Open liveblog
2) Scroll to the bottom of content and press '+' to show all content
3) wait for an update to the liveblog
4) attempt to scroll to the bottom of the page

Result:
you will scroll past content comments and recommendations and keep on scrolling into the pure white light. forever.

![screen shot 2014-11-19 at 16 49 00](https://cloud.githubusercontent.com/assets/7239344/5109934/a050dd06-700c-11e4-8fea-6c47699efe51.png)

**Comment by paperboyo** [comment]
Can’t reproduce on Windows 10 TP, FF, Chrome, IE. Safe to close?

Of course, just on a related note, when an update to the Liveblog happens, the page suddenly scrolls and the reader looses the context, feeling sad and lonely, like a panda (:panda_face:). Instead, the page should stay put and display a notification specifying a number of unseen updates which, when clicked, would take the reader to the _first unread_ of new updates, irrespective of the initial order set (newest, oldest).
