### ISSUE TITLE
Profile pages: suggested links

### ISSUE THREAD

**Issue by alastairjardine** [guardian/frontend#7190]
Some granularity in the linking to comments on the profile page would be helpful. Currently, they all link to the same place, which makes navigation slightly trickier. See attached screenshot for suggestions. 
![screen shot 2014-11-20 at 10 09 35](https://cloud.githubusercontent.com/assets/4292469/5122919/0c8b832c-709e-11e4-8d94-d1ef74bb6e33.png)

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
