### ISSUE TITLE
User not able to report comments using iPad2

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7195]
Report comment box is not working for iPad2 running iOS7. Specifically the "Reason for reporting" 
drop-down does not open. Also noticed that sometimes the text-box is not responsive, however this last is only happening sporadically.

User issues reported that relate to this: 
"
We received a complaint about a problem with reporting comments on an iPad. So I tried to replicate it on my iPad 2. I found it difficult to complete the report box on a NextGen article. The keyboard becomes slow to respond. I'm on iOS 8.0. The report box is more responsive in Chrome.
...
The report box does come up, but the rest of the box is nonfunctional when i'm on the Ipad.   Any ideas?
"

**Comment by ScottPainterGNM** [comment]
Attempting to report comments on mobile apps teams device GNM60237 replicate issues, report button is selectable but the form is unresponsive and can cause safari to crash

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
