### ISSUE TITLE
Footer links 404 on https://profile.theguardian.com pages

### ISSUE THREAD

**Issue by gidsg** [guardian/frontend#7200]
Steps to reproduce
==============
Go to https://profile.theguardian.com/user/id/1186733
Click on footer link e.g. Info

Actual Result
==========
Relative links 404 (e.g. info and resources)

Expected Results
=============
Use absolute paths in the footer so they work

**Comment by ScottPainterGNM** [comment]
I cannot reproduce this issue with the footer links so think it may have been resolved, did you want to just double check and confirm before I close off?

**Comment by gidsg** [comment]
Yes, this is resolved.

**Comment by ScottPainterGNM** [comment]
Cheer Gideon, much appreciated

On 27 April 2015 at 11:32, Gideon Goldberg <notifications@github.com> wrote:

> Closed #7200 <https://github.com/guardian/frontend/issues/7200>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/7200#event-290734227>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396
