### ISSUE TITLE
headline running into coment count

### ISSUE THREAD

**Issue by Vilderness** [guardian/frontend#7214]
In the 'more galleries' container at the bottom of this page, 2 story headlines are running into comment count meta. Viewed on mac laptop / chrome 35

http://www.theguardian.com/environment/gallery/2014/sep/11/lost-frogs-finding-the-worlds-rarest-amphibians-in-pictures

![screen shot 2014-11-20 at 18 28 21](https://cloud.githubusercontent.com/assets/6472162/5130559/84a766d8-70e3-11e4-9aaa-8f60932d8d37.png)

**Comment by paperboyo** [comment]
Can’t reproduce on Windows 10 TP, FF, Chrome, IE. Safe to close?
