### ISSUE TITLE
Icon clipping

### ISSUE THREAD

**Issue by sndrs** [guardian/frontend#7263]
In IE (in particular) icons on the fronts are clipping, despite having `background-size: cover`

![screen shot 2014-11-24 at 17 44 37](https://cloud.githubusercontent.com/assets/867233/5169681/5f5a43c0-7401-11e4-9e0d-a0575c98f2ef.png)

appears to be the way IE manages the sizing

**Comment by paulrobertlloyd** [comment]
If @sndrs is inlining SVGs (which we can change the colour of using CSS) this might no longer be a problem? (Can we inline SVGs with content that’s coming from CAPI?)

**Comment by ScottPainterGNM** [comment]
Clipping issue originally raised seems to have been resolved by the bleeding of icons in zoom is reproducible.

**Comment by johnduffell** [comment]
looks ok in latest chrome, anyway closing this as it hasn't been fixed so far and probably won't be fixed in the near future

**Comment by NataliaLKB** [comment]
Opening again, and going to fix today

**Comment by NataliaLKB** [comment]
This should now be fixed!
