### ISSUE TITLE
Random crashes on Firefox Mobile

### ISSUE THREAD

**Issue by mattandrews** [guardian/frontend#7275]
This is kind of a placeholder until I get time to isolate the cause, but would be interested if anyone else has any theories/similar experiences.

I use Firefox Mobile on my phone (Nexus 5, Android Lollipop). NGW crashes the browser almost every time I use it. I haven't seen this happen on any other site, FWIW.

The pattern is roughly this: I browse the site, open a few articles in tabs, and start reading one. I can't be certain but it seems to happen when I scroll past an in-article ad. Often when I'm reading I have a thumb constantly touching the screen and slowly scroll the article as I'm reading – after doing this past an ad I tend to get the crash.

Does this sound like a known issue or has anyone else seen it? When I get a chance I'd like to try to make it more reproduceable and maybe debug it a bit, although unsure how...

**Comment by ScottPainterGNM** [comment]
Is this issue still occurring?? just tried testing this for a while on lollipop on a Galaxy S6 and couldn't replicate but wondered whether you still get these crashes?

**Comment by mattandrews** [comment]
Yeah, haven't seen it in a while – quite possible all the work to stop crashes on older iPads etc might've sorted this :)

**Comment by ScottPainterGNM** [comment]
Awesome, thanks for letting me know!
