### ISSUE TITLE
iPad1 - attempting to load network front crashes browser

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7316]
Reproduced on iPad1 - article pages load ok, but show same display issues as witnessed in IE8.
Network front loads initial stories and containers but browser crashes before page fully built. 
xcode logs follow:

"
Nov 26 15:28:07 DHurleys-iPad kernel[0] <Debug>: launchd[170] Builtin profile: MobileSafari (sandbox)

Nov 26 15:28:24 DHurleys-iPad SpringBoard[51] <Warning>: Received memory warning.

Nov 26 15:28:24 DHurleys-iPad MobileMail[156] <Warning>: Received memory warning.

Nov 26 15:28:25 DHurleys-iPad UserEventAgent[12] <Notice>: jetsam: kernel termination snapshot being created

Nov 26 15:28:25 DHurleys-iPad com.apple.launchd[1] (UIKitApplication:com.apple.mobilemail[0x5413][156]) <Notice>: (UIKitApplication:com.apple.mobilemail[0x5413]) Exited: Killed: 9

Nov 26 15:28:25 DHurleys-iPad com.apple.launchd[1] (UIKitApplication:com.apple.Preferences[0x1556][157]) <Notice>: (UIKitApplication:com.apple.Preferences[0x1556]) Exited: Killed: 9

Nov 26 15:28:25 DHurleys-iPad com.apple.launchd[1] (UIKitApplication:com.apple.mobilesafari[0x7d5e][170]) <Notice>: (UIKitApplication:com.apple.mobilesafari[0x7d5e]) Exited: Killed: 9

Nov 26 15:28:25 DHurleys-iPad SpringBoard[51] <Warning>: Application 'Safari' exited abnormally with signal 9: Killed: 9

Nov 26 15:28:26 DHurleys-iPad SpringBoard[51] <Warning>: Application 'Settings' exited abnormally with signal 9: Killed: 9

Nov 26 15:28:26 DHurleys-iPad SpringBoard[51] <Warning>: Application 'Mail' exited abnormally with signal 9: Killed: 9

Nov 26 15:28:26 DHurleys-iPad kernel[0] <Debug>: launchd[175] Builtin profile: MobileMail (sandbox)

Nov 26 15:28:26 DHurleys-iPad DTPower[159] <Warning>: Task info failed for task com.apple.mobilesafari

Nov 26 15:28:27 DHurleys-iPad ReportCrash[174] <Notice>: Saved crashreport to /Library/Logs/CrashReporter/LowMemory-2014-11-26-152827.plist using uid: 0 gid: 0, synthetic_euid: 0 egid: 0

Nov 26 15:28:33 DHurleys-iPad MobileMail[175] <Warning>: ERROR: MFMessageErrorDomain/Authentication Failed - Check the account settings for the outgoing server “-s-m-t-p-.-g-m-a-i-l-.-c-o-m”-.

Nov 26 15:28:34 DHurleys-iPad MobileMail[175] <Warning>: ERROR: MFMessageErrorDomain/Authentication Failed - Check the account settings for the outgoing server “-s-m-t-p-.-g-m-a-i-l-.-c-o-m”-.

Nov 26 15:28:35 DHurleys-iPad MobileMail[175] <Warning>: ERROR: MFMessageErrorDomain/Authentication Failed - Check the account settings for the outgoing server “-s-m-t-p-.-g-m-a-i-l-.-c-o-m”-.
"

**Comment by ScottPainterGNM** [comment]
Upon retesting the Ipad1 can load the network front after fixes applied (though has visual issues), closing issue.

**Comment by ng850** [comment]
Hi,
      this has certainly fixed the 'fail on load' issue with Safari and 
Chrome. Thanks!

Safari lasts longer than Chrome before it bales on 'Low Memory' issues, 
but that's to be expected.

Regs

ng
