### ISSUE TITLE
Guardian video pages opened in facebook app display poorly and don't play

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7319]
Open a guardian video page from the facebook app (befriend "MichaelMcNamaraapp" - my test user - if you want some sample data.
I used this video: http://www.theguardian.com/world/video/2014/nov/26/siberians-push-own-plane-video
The video is opened in facebook ap's own browser window.
We display a very poorly formatted guardian app ad (see screenshot below)

Despite repeated presses of the play button, video does not play.

Screenshot of app ad: 
![screenshot_2014-11-26-16-51-18](https://cloud.githubusercontent.com/assets/7239344/5205239/997c6dc0-758d-11e4-8676-033c548d03f8.png)

Screenshot of video not playing:
![screenshot_2014-11-26-16-52-44](https://cloud.githubusercontent.com/assets/7239344/5205249/abe21f8c-758d-11e4-9164-4fb30635e866.png)

**Comment by ScottPainterGNM** [comment]
Closed off as non frontend bug, did you want to check with T about this @michaelwmcnamara ?
