### ISSUE TITLE
IE9, IE8 - Shark myths debunked content page does not display any content beyond the standfirst

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7321]
Page: http://www.theguardian.com/environment/ng-interactive/2014/nov/26/-sp-great-white-sharks-10-myths-debunked

In IE9 & IE8, apart from the headline and standfirst, none of the content for this page is displayed:

![screen shot 2014-11-26 at 17 54 05](https://cloud.githubusercontent.com/assets/7239344/5206088/63f6cc60-7595-11e4-9eea-6b4debebedf4.png)

**Comment by johnduffell** [comment]
it's an interactive so it's probably got ie issues
