### ISSUE TITLE
Sponsor badge has no alt text

### ISSUE THREAD

**Issue by gidsg** [guardian/frontend#7325]
Steps to reproduce
================
Go to: http://www.theguardian.com/cities
Inspect Element on sponsor badge

Actual Result
===========
Badge image has no alt text
![screen shot 2014-11-27 at 09 45 51](https://cloud.githubusercontent.com/assets/1764158/5214936/57b71b82-761a-11e4-95c4-5531021754f4.png)

Expected Result
=============
Sponsor badge has empty alt text: `alt=""` or descriptive alt text

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
