### ISSUE TITLE
Australian edition nav section - all fronts - inconsistency between edition selector and nav names in capitalising country name

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7328]
Currently we show the edition selector setting as capitalised "Australia edition"
The rest of the nav shows as not capitalised - eg "australia" 

These need to be made consistent.

Personally I think it needs to be made capital 'A' everywhere for 3 reasons:
1)  Its basic primary school english that country names are capitalised (the style guide males no mention of country names but every time the body text of the style guide mentions a country, its name is capitalised)

2) We capitalise other country names in the paper - eg: container name for France: http://www.theguardian.com/world/france

3) We've just gone to the effort of making an Australian edition. It seems crazy to then go and offend them by not capitalising their countries name (its also exactly the kind of rhetorical ammunition that the Herald Sun and the Liberal Party will love any time they want to marginalise any of our content and cast us as "foreign interlopers" (trust me I grew up there).

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
