### ISSUE TITLE
Headline text jittering

### ISSUE THREAD

**Issue by daanlouter** [guardian/frontend#7331]
Just noticed that some text in article page are jittering in Chrome 40.0.2214.10 beta (64-bit) (mac).

For instance: .content__section-label__link in http://www.theguardian.com/lifeandstyle/2013/dec/06/why-wont-buy-barbie-daughter-christmas

It stops jittering when I disable webkit-font-smoothing: antialiased; in devtools.

Maybe connected to this, I noticed that the page is constantly repainting (see video: http://cl.ly/0r1b1e1E1C2N)

**Comment by johnduffell** [comment]
was probably a dodgy ad, it doesn't happen with latest chrome now
