### ISSUE TITLE
Video's shared in facebook app are not playing when user selects item

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7335]
When a user opens a guardian video in the facebook app, the video page loads in a facebook browser that is native to the app. Our videos are frequently not playing in this browser.

![image](https://cloud.githubusercontent.com/assets/7239344/5220030/5724e4b4-7657-11e4-90a2-25c383c5d270.png)

**Comment by ScottPainterGNM** [comment]
Tried to reproduce across a handful of andriod devices and seems fine, closed off unless it reaoccurs.
