### ISSUE TITLE
Specific video wont play on Chrome

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7339]
This one video http://www.theguardian.com/world/video/2014/nov/27/mps-brawl-parliament-world-video won't play on Chrome. I'm running version  39.0.2171.
It works fine on other browsers, but on chrome the video player shows message "The video could not be loaded because the server or network failed or because the video format is not supported"
Console errors show 400 - bad request 

Other videos play without any problems.

screenshot:

![screen shot 2014-11-27 at 17 53 28](https://cloud.githubusercontent.com/assets/7239344/5220531/6f2f340e-765e-11e4-8360-abe5e74b97a0.png)

Full console errors:
mps-brawl-parliament-world-video:1 GET http://multimedia.guardianapis.com/interactivevideos/video.php?octopusid=9806167%20&format=video/mp4 400 (Bad Request)
mps-brawl-parliament-world-video:1 GET http://multimedia.guardianapis.com/interactivevideos/video.php?octopusid=9806167%20&format=video/mp4 400 (Bad Request)
img?mt_aid=4090724246609340944&mt_id=1054323&mt_adid=115349&mt_sid=511506&mt_exid=14&mt_uuid=51db53…:129 Resource interpreted as Script but transferred with MIME type text/html: "https://b3-uk.mookie1.com/2/Xaxis/Xaxis_ePrivacy_secure/479730084@x50?_RM_HTML_AAC12Height_=90&_RM_HTML_AAC12Width_=728".
mps-brawl-parliament-world-video:1 Resource interpreted as Image but transferred with MIME type text/html: "http://pubads.g.doubleclick.net/pagead/adview?ai=BHpEpEGV3VO2iNKf37AaV74CwD…C92aWRlby9uZ_gChNIekAPQBZgD0AWoAwHgBAGQBgGgBiM&sigh=CWKOcd4AMGM&cid=5GhFHw".
video.js:26 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The video could not be loaded, either because the server or network failed or because the format is not supported. t.D {code: 4, message: "The video could not be loaded, either because the …rk failed or because the format is not supported.", status: null, MEDIA_ERR_CUSTOM: 0, MEDIA_ERR_ABORTED: 1…}
img?mt_aid=4090724246609340944&mt_id=1054323&mt_adid=115349&mt_sid=511506&mt_exid=14&mt_uuid=51db53…:132 Resource interpreted as Image but transferred with MIME type text/html: "http://googleads4.g.doubleclick.net/pcs/view?xai=AKAOjsvhKwp_KTb9AxrUNabo74…0A37J-cEgTs0zlNhMplwWSwpqJA5Lz0IaugmUgA&sig=Cg0ArKJSzLGcCm_XKuf8EAE&adurl=".

**Comment by ScottPainterGNM** [comment]
I'm going to close this issue off as works fine across newer versions of Chrome and other browsers.
