### ISSUE TITLE
margin issues in highlights container - OZ network front

### ISSUE THREAD

**Issue by Vilderness** [guardian/frontend#7383]
The bottom slice of highlights container, the left side column, the four stories have a margin popping up below the image - as if space is increased by the story on the right, but there's not enough content to push it out like it is.

http://m.code.dev-theguardian.com/au

![screen shot 2014-12-02 at 12 10 24](https://cloud.githubusercontent.com/assets/6472162/5262344/a98bbf48-7a1c-11e4-8dac-d36b0c1c6387.png)

**Comment by robertberry** [comment]
@ScottPainterGNM I'm not sure this is still happening. Where did you reproduce it?

**Comment by SevereOverfl0w** [comment]
Looks like the issue has gone away with a new design.

**Comment by robertberry** [comment]
Cheers! :+1:
