### ISSUE TITLE
call to action button broken

### ISSUE THREAD

**Issue by Vilderness** [guardian/frontend#7405]
Email promo component - the arrow has fallen from the 'see your email preferneces' button - desktop and wide.

![screen shot 2014-12-03 at 13 36 05](https://cloud.githubusercontent.com/assets/6472162/5281112/72d2649a-7af1-11e4-9fdf-2d09602b2fa3.png)
![screen shot 2014-12-03 at 13 32 56](https://cloud.githubusercontent.com/assets/6472162/5281113/72d4f2f0-7af1-11e4-8d56-460aa4ff26d6.png)

http://www.theguardian.com/music/classicalmusicandopera

**Comment by ScottPainterGNM** [comment]
Re-produced in the sense that the arrow is now totally missing from all desktop browsers I have tested at all resolutions (until it goes into mobile breakpoints where the see email preferences button disappears entirely).

**Comment by robertberry** [comment]
Looks like this is now fixed.
