### ISSUE TITLE
Subscriptions component - broken button

### ISSUE THREAD

**Issue by Vilderness** [guardian/frontend#7431]
The guardian subscriptions component at the bottom of this page - button is broke at all brekpoints (arrow is dropped down).

http://www.theguardian.com/us-news/2014/dec/03/justice-department-eric-holder-eric-garner-investigation

![screen shot 2014-12-04 at 16 04 57](https://cloud.githubusercontent.com/assets/6472162/5301288/75e17a84-7bcf-11e4-8afb-74c5b3cf26d8.png)

**Comment by ScottPainterGNM** [comment]
Cannot reproduce on same page but on an AU subscription banner the arrow is totally missing:

![screen shot 2015-04-28 at 10 20 33](https://cloud.githubusercontent.com/assets/11922253/7366423/0b1b9d5a-ed90-11e4-8215-3d02dcb003e7.png)

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
