### ISSUE TITLE
Location preference should be honoured when displaying Most Popular

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7472]
Request originating from Wolfgang. Remember to run by him before closure.
-If I am in the UK, the US or Australia and open any of those three regional editions, the most-popular container in fronts or articles will always show what is most popular of that specific edition I am currently looking at. 
-When I am outside of the UK, US or AU and am looking at the US edition or AU editon, I will be shown most-popular containers that show me what is most popular in those two countries. Again: Since I have expressed a distinct interest in the US or AU by switching into these editions, than my interested should be respected. 
-But: If I am in one of the currently 195+ countries in the world where the UK edition is my default and if am not choosing to see another edition, then my most-popular-container should show me what is currently most popular amongst all readers of my own region.

**Comment by ScottPainterGNM** [comment]
This was mentioned today re: sharing so have added a flag to keep on the issues log for now.

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
