### ISSUE TITLE
Section indexes cut off at right when not maximized

### ISSUE THREAD

**Issue by Smylers** [guardian/frontend#7510]
Some (but not all) section index pages are displaying cut off at the right, midway through headlines, in non-maximized windows. This is in Firefox desktop (on Ubuntu Linux, if it matters). Here's [a cricket subsection](http://www.theguardian.com/sport/england-cricket-team+tone/minutebyminute) at 882 px wide:

![guardian_882_px_index_cut_off](https://cloud.githubusercontent.com/assets/598534/5392431/eb5ae784-811d-11e4-82fb-445348b319df.png)

And showing the next breakpoint up, here's [family](http://www.theguardian.com/lifeandstyle/family) at 1115 px:

![guardian_1115_px_index_cut_off](https://cloud.githubusercontent.com/assets/598534/5392433/f0518bc6-811d-11e4-9cb3-6537a3357130.png)

Note there isn't a horizontal scroll bar for getting to the content cut off at the right.

1140 px or wider is fine (looks generally like the bottom image, but is actually wide enough to fit it all in), and 739 px or narrower is fine (everything in a single column).

**Comment by ScottPainterGNM** [comment]
Issued appears to be resolved in Firefox, closed off.
