### ISSUE TITLE
Image captions on live blogs looking broken

### ISSUE THREAD

**Issue by Pearson82** [guardian/frontend#7540]
Looks like we have lost the padding below margins on images on liveblogs, at mobile breakpoint.

Can we put them back? See screen shot.

![screen shot 2014-12-12 at 11 39 09](https://cloud.githubusercontent.com/assets/3416696/5411018/a286718c-81f3-11e4-87b4-20cbb52bdbc4.png)

**Comment by paperboyo** [comment]
Seems fixed. Safe to close?
