### ISSUE TITLE
Timestamps cut off by bylines

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#7552]
Hello,

`fc-item__timestamp` partially hidden under the byline picture like so:

![z index timestamp meta](https://cloud.githubusercontent.com/assets/6032869/5427442/57f9836e-8394-11e4-9f34-44ec201acec4.GIF)

URL: http://www.theguardian.com/commentisfree/2014/dec/14/corporate-tax-too-low-britain-companies-the-state-poverty-benefits

Regards
Mateusz

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
