### ISSUE TITLE
Show a message to XP users to enable ClearType?

### ISSUE THREAD

**Issue by mattandrews** [guardian/frontend#7630]
I've seen a fair amount of users (of older OSes/browsers) complaining the font is unreadable. I dug into [one case recently](http://discussion.theguardian.com/comment-permalink/45289337) and enabling ClearType (on Windows XP) fixed the issue.

It looks like [it's possible to detect font-smoothing support](http://www.useragentman.com/blog/2009/11/29/how-to-detect-font-smoothing-using-javascript/) (which is effectively ClearType enabled on WinXP) – would it be worth doing this and showing a message explaining how to enable it for these users? At the moment it's quite a poor experience for them and makes the site effectively unreadable:

![graun_beta_sample_zpsafff80f3](https://cloud.githubusercontent.com/assets/394376/5568567/eea98b56-8f56-11e4-9da4-2a372043455a.jpg)

In the last 30 days, traffic from XP was 2,649,303 	unique visitors (2.6%) – this is a lot of people experiencing a pretty ugly type appearance. Can we at least acknowledge it for them?

cc @phamann / @crifmulholland

**Comment by sammorrisdesign** [comment]
I imagine a large percentage of that 2.6% are on XP at work and probably can't alter their font rendering settings. So as much as it pains me to say it, couldn't we just use Georgia or something else web safe for body/vital text on XP?

**Comment by sndrs** [comment]
i'd be more inclined to switch the body font (and any others that cause
problems) to something native if we detect font smoothing disabled on XP?

we shouldn't have to ask users to change a setting on their computer for
our design to work, the design (or its build) ought to be the one
accommodating users?

On Mon Jan 05 2015 at 11:02:00 AM Sam Morris <notifications@github.com>
wrote:

> I imagine a large percentage of that 2.6% are on XP at work and probably
> can't alter their font rendering settings. So as much as it pains me to say
> it, couldn't we just use Georgia or something else web safe for body/vital
> text on XP?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/7630#issuecomment-68694178>.
>
> ------------------------------
> Visit theguardian.com. On your mobile and tablet, download the Guardian
> iPhone and Android apps theguardian.com/guardianapp and our tablet
> editions theguardian.com/editions.  Save up to 57% by subscribing to the
> Guardian and Observer - choose the papers you want and get full digital
> access.  Visit subscribe.theguardian.com
>
> This e-mail and all attachments are confidential and may also be
> privileged. If you are not the named recipient, please notify the sender
> and delete the e-mail and all attachments immediately. Do not disclose the
> contents to another person. You may not use the information for any
> purpose, or store, or copy, it in any way.  Guardian News & Media Limited
> is not liable for any computer viruses or other material transmitted with
> or as part of this e-mail. You should employ virus checking software.
>
> Guardian News & Media Limited is a member of Guardian Media Group plc. Registered
> Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered
> in England Number 908396
>
>
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by sndrs** [comment]
sorry sam - had reply open while yours came in. yes, i agree

On Mon Jan 05 2015 at 11:09:29 AM Alex Sanders <alex.sanders@guardian.co.uk>
wrote:

> i'd be more inclined to switch the body font (and any others that cause
> problems) to something native if we detect font smoothing disabled on XP?
>
> we shouldn't have to ask users to change a setting on their computer for
> our design to work, the design (or its build) ought to be the one
> accommodating users?
>
> On Mon Jan 05 2015 at 11:02:00 AM Sam Morris <notifications@github.com>
> wrote:
>
>> I imagine a large percentage of that 2.6% are on XP at work and probably
>> can't alter their font rendering settings. So as much as it pains me to say
>> it, couldn't we just use Georgia or something else web safe for body/vital
>> text on XP?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/guardian/frontend/issues/7630#issuecomment-68694178>.
>>
>> ------------------------------
>> Visit theguardian.com. On your mobile and tablet, download the Guardian
>> iPhone and Android apps theguardian.com/guardianapp and our tablet
>> editions theguardian.com/editions.  Save up to 57% by subscribing to the
>> Guardian and Observer - choose the papers you want and get full digital
>> access.  Visit subscribe.theguardian.com
>>
>> This e-mail and all attachments are confidential and may also be
>> privileged. If you are not the named recipient, please notify the sender
>> and delete the e-mail and all attachments immediately. Do not disclose the
>> contents to another person. You may not use the information for any
>> purpose, or store, or copy, it in any way.  Guardian News & Media Limited
>> is not liable for any computer viruses or other material transmitted with
>> or as part of this e-mail. You should employ virus checking software.
>>
>> Guardian News & Media Limited is a member of Guardian Media Group plc. Registered
>> Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered
>> in England Number 908396
>>
>>
>>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by Vilderness** [comment]
Massively agree with this...

"we shouldn't have to ask users to change a setting on their computer for
our design to work, the design (or its build) ought to be the one
accommodating users? "



On 5 January 2015 at 11:10, Alex Sanders <notifications@github.com> wrote:

> sorry sam - had reply open while yours came in. yes, i agree
>
> On Mon Jan 05 2015 at 11:09:29 AM Alex Sanders <
> alex.sanders@guardian.co.uk>
> wrote:
>
> > i'd be more inclined to switch the body font (and any others that cause
> > problems) to something native if we detect font smoothing disabled on
> XP?
> >
> > we shouldn't have to ask users to change a setting on their computer for
> > our design to work, the design (or its build) ought to be the one
> > accommodating users?
> >
> > On Mon Jan 05 2015 at 11:02:00 AM Sam Morris <notifications@github.com>
> > wrote:
> >
> >> I imagine a large percentage of that 2.6% are on XP at work and
> probably
> >> can't alter their font rendering settings. So as much as it pains me to
> say
> >> it, couldn't we just use Georgia or something else web safe for
> body/vital
> >> text on XP?
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/guardian/frontend/issues/7630#issuecomment-68694178>.
>
> >>
> >> ------------------------------
> >> Visit theguardian.com. On your mobile and tablet, download the
> Guardian
> >> iPhone and Android apps theguardian.com/guardianapp and our tablet
> >> editions theguardian.com/editions. Save up to 57% by subscribing to
> the
> >> Guardian and Observer - choose the papers you want and get full digital
> >> access. Visit subscribe.theguardian.com
> >>
> >> This e-mail and all attachments are confidential and may also be
> >> privileged. If you are not the named recipient, please notify the
> sender
> >> and delete the e-mail and all attachments immediately. Do not disclose
> the
> >> contents to another person. You may not use the information for any
> >> purpose, or store, or copy, it in any way. Guardian News & Media
> Limited
> >> is not liable for any computer viruses or other material transmitted
> with
> >> or as part of this e-mail. You should employ virus checking software.
> >>
> >> Guardian News & Media Limited is a member of Guardian Media Group plc.
> Registered
> >> Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.
> Registered
> >> in England Number 908396
> >>
> >>
> >>
>
> --
>
> ------------------------------
> Visit theguardian.com. On your mobile and tablet, download the Guardian
> iPhone and Android apps theguardian.com/guardianapp and our tablet
> editions
> theguardian.com/editions. Save up to 57% by subscribing to the Guardian
> and Observer - choose the papers you want and get full digital access.
> Visit subscribe.theguardian.com
>
> This e-mail and all attachments are confidential and may also be
> privileged. If you are not the named recipient, please notify the sender
> and delete the e-mail and all attachments immediately. Do not disclose the
> contents to another person. You may not use the information for any
> purpose, or store, or copy, it in any way. Guardian News & Media Limited
> is not liable for any computer viruses or other material transmitted with
> or as part of this e-mail. You should employ virus checking software.
>
> Guardian News & Media Limited is a member of Guardian Media Group plc.
> Registered
> Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.
> Registered
> in England Number 908396
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/7630#issuecomment-68694948>.
>



-- 
*Katrina Stubbings*
Design Director
Guardian News & Media
—
katrina.stubbings@guardian.com
+44 (0) 7968 034 799
@vilderness
—
Kings Place, 90 York Way,
London N1 9GU

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by sndrs** [comment]
installing chrome to check the font-smoothing check stuff, in XP with system font smoothign disabled:

![screen shot 2015-01-05 at 11 58 16](https://cloud.githubusercontent.com/assets/867233/5612781/3bdccf34-94d2-11e4-952b-892e24d279ac.png)

**Comment by mattandrews** [comment]
Nice work!
