### ISSUE TITLE
iphone5 - liveblogs - guardian videos - video player is on a hair trigger

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7690]
On iphone5 - safari browser - navigate to a liveblog that has a video at the very top
If you happen to begin your swipe by touching the native player and especially scroll down too slowly, the video starts playing in the native player.
This is a particular nuisance on the iphone as when a video plays, you are taken away from the page onto the video player, usually with a pause while the video loads and there is a delay before you can show the player options, minimise the screen and get back to the liveblog you were reading - oddly, the minimise button on the native player does require touching for a significant time period before it registers as a selection.

Issue happens on native player but not on youtube embeds

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
