### ISSUE TITLE
Liveblog issue - js enhancements not applied to newly injected posts

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7708]
Liveblogs - js enhancements appear to not be applied to newly injected posts.

I am looking at liveblog http://www.theguardian.com/world/live/2015/jan/09/charlie-hebdo-manhunt-kouachi-terrorist-links-live-updates .  
When the liveblog updated a 489 x 984 image was displayed in a 520 x 150 container with a scrollbar to move within the image.
 After I refreshed the page the image was displayed full size.

![image](https://cloud.githubusercontent.com/assets/7239344/5681390/239614da-9810-11e4-9a73-f62173ea4cbb.png)

...

![image](https://cloud.githubusercontent.com/assets/7239344/5681411/49572844-9810-11e4-988d-ac9a919202fe.png)

In addition Sam Morris has also mentioned seeing unenhanced Twitter embeds on the paris liveblog on newly injected posts.

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
