### ISSUE TITLE
Long most popular headlines overlap

### ISSUE THREAD

**Issue by sndrs** [guardian/frontend#7732]
![screen shot 2015-01-11 at 22 23 21](https://cloud.githubusercontent.com/assets/867233/5700518/6122ab14-9a37-11e4-9f69-623c772f8b88.png)

**Comment by ScottPainterGNM** [comment]
Can't reproduce this one at the moment, have you seen it any time recently?

**Comment by paperboyo** [comment]
Just now. URL: http://www.theguardian.com/artanddesign/2015/may/27/bill-owens-best-photograph-tupperware-party-1970s-california

![rhc overlap](https://cloud.githubusercontent.com/assets/6032869/7841401/3b37e0be-0494-11e5-99e3-d0a4bbd6769a.jpg)

**Comment by ScottPainterGNM** [comment]
Re-opened issue, thanks @paperboyo!

**Comment by paperboyo** [comment]
Thanks!

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
