### ISSUE TITLE
Remove visualTone from the app

### ISSUE THREAD

**Issue by sammorrisdesign** [guardian/frontend#7740]
I was just about to experimenting in adding new tones until I stumbled upon this

```scala
  // Tones are all considered to be 'News' it is the default so we do not list news tones explicitly
  /**
   * NOTE:
   *
   * This is used only for OLD-STYLE containers. It only includes the visual tones those containers care about. For
   * the new container equivalent, see `views.support.CardStyle`.
   *
   * TODO: Once we've deleted all of the old-style containers, remove this.
   */
  lazy val visualTone: String =
    if (isLiveBlog) Tags.VisualTone.Live
    else if (isComment) Tags.VisualTone.Comment
    else if (isFeature) Tags.VisualTone.Feature
    else Tags.VisualTone.News
```

Find it here in [meta.scala](https://github.com/guardian/frontend/blob/6ce927519e7e376bd35dac14ce4530e07051e094/common/app/model/meta.scala#L268-L281)

I did what the readme told me told but it looks like there's still quite a bit of `visualTone` used elsewhere. Despite being a verified Scala developer myself, I think this might be one for @robertberry to show his Scala chops.

**Comment by robertberry** [comment]
Ah yeah ... this definitely needs to be deleted now. I'll have a look ASAP.

**Comment by ScottPainterGNM** [comment]
Hi @robertberry did this one get sorted or something that sustain can pick up??

**Comment by robertberry** [comment]
Think sustain can pick it up yeah

**Comment by ScottPainterGNM** [comment]
Cheers mate, will pass it over!

On 28 April 2015 at 16:44, Rob Berry <notifications@github.com> wrote:

> Think sustain can pick it up yeah
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/7740#issuecomment-97110968>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by johnduffell** [comment]
this must be a quick win for anyone who wants to up their "deleting old code" quota up

**Comment by jennysivapalan** [comment]
Closing as this looks to be completed.
