### ISSUE TITLE
Weather locations on tablet

### ISSUE THREAD

**Issue by mr-mr** [guardian/frontend#7742]
Weather place names at tablet breakpoint are overlapping search.
Some sort of truncation is in order.

![weather-overlap](https://cloud.githubusercontent.com/assets/2067172/5705709/488f93fa-9a73-11e4-93f7-dc50fe6cfba6.png)

**Comment by ScottPainterGNM** [comment]
This appear to be resolved in the tablet breakpoint through truncating the location name, closing issue.
