### ISSUE TITLE
Weird maleware alert(); most likely third-party related

### ISSUE THREAD

**Issue by kevingimbel** [guardian/frontend#7756]
I've visited an article just a few minutes ago from my phone (Nexus 5, Android 5.0.1, Chrome 39.0) and got some weird alerts telling me my phone could be infected by viruses. (See Screenshots here https://twitter.com/_kevinatari/status/555015725631680512/photo/1) First alert was from gurdian.co.ul, second was from mobilps.com

The article I opened was this one: http://www.theguardian.com/media/2015/jan/13/charlie-hebdo-cover-magazine-prophet-muhammad

I'm sure the first one comes from advertising. Anyway, thought you should acknowledge this so you can fix it.

**Comment by piuccio** [comment]
Thanks for reporting. It was indeed an advert problem. It has been removed.

cc @dbgdngit @mattandrews
