### ISSUE TITLE
Allow inline notes from the reader to the author

### ISSUE THREAD

**Issue by jakub-** [guardian/frontend#7768]
The Guardian is great! However, occasionally I will come across a typo or a poorly structured sentence in an article and would love to be able to communicate that to the author.

What I think would address this use case well are Medium.com-like annotations that can be placed on any fragment of an article inline. In fact, the frontend already seems to display contextual icons (Facebook, e-mail) when a portion of an article is selected so that could be extended with a "leave a note for the author" button.

Apologies if this bug tracker is not the right medium for feature requests like this.

**Comment by jakub-** [comment]
cc @michaelwmcnamara @paperboyo

Could you perhaps clarify if this issue tracker is an appropriate medium for feature requests like this one? I understand having something like this live on theguardian.com would require a greater number of voices in favour and a significant consensus within the organisation but, at the same time, it would be nice to know if these suggestions are being heard by the right parties in the first place.

**Comment by ScottPainterGNM** [comment]
Hi @jakub- in terms of corrections etc. to the author then the comments section on an article is often used for this purpose and corrections have been made by authors off the back of this. 

If there is a larger issue/complaint with content then the attached guide goes into detail regarding this and how to contact the readers editor - http://www.theguardian.com/info/2014/sep/12/-sp-how-to-make-a-complaint-about-guardian-or-observer-content

I will close this off as an issue but appreciate the suggestion and we will pass it on to the product managers.
