### ISSUE TITLE
Economy front - stock market indicators - in firefox a scrollbar is displayed when indicators run out of displayable space

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7839]
On the economy front using firefox, resize the window to a narrow column that cannot display all 3 market indicators
Result:
In firefox a scrollbar is displayed directly below the indicators. This scrollbar is not echoed in chrome or safari.

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
