### ISSUE TITLE
Business Market indicators - display broken altogether in IE9

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7842]
In IE9 the new market indicators display as text with no formatting and no coloured trend indicators.

![image](https://cloud.githubusercontent.com/assets/7239344/5780979/aab7b4d2-9da6-11e4-9651-8204ad9e39d5.png)

**Comment by ScottPainterGNM** [comment]
There are now icons for up and down in red and green but the display is now making the container move down leaving a large amount of white space. This occurs across all breakpoints

![screen shot 2015-05-11 at 09 51 51](https://cloud.githubusercontent.com/assets/11922253/7561377/6842d2d6-f7c3-11e4-8c47-2f69a85e2678.png)

**Comment by johnduffell** [comment]
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
