### ISSUE TITLE
Minor Weather widget glitches

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#7845]
Hello,

1. The search bar does not respond to some keyboard events it should, IMHO. ESC should dismiss the search/editing mode and go back to last selected city, ~~while Return/Enter should commit (it does) and exit editing mode (it doesn't) as well.~~

2. While going through the list with UP/DOWN arrow keys there is an unneeded step after last/before first item of nothing being selected and just the entered text in the search box (yeah, I know I haven't described it well enough and also it is a minor point!). Maybe it would be a good idea not to wrap around the five suggestions, but provide a longer list when pressing the DOWN arrow key?

3. ~~The modal search box for Weather finally works like the rest of the interwebz! Clicking anywhere outside of it exits editing mode. Well done! Now if only __every other dropdown/search box of ours__ worked that well... ;-)~~ [finally fixed, only the search popup left to fix]

4. This one is probably going to be hard to describe, then hard to understand/agree with and then even harder/impossible to 'fix', so, please, stop reading now. Suppose you are from Żywiec. Suppose you are on a managed machine and cannot change the keyboard layout/IME. You type Zywiec, but it is not recognized. You are used to it. You go to google, type zywiec, it's recognised, the first result is Żywiec, you copy and paste. If only it would be super-easy to provide suggestions for Zywiec that include Żywiec (after all cities starting with Zywiec, obviously). BUT! It's great that our feed is using Unicode. Great! We should not forego that under any circumstances, the least of all to 'fix' that obscure 'issue'.

5. I can see that there is no search on mobile breakpoints. Are we querying the location data? If not, shouldn't the search for a Weather city be at least a part of future user preferences?

6. I just wonder: what is the logic behind the order of suggestions?

+7. Tooltips to smaller icons have disappeared one day. They are useful as some icons look the same even though they depict different weather conditions.

I would say, only pt. 1 ~~(and 3!)~~ is really a bug.

Regards
Mateusz

**Comment by johnduffell** [comment]
sorry!
closing this as it hasn't been fixed so far and probably won't be fixed in the near future
