### ISSUE TITLE
Optimise football crests

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#7848]
Hello,

URL: http://www.theguardian.com/football/live/2015/jan/18/deportivo-la-coruna-v-barcelona-la-liga-live

These crests are unoptimised PNG24s. This particular one can easily be ~3 times smaller without any discernible loss in quality by running it through pngquant. I would do them all, but I do not know how to get access to them all (http://sport.guim.co.uk/football/crests/)...

Also, as a side note, truncating Deportivo de La Coruña like that looks excessive and unnecessary at wider BPs:
![football](https://cloud.githubusercontent.com/assets/6032869/5794078/3c9163d4-9f56-11e4-963f-d8e2d5981859.PNG)

Regards
Mateusz

p.s. how many other unoptimised PNGs are there? me coming to the football pages is an entirely accidental occurrence, I assure you ;-)

**Comment by paperboyo** [comment]
Also, because poor Spaniards have no crest image associated, there is an ugly image placeholder on their tag page:

![deportivo](https://cloud.githubusercontent.com/assets/6032869/5794184/ea887d48-9f5a-11e4-8926-381b6d3d4f42.PNG)

p.s. ñ lighter than the rest of the word, because in WOFF we serve limited charset for that font, something we could fix by progressively enhancing charsets, which would possibly cut the initial font load by ~half...

**Comment by johnduffell** [comment]
this could be a win for page weight but I don't know who sport.guim is managed by.
The missing images it's hard to know whether they're there or not when the page is constructed unless we ajax it in so it would be more tricky.
Maybe ask around to find out who owns sport.guim?
