### ISSUE TITLE
Comment links on trails with a series kicker go to the series page

### ISSUE THREAD

**Issue by mattandrews** [guardian/frontend#7849]
Go to http://www.theguardian.com/tv-and-radio and look at a comment link, eg. this:

![screen shot 2015-01-19 at 10 59 20](https://cloud.githubusercontent.com/assets/394376/5799431/3f510e2a-9fca-11e4-9875-225bf50c664d.png)

That link goes to: `http://www.theguardian.com/culture/series/lastnightstv#comments`

It should be going to: `http://www.theguardian.com/tv-and-radio/2015/jan/19/last-nights-tv-call-the-midwife-foyles-war#comments`

A few users have complained about this – would be good to fix ASAP.

**Comment by gidsg** [comment]
This only appears to happen on trails which start with a Series kicker link.
e.g. http://www.theguardian.com/lifeandstyle/fruit it happens on the trail starting 'Australian food blog /'  but not 'Six brilliant bakes from Claire Ptak which doesn't have a series kicker link.

**Comment by gidsg** [comment]
Perhaps the regression came in this commit https://github.com/guardian/frontend/commit/32107ea9a9461aea60ac253efa76f8305ac01c89 @robertberry?

**Comment by mattandrews** [comment]
Seems to be fixed now.
