### ISSUE TITLE
Reporting comments - no acknowledgement displayed when user reports a comment

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7857]
When a user reports a comment, no acknowledgement is displayed to the user.
It leaves the impression that the reporting process has not worked. This issue has been raised to userhelp by one of our users.
The reporting actually does make it through the moderator, there is just some work needed to acknowledge the fact to the user/.

**Comment by johnduffell** [comment]
this hasn't been fixed in a while so it's probably not going to be fixed soon
