### ISSUE TITLE
Dedupe locations for weather?

### ISSUE THREAD

**Issue by sammorrisdesign** [guardian/frontend#7861]
One for @robertberry but I'd be curious to from hear @uplne @crifmulholland @mr-mr on this as well. Should we be de-duping locations from the weather location search? I just got this...

![](https://s3.amazonaws.com/f.cl.ly/items/2n133w0U0K412T2i0t2r/Image%202015-01-19%20at%205.05.57%20pm.png)

**Comment by crifmulholland** [comment]
Let's not fool with results just yet - I'll raise it with accuses thee.

**Comment by crifmulholland** [comment]
Damn autocorrect! accuweather!

**Comment by robertberry** [comment]
Ha. I'll have a closer look at it when I get in.
On 20 Jan 2015 07:19, "Chris Mulholland" <notifications@github.com> wrote:

> Damn autocorrect! accuweather!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/7861#issuecomment-70613648>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by johnduffell** [comment]
this hasn't been fixed in a while so it's probably not going to be fixed soon
