### ISSUE TITLE
Fronts editor tool - Paste option not available on empty containers

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7862]
The paste option for a copied article only displays on fronts that already have a story present.
If I want to paste into an empty front I cannot. I have to drag a story in first, then I can paste.

**Comment by piuccio** [comment]
Almost true :smile: 
There's an invisible click area just below the collection/group title, exactly where you would drop an article.
However that feature is broken, if you try now it'll throw an error.
I'm working on the copy/paste, I'll keep in mind to make this feature more intuitive.
