### ISSUE TITLE
Commenters names clash with recommendation arrows on narrow screens

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#7880]
Hello,

On i9100 (horizontal resolution 480px):

![screenshot_2015-01-20-01-21-09](https://cloud.githubusercontent.com/assets/6032869/5820173/043b8972-a0bb-11e4-83f7-ff02943c0ef8.png)

Regards
Mateusz

**Comment by ScottPainterGNM** [comment]
Can you reproduce this @paperboyo ?? What device did you find this on, checking it out on a Samsung S3 and on desktop at that breakpoint it appears fine for me.

**Comment by paperboyo** [comment]
Yes. Will come up...

**Comment by johnduffell** [comment]
this hasn't been fixed in a while so it's probably not going to be fixed soon
