### ISSUE TITLE
example link of article links to article that has been removed

### ISSUE THREAD

**Issue by drtortoise** [guardian/frontend#7929]
the first example in https://github.com/guardian/frontend/wiki/Articles ie http://m.code.dev-theguardian.com/sport/2012/jul/26/london-2012-athletes-anti-doping the article has been removed 
![screen shot 2015-01-22 at 15 55 28](https://cloud.githubusercontent.com/assets/201994/5859039/3c9d6106-a24f-11e4-8be8-effa920d7e65.png)

**Comment by gidsg** [comment]
Thanks, have changed the link to a working one with a Story Package.
