### ISSUE TITLE
Abrupt end of the road if Flash is the only available video source

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#7966]
Hello,

Steps to reproduce:
- do not download/disable Flash plugin
- go to a video page where Flash is the only available video tech e.g. http://www.theguardian.com/world/video/2008/may/16/gaza.children

Current behaviour:
The player gives ‘No compatible source was found for this video.’ There is no indication as to what is the cause of this message and the user is left to figure it out on her own.

Expected behaviour:
The video plays (we reencode all Flash-only videos in other formats). Failing that, we should __at least__ prompt users to download Flash player to play the video.

Regards
Mateusz

**Comment by gidsg** [comment]
@paperboyo thanks for reporting.

 NGW does not support FLV video playback. If you find videos like this with no other encodings please send them to Andy Gallagher for re-encoding,

**Comment by paperboyo** [comment]
Thanks!

It plays fine if there is Flash on the machine... The problem is, when there is no Flash. I'll try to learn more about re-encoding our old stuff...

Regards
Mateusz

**Comment by gidsg** [comment]
@paperboyo We do not want to rely on clients having Flash as some e.g. iOS never will. So where you find videos like this please email the URL to Andy Gallagher and request that they are re-encoded. Thanks
