### ISSUE TITLE
iPhone 3GS - Comments section inaccessible

### ISSUE THREAD

**Issue by zenonp** [guardian/frontend#7967]
iphone 3gs, safari, business blog, specifically http://www.theguardian.com/business/live/2015/jan/24/davos-2015-day-four-live

You scroll to the bottom of ATL and there is no comments section. Where it should be, there is a link "View all comments". You tap it and a page loads fresh. You scroll again to the bottom of ATL and there is no comments section. Where it should be, there is a link "View all comments".

On a Samsung tablet the same page works just fine. Hence, the prime suspect is new javascript that's incompatible with old safari.

**Comment by ScottPainterGNM** [comment]
Due to the fact that the maximum OS the 3GS is capable of supporting isn't capable of serving the javascript used by the site this won't be supported unfortunately.
