### ISSUE TITLE
Contributor name in liveblog appears crossed out in red

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7988]
Contributor name on liveblog: http://www.theguardian.com/us-news/live/2015/jan/26/north-east-winter-storm-noreaster-snow-live appears crossed out.
It does not appear this way on any of his older liveblogs or articles.
A quick inspection suggests it may be a red border on the timeline container which appears to overlap behind the contributor byline - see screenshot

![image](https://cloud.githubusercontent.com/assets/7239344/5903954/b78d42b6-a57c-11e4-9e2d-50d49bec6497.png)

**Comment by michaelwmcnamara** [comment]
Fabio has pointed out when you scroll, the timeline jumps overlapping with byline even more destructively:
![image](https://cloud.githubusercontent.com/assets/7239344/5904006/2a87016c-a57d-11e4-9cd5-b305f958cf94.png)

**Comment by michaelwmcnamara** [comment]
Fixed - spun up an old branch and could reproduce this in www.theguardian.com/world/live/2015/jan/27/alexander-litvinenko-inquiry-begins-in-high-court-live-updates
However on the live version of this page the issue does not occur.

**Comment by mattosborn** [comment]
fixed by #7990
