### ISSUE TITLE
Rendering of search box and results is flawed

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7991]
Display issues with google search on network front:

- Currently search box does not display text-box outline

![image](https://cloud.githubusercontent.com/assets/7239344/5904820/4fd003a0-a583-11e4-9a57-2cb126bc9f06.png)

- Font used for text and autocomplete is wrong (arial - sans-serif)

![image](https://cloud.githubusercontent.com/assets/7239344/5904859/94884c6e-a583-11e4-8289-a97f72686815.png)

- Size of results box does not line up with search box

![image](https://cloud.githubusercontent.com/assets/7239344/5904872/bd3499d8-a583-11e4-997b-1f6d81babd19.png)

**Comment by paperboyo** [comment]
Hello,

That is a hairy one that is! More than myself, if that’s even possible ;-)

- ‘Takes up to 8s to show up, even on 8 core desktop’™

- ESC won’t dismiss the bugger

- styling/typography inconsistent with beautiful Weather search, including the ugly pixelated search icon and Google logo

- dismissing behaviour inconsistent with Weather search + the rest of the Interwebz (see https://github.com/guardian/frontend/issues/3437 and https://github.com/guardian/frontend/issues/7845 pt. 3)

- suggestions should be more structured and deduplicated:
 - contibutors (e.g. search for ‘Sarah Philips’: suggestions show multiple pages of her content, shoud show just the first one at the top; bylines in suggestions aren't updating when we update the byline in R2 - http://www.theguardian.com/profile/sarahphillips)
 - series
 - media types
 - tags
 - text search

_[hairy dream mode on]_
 - search results for a specific query should produce a new ‘search front’ much like current ‘tag fronts’ but complete with filtering, sorting and _weighting_, the query should register explicitly in the address bar and thus be shareable

_[hairy dream mode off]_

Regards
Mateusz

**Comment by ScottPainterGNM** [comment]
Looking at this today it appears that some of the initial issue raised by @michaelwmcnamara are improved upon but items such as the lack of dismissal through the escape etc. and search results in the subsequent comments are still apparent. Maybe worth looking at another forum for improvement suggestions rather then the issue list but will close this off soon unless anyone protests?

**Comment by paperboyo** [comment]
I won't protest but if I could be included in that forum, please - that would be amazing!
