### ISSUE TITLE
Malformatted links

### ISSUE THREAD

**Issue by zenonp** [guardian/frontend#8008]
See http://discussion.theguardian.com/comment-permalink/46712418 . 

The link that was posted was 
```<a href="http://www.tovima.gr/politics/article/?aid=504155">To Vima, 22 March <b>2013</b></a>```
and it appeared exactly as it should in the preview. i.e. <a href="http://www.tovima.gr/politics/article/?aid=504155">To Vima, 22 March <b>2013</b></a>. Posting it, however, produced this mess ```<a rel="nofollow">To&quot;&gt;http://www.tovima.gr/politics/article/?aid=504155&quot;&gt;To</a> Vima, 22 March <b>2013</b>```, which appears as <a rel="nofollow">To&quot;&gt;http://www.tovima.gr/politics/article/?aid=504155&quot;&gt;To</a> Vima, 22 March <b>2013</b>.

**Comment by ScottPainterGNM** [comment]
I'm afraid it appears that particular comment is no longer present, has this issue appeared since then when you have attempted to post links?

**Comment by johnduffell** [comment]
this hasn't been fixed in a while so it's probably not going to be fixed soon
