### ISSUE TITLE
IE9 - tablet size window - view of Front is cut off

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8033]
IE9 - when viewing tablet size window - view of Front is cut off - refreshing page does not fix.

![image](https://cloud.githubusercontent.com/assets/7239344/5923839/6201a95e-a64e-11e4-94e8-5cf317c0d755.png)

**Comment by ScottPainterGNM** [comment]
Reproduced but appears to just happen on the point just before it reshuffles the containers into the tablet breakpoint.

**Comment by johnduffell** [comment]
this hasn't been fixed in a while so it's probably not going to be fixed soon
