### ISSUE TITLE
Cleanup redundant cookies - Bad request Page displayed when user attempted to access crosswords page from the network front

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8044]
Mario attempted to access the crosswords page from the network front.
He was shown a bad request page.
We haven't managed to reproduce this elsewhere but it was suggested that this might be caused by a large number of redundant cookies in his browser (secreenshot of cookie list to be added).
Apparently we have a list of cookies we automatically clean up.
Recommend we do an audit of what cookies are now redundant and add these to the list

**Comment by ScottPainterGNM** [comment]
Haven't been able to reproduce this so closing off unless it reappears
