### ISSUE TITLE
Congratulations!!!!

### ISSUE THREAD

**Issue by kaelig** [guardian/frontend#8045]
It's now time to change the repository's description…

![](https://cloud.githubusercontent.com/assets/85783/5937281/91b7431a-a6e5-11e4-86f1-8734fe93e532.png)

![ ](http://media.giphy.com/media/IjmMzurYulKEw/giphy.gif)

**Comment by sndrs** [comment]
![screen shot 2015-01-28 at 14 53 27](https://cloud.githubusercontent.com/assets/867233/5939642/690c91fa-a6fd-11e4-8cb9-3a0aec10bd81.png)

:+1:
