### ISSUE TITLE
Browse all sections button: underline bleeds to the left of text on hover

### ISSUE THREAD

**Issue by kaelig** [guardian/frontend#8062]
### Actual:

![screenshot 2015-01-29 10 10 14](https://cloud.githubusercontent.com/assets/85783/5955842/1e35fe3a-a79f-11e4-8223-82ab09b255ff.png)

### Expected:

![screenshot 2015-01-29 10 12 07](https://cloud.githubusercontent.com/assets/85783/5955865/5135f678-a79f-11e4-8efd-277e0c82c25d.png)

**Comment by crifmulholland** [comment]
No pull request?

**Comment by kaelig** [comment]
I can't run the project anymore :p

**Comment by kaelig** [comment]
The same issue appears in the footer navigation and on container titles

![screenshot 2015-02-05 18 32 33](https://cloud.githubusercontent.com/assets/85783/6066502/598a1d24-ad65-11e4-8d2b-5cb0304f572b.png)
![screenshot 2015-02-05 18 32 20](https://cloud.githubusercontent.com/assets/85783/6066504/5b825272-ad65-11e4-964f-97188d1e15f8.png)

**Comment by kaelig** [comment]
In the CSSWG's minutes, they just discussed this: "Add the `trailing-spaces` value to `text-decoration-skip`". That would solve this issue easily!

**Comment by ScottPainterGNM** [comment]
Looks like browse all sections appears to be fixed but close still has an underline bleed, also 'all sections' has a similar issue as per screengrab below.

![screen shot 2015-04-24 at 17 44 59](https://cloud.githubusercontent.com/assets/11922253/7323831/72d7c69c-eaa9-11e4-906e-b86d71507009.png)

**Comment by johnduffell** [comment]
this hasn't been fixed in a while so it's probably not going to be fixed soon

**Comment by crifmulholland** [comment]
It is fixed - lets not close and comment before looking at the detail.
