### ISSUE TITLE
When I am 1st commenter I cannot see comment until I sign out

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8065]
I left a comment on http://www.theguardian.com/technology/2015/jan/29/ship-your-enemies-glitter-fooled-us-all-by-shipping-enemies-glitter-wait-what which happened to be the first comment.
When I posted my comment, the comment was not displayed, instead I now saw 2 textboxes for entering a comment.
When I refreshed this did not change.
It was only after I signed out that the comment could be seen.

Screenshot showing state after posting comment:
![image](https://cloud.githubusercontent.com/assets/7239344/5956640/c6915f90-a7a7-11e4-89e7-1f8b663ef26c.png)

Screenshot after refresh:
![image](https://cloud.githubusercontent.com/assets/7239344/5956645/d72e615e-a7a7-11e4-9cf3-e29bbd56002a.png)

**Comment by johnduffell** [comment]
this hasn't been fixed in a while so it's probably not going to be fixed soon
