### ISSUE TITLE
Can't recommend comments if I am not signed in

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8066]
On the next gen site, I can only recommend comments if I am signed in.
This is a change from R2 where anyone could recommend comments.
(can confirm this on a poll or quiz as they are still R2 - eg: http://www.theguardian.com/technology/poll/2015/jan/29/elon-musk-billgates )

**Comment by mattandrews** [comment]
Not sure but I think this was a deliberate change to prevent anonymous spamming of recommends?

**Comment by gidsg** [comment]
Yes, this was done deliberately, we do not allow anonymous recommends on NGW as they are easy to manipulate.
