### ISSUE TITLE
Cannot post a comment on iPad if I have pasted in text

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8067]
If I compose a comment in notepad and paste it into the comment thread, when I press "post" the textbox flashes blue but other wise nothing happens. The comment is not posted.
Typing the same comment in, it posts successfully.

**Comment by ScottPainterGNM** [comment]
Just tested on Ipad Mini and this seems to work fine now, closed off issue unless it can be reproduced.
