### ISSUE TITLE
Weird rendering issue on comment thread

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8093]
Display issue found on chrome about 3/4 of the way down the comment thread on page 

http://www.theguardian.com/commentisfree/2015/jan/19/selma-majority-black-city-kids-grow-up-poor-powerful-do-not-care
comment id = 46346733

Appearance is as though an empty white box has been positioned over the comment in question.

Screenshots:
2 different bits highlighted in inspector:

number 1:
![image](https://cloud.githubusercontent.com/assets/7239344/5962174/db4e76b6-a7d9-11e4-96c0-00bc7d58ce86.png)
.
.
number 2:
![image](https://cloud.githubusercontent.com/assets/7239344/5962169/c640bf4a-a7d9-11e4-9773-f21574fdaeec.png)

**Comment by mattosborn** [comment]
can you reproduce this? 

i'm thinking it's just a rendering bug/anomaly in chrome.

**Comment by ScottPainterGNM** [comment]
Unable to reproduced in Chrome, closed unless this reappears
