### ISSUE TITLE
Make PNG resizer produce webP

### ISSUE THREAD

**Issue by johnduffell** [guardian/frontend#8094]
# WebP!
We are planning to serve webp for browsers that can manage it, here are some notes on that process.

- initially change the png resizer to produce webp if it's accepted
- later we can forward all traffic from nginix (jpeg resizes) which has the webp header to the png resizer which will produce a webp - change in image.conf.erb
- for PNGs we can potentially resize from the original 24 bit colour png, rather than the optimised 256 colour one - talk to @paperboyo to decide how to make the images available

## fastly adds and varies on a header:
X-Gu-Webp: true|false

## encoding webp is a lot faster than our current png pipeline

32599:tmp jduffell$ time bash -c 'for i in {1..100}; do convert orig/Abigail-Radnor-L.png -resize 360 -sharpen 1.0 -quality 0 png:-|pngquant -q 100 - >/dev/null; done'

real	0m22.615s
user	0m21.629s
sys	0m1.171s
32599:tmp jduffell$ time bash -c 'for i in {1..100}; do convert orig/Abigail-Radnor-L.png -resize 360 -sharpen 1.0 -quality 80 webp:- >/dev/null; done'

real	0m11.000s
user	0m9.593s
sys	0m1.054s

## image size is smaller
-rw-r--r--  1 jduffell  staff   29834 29 Jan 16:06 webp/Abigail-Radnor-L.png
-rw-r--r--  1 jduffell  staff   20438 29 Jan 17:01 webp/Abigail-Radnor-L.webp

## Quality is better
(webp is converted to a lossless PNG because github can't use it otherwise)
PNG: ![abigail-radnor-l](https://cloud.githubusercontent.com/assets/7304387/5962447/e90bd954-a7db-11e4-9e25-41f26a174160.png)
WebP: ![webpconverted](https://cloud.githubusercontent.com/assets/7304387/5962480/2bd0d0aa-a7dc-11e4-9bdf-b8fd9128525f.png)

**Comment by paperboyo** [comment]
Hello,

Wow! But.

For WebP generation we should ideally use unoptimised PNGs (24bit instead of dithered 256 colours). The thing is, they are nowhere on the system currently... I have them in my one-day-we-should-use-that pocket.

Chat? [if interested, obviously!]

Regards
Mateusz

**Comment by johnduffell** [comment]
Agreed - in fact I didn't realise the available images are dithered - for best quality we shouldn't really be doing any quantization (including resizing) on an already dithered image.  Anyway I am 100% interested - however it's baby steps at the moment.  I'll add it to the plan at the top of this issue =)

**Comment by paperboyo** [comment]
Yeah, and WebPs could probably be also a little bit smaller when they won't have to try to compress the dithering :-)

Regards
Mateusz

**Comment by paperboyo** [comment]
Hi,

Luckily, because we do have a high quality sources this does not directly apply, but just so I don’t forget, would we ever want to manipulate/convert dithered sources (GIFs, PNG8), we should look at https://github.com/pornel/undither.

cc/ @theefer, @jamesgorrie

Regards
Mateusz

**Comment by johnduffell** [comment]
So @gklopper has negotiated a trial of an image resizing service so this work is on hold for now - have pushed this to the https://github.com/guardian/frontend/tree/resize-webp branch in case we need it back
