### ISSUE TITLE
Mobile devices - breaking News notifications ovelap with search textbox when keyboard is opened

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8114]
On mobile devices - when you are viewing the network front with a "breaking news" notification.
Expand the weather display and select the text field
Result:
Keyboard displays and this pushes the breaking news notification up the screen to the point that it overlaps with the search field. This means people cant see what they are typing or the list of options in the auto-complete section
Ideally when breaking news notification is present, we should push the search field up the screen so that it is still visible.

Screenshot:
![screen shot 2015-01-30 at 16 15 27](https://cloud.githubusercontent.com/assets/7239344/5978934/4da73aec-a89b-11e4-9b8c-1696eef44204.png)

**Comment by johnduffell** [comment]
sticky mess...
we haven't got around to fixing this yet so it's probably not going to be fixed any time soon
