### ISSUE TITLE
Video trails twitch on fronts before play

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#8118]
Hello,

All desktop platforms/browsers tested. Go to any front with a video player(s), start any video.

Before hitting play, there is a trail pic shown, after hitting play but before video starts, the same trail displays but cropped differently, after that I am not sure what happens myself (the trail is shown the third time again cropped differently?).

The same videos play correctly on their respective video pages. Ideally, the videos of fronts should play as cleanly as on video pages.

Below a presentation of above in slow motion (buffering courtesy of Virgin’s ‘Superfast and super value Up to 120Mb Broadband’):

![twitch1](https://cloud.githubusercontent.com/assets/6032869/5984849/577e2440-a8d2-11e4-97fd-0619e4cabeb3.gif)

Regards
Mateusz

**Comment by johnduffell** [comment]
we haven't got around to fixing this yet so it's probably not going to be fixed any time soon

**Comment by paperboyo** [comment]
Ok, I _think_ it may be because there is a progression of trail pic>poster frame[>possibly another poster frame]. We should just get rid of poster frames on fronts. This would shave e.g. ~1,7MB off current video front. We will save on bandwidth and will have no twitching. I may be wrong, though!
