### ISSUE TITLE
‘More from this series’ video endslate fail

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#8119]
Hello,

All desktop platforms/browsers tested.
- some videos from the series show the end slates while embedded on fronts  - they should not (e.g. http://www.theguardian.com/lifeandstyle/video/2015/jan/30/get-over-ex-boyfriend-agony-aunt-problem-video)
- other do not display the end slate at all, which is wrong as well (‘Film show’ - a lot of available content)
- if there is just one more piece of content from a specific series, like in a link above, end slate looks wrong

Screenshots:

![series slate fail 1](https://cloud.githubusercontent.com/assets/6032869/5985268/0a043c6c-a8d8-11e4-93cb-602674ebd5f7.PNG)

![endslate-fail-2](https://cloud.githubusercontent.com/assets/6032869/5985274/0df233f6-a8d8-11e4-9dc6-6d00f9db0f0f.jpg)

![endslate fail 3](https://cloud.githubusercontent.com/assets/6032869/5985275/10fb0b22-a8d8-11e4-818e-37d58292ad5d.PNG)

Regards
Mateusz

**Comment by johnduffell** [comment]
I have fixed the first point:
- some videos from the series show the end slates while embedded on fronts - they should not (e.g. http://www.theguardian.com/lifeandstyle/video/2015/jan/30/get-over-ex-boyfriend-agony-aunt-problem-video)

**Comment by paperboyo** [comment]
Thx!

**Comment by johnduffell** [comment]
second point, I can't reproduce?  If I skip to the end of this, http://www.theguardian.com/film/video/2015/jan/30/the-guardian-film-show-kingsman-the-secret-service-inherent-vice-trash-big-hero-6
then I can see some related content
![image](https://cloud.githubusercontent.com/assets/7304387/6108219/2120168a-b069-11e4-8d3c-4aace388136e.png)
is it still broken?

**Comment by paperboyo** [comment]
Hi,

Ok, that's going to be embarassing... AdBlock Plus is preventing the end slate from showing up in both Chrome and Firefox on both Mac and Windows (default extension filters).

Hmm... I though I do not miss any of the good stuff... It's a pity it gets blocked, shouldn't, right?

:facepalm:
![embarrassed](https://cloud.githubusercontent.com/assets/6032869/6108432/0d080d4a-b06b-11e4-85ed-118636619f9c.gif)


Regards
Mateusz

**Comment by johnduffell** [comment]
I think that's still kind of a bug, I'll have a look.

In related news, I found that videos aren't playable in related content now that it's ajaxed in when you scroll down, Matt O has given me some pointers how to deal with it, so I'm going to fix that next.

**Comment by paperboyo** [comment]
:sigh of relief:

**Comment by johnduffell** [comment]
Ok I took a look and basically in the "easylist" they are blocking downloads of http://imasdk.googleapis.com/js/sdkloader/ima3.js which is javascript used by the video.js player.  Actually our content is coming in fine.

I've submitted a request to https://forums.lanik.us/viewforum.php?f=64 just now, so we will see what they say assuming the message is approved by the moderators.

**Comment by johnduffell** [comment]
I also discovered that related content is broken when adblock is turned on because the url includes exclude-tag=tone/advertisement-features

**Comment by paperboyo** [comment]
Hi,

Thanks to John, most (and more!) of the issues are now fixed. The third one of the original issues is still present but the given URL is no good for judging it any more (there is now more than one content item in this series), thus closing.

Regards
Mateusz
