### ISSUE TITLE
Lightbox won’t open where there is an icon for it

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#8120]
Hello,

Different desktop browsers. Some cartoons below behave like they should open Lightbox (icon, link), but won’t:

e.g.:
http://www.theguardian.com/artanddesign/cartoon/2014/oct/15/roy-lichtenstein-peter-duggan-artoon

http://www.theguardian.com/artanddesign/cartoon/2014/nov/12/peter-duggan-artoon-henry-fuseli-allen-jones

Regards
Mateusz

**Comment by Jholder112233** [comment]
This will only affect image pages where the largest crop we have is between 620px and 940px wide. 

Originated here: https://github.com/guardian/frontend/commit/16e04117aa465c9c005ada96adc4dbee6bbdea3b

I'll add this to the to-do list.

**Comment by paperboyo** [comment]
Hi,

Thanks! I still think that we have some _small_ errors in ``largestEditorialCrop`` logic that result in small amount of old high res imagery missing.

Two examples are below:
- http://www.theguardian.com/world/picture/2014/jun/02/1#img-1 (we show 940px × 705px)
while there is _uncut_ higher res of 2,048px × 1,536px available here: https://gnmrem1.guardian.co.uk/+CSCO+01756767633A2F2F66676E6776702E7468767A2E70622E6878++/sys-images/Guardian/Pix/pictures/2014/6/2/1401695757946/Normandy-020.jpg (strangely, there is also another one available of exactly 

-

**Comment by paperboyo** [comment]
Hi,

Main issue fixed. The logic error in ``largestEditorialCrop`` from above comment persists, though...

:panda_face: closing. Thanks @Jholder112233, @mattosborn!

Regards
Mateusz
