### ISSUE TITLE
Today’s matches overlap Key events on football Liveblog

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#8121]
Hello,

All browsers tested on Win 8.1:

URL: http://www.theguardian.com/football/live/2015/jan/31/premier-league-and-africa-cup-of-nations-clockwatch-live (scroll down)

“Fetching today’s matches…
Impatient?” displayed and then, after scrolling down:

![liveblog fail](https://cloud.githubusercontent.com/assets/6032869/5988596/f96ec28c-a95e-11e4-864f-ec7850282733.PNG)

Regards
Mateusz

**Comment by ScottPainterGNM** [comment]
Reproduced - looks like the key events functionality that follows the page down is then overlapping the premier league table when it reaches that part of the page.

**Comment by johnduffell** [comment]
we haven't got around to fixing this yet so it's probably not going to be fixed any time soon
