### ISSUE TITLE
Performance: video-player.js is not properly minified

### ISSUE THREAD

**Issue by robertberry** [guardian/frontend#8122]
See for example the bottom half of http://assets.guim.co.uk/javascripts/bootstraps/2f826dae1309f6e002c6ffbc60f67f62/video-player.js

**Comment by phamann** [comment]
Very strange, must have been when we were still developing locally. Anyway it's pretty easy to fix: 
https://github.com/guardian/frontend/blob/master/grunt-configs/requirejs.js#L186

**Comment by rich-nguyen** [comment]
Fixed in #8287
