### ISSUE TITLE
Performance: ~50% of DOM nodes are behind 'Show More'

### ISSUE THREAD

**Issue by robertberry** [guardian/frontend#8123]
Go to any front you like

Open the console, type

```javascript
document.querySelectorAll("*").length
Array.prototype.slice.call(document.querySelectorAll(".fc-container--has-show-more .fc-slice-wrapper:last-of-type")).forEach(function (el) { el.parentNode.removeChild(el) });
document.querySelectorAll("*").length
```

And you'll get given a count of elements on the page, and then elements on the page that are not behind show more.

On the homepage (where we have relatively little behind Show More), currently only 2423 / 4840 are not behind show more.

On a front with automated backfills, this is much worse. Culture for instance shows only 2082 / 6025 elements at the moment.

**Comment by sndrs** [comment]
`document.querySelectorAll('.linkslist-container *').length` will give you total elements used for show more items

**Comment by sndrs** [comment]
this is pretty insane

**Comment by sndrs** [comment]
comment counts are also loaded for show more

**Comment by sndrs** [comment]
the hidden elements on the current network front account for 25k, gzipped

**Comment by robertberry** [comment]
Nutty. I think this is clearly one of the biggest things we can optimise.
