### ISSUE TITLE
Comment front does not show comment counts

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8124]
Comment counts not showing on "Opinion" (cif) front.

Articles are not showing a comment count on the Opinion front, despite being open for comments and having a number of comments already.
Debug console does not show any errors.

![image](https://cloud.githubusercontent.com/assets/7239344/5994468/9b23f206-aa6c-11e4-91af-555cbf085848.png)

**Comment by robertberry** [comment]
This is now fixed.
