### ISSUE TITLE
Icons missing on Picture/Cartoon items

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#8134]
Hello,

As seen in ‘world news’ (after ‘More world news’) container on ‘world’ UK front:

![picture cartoon1](https://cloud.githubusercontent.com/assets/6032869/6015596/6f7390f0-ab6e-11e4-85e9-ba73c3f15859.PNG)

and in ‘opinion’ (after ‘More opinion’) container on ‘opinion’ UK front:

![picture cartoon2](https://cloud.githubusercontent.com/assets/6032869/6015602/a098eb76-ab6e-11e4-8e2b-667ff4a5ee46.PNG)

Regards
Mateusz

**Comment by sammorrisdesign** [comment]
We don't have a cartoon icon if memory serves me right, but Eyewitness should be getting the icon. It looks like the `fc-item--gallery` class isn't being added and I can't figure out why. @robertberry any ideas?

**Comment by paperboyo** [comment]
Hello,

Missing icons are one thing, but the trail pics are also not displayed on these. While it may be true that we need a special icon for cartoons and infographics, and interactives, and tables, and documents, and animated gifs, and... you see where this is going?, in my humble opinion, imagecontent type needs trail pics on items:

![eyewitness](https://cloud.githubusercontent.com/assets/6032869/6099393/a4f0d09c-afee-11e4-8f29-4ffe02fe1f70.PNG)

Regards
Mateusz

**Comment by ScottPainterGNM** [comment]
Looking at this now, it appears trail images are present for Eyewitness and Cartoons as per second comment, happy to close this off?

**Comment by paperboyo** [comment]
Hi,

The problem still manifests itself when the tiles are too small to show the trail pic and there is no Cartoon kicker, like on David Squire’s piece illustrated below. There is no icon (as per @sammorrisdesign comment above) and only tone colour indicates content type. It may not be clear for readers not familiar with our style. I still think it’s lesser evil to show camera icon for illustrations/cartoons. And, as per my comment above, I do not think that we absolutely have to introduce new icons for *all* our content types...

![cartoons no icon](https://cloud.githubusercontent.com/assets/6032869/7585024/d06eae26-f899-11e4-88a0-70ea7758a74a.PNG)

But if everybody is cool with how it stands currently, I’m happy to close (will wait for eventual comments a bit...).

Regards
Mateusz

**Comment by paperboyo** [comment]
Also, because I can’t seem to find a way to test this (preview fronts won’t do ‘More...’ buttons), would non-cartoons Cartoon/Picture types while small/no trail pics show the camera icons - like e.g. Eyewitness? How would the system add icons to Eyewitness series but not to any cartoons when they are the same content type? By series (non-sustainable...)? This would be another argument to have camera icons for all Cartoon/Picture types, IMHO.

**Comment by sammorrisdesign** [comment]
If these cartoons/eyewitness things are all series, couldn't we show the tag instead?

**Comment by paperboyo** [comment]
You mean - force the tag kicker for the tiles from specific series, like Eyewitness but not for the cartoon series? I presume yes, that would sort it. I do not know the way to have a list of all series within Cartoon/Picture type. Would like to know the CAPI query to find out :smiley:

**Comment by paperboyo** [comment]
Or this top-of-tile series thingy I still not totally understand the raison d'être?

**Comment by sammorrisdesign** [comment]
I imagine most of the ones not getting icons are part of a series. So "EyeWitness / Title of witness story" to be forced would probably do the trick. If most of them are.

If not maybe we do need to add a camera icon (I think adding more icons just creates more confusion) for all imagery.

**Comment by paperboyo** [comment]
Agreed. The easiest would be just to add camera icons to all. If not, then someone would have to go through all series of Cartoon/Picture type and pick photographic series and hardcode the logic that adds camera icons just to these (and maintain it in perpetuity :wink:). I just wanted to start the conversation. Feel free to close the issue whenever, Gentlemen, provided it’s somehow taken care of. Someday.

Regards
Mateusz

**Comment by ScottPainterGNM** [comment]
@sammorrisdesign did you want to pick this up under a separate job perhaps or is it for someone else? I can close off this issue or ask Sustain to pick up if not?

**Comment by sammorrisdesign** [comment]
Sounds like it makes sense for sustain to investigate the issue a little more. Shouldn't be too much work to get these types to behave like galleries with a camera icon.

**Comment by ScottPainterGNM** [comment]
No worries, I'll have a chat with whoever is assigned to sustain!

On 12 May 2015 at 12:31, Sam Morris <notifications@github.com> wrote:

> Sounds like it makes sense for sustain to investigate the issue a little
> more. Shouldn't be too much work to get these types to behave like
> galleries with a camera icon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/8134#issuecomment-101245916>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by johnduffell** [comment]
we haven't got around to fixing this yet so it's probably not going to be fixed any time soon

**Comment by sammorrisdesign** [comment]
Why are we closing issues that we haven't fixed? I'm a little worried we're going to lose things that we should get around to fixing at some point.
