### ISSUE TITLE
Taken to login prompt when I click on link to my profile (even though I am logged in)

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8168]
I am currently logged in and can post comments, but if I try to access my profile page I am taken to the login prompt.

![image](https://cloud.githubusercontent.com/assets/7239344/6040606/8f8d75b0-ac6b-11e4-800f-d799bc1dc9c8.png)

**Comment by ScottPainterGNM** [comment]
This now appears to be fine
