### ISSUE TITLE
Weather - US edition shows Fareinheight temp degrees C temperature symbol next to it

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8213]
Select New York edition, weather is displayed with degrees C symbol, even though the actual temperature displayed is in Fareinheit.

![image](https://cloud.githubusercontent.com/assets/7239344/6078557/f6a5a768-adf1-11e4-8009-ef08e525ade3.png)

**Comment by michaelwmcnamara** [comment]
Now showing Celcius temp and Celcius scale symbol - halfway there - at least temperature is correct.
Now just need to convert to F for US editions

**Comment by uplne** [comment]
This has been fixed

**Comment by ScottPainterGNM** [comment]
Checked and this appears to be working fine, closed issued.
