### ISSUE TITLE
Weather - time scale of forecast is incorrect - showing uk times

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8215]
Timescale on weather is incorrect for US edition - the time shown for New York is either UK time or UTC time with no offset ( both give the same value at the moment)
Timescale should contain 0600 (current time in New York as I write) instead it shows the block containing 11AM (the time here - or the time it would be if we were not applying any offset from UTC).

![image](https://cloud.githubusercontent.com/assets/7239344/6078701/84c17724-adf3-11e4-86b5-f0c5364fd374.png)

**Comment by uplne** [comment]
This should be fixed by https://github.com/guardian/frontend/pull/8242

The weather is showing F on US edition now and it's showing right timezone for US, AU and UK editions. But the timezones are for Sydney and New York now, so there is still some work to do on that. It's not bug tho.

**Comment by johnduffell** [comment]
we haven't got around to fixing this yet so it's probably not going to be fixed any time soon
