### ISSUE TITLE
Sharing icons overlap caption in ‘supporting’ video

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#8232]
Hello,

I am not sure if it shouldn’t be posted in Composer’s repo.

URL: http://www.theguardian.com/world/2015/feb/08/ukraine-summit-minsk-end-conflict-russia

Multiple browsers, wider breakpoints.

When video is set to ‘supporting’, the sharing icons overlap it’s caption text like so:

![supporting](https://cloud.githubusercontent.com/assets/6032869/6097374/e6f926c8-afb3-11e4-8bc9-f4815da2d1a5.PNG)

Regards
Mateusz

**Comment by Jholder112233** [comment]
Also fixed as part of https://github.com/guardian/frontend/issues/8241

**Comment by paperboyo** [comment]
Fixed by https://github.com/guardian/frontend/pull/8241.

Thank you!
