### ISSUE TITLE
Add RSS links in the <head>

### ISSUE THREAD

**Issue by julien51** [guardian/frontend#8298]
Being able to follow RSS feeds from the Guardian is very important, because not everybody wants to come back to the home page over and over again to learn about new/developing stories.

The Guardian provides RSS feeds, which is amazing! Thank you for this...

Yet, these feeds are not "discoverable" by machines/feed readers, even though it's as easy as adding a link element in head `<head>` section of the HTML like this:

```
<link rel="alternate" href="/rss" type="application/rss+xml" >
```

It won't affect anything visible... but it will change the lives of the people, like me, who follow RSS feeds and won't want to *guess* what the URL of a feed is.

**Comment by julien51** [comment]
The saddest part is that since nobody can find these feeds, sooner or later the Guardian will drop them saying that nobody used them... but people would if they know they existed.

**Comment by lloydwatkin** [comment]
Please keep the RSS feeds and make them discoverable :+1:

**Comment by jsherer** [comment]
It's important for the community and ecosystem to have discoverable RSS feeds. +1

**Comment by samuelclay** [comment]
This would greatly help news readers like @newsblur. +1

**Comment by paperboyo** [comment]
+1 for “dead” RSS!

**Comment by secou** [comment]
Yes please do it !
Here is the specification of the "RSS Autodiscovery" : 
http://www.rssboard.org/rss-autodiscovery

**Comment by janua** [comment]
@julien51 We definitely will not drop RSS.

I will look into putting this into all the front pages it's appropriate on.

**Comment by julien51** [comment]
Thanks @janua!

**Comment by secou** [comment]
Thanks @janua !

**Comment by janua** [comment]
@julien51 @secou @samuelclay  I have just released this now. It's not for ALL pages, but it's for most fronts.

Would you be able to verify if your RSS reader picks it up?

**Comment by secou** [comment]
Thanks so much! It works fine!

**Comment by julien51** [comment]
Thanks! I checked a couple pages and that worked great... now, think about [SubToMe](https://subtome.com) if you want to add RSS buttons to the site as well :)
