### ISSUE TITLE
Unwanted whitespace caused by coincidence of MPU and long headline

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8317]
from Tara Herman
"Good morning,

For containers that feature an MPU, can you please watch out for big gaps appearing underneath them.

This is caused by the adjacent story cards being too deep because of wordy headlines so subbing them down or removing sublinks will restore the balance (and not leave the stories in column three stranded)."

![image](https://cloud.githubusercontent.com/assets/7239344/6185860/05715f8e-b36b-11e4-8b64-b8809293a1e9.png)

Really we should be preventing this from happening rather than forcing editorial to have to tiptoe around it.

**Comment by ScottPainterGNM** [comment]
Reproduced today - 05/05/15 on Football container on Sport Front

![screen shot 2015-05-05 at 10 06 47](https://cloud.githubusercontent.com/assets/11922253/7469681/49223766-f30e-11e4-83e9-a026cac716a6.png)

**Comment by johnduffell** [comment]
we haven't got around to fixing this yet so it's probably not going to be fixed any time soon
