### ISSUE TITLE
Impossible to add or edit cutout image url without getting the incorrect url popup

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8335]
Incorrect url pop-up appears and takes over the window as soon as you enter any text into this field. This is very annoying.

![image](https://cloud.githubusercontent.com/assets/7239344/6191843/917f897c-b3a4-11e4-98da-9e7f4e648ea0.png)

**Comment by ScottPainterGNM** [comment]
Re-tested by @michaelwmcnamara today (24/04/15) and still an issue

**Comment by piuccio** [comment]
I'm not sure this is a bug. You're not supposed to type in that field, but paste an image url directly

**Comment by ScottPainterGNM** [comment]
In which case I shall close off unless it's raised as a requirement by editorial at any point, seems to be that they will pull everything in from the grid anyway rather then paste the URL in directly.

**Comment by paperboyo** [comment]
Not for these they don’t. Grid won’t do cut outs. None of the tools will. Batch uploader + pasting Gchatted URL it is for the time being :dizzy_face:
