### ISSUE TITLE
T&C on profile page gives a 404

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8336]
Navigate to profile page (https://profile.theguardian.com/public/edit)
click terms and conditions link in bottom nav

Result
link tries to go to https://profile.theguardian.com/help/terms-of-service
which doesn't exist

Expected:
Link should go to http://www.theguardian.com/help/terms-of-service

**Comment by johnduffell** [comment]
mike and I will have a go

**Comment by marchibbins** [comment]
This is the case for all footer links on the `profile` subdomain. They've never worked.

**Comment by michaelwmcnamara** [comment]
This is now fixed on live.
