### ISSUE TITLE
[a question and a plea] Whatever happens in the fronts tool, stays with the fronts tool (?)

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#8337]
Hello,

I’ve recently learned that whatever happens in the fronts tool disappears into nothingness - image replacements, cut outs, weighting options, position of items and the time they are on their respective fronts, breaking news status and more. Is that true? If it’s not true, then please excuse me, disregard and stop reading now.

But if it’s true I would like to put up a case for an immediate change of that insane policy, if I may.

The obvious question would seem to be: why would you want to keep that information and what you think could be the future benefit of keeping it?

To that I would answer in the most polite, informative and convincing way (as I always do): What a stupid question?!

How many times I wished some system kept information that I am in a need of and that could be useful, but because it was never kept, it now has to be inferred somehow which is hard or impossible.

Editorial decisions are all about weighting. Current tag fronts and all other chronological lists of our content carry, and thus convey, no weighting. Absurdly, and counter to the manned fronts, they go against our model of ‘bigger is more important’, because the size of items on these lists comes purely from detached CSS rules for their placement - it’s purely aesthetic.

One way to infer the weighting would be to observe the CAPI fields for ``newspaper-book`` and ``newspaper-book-section``. Because of the structured nature of the printed products they convey the importance of the stories by their mere placement. We are currently not using this information on the web. And that’s fine. But we keep it for when it will (and it will!) prove useful.

If it’s true that we are throwing away similar information that the editors are putting into fronts tool, then we are depriving ourselves of the ability to present past content in the more structured manner that conveys The Guardian’s and The Observer’s editor’s judgement. We will indeed be very sorry one day...

Regards
Mateusz

p.s. [strong irony warning] do not be fooled by those pretty words, it’s all about my cut outs! WHY GUARDIANZ NO KEEPZ MY CATOUTS IN PERPETUITY?!

**Comment by piuccio** [comment]
I would say instead that fronts tool never forgets, but I don't really understand the problem. There's history of everything, it's just not user friendly ti dig into.
@janua am I wrong?

**Comment by paperboyo** [comment]
Mornin’

I find my lack of faith disturbing. So are hypothetical science-fiction scenarios below possible (nevermind if they are good ideas!):

- a story from today that has got some settings set in fronts tool brought to some other front in 2017, because it’s suddenly super-relevant, could automatically carry these settings with it

- Composer could warn that the trail picture of a story that has got image replacement on one of the fronts could warn about it and link to that image replacement in the Grid and then the Grid could make a request to the fronts tool for that replacement to be replaced with a newer version of the image

- a search on frontend could return all breaking news stories from the second half on 2019 and present them in their respective weighting

- at the request of the British Museum, a list can be prepared of all the cut outs and the stories they were used for on fronts

Regards
Mateusz

**Comment by janua** [comment]
Where did you learn this? The fronts-tool saves all curated history. So we have never lost that information.

When curating a front, or a tag page as a better example, the editors fill out the top of the container and the rest can come from backfills. On top of that items are deduped while being output. This mix would be hard to preserve so we don't save any of that information. This is what the time machine is made for; it preserves both the `HTML` and takes a picture of the full front at 3 breakpoints.

Even though we save all history, it's never really been worked on and isn't in the best structure for querying. So to answer your scenarios:

> a story from today that has got some settings set in fronts tool brought to some other front in 2017, because it’s suddenly super-relevant, could automatically carry these settings with it

 Yes.

> Composer could warn that the trail picture of a story that has got image replacement on one of the fronts could warn about it and link to that image replacement in the Grid and then the Grid could make a request to the fronts tool for that replacement to be replaced with a newer version of the image

Yes, this is possible.

> in 2019, a search on frontend could return all breaking news stories from the first half of 2015 and present them in their respective weighting

Yes. But, respective weighting? There is usually only one story in breaking news at a time, so there is no weighting. Maybe represented by time?

> at the request of the British Museum, a list can be prepared of all the cut outs and the stories they were used for on fronts

Yes.

I think the Trail picture one would require a good bit of work and coordination of different systems, but is certainly possible.

**Comment by paperboyo** [comment]
Hello!

Such a relief! Thank you, @janua and @piuccio for a thorough explanation. Obviously, just a total dilettantism on my part. So happy to be proved oblivious :-)

Regards
Mateusz
