### ISSUE TITLE
iphone4S - iOS8- frequently freezing for 1-4 seconds when scrolling

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8352]
When using the phone it frequently freezes for 1-4 seconds before resuming.
Seems to happen mainly when scrolling.
Witnessed on articles and fronts.

On articles often if you scroll down quickly the text does not display and you are frozen on whitespace for a few seconds before text displays and phone becomes responsive again.
Phone becomes very warm while this is happening
Better than a crash, but worth investigating to see if we can smooth the behaviour further.

**Comment by paperboyo** [comment]
Same thing on Galaxy S2. Yeah, I should get a better phone ;-)

**Comment by johnduffell** [comment]
seems like a general manifestation of the perf issues
