### ISSUE TITLE
Internet Explorer - back button is not working correctly

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8365]
IE11 users are reporting that the back button on the browser is being ignored on our website.
I have managed to reproduce this on a virtual machine, but it isn't consistent.
Suspect it may be generated when you press back while some resources are still loading. 
Will update with more info.

**Comment by michaelwmcnamara** [comment]
Reproduced in IE10 and IE9 - reproduction is not consistent and seems to be related to unexpected url's entering the back buttons history

Example 1:
Found in IE10:
In google - searched for "guardian world" and selected http://www.theguardian.com/world/2015/feb/17/russia-shelled-ukrainians-from-within-its-own-territory-says-study from the search results.
When I pressed the back button to navigate back to the search page, the page that I was currently on reloaded.
Right-clicking to look in the back buttons history list, I could see the a google url as the immediately previous site - but it was the url for the search result I had selected rather than the page with all the search results.

![image](https://cloud.githubusercontent.com/assets/7239344/6247878/bd7a8c54-b771-11e4-9f02-4ea86c0ecfe3.png)


Example 2:
Found in IE9:
Navigated from network front to http://www.theguardian.com/science/2015/feb/18/limpet-teeth-strongest-natural-material
Was unable to navigate back to the network front.
Looking at the history in my back button, the immediately previous url was shown as:
http://tags.mathtag.com/external/eyeblaster/addingeyeV2.html
(presumably part of our marketing paraphenalia - see (http://stackoverflow.com/questions/13462795/determine-which-advertisement-made-a-request-to-eyeblaster-addineyev2-html for details on this url) 

![image](https://cloud.githubusercontent.com/assets/7239344/6247962/85e6dd46-b772-11e4-978d-f06ccd0558db.png)

**Comment by ScottPainterGNM** [comment]
I'm having trouble reproducing this @michaelwmcnamara , has this come up recently?

**Comment by ScottPainterGNM** [comment]
Unable to reproduce testing multiple times, closed off unless issue reoccurs
