### ISSUE TITLE
Videos from the embed code don't render correctly.

### ISSUE THREAD

**Issue by sammorrisdesign** [guardian/frontend#8379]
The downsides to the external embed code that we offer is that sometimes it gets used internally in articles (I think InCopy seems to like generating these as well), this means we get the external player on our page. We probably need to make it so our articles only get one version of our player and I've mentioned this to top men who will be able to fix this.

However, at the very least the iframe should get the correct height.

cc @Jholder112233 @phamann 

![screen shot 2015-02-19 at 09 54 00](https://cloud.githubusercontent.com/assets/1607666/6264690/eb736188-b81d-11e4-8dfc-652111b33c5b.png)

**Comment by paperboyo** [comment]
Related: https://github.com/guardian/frontend/pull/8148

**Comment by johnduffell** [comment]
we haven't got around to fixing this yet so it's probably not going to be fixed any time soon
