### ISSUE TITLE
Images not showing up below 500px

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#8396]
Hello,

Crops of less than 500px made in Grid are not showing up on frontend preview.

Preview URL: http://preview.gu[...].co.uk/global/2015/feb/20/test-ngw-not-picking-up-images-and-serves-bigger-than-it-should

They should show up. They do in Composer...

Related to [INTERNAL RESOURCE] https://github.com/guardian/media-service/issues/500

Regards
Mateusz

**Comment by paperboyo** [comment]
Hello,

Still very much an issue. Sorry, the Preview for the above has expired. Here is the content [INTERANAL RESOURCE] https://composer.gutools.co.uk/content/54e6fb45e4b0d7e8c5774613

Inspector reveals ``<!--Error: Failed to load image asset-->``

See also discussion linked above.

Regards
Mateusz

**Comment by ScottPainterGNM** [comment]
The preview doesn't appear, would you be able to serve me up another example to take a look possibly? @paperboyo

**Comment by paperboyo** [comment]
http://preview.gu[...].co.uk/global/2015/feb/20/thubnail-tests or is it kosher to post URLs to the preview server?

**Comment by ScottPainterGNM** [comment]
I'm not sure, that link still doesn't display for me for some reason. Could you ping me the full URL over hangouts possibly?

**Comment by rich-nguyen** [comment]
update: the current threshold which causes this issue is now 460px. So a grid image used in composer which is 459px or less will result in a `<!-- Error: Failed to load image asset --> ` in the body. one for flexible content, @theefer

**Comment by paperboyo** [comment]
Thank you for the update, @rich-nguyen! Should I open Composer's bug? (cc/ @na7hangood)
