### ISSUE TITLE
Thumbnails served at 620px instead of 140px

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#8398]
Hello again,

NGW shows thumbnailed images at 140x140px (if not zoomed in). I produced assets through Grid that is making all the needed sizes available for NGW including 140x140px. Despite that, NGW serves oversized 620x620px images unnecessarily increasing page weight.

Preview URL: http://preview.gutools.co.uk/global/2015/feb/20/test-ngw-not-picking-up-images-and-serves-bigger-than-it-should

Big thanks to @theefer for helping me investigate (investigating for me, really...) at such an early morning hour...

Regards
Mateusz

**Comment by rich-nguyen** [comment]
I cannot see how the code could possibly deal with thumbnails correctly. Will fix.

**Comment by theefer** [comment]
Great thanks @rich-nguyen !
