### ISSUE TITLE
Membership merchandising component: Button wraps onto 2 lines (iOS)

### ISSUE THREAD

**Issue by gidsg** [guardian/frontend#8412]
Steps to reproduce
===============
* On an iPhone at 320px width go to:  http://www.theguardian.com/film/2015/feb/23/oscars-2015-list-of-winners
* Scroll down to Membership merchandising component

Actual Result
==========
CTA text wraps on to 2 lines:
![img_0689](https://cloud.githubusercontent.com/assets/1764158/6325518/6f1150c0-bb40-11e4-9a76-c2e6a494398a.jpg)

Expected Results
=============
CTA text fits within button (as per other platforms & viewports)
CC @kenlim

**Comment by ScottPainterGNM** [comment]
Not been able to reproduce this with the current membership ads, there are other similar types but they seem to be fine. Have you seen this recently?

**Comment by paperboyo** [comment]
Hi, I know it’s not directly related but the new narrow nav for interactives wraps over two lines on my 800x480 S2. URL: http://www.theguardian.com/politics/ng-interactive/2015/may/07/live-uk-election-results-in-full. Presumably, it’s even worse on that iPhone...

**Comment by ScottPainterGNM** [comment]
Have you got a screenshot of that second item? Browsing through my iPhone on this screen I can't locate the issue reported?

**Comment by paperboyo** [comment]
With pleasure:

![screenshot_2015-05-11-10-38-37](https://cloud.githubusercontent.com/assets/6032869/7562167/15a6bc2a-f7ca-11e4-8ffe-e9af053c6612.png)

**Comment by ScottPainterGNM** [comment]
I see that as well, could you raise a new issue for that one and I'll close this off?

**Comment by paperboyo** [comment]
Will do. Thanks!
