### ISSUE TITLE
Local Navigation unavailable in footer meganav

### ISSUE THREAD

**Issue by kaelig** [guardian/frontend#8415]
1. Go to any section or article http://www.theguardian.com/fashion
2. Open the footer navigation

**Expected:** User can go to a sibling section

**Actual:** Local navigation is unavailable

**Comment by rich-nguyen** [comment]
on it.

**Comment by kaelig** [comment]
Cheers!

- not sure the footer local nav it should appear when the meganav is closed (I think it didn't use to be the case in old designs)
- and probably should appear at the top of the open footer meganav
