### ISSUE TITLE
Showcase images display underneath quoted blockquotes quote marks

### ISSUE THREAD

**Issue by rcrphillips** [guardian/frontend#8423]
See: http://www.theguardian.com/books/booksblog/2014/aug/05/new-york-in-books-readers-picks

![screenshot 2015-02-23 17 56 35](https://cloud.githubusercontent.com/assets/2051501/6333483/6604f42e-bb85-11e4-950b-8e66c0ed5d63.png)

**Comment by OliverJAsh** [comment]
This bug happens because the quote mark pseudo-element is positioned using `position: absolute; left: 0;`, which has no respect for the `figure` which is positioned using `float: left;`.

Got a fix (floating the pseudo-element), but need to implement and test.
