### ISSUE TITLE
Win XP - firefox - ads frequently not loading

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8424]
Especially the case for ads in culture section.
I am frequently getting ads failing to load. firebug shows aborted get request which seems to relate to the ad:
Sample get request:

http://undefined/rtbads/pq?mode=s&placement=LtKGsC&adgroup=COND8RsmSWKYfiwkkkV0Gp6V9sY&blob=CjQ3NTQ1NWMzNC0wMWU3LTQ3ZmEtODMwOS1mOWYwYzk2MGUxYmYtMTQyMzY2NzAyNjI0OS0y&cachebuster=1942179865&click=http://adclick.g.doubleclick.net/aclk%253Fsa%253DL%2526ai%253DBE1Pmh3DrVKWQE-n97Qar64CgBp-qxpEGAAAAEAEg75TfITgAWP-R34jBAWC7vq6D0AqyARN3d3cudGhlZ3VhcmRpYW4uY29tugEJZ2ZwX2ltYWdlyAEJ2gEfaHR0cDovL3d3dy50aGVndWFyZGlhbi5jb20vZmlsbakCFNl81E7xuT7AAgLgAgDqAicvNTk2NjYwNDcvdGhlZ3VhcmRpYW4uY29tL2ZpbG0vZnJvbnQvbmf4AoXSHpAD0AWYA9AFqAMB0ASQTuAEAaAGINgHAA%2526num%253D0%2526sig%253DAOD64_2wd1F0TkdHV_6KquC_j1UDAbrIuw%2526client%253Dca-pub-4830087483992392%2526adurl%253D

**Comment by johnduffell** [comment]
probably broken adverts
