### ISSUE TITLE
Video page layout breaking

### ISSUE THREAD

**Issue by Pearson82** [guardian/frontend#8429]
The right hand col clashes into the main column at around 1300px. See below...

![screen shot 2015-02-24 at 14 23 32](https://cloud.githubusercontent.com/assets/3416696/6351143/f8fd473a-bc30-11e4-9c88-6fceb5a65220.png)

**Comment by ScottPainterGNM** [comment]
Hi @Pearson82 - having trouble replicating this, could you check and advise whether this is still occuring and the os/brower if so?

**Comment by Pearson82** [comment]
This still seems to be occurring for me. Mac OSX 10.10, Chrome 41.0.2272.104.

Seems to be at about 1285px 

@ScottPainterGNM

**Comment by ScottPainterGNM** [comment]
Ah yes got it that time, thanks for the extra info!

**Comment by johnduffell** [comment]
this issue hasn't been fixed yet and probably won't be in the near future so closing for now
