### ISSUE TITLE
Network front on mobile - page jumps significantly towards end of loading

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8444]
On a moto-g running android 4.4.
Loaded network front and scrolled down to an article that looked interesting
Just as I was about to select the article I wanted, the page jumped *up* higher.
As a result I selected a totally different article

Where my screen was:
![screenshot_2015-02-25-21-57-41](https://cloud.githubusercontent.com/assets/7239344/6381569/fe0e8d38-bd39-11e4-88b7-36e33c72470b.png)
.
.
.
.
.
.
Where it ends up:
![screenshot_2015-02-25-21-58-28](https://cloud.githubusercontent.com/assets/7239344/6381580/14d42334-bd3a-11e4-8759-bd2c93abdc50.png)

**Comment by paperboyo** [comment]
+ 1

A long-term problem. Not only ad-related. Not only ‘more [...]’-related. Not only lazy-loading-related. Not only on fronts. Not only on Liveblog when there is an update.

Super-annoying. Once, I ended up in an article about Fifty Shades of Grey, in breach of my internal policy!

Regards
Mateusz

**Comment by johnduffell** [comment]
yeah this is really annoying, the most obvious offender is ads at the top.  maybe we need a line in the sand to say don't change the size of anything above the last line of content after initial render :grimacing: not sure if this is a sustain thing, I think it's more high level than that.

**Comment by OliverJAsh** [comment]
> yeah this is really annoying, the most obvious offender is ads at the top. maybe we need a line in the sand to say don't change the size of anything above the last line of content after initial render  not sure if this is a sustain thing, I think it's more high level than that.

Yes, we should definitely have a design line in the sand for "no page jump".

The most recent variant of this is https://github.com/guardian/frontend/issues/10147.

The other offender on fronts is lazy loading containers, which ironically we do for performance reasons, but this actually worsens perceived performance when using the site.

@paperboyo Any other offenders you know of?

**Comment by paperboyo** [comment]
@OliverJAsh One other that comes to mind is not a bug per se but a lack of a feature, really. When a liveblog's autoupdate is on and there is a new update, the content one is reading/watching just disappears from view. One solution would be to have an overlay notification displayed (new sort, I know :cry:), that there was an update(s) that takes one to the top/bottom on click.

But the most offensive are indeed lazy loading elements and the ads/sticky situation (although, bit better now, thanks to @Calanthe).

**Comment by paperboyo** [comment]
Oh, another offender is progressive enhancement of design elements that causes reflows like e.g. of rich links...
