### ISSUE TITLE
Caption/credit not in sync for Cartoon/Picture type

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#8446]
Hello,

URL: http://www.theguardian.com/commentisfree/picture/2015/feb/26/martin-rowson-on-cover-ups-from-isis-to-nhs-cartoon

The above contains credit. It’s displayed in the lightbox, in Composer and in Preview on the main page. It’s not displayed on the main page on frontend.

Let me know, please, if I should raise it with some other team.

Regards
Mateusz

**Comment by paperboyo** [comment]
Hello,

It's still fishy. Here is another instance of changes in Composer not carried over to frontend:

Live URL: http://www.theguardian.com/commentisfree/picture/2015/mar/13/martin-rowson-media-furore-miliband-kitchens-cartoon

![cartoon-credit](https://cloud.githubusercontent.com/assets/6032869/6652216/c3df86ca-ca5f-11e4-965a-39f41e5a2ed1.png)

There was some recent work done to Picture type in Composer, maybe something fall through the cracks?

cc/ @na7hangood

Regards
Mateusz

**Comment by na7hangood** [comment]
We've only moved fields in this content type rather than introduce anything new into CAPI. It appears the CAPI structure is fine for both the examples. Let's speak to frontend and amend this issue as such.
Mateusz - I'll set something up with Patrick this week

**Comment by michaelwmcnamara** [comment]
This is superseeded by https://github.com/guardian/frontend/issues/8833

**Comment by michaelwmcnamara** [comment]
Credits are now coming through in frontend for both examples.
Looks like this was fixed but the bug never updated,
