### ISSUE TITLE
Certain Ads destroying ability to scroll on article pages

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8479]
This has been seen on Android and iOS. When certain ads display on the phone they make it almost impossible to scroll down the page. Swiping causes the page to move a tiny distance - to the point that it feels like you are reading faster than you can scroll.

Issue has occured with Ford, Asda, and Samsung ads and appears to be increasing in frequency - perhaps the offending ad style or library is becoming more popular among advertisers.
Issue does not occur when ads are switched off.

Rob saw this with an Asda ad on 2nd March and identified the issue as being "...something from this VM137 script, ..." 

![screen shot 2015-03-02 at 12 07 51](https://cloud.githubusercontent.com/assets/7239344/6466629/f9e8ef42-c1c0-11e4-9bf0-29a5b1f7c238.png)

Issue has occured again on 3rd March with Samsung ad and with Asda proto-bricks ad
When it manifests, this issue severly impacts the user experience.

![image](https://cloud.githubusercontent.com/assets/7239344/6601434/945c5c7e-c80d-11e4-8fad-fab99642cdb2.png)

**Comment by michaelwmcnamara** [comment]
Issue occurred again with a google ad. Thursday 5th March 2015.
This is increasing the fragility of our site - requires a human to notice the ad display issue and ask ad-ops to shut down the ad, plus lag time involved in getting the ad stopped.
On top of this, reported ads can only be actioned when people are in the office to action them so out of hours, weekends etc we are exposed.

**Comment by johnduffell** [comment]
need to talk to adops if there are specific ads causing a problem
