### ISSUE TITLE
Time indicator too close to an image in Liveblogs

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#8482]
Hello:

All browsers/OSes.

URL: http://www.theguardian.com/football/live/2015/mar/03/aston-villa-west-bromwich-albion-live#block-54f61374e4b0114b1f3c5c89

Image is too close to the hour time indicator of a block, like so:

![liveblog image](https://cloud.githubusercontent.com/assets/6032869/6471412/b1440c96-c1e2-11e4-9842-27c0078b06dc.PNG)

Regards
Mateusz

**Comment by johnduffell** [comment]
this issue hasn't been fixed yet and probably won't be in the near future so closing for now
