### ISSUE TITLE
Tag page by day view shows wrong day (offset by 1 day)

### ISSUE THREAD

**Issue by gidsg** [guardian/frontend#8489]
Steps to reproduce
===============
Go to: http://www.theguardian.com/sport/lawrence-donegan-golf-blog/2009/jun/12/all

Actual Results
===========
Content from Saturday 13 June 2009 
![screen shot 2015-03-04 at 15 48 22](https://cloud.githubusercontent.com/assets/1764158/6486921/20cbf828-c286-11e4-9207-fa28ddf4c331.png)

Expected Results
===============
Content from Friday 12 June 2009

**Comment by ScottPainterGNM** [comment]
Re-produced and testing other days it appears that the URL is one day behind the page content.

**Comment by davidrapson** [comment]
@ScottPainterGNM Not sure it's the URL, the url and actual content match and all articles on that page appear to be from the 12th. Might be the date on the left in the block that's out?

**Comment by ScottPainterGNM** [comment]
@davidrapson good spot, you are totally right it's an issue with the block on the left rather than URL.

**Comment by johnduffell** [comment]
this issue hasn't been fixed yet and probably won't be in the near future so closing for now

**Comment by crifmulholland** [comment]
Keeping this opened. It's a clear bug with and should be a simple fix.

**Comment by johnduffell** [comment]
indeed it is a bug, but if noone fixes it after 4 months something else is wrong

**Comment by ScottPainterGNM** [comment]
A member of the public has actually emailed about this to the dotcom feedback, somebody noticed!

**Comment by heralder99** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

heralder@naver.com 님께 보내신 메일 <Re: [frontend] Tag page by day view shows wrong day (offset by 1 day) (#8489)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
