### ISSUE TITLE
Safari - "more on this story" container at the bottom of article pages is not showing images

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8505]
On safari - page http://www.theguardian.com/technology/2014/may/27/-sp-privacy-under-attack-nsa-files-revealed-new-threats-democracy
The more on this story container near the bottom of this page does not display images.
It displays them ok on Chrome so this appears to be Safari specific.

![image](https://cloud.githubusercontent.com/assets/7239344/6507514/5ab81dfe-c34a-11e4-81c5-ba6e54f2adaa.png)

**Comment by ScottPainterGNM** [comment]
Seems to be resolved now, closing issue
