### ISSUE TITLE
Container kicker clips for 'More from the UK' as 'More from the'

### ISSUE THREAD

**Issue by gidsg** [guardian/frontend#8516]
Steps to reproduce
===============
Go to http://gu.com on iOS8 iPhone 320px width
Scroll to 'More from the UK' container
![img_0700](https://cloud.githubusercontent.com/assets/1764158/6530027/51cb5892-c425-11e4-87a1-7aaafd6e6502.PNG)

Actual Results
============
'More from the'

Expected Results
==============
Link text does not clip (restrict it to a viewable string length at 320px)

**Comment by gidsg** [comment]
@michaelwmcnamara is fixable from within the Fronts tool?

**Comment by johnduffell** [comment]
this issue hasn't been fixed yet and probably won't be in the near future so closing for now
