### ISSUE TITLE
ipad2 - iOS6 - no option to comment even though signed in

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8544]
in iOS6 Comments and the option to leave a comment are not displayed on comment pages even though I am signed in. 
This is reproduceable even with ads turned off so its definitely something to do with our core page load.

Page source on comment page in ipad2 - iOS6:

![image](https://cloud.githubusercontent.com/assets/7239344/6596486/b60291de-c7ec-11e4-9f06-922f475b1f3e.png)

**Comment by ScottPainterGNM** [comment]
Closing off as known issue with older browser/OS that comments aren't possible.
