### ISSUE TITLE
Firefox Sponsored badges display twice for sponsored recommendations on article pages

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8545]
On firefox current version (36.0.1) sponsored recommendation containers at the bottom of article pages are showing two copies of the sponsorship badge instead of one, even after clearing cache.
page is:
http://www.theguardian.com/society/2015/feb/25/scientific-brilliance-battle-dementia-ara-darzi

firebug console shows: "TypeError: can't redefine non-configurable property '__swiffy_as2_baseclass'"

![image](https://cloud.githubusercontent.com/assets/7239344/6599482/f5ba852e-c801-11e4-8cb0-7563a7c761a4.png)

**Comment by ScottPainterGNM** [comment]
Unable to replicate this on current sponsorship pages on Firefox, closing off this issue and new one to be raised if it appears again.
