### ISSUE TITLE
Rendering of twitter handle in byline is too big

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8568]
The twitter icon we display in the byline for contributors who have supplied their twitter handle is too large.
As a result it displays too low and also pushes down the time of publishing.

example can be seen on:
http://www.theguardian.com/tv-and-radio/2015/mar/11/ramsay-street-neighbours-30th-birthday
 
![image](https://cloud.githubusercontent.com/assets/7239344/6618158/686f21f4-c8b8-11e4-8163-76810d6c9626.png)

Rendering of twitter icon in tilt 3D app on firefox:
![image](https://cloud.githubusercontent.com/assets/7239344/6618178/a037e828-c8b8-11e4-9cb1-39e4d62938cb.png)

**Comment by phamann** [comment]
This has been fixed.
