### ISSUE TITLE
Links in captions displaying as html code

### ISSUE THREAD

**Issue by rcrphillips** [guardian/frontend#8582]
http://preview.gutools.co.uk/global/2015/mar/13/54ff0f3ee4b084c7b784bb80
![screenshot 2015-03-13 10 11 11](https://cloud.githubusercontent.com/assets/2051501/6636569/458880b6-c969-11e4-9cd1-fa286cd60f60.png)

**Comment by lydiasmears** [comment]
A further example of this bug can be found here:
http://www.theguardian.com/observer-ethical-awards/2015/jan/25/observer-ethical-awards-2015-categories

**Comment by OliverJAsh** [comment]
Fixed by https://github.com/guardian/frontend/pull/8584
