### ISSUE TITLE
Ad covers the image in gallery lightbox

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#8588]
Hello,

URL: [expired]

Ad covers the image in gallery lightbox, like so:

![ad-overlays-lightbox](https://cloud.githubusercontent.com/assets/6032869/6640189/859dbb8e-c98d-11e4-8bfb-6e876f4485e0.jpg)

Regards
Mateusz

**Comment by ScottPainterGNM** [comment]
@paperboyo Have you seen this come up since? Might be an ad specific issue but having trouble reproducing this one.

**Comment by paperboyo** [comment]
No, I have not... Should be safe to close if it's not a common sight... I wouldn't know.

**Comment by ScottPainterGNM** [comment]
Thanks for letting me know, will close off for now but if it re-appears someone can re-raise and we can look into.

**Comment by paperboyo** [comment]
:)

**Comment by paperboyo** [comment]
Hello,

Happened again yesterday :cry:

URL: http://www.theguardian.com/artanddesign/2015/may/22/grayson-perry-provincial-punk-review-turner-contemporary-margate

Regards
Mateusz

![grayson perry review like being trapped in a room full of trendy folk talking bollocks art and design the guardian](https://cloud.githubusercontent.com/assets/6032869/7783344/64c38196-0137-11e5-9968-72723ce59626.png)

**Comment by paperboyo** [comment]
I am unable to reopen the issue... :cry:

**Comment by ScottPainterGNM** [comment]
Issue reopened as per the above comments

**Comment by paperboyo** [comment]
Thanks, @ScottPainterGNM!

**Comment by johnduffell** [comment]
this is probably one for adops as and when it happens

**Comment by paperboyo** [comment]
Hmm, so should that be sorted on ad by ad basis?!

**Comment by johnduffell** [comment]
yeah I think we get a few badly behaved ads over the course of time, usually if I spot one I just send them a message with info about which ad it is and they sort it out!  however I'm happy to be corrected on that

**Comment by paperboyo** [comment]
Yeah, if nothing can be done in frontend to prevent that, this should indeed be closed!
