### ISSUE TITLE
No images in ‘related content’

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#8595]
Hello,

URL: http://www.theguardian.com/artanddesign/guardianwitness-blog/2015/mar/13/calling-all-art-students-alternative-general-election-posters-competition-challenge

All non-Blink browsers on Win 8.1. Lazy-loaded responsive images do not display/flash in ‘related content’ container. IE11 displays no images at all, in Firefox 37 they flash and then disappear, like so:

![image flash disappear](https://cloud.githubusercontent.com/assets/6032869/6653128/a081da98-ca7d-11e4-937c-4061ab17e5f3.gif)

Regards
Mateusz

**Comment by michaelwmcnamara** [comment]
Still occurring

**Comment by johnduffell** [comment]
this could be a polyfill problem as per #8338 the src is there at first but then is replaced by the filled src
