### ISSUE TITLE
Difficult to decipher a draw within sports league tables

### ISSUE THREAD

**Issue by jshjohnson** [guardian/frontend#8660]
".team-result--drew" background colour could do with being a little lighter.

![screen shot 2015-03-22 at 14 04 33](https://cloud.githubusercontent.com/assets/3064889/6771834/1ed18a36-d0e3-11e4-9452-14762e74fef1.png)

**Comment by johnduffell** [comment]
this is a bit of an accessibility joke and certainly needs design input, I'm surprised we don't get more complaints from people with r/g colourblindness.  howveer this hasn't been fixed so far so it's not likely to be fixed any time soon
