### ISSUE TITLE
tech-feedback looks broken from https://profile page

### ISSUE THREAD

**Issue by gidsg** [guardian/frontend#8661]
Steps to reproduce
===============
Go to: https://profile.theguardian.com/user/id/12216654
Click 'report technical issue'

Actual Results
============ 
some calls fail due to mixed content warnings
![screen shot 2015-03-23 at 09 50 27](https://cloud.githubusercontent.com/assets/1764158/6777565/acf6a4ea-d142-11e4-8902-2cf1e2eea9d6.png)
Styling looks broken
![screen shot 2015-03-23 at 09 53 35](https://cloud.githubusercontent.com/assets/1764158/6777570/b9fb05aa-d142-11e4-91bd-8f52ad1a1b76.png)

Expected Results
==============
Styling and functionality is equivalent to clicking link from Network Front. 
CC @johnduffell

**Comment by johnduffell** [comment]
this works fine now due to a redesign
