### ISSUE TITLE
Tablet breakpoint - Commercial pages - ads injected into body cause display issues

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8722]
On commercial pages, ads injected into the body are clashing with components causing awkward amounts of whitespace.

![image](https://cloud.githubusercontent.com/assets/7239344/6873495/a814afb2-d4a8-11e4-8fcc-286c54eb5222.png)

**Comment by johnduffell** [comment]
I've a feeling this was fixed, if not someone should complain again
