### ISSUE TITLE
Split facia-tool from frontend

### ISSUE THREAD

**Issue by piuccio** [guardian/frontend#8752]
I'm creating this issue to list all dependencies between facia-tool and frontend. Once we remove them, facia-tool can live on its own. I'm sure the list is incomplete

- [ ] [Fronts meta defaults](https://github.com/guardian/frontend/blob/44f530259cd8bc853fb5380481e426b7e6ed3fd0/common/app/fronts/MetadataDefaults.scala) default values of trails depending on tags.
- [ ] [Fronts meta tone](https://github.com/guardian/frontend/blob/44f530259cd8bc853fb5380481e426b7e6ed3fd0/common/app/views/support/CardStyle.scala) get the tone from the tags.
- [ ] [fixed-containers](https://github.com/guardian/frontend/blob/aa87794c85cd88c75bfcb9108a85c9b0961684eb/common/app/slices/FixedContainers.scala) and [dynamic-containers](https://github.com/guardian/frontend/blob/aa87794c85cd88c75bfcb9108a85c9b0961684eb/common/app/slices/DynamicContainer.scala) list of slices, used in the config tool
- [ ] [stories-visible](https://github.com/guardian/frontend/blob/d01b9549efaa33c8a57ed5c221598ef52113134d/facia-tool/app/controllers/StoriesVisibleController.scala) number of stories visible in a container, depends on slices.
- [ ] [thumbnails](https://github.com/guardian/frontend/blob/master/facia-tool/app/thumbnails/ContainerThumbnails.scala) shows a thumbnail of each collection type in the config tool.
- [ ] [environment](https://github.com/guardian/frontend/tree/master/common/conf/env) environment variables of different stages

**Comment by robertberry** [comment]
The thumbnails

**Comment by michaelwmcnamara** [comment]
adding reproduced tag to guard this issue from our bug pogrom.

**Comment by ScottPainterGNM** [comment]
@janua @piuccio Would this be up for closing once the transition to tools is completed?
