### ISSUE TITLE
Long headlines won't hyphenate, words brake erroneously

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#8784]
Hello,

All platforms, all breakpoints (here: but mobile BP). This is but one example, there are many other places where that happens, obviously.

![hyphenate](https://cloud.githubusercontent.com/assets/6032869/6980303/7fe4b91c-d9e7-11e4-959b-6b3db8352475.jpg)

Inserting a soft hyphen character in fronts tool works in Chrome, but doesn't in Firefox (character is displayed but does not break the word) - could that be sorted by adding some CSS property?

Maybe we should consider using CSS hyphens (working draft) standard partially supported in Firefox, Safari and IE?

Or do we have to wait for full browser support?

Regards
Mateusz

**Comment by michaelwmcnamara** [comment]
Need to get a list of what browsers and devices this effects and what proportion of our user-base they make up in order to prioritise this

**Comment by johnduffell** [comment]
this hasn't been fixed so far so it's not likely to be fixed any time soon, I know a couple of specific instances were rejigged
