### ISSUE TITLE
Inconsistently with other types, pagination unavailable for type/gallery

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#8792]
Hello,

If I want a list of all articles, ``/type/article`` (redirected to ``/articles``), gives me a paginated, chronological view.

Ditto for ``/type/picture`` (redirected to ``/pictures``).

But if I want a paginated, chronological view of all galleries, ``/type/gallery`` redirects to ``/inpictures`` which has all sorts of containers, but no paginated, chronological view ("latest" container doesn't count as there is no pagination to see older items). One way to get what I want, consistently with above type searches, is to manually add a pagination ``/inpictures?page=1``.

Also, inconsistently with, lat's say, ``/world``, ``/inpictures`` has no ``/all`` user-accessible link at the bottom of the page in Topics.

Regards
Mateusz

**Comment by michaelwmcnamara** [comment]
Confirmed - type/gallery redirects to /inpictures which is a curated front.
Response code for /type/gallery is 302 which suggests this is a policy choice rather than just failing soft due to a missing page.
I will investigate and confirm if this configuration is deliberate.

**Comment by paperboyo** [comment]
Thanks a lot, @michaelwmcnamara! Don't you think that, independently of your investigation, it would be a good idea to add "All today's stories" link (``http://www.theguardian.com/inpictures/all``) to the bottom of ``http://www.theguardian.com/inpictures`` just as on every other front (bar network front)?

Regards
Mateusz

**Comment by johnduffell** [comment]
this hasn't been fixed so far so it's not likely to be fixed any time soon
