### ISSUE TITLE
RSS always has some articles with timestamp 2014-12-16T14:13:53Z (and sometimes 2015-04-16T09:12:35Z)

### ISSUE THREAD

**Issue by mhart** [guardian/frontend#8810]
This URL for example:

http://www.theguardian.com/world/rss

Stories keep appearing in this feed that have `<pubDate>Tue, 16 Dec 2014 14:13:53 GMT</pubDate>` and `<dc:date>2014-12-16T14:13:53Z</dc:date>` – with this exact timestamp – whereas the stories are clearly not from that date (eg `/us-news/2015/apr/08/rand-paul-abortion-foreign-policy-interviews`)

These have been appearing in the feed for a few months now – and it messes with most (if not all) RSS readers as they think the articles are actually from this date.

**Comment by mhart** [comment]
To add to the mystery, a bunch have now appeared with dates all on Apr 16 – although the stories are not. Eg:

```xml
<pubDate>Thu, 16 Apr 2015 09:12:35 GMT</pubDate>
<guid>
/uk-news/2015/apr/26/mixed-heritage-britain-casual-racism-less-acceptable-than-ever
</guid>
<dc:creator>Hugh Muir</dc:creator>
<dc:date>2015-04-16T09:12:35Z</dc:date>
```

**Comment by OliverJAsh** [comment]
I'm unable to reproduce this. @michaelwmcnamara Can you show me what you saw?

**Comment by mhart** [comment]
There indeed appears to be no April 16 stories at the moment – but there is a Dec 16 one (just do a search in the XML linked above for "16 Dec 2014")

**Comment by mhart** [comment]
![screen shot 2015-04-27 at 11 10 46 am](https://cloud.githubusercontent.com/assets/367936/7350591/23205e76-ecce-11e4-8b0f-a50efda6ecb1.png)

**Comment by mhart** [comment]
There are currently (at 2015-04-29T19:11:00Z) four entries with `16 Dec` and three with `16 Apr`

Let me know if you need more help reproducing this, I'm happy to post the entire RSS XML or whatever – but following that link should yield results most of the time.

![screen shot 2015-04-29 at 3 10 03 pm](https://cloud.githubusercontent.com/assets/367936/7399178/e2864d2a-ee81-11e4-9c74-5ce5e5d2fe0c.png)

**Comment by mhart** [comment]
(note that the 16 Apr entry above also has the same timestamp as the one I commented about previously too: `2015-04-16T09:12:35Z`)

**Comment by janua** [comment]
@mhart Is this still an issue? I can't seem to reproduce this. I have checked the whole feed for weird dates not matching the article.

I have done work in RSS and other things recently that may have affected and fixed the date. Some of the changes were far upstream, so I am unable to say if they have directly affected the `pubDate`.

**Comment by mhart** [comment]
No, haven't seen it for ages actually – thanks for that!

**Comment by janua** [comment]
Thanks @mhart
