### ISSUE TITLE
Another icons fail - comment quotes over analysis (?)

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#8818]
Hello,

As seen on Network front today:

![quotes-fail](https://cloud.githubusercontent.com/assets/6032869/7083333/4509ef62-df58-11e4-9475-666471f25ed4.jpg)

Regards
Mateusz

p.s. maybe we should think of creating a comprehensive colour schemes test page, in the spirit of http://m.code.dev-theguardian.com/cutouttest (which we still would better act upon)

**Comment by michaelwmcnamara** [comment]
Issue still occurring.
To reproduce: Add an analysis to a container, select "quote headlines" option and save & launch

**Comment by paperboyo** [comment]
Looks like it's been fixed:
![icon fix](https://cloud.githubusercontent.com/assets/6032869/8508264/0000b58e-2262-11e5-869c-87d2fe2d9e94.jpg)
[icon, not Greek crisis]

Closing.
