### ISSUE TITLE
IE11 - liveblog - key events overlaps with commenting and sharing icons

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8876]
In IE11 - key events are displaying on top of the commenting and sharing icons instead of below these icons.
seen on www.theguardian.com/politics/live/2015/apr/14/election-2015-live-conservative-manifesto-david-cameron-right-to-buy but occurs on all liveblogs that have a key events listing.

![image](https://cloud.githubusercontent.com/assets/7239344/7162368/1d95a290-e38c-11e4-8c18-5d6b47a7dfb3.png)

**Comment by robertberry** [comment]
This should have been fixed by https://github.com/guardian/frontend/pull/8879

See CODE at the moment
