### ISSUE TITLE
FF -  popular in podcast container does not show images

### ISSUE THREAD

**Issue by sndrs** [guardian/frontend#8943]
Windows 7 - Firefox latest (with latest flash) 

On audio pages, popular in podcast container does not show images. see: http://www.theguardian.com/environment/audio/2015/apr/20/podcast-biggest-story-economics-episode5

**Comment by paperboyo** [comment]
Yeah. @rich-nguyen fought these gremlins bravely, but some eggs must have survived...

Below latest release FF on 10.9.3 (note other containers, happens on Win 8.1 latest beta as well):

![fail-images-not-showing](https://cloud.githubusercontent.com/assets/6032869/7254886/9e5a4696-e83d-11e4-9537-9e8fdd891c5f.jpg)

**Comment by paperboyo** [comment]
Related? https://github.com/guardian/frontend/issues/8595

**Comment by michaelwmcnamara** [comment]
Still occurring - images display for a fraction of a second on load then disappear.
gif from #8595 below is a perfect example of what it looks like
![image](https://cloud.githubusercontent.com/assets/7239344/7295006/3a13c02c-e9aa-11e4-9864-d2b6b818342b.png)

**Comment by johnduffell** [comment]
must be yet another image polyfill problem?  I'm sure I've spotted a few similar reports around this time

**Comment by paperboyo** [comment]
Yes. Safe to close as long as https://github.com/guardian/frontend/issues/8338 is kept open. This one contains a handy GIF movie to illustrate the disappearance (is linked from https://github.com/guardian/frontend/issues/8338).
