### ISSUE TITLE
Firefox 26 - Video Play Button Misaligned

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#8947]
On the network fronts when in Firefox 26 the video play button appears near to the lefthand corner of the video preview, once selected it moves to the centre as the video loads up.

![screen shot 2015-04-21 at 16 25 34](https://cloud.githubusercontent.com/assets/11922253/7255706/dd74608c-e842-11e4-88fe-1ef92f76bb9b.png)

**Comment by johnduffell** [comment]
noone's fixed it yet, so it's probably not going to be fixed any time soon
