### ISSUE TITLE
cutouts in rich links should go through the resizer

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#8948]
Cutout in the article link below displaying pixelated in IE11 - displays fine in fronts

http://www.theguardian.com/football/blog/2015/apr/17/gareth-bale-galactico-premier-league-real-madrid

![screen shot 2015-04-21 at 16 38 26](https://cloud.githubusercontent.com/assets/11922253/7255973/a29cee8c-e844-11e4-9674-8dcdd421f6cc.png)

**Comment by paperboyo** [comment]
Confirmed in IE 11 on WIn 8.1. Also these (in rich links?) are not ran through the resizer (which may or may not fix the issue with crappy interpolation algorithm).

**Comment by johnduffell** [comment]
could be a good win for page weight - these should be put through the resizer

**Comment by jennysivapalan** [comment]
Confirmed on IE 11 Win 8.1 that the rich cut out is no longer pixelated! 
![fixed](https://cloud.githubusercontent.com/assets/944375/9272883/b0717ab6-427e-11e5-8967-296c191d1ae6.png)

(Okay this print screen looks rubbish but it is much better on the browser.)

**Comment by paperboyo** [comment]
:clap: Thanks! :smiley:
