### ISSUE TITLE
All version of Internet Explorer - Issue with Thrasher

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#8950]
On the network fronts - there are a number of issues with the Thrasher image across IE, the listen now button only displays an arrow and is longer then on other operating systems, also the logo and quote are layered rather then separated out. Examples below:

IE:
![screen shot 2015-04-21 at 17 00 39](https://cloud.githubusercontent.com/assets/11922253/7256576/caace55a-e847-11e4-97a8-419f5a638676.png)

Chrome (Same as on other browsers):
![screen shot 2015-04-21 at 17 01 45](https://cloud.githubusercontent.com/assets/11922253/7256589/e34d63be-e847-11e4-9509-46e1cfbd350c.png)

**Comment by paperboyo** [comment]
Confirmed in IE 11 om Win 8.1.

**Comment by johnduffell** [comment]
this is an issue with the thrasher, not sure if the interactives team do these or a dedicated team
