### ISSUE TITLE
Nexus 7 - Rotation Issue with MPU within an article

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#8952]
When viewing an article in portrait mode on the Nexus 7, the ad is cut off as per the screenshot. However, if you rotate to landscape and back again then the ad is aligned correctly.

![screenshot_2015-04-20-15-08-25](https://cloud.githubusercontent.com/assets/11922253/7256799/3bb3a2ba-e849-11e4-99fa-582892d421e7.png)

**Comment by johnduffell** [comment]
noone's fixed it yet, so it's probably not going to be fixed any time soon
