### ISSUE TITLE
Safari and iPad - network front - large number of console errors when page is loaded

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8953]
When I access the network front using safari on a mac or an iPad, I receive a large number of errors of the type:

"Blocked a frame with origin "http://ad.doubleclick.net" from accessing a frame with origin "http://www.theguardian.com". Protocols, domains, and ports must match.

full list or errors follows:

[Error] Blocked a frame with origin "http://ad.doubleclick.net" from accessing a frame with origin "http://www.theguardian.com". Protocols, domains, and ports must match.
	(anonymous function) (lidar.js, line 82)
	global code (lidar.js, line 105)
[Error] Blocked a frame with origin "http://ad.doubleclick.net" from accessing a frame with origin "http://www.theguardian.com". Protocols, domains, and ports must match.
	xa (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 7)
	ge (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 55)
	F (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 143)
	xh (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 140)
	Dh (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 143)
	V (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 144)
	Bg (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 100)
	Cg (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 109)
	Dg (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 109)
	(anonymous function) (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 160)
	global code (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 160)
[Error] Blocked a frame with origin "http://ad.doubleclick.net" from accessing a frame with origin "http://www.theguardian.com". Protocols, domains, and ports must match.
	hc (lidar.js, line 22)
	yf (lidar.js, line 96)
	(anonymous function) (lidar.js, line 9)
	Pa (lidar.js, line 8)
	(anonymous function) (lidar.js, line 9)
[Error] Blocked a frame with origin "http://ad.doubleclick.net" from accessing a frame with origin "http://www.theguardian.com". Protocols, domains, and ports must match.
	ne (lidar.js, line 83)
	yf (lidar.js, line 96)
	(anonymous function) (lidar.js, line 9)
	Pa (lidar.js, line 8)
	(anonymous function) (lidar.js, line 9)
[Error] Blocked a frame with origin "http://ad.doubleclick.net" from accessing a frame with origin "http://www.theguardian.com". Protocols, domains, and ports must match.
	yf (lidar.js, line 96)
	(anonymous function) (lidar.js, line 9)
	Pa (lidar.js, line 8)
	(anonymous function) (lidar.js, line 9)
[Error] Blocked a frame with origin "http://ad.doubleclick.net" from accessing a frame with origin "http://www.theguardian.com". Protocols, domains, and ports must match.
	oa (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 116)
	Qg (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 111)
	K (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 153)
	mh (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 151)
	vb (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 151)
	(anonymous function) (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 20)
	qc (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 22)
	n (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 22)
	$b (dfa7banner_flash_inpage_rendering_lib_200_76.js, line 17)
	PromiseResolutionHandlerFunction ([native code], line 0)
[Error] Blocked a frame with origin "http://ad.doubleclick.net" from accessing a frame with origin "http://www.theguardian.com". Protocols, domains, and ports must match.
	hc (lidar.js, line 22)
	yf (lidar.js, line 96)
	(anonymous function) (lidar.js, line 9)
	Pa (lidar.js, line 8)
	(anonymous function) (lidar.js, line 9)
[Error] Blocked a frame with origin "http://ad.doubleclick.net" from accessing a frame with origin "http://www.theguardian.com". Protocols, domains, and ports must match.
	ne (lidar.js, line 83)
	yf (lidar.js, line 96)
	(anonymous function) (lidar.js, line 9)
	Pa (lidar.js, line 8)
	(anonymous function) (lidar.js, line 9)
[Error] Blocked a frame with origin "http://ad.doubleclick.net" from accessing a frame with origin "http://www.theguardian.com". Protocols, domains, and ports must match.
	yf (lidar.js, line 96)
	(anonymous function) (lidar.js, line 9)
	Pa (lidar.js, line 8)
	(anonymous function) (lidar.js, line 9)
[Error] Blocked a frame with origin "http://ad.doubleclick.net" from accessing a frame with origin "http://www.theguardian.com". Protocols, domains, and ports must match.
	hc (lidar.js, line 22)
	yf (lidar.js, line 96)
	(anonymous function) (lidar.js, line 9)
	Pa (lidar.js, line 8)
	(anonymous function) (lidar.js, line 9)
[Error] Blocked a frame with origin "http://ad.doubleclick.net" from accessing a frame with origin "http://www.theguardian.com". Protocols, domains, and ports must match.
	ne (lidar.js, line 83)
	yf (lidar.js, line 96)
	(anonymous function) (lidar.js, line 9)
	Pa (lidar.js, line 8)
	(anonymous function) (lidar.js, line 9)
[Error] Blocked a frame with origin "http://ad.doubleclick.net" from accessing a frame with origin "http://www.theguardian.com". Protocols, domains, and ports must match.
	yf (lidar.js, line 96)
	(anonymous function) (lidar.js, line 9)
	Pa (lidar.js, line 8)
	(anonymous function) (lidar.js, line 9)
[Error] Blocked a frame with origin "http://ad.doubleclick.net" from accessing a frame with origin "http://www.theguardian.com". Protocols, domains, and ports must match. (x2)

![image](https://cloud.githubusercontent.com/assets/7239344/7257194/b3fb3eca-e84b-11e4-9a68-471b60e5f71d.png)

**Comment by johnduffell** [comment]
noone's fixed it yet, so it's probably not going to be fixed any time soon
