### ISSUE TITLE
iPad Air - uk sport front - mpu displays with incorrect alignment

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8954]
On the uk sport front, the mpu is is displaying vertically aligned with the top of the slot instead of in the middle of the slot.

![image](https://cloud.githubusercontent.com/assets/7239344/7257366/1838c7bc-e84d-11e4-8d65-47eebeb73d51.png)

**Comment by johnduffell** [comment]
noone's fixed it yet, so it's probably not going to be fixed any time soon
