### ISSUE TITLE
iPad air - videos on fronts require 2 taps to play

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8956]
Find a video on a front.
Attempt to play it

first tap is ignored
second tap plays the video.

Debugger shows there are a large number of errors of the type:
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (crop_640x360.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (crop_KP_153143_640x360.png, line 0)

![image](https://cloud.githubusercontent.com/assets/7239344/7257562/960092c8-e84e-11e4-9d21-082c1987bbe9.png)

**Comment by johnduffell** [comment]
noone's fixed it yet, so it's probably not going to be fixed any time soon
