### ISSUE TITLE
iPad air - suspected lazy-loading issue - mpu in most popular container does not display

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8957]
If I load a page and scroll down to the most popular container, the ad slot does not load an ad.
If I refresh the page with the focus on the most popular container the ad loads correctly
If I move the focus back to the top of the page and reload then scroll down again to the most popular container, the ad slot is once again empty.

Suspect there is a problem here with lazy loading - it should be triggering the load of an ad to this slot when it comes into focus, but it is not.

Issue occurs fro both fronts and content pages.

![image](https://cloud.githubusercontent.com/assets/7239344/7257681/5bab3140-e84f-11e4-8ca8-2f8db6bed833.png)

**Comment by patstirling** [comment]
Is this just on iPad Air Mike or does it happen on other devices?

**Comment by johnduffell** [comment]
there's a card open on the board so no need to track this here too
