### ISSUE TITLE
Card colours are inconsistent and their hover states broken when cutouts used

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#8963]
Hello,

That must be the lowest priority issue from me :) [EDIT: Not anymore it's not! See last comment]

Currently, trail pictures and the rest of tiles/cards/whatevah do not darken on hover in a consistent manner. If the image has exactly the same background colour as the tile (not that this is a good future-proof policy...), on hover - it doesn't anymore. If the image has a transparent background (that would be a much better future-proof policy), the effect is infinitely worse (see Feature tone below). We should make darkening (or any other effect) be applied consistently.

![trails ovelay](https://cloud.githubusercontent.com/assets/6032869/7271332/892151fa-e8da-11e4-9c01-98dbd2b0141b.gif)

Regards
Mateusz

**Comment by michaelwmcnamara** [comment]
We may need some input from design to pursue this one.

**Comment by paperboyo** [comment]
Hi,

Also, recently introduced slideshow is not consistent with the rest. Images do not darken at all, only during the transition...

Regards
Mateusz

**Comment by johnduffell** [comment]
since no-one has looked at this yet, it probably won't be looked at soon

**Comment by paperboyo** [comment]
Hi,

Soon Grid will be serving transparent images, so the use-case for what's shown on the left of the above GIF will grow in importance...

Regards
Mateusz

**Comment by paperboyo** [comment]
Issue visible live on current CODE network front in the web we want container and below.

**Comment by paperboyo** [comment]
- [ ] card colours are inconsistent between the visible area and the area where the trail picture sits
- [ ] they darken inconsistently on hover

Change to this may also affect how slideshow transitions look on cards (background is showing through then, probably shouldn't).

![cutouts coming](https://cloud.githubusercontent.com/assets/6032869/15546609/70dadbf4-2298-11e6-81f8-578c06e6bc14.gif)

**Comment by SiAdcock** [comment]
@paperboyo do you have any idea if this was fixed, intentionally or otherwise, during Garnett?

**Comment by paperboyo** [comment]
@SiAdcock Not fixed as far as I can tell, no. Maybe something to have at the back of our heads when building guui? Test images are at https://preview.gutools.co.uk/training-site-2 (one is an SVG).

Somehow, I cannot replace an image from Grid there (getting 403 on any cutout or non-cutout 5:3s; https://preview.gutools.co.uk/training-site-2), so cannot test any new ones.

**Comment by paperboyo** [comment]
Update: now the front above shows the problem: birds in the special container are a cutout. Dragging from Grid to Replace image works, but pasting an URL doesn’t…

**Comment by SiAdcock** [comment]
Nice one, thanks @paperboyo, I shall investigate!

**Comment by paperboyo** [comment]
Thank you, @SiAdcock!
There is more things worth keeping at the back of the head while creating a Brave New World: [HiDPI support](https://trello.com/c/cWSiXgfV/87-all-imagery-to-properly-use-master-assets-and-resizer-responsively) for ALL imagery (possibly even interactives/thrashers?), supporting cutouts and SVGs everywhere and consistently, maybe supporting [height-by-breakpoints](https://github.com/guardian/frontend/issues/12216#issuecomment-196869603), too? Making sure any use of fluid crops (immersive, hero etc.) is as predictable for everybody as possible. Possibly, many others too. Plus, not re-introducing all the bugs we have never fixed yet 😜.

**Comment by oliverlloyd** [comment]
[This PR](https://github.com/guardian/dotcom-rendering/pull/1023) implement hover styles on card images for DCR using an approach that deals with the transparency issue

**Comment by paperboyo** [comment]
Closing as fixed in DCR. Thank you. @oliverlloyd!
