### ISSUE TITLE
IE8 - Guardian Logo not displaying correctly

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#8965]
On all fronts on IE8 the guardian logo is only displaying 'the' with the name obscured as per the below screenshot (produced on Windows XP)

![screen shot 2015-04-22 at 11 35 00](https://cloud.githubusercontent.com/assets/11922253/7272524/6b5dc6ae-e8e3-11e4-90a8-1c79233e6465.png)

**Comment by OliverJAsh** [comment]
Can no longer reproduce.
