### ISSUE TITLE
IE8 - MPU ad cut

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#8969]
In IE8 (produced on Windows XP) the most popular MPU ad appears to load correctly but then switches to a version where most of the ad is cut from the display. This appears on the culture front next to 'talking points' and looks like the container is too small rather then the ad itself (reproduced across numerous ads).

![screen shot 2015-04-22 at 11 54 23](https://cloud.githubusercontent.com/assets/11922253/7273035/b56fc55e-e8e7-11e4-803e-4b173984502d.png)

**Comment by johnduffell** [comment]
since no-one has looked at this yet, it probably won't be looked at soon
