### ISSUE TITLE
IE8 - Key Events not displayed on live blog

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#8970]
On a live blog the key events area in the left hand column is blank, there is a 'show' button available but this doesn't appear to display the events when selected. (Produced on Windows XP)

![screen shot 2015-04-22 at 12 13 10](https://cloud.githubusercontent.com/assets/11922253/7273170/e3d6fc7c-e8e8-11e4-99a0-066eb6cfce42.png)

**Comment by johnduffell** [comment]
probably needs to cut the mustard to get these dynamic bits
