### ISSUE TITLE
IE8 Live Blog - Show Button

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#8971]
In the Live Blogs there is a button labelled show above the updates, this doesn't appear to perform an action when selected though? Similar issue raised with the key events section under #8970

![screen shot 2015-04-22 at 12 13 10](https://cloud.githubusercontent.com/assets/11922253/7273244/9b528ce0-e8e9-11e4-8bda-76ab097dbd36.png)

**Comment by johnduffell** [comment]
ie8 doesn't cut the mustard so the JS won't run
