### ISSUE TITLE
Front description should align right on all breakpoints except desktop

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8974]
From Katherine Le Ruez 
I'm trying to add a description to the Sport front on code but it aligns oddly at different breakpoints:

http://m.code.dev-theguardian.com/uk/sport

I've confirmed with Alex that the description should align right on all breakpoints (except desktop, where it sits underneath the container title).

Please could this be fixed?

**Comment by michaelwmcnamara** [comment]
![image](https://cloud.githubusercontent.com/assets/7239344/7274881/726f135c-e8f8-11e4-9617-8c9a73f49718.png)

![image](https://cloud.githubusercontent.com/assets/7239344/7274896/86fcc71a-e8f8-11e4-9d3c-b0ba146d1a6d.png)

![image](https://cloud.githubusercontent.com/assets/7239344/7274924/b9c025a2-e8f8-11e4-9147-b7912e7afe80.png)

**Comment by JustinPinner** [comment]
Closing as fix now deployed to prod.
