### ISSUE TITLE
Dream-Snaps are being de-duped if story appears higher on front

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8979]
Dream Snaps are being de-duped if story that is pulled in is already visible higher in the front

eg on http://www.theguardian.com/us/commentisfree the dreamsnap for Steven W Thrasher is hidden because the same article is already present in the #FergusonNext container.

Shot of the dreamsnaps in the editorial tool:
![image](https://cloud.githubusercontent.com/assets/7239344/7279197/12900d5a-e912-11e4-9369-5041d3658e82.png)

Screenshot of the same container in facia - minus Steven's dreamsnap:
![image](https://cloud.githubusercontent.com/assets/7239344/7279224/42252212-e912-11e4-9efc-fb8b377c013a.png)

**Comment by piuccio** [comment]
I think this has fixed few minutes agoby @stephanfowler

**Comment by stephanfowler** [comment]
Yep, being fixed (revert of an earlier PR)
