### ISSUE TITLE
Chrome on OSX Yosimite - border around comment box is not visible

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8980]
The border around the comment box is invisible when viewed on my chrome browser.
I am running chrome: 42.0.2311.90 (64-bit) on OSX Yosimite.

Looks fine on safari, firefox and also on windows 7 chrome IE and firefox, but broken on chrome running on mac.

tres weird!

example found on http://www.theguardian.com/uk-news/2015/apr/22/pret-free-coffee-people-they-like-discrimination-or-nice-gesture
![image](https://cloud.githubusercontent.com/assets/7239344/7279978/94993a42-e917-11e4-9cc9-12649c16d1c5.png)

**Comment by OliverJAsh** [comment]
I can't seem to reproduce this?

![image](https://cloud.githubusercontent.com/assets/921609/7346411/e924e1a8-ecd5-11e4-8187-ee99f18b7131.png)


OS X 10.10.3, Chrome 42.0.2311.90 (64-bit)

**Comment by johnduffell** [comment]
this is  if your browser isn't at 100%, the px to rem library turns to the number of rem that takes it below 1 pixel, and then it's rounded to zero
