### ISSUE TITLE
Live Scores on IPhone 5C -Aggregate score overlap

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#8987]
When viewing the live scores on IPhone 5C on the football page the aggregate scores are overlapping with the main score details on this breakpoint

![screen shot 2015-04-23 at 11 51 24](https://cloud.githubusercontent.com/assets/11922253/7296380/084dbf54-e9b7-11e4-8613-8bf3dca58ed6.png)

**Comment by johnduffell** [comment]
since no-one has looked at this yet, it probably won't be looked at soon
