### ISSUE TITLE
Overlap of title & updated information in Dynamic/Fast Container on mobile breakpoint

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#8990]
If the 'show latest update in header' option is selected in the fronts config for container type dynamic/fast then the time last updated overlaps with the title on mobile breakpoints.

![screen shot 2015-04-23 at 14 44 30](https://cloud.githubusercontent.com/assets/11922253/7298439/7b467c3e-e9c7-11e4-9bd6-2a882aff6a43.png)

**Comment by phamann** [comment]
This should be fixed by #8988

**Comment by johnduffell** [comment]
it's either fixed or it probably won't be looked at soon
