### ISSUE TITLE
Breaking News - Older Mobile Devices

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#9003]
Raised by User Help:

Browser: Safari
IOS version: 7.1.1

When breaking news popup appears on users IPhone 4 he has great difficulty dismissing it which means the news is unreadable, dismiss button is very unresponsive and keeps sending him to other pages. Each time he then brings the browser back up the alert then reappears and starts the cycle over making the site unreadable.

**Comment by ScottPainterGNM** [comment]
@JustinPinner haven't been able to reproduce as no breaking news alert currently, will take another look on Monday.

**Comment by ScottPainterGNM** [comment]
Cannot reproduce due to a lack of hardware with the same IOS, IPhone 4 with IOS5 didn't manage to load any breaking news at all and IPhone 4S running both IOS 7&8 worked without issue.

**Comment by paperboyo** [comment]
Oh! That has happened to me on my ancient Galaxy SII in latest Chrome beta more than enough times! In general, when the site is slow and the user quick - these can and will happen. Annoying as hell, but if there is something specific that can be done... I wouldn’t know. It would be cool to somehow make sure that *all* actionable banners/notifications appear only _after they can be reliably interacted with_.

Possibly related to https://github.com/guardian/frontend/issues/8444?

Regards
Mateusz

**Comment by ScottPainterGNM** [comment]
Reproduced across Galaxy SII and Windows 8 Phone as well, a similar issue arises with the advertisement for the app having a very small close button which is hard to select. The combination means that the site is very hard to read.

**Comment by johnduffell** [comment]
since no-one has looked at this yet, it probably won't be looked at soon
