### ISSUE TITLE
Toggle match stats on mobile breakpoint not working

### ISSUE THREAD

**Issue by phamann** [guardian/frontend#9006]
The heading toggle to show/hide the match stats and table data is not functioning on the mobile breakpoint.

Steps to reproduce:
Open match live blog on mobile device or browser breakpoint. Attempt to close the match stats data using arror.button on right hand side.

http://www.theguardian.com/football/live/2015/apr/26/everton-v-manchester-united-premier-league-live

First seen on: Chrome, Android 4.2, Nexus 5

**Comment by johnduffell** [comment]
can't see this button myself, and since no-one has looked at this yet, it probably won't be looked at soon
