### ISSUE TITLE
Deprecate RequireJS and complete migration to SystemJS

### ISSUE THREAD

**Issue by OliverJAsh** [guardian/frontend#9007]
- [ ] Run all tests through karma-jspm. Currently only crosswords are being run through this, whereas everything else is ran through karma-requirejs. @rich-nguyen and I started this and can share our patches, but the showstopper was Squire—a dependency injector we use in our tests, specifically built for RequireJS. According to @guybedford it should be possible to fork Squire to work with System instead of Require.

**Comment by guybedford** [comment]
It may also be worth considering the use of karma-systemjs here as well - https://github.com/rolaveric/karma-systemjs. The SystemJS one runs through the same plugin system in Karma as the RequireJS one, so might be more similar in terms of configuration. I haven't looked into the details or done a full comparison of the two though.

**Comment by OliverJAsh** [comment]
We're actually already using a heavily forked version of `karma-jspm`, after reviewing both `karma-jspm` and `karma-systemjs`. Neither are great if I'm honest. We'll work to push our changes upstream.
