### ISSUE TITLE
End slate shown for the video embedded on front

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#9008]
Hello,

This should not be happening at all or the end slate styling should be responsive, I believe:

![end slate](https://cloud.githubusercontent.com/assets/6032869/7342293/a300af3a-eca9-11e4-815b-db675d271ab1.PNG)

(related https://github.com/guardian/frontend/pull/8237)

Regards
Mateusz

**Comment by paperboyo** [comment]
Thanks, @ScottPainterGNM! Here (https://github.com/guardian/frontend/issues/8119#issue-56099519) are just some screen shots would someone ever wanted to have a look at syling fixes for endslates...

**Comment by robertberry** [comment]
We didn't used to ever show the end slate on fronts, as there's not really room for it apart from on full-width cards (`FullMedia50`, `FullMedia75`, and `FullMedia100`). @johnduffell added something to make it appear for these cards (on which it renders OK) and some for which it doesn't (`ThreeQuarters`, `ThreeQuartersRight`, and `Half`).

Unless anyone has any objections I'll only make it show for the full width ones.

**Comment by johnduffell** [comment]
:+1: as discussed the click through for end slates is quite good but squeezing 4 on looks naff.  In the absence of unlimited time it's indeed best to turn it off. Unless @crifmulholland wants to weigh in!

**Comment by paperboyo** [comment]
Yeah, ideally we should make end slates fully responsive. But, maybe, before we can do that (hopefully, sooner than _unlimited_ :wink:), we should turn them off as @johnduffell suggests.

**Comment by robertberry** [comment]
OK that is out now
