### ISSUE TITLE
Same video appears three times in Popular videos

### ISSUE THREAD

**Issue by theefer** [guardian/frontend#9018]
See on http://www.theguardian.com/world/video/2015/apr/27/nepal-earthquake-avalanche-everest-base-camp-video

![screenshot-popular-video](https://cloud.githubusercontent.com/assets/36964/7347810/0a5bbf82-ece4-11e4-9033-b42a9d5aec11.png)

**Comment by phamann** [comment]
/cc @tackley @philwills 

We can dedupe these but may be good to do it at the source?
