### ISSUE TITLE
&amp; in tags below article

### ISSUE THREAD

**Issue by janua** [guardian/frontend#9020]
There is an `&amp;` appearing in the tags below an article.

Originally, the tone in the content API had the literal string `q &amp; a`, but this is since been fixed.

On the top left of [here](http://www.theguardian.com/tone/q-and-as), it had the `&amp;` but has now since disappeared because of the fix.

But it remains at the bottom of article as `More q &amp; a`;
http://www.theguardian.com/teacher-network/2015/apr/24/parental-engagement-schools-tips-tricks-live-chat

**Comment by mchv** [comment]
Seems working fine now for me, caching issue I supposed

**Comment by janua** [comment]
@mchv Thanks! I've just been Firefox'd, with its crazy seemingly aggressive caching!
