### ISSUE TITLE
Preview for article is not loading on older Mac OS

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#9024]
Preview for article id /content/553e15e9e4b0a2888e2f3dfc  is not loading on a Mac in one of the pods.
Mac is running Chrome Version 41.0.2272.89 (64-bit) and OS X 10.8.5 (Mountain Lion).

Even on more modern browsers and operating systems, a large number of errors show up in the debugger - possible the browser is just not tolerating these errors as well as later versions do.

![image](https://cloud.githubusercontent.com/assets/7239344/7353444/84b76200-ed0b-11e4-9cdf-8462dafb6a49.png)

**Comment by michaelwmcnamara** [comment]
Issue found by Hannah Jane Parkinson.

**Comment by johnduffell** [comment]
since no-one has looked at this yet, it probably won't be looked at soon
