### ISSUE TITLE
Cut out overlaps link text in rich link

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#9025]
Hello,

another instance when a ``z-index`` adjustment is necessary. Without adding a very thin border/shadow to the text consistent with a tone background colour this is not 100% safe (depending on cut out’s colours) but I don’t know what would be performance implications of all that text shadows...

As seen on http://www.theguardian.com/money/reality-check/2015/apr/27/will-scrapping-stamp-duty-first-time-buyers-push-up-house-prices

![rich link cut out](https://cloud.githubusercontent.com/assets/6032869/7359745/fb311ace-ed39-11e4-9bb4-631962d77db8.PNG)

Related to https://github.com/guardian/frontend/pull/9004, https://github.com/guardian/frontend/issues/8935, https://github.com/guardian/frontend/pull/9017 and, finally, https://github.com/guardian/frontend/issues/7552.

Regards
Mateusz

**Comment by johnduffell** [comment]
since no-one has looked at this yet, it probably won't be looked at soon
