### ISSUE TITLE
Expired content needs to be distinguished from 410's

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#9042]
From Sian Cain:
Due to the volume of enquiries about expired content, the readers' editor team have requested that a unique redirect page be made for expired content, to distinguish it from the 410 message ("this content has been removed for a rights/legal/other issue").

The rights team and the readers' editor have provided the following wording for the expiry redirect page:

"
Sorry - the page you are looking for has been removed

This content has been removed as our licence to display this material has expired.

To continue reading, please visit The Guardian's home page.
"

Can anyone confirm this can be done for expired content and provide a rough ETA? Chris Elliott is interested in writing about this in an upcoming column for the paper, so if it could be implemented as soon as possible, editorial will be very grateful.

According to Lydia Smears, has been done at the CAPI end to distinguish between expired content and 401, however we need front end to return a different wording for the "expired" removals.

**Comment by JustinPinner** [comment]
This sounds more like a feature request to me. Or at least I don't think it's a bug anyway.

**Comment by johnduffell** [comment]
since no-one has looked at this yet, it probably won't be looked at soon
