### ISSUE TITLE
Multiple contributors in facia tool

### ISSUE THREAD

**Issue by piuccio** [guardian/frontend#9043]
When selecting `cutout image` for an article that has more than one contributor, `facia` will show no image, while `facia-tool` will show the first contributor image.

They should have the same behaviour, and probably the best is to show no cutout image.

It should still be possible to override the image with a user defined value.

**Comment by robertberry** [comment]
@piuccio It ought to change in Facia Tool. All the downstream applications only display the contributor image automatically if there is only a single contributor.

**Comment by johnduffell** [comment]
since no-one has looked at this yet, it probably won't be looked at soon - facia is the requested behaviour, and facia tool probably wasn't updated at the time.

**Comment by piuccio** [comment]
I'd like to keep it open. I'll work on it eventually
