### ISSUE TITLE
Comment icon is blue for all tones

### ISSUE THREAD

**Issue by Pearson82** [guardian/frontend#9047]
Seems to be missing the correct tonal colour value for the appropriate tone. 

Also alignment looks like it's been thrown out. 

![screen shot 2015-04-28 at 16 04 48](https://cloud.githubusercontent.com/assets/3416696/7372758/7a12bcea-edc0-11e4-9bd0-1ee012527145.png)

**Comment by ScottPainterGNM** [comment]
Just added you @OliverJAsh as know you were looking at this but an issue has been raised already on Github

**Comment by OliverJAsh** [comment]
Fix going out now
