### ISSUE TITLE
Comments box on article looks to be slightly misaligned

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#9051]
On an article the icon and word comments seem to be aligned to the right which leaves a space between the shares details

![screen shot 2015-04-28 at 16 49 58](https://cloud.githubusercontent.com/assets/11922253/7373795/830b113e-edc6-11e4-9a24-19a22d6e1b64.png)

Worth amending possibly?

**Comment by OliverJAsh** [comment]
I think this was fixed with my icon changes yesterday:

![image](https://cloud.githubusercontent.com/assets/921609/7388418/dffc5c04-ee5c-11e4-927d-8bbdb2c4a567.png)
