### ISSUE TITLE
Comment icon: Blue on purple is very low contrast

### ISSUE THREAD

**Issue by gidsg** [guardian/frontend#9052]
Steps to reproduce
===============
go to: http://www.theguardian.com/profile/hadleyfreeman

Actual Results
============
comment icon has 1.06 colour contrast on features :eyes: :fire: 
![screen shot 2015-04-28 at 15 59 01](https://cloud.githubusercontent.com/assets/1764158/7373826/b3af782a-edc6-11e4-8f72-3641fa383b8b.png)

![screen shot 2015-04-28 at 16 49 07](https://cloud.githubusercontent.com/assets/1764158/7373837/b91c137c-edc6-11e4-90ce-767a8e35b083.png)

Expected results
============
At least 4.51 contrast

**Comment by paperboyo** [comment]
Hmm. Strange. Can’t reproduce in any browser on my PC... The colour is the same as the clock icon and the placement is correct.

**Comment by paperboyo** [comment]
Ah! Taken care of by @OliverJAsh, thank you! https://github.com/guardian/frontend/issues/9047
