### ISSUE TITLE
Video icon wrong colour in ‘popular’ container

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#9053]
Hello,
As seen on http://www.theguardian.com/uk/culture, I believe, consistently with all other icons here, it shouldn’t be yellow:

![video icon in popular](https://cloud.githubusercontent.com/assets/6032869/7376052/d7fe6836-edd4-11e4-9f0f-fb8ae069e1a6.PNG)

Regards
Mateusz

**Comment by robertberry** [comment]
CC @sammorrisdesign Should I change this to grey?

**Comment by sammorrisdesign** [comment]
We bring the red in for live right? So I'd say these should all be yellow.

What do you think @Pearson82?

**Comment by Pearson82** [comment]
Yeah I guess so. Part of me thinks we should just get rid of them altogether in the most popular as they look a bit messy. 

But if they are there, then i agree they should all follow the correct tonal colours, ie. all the multimedia should be yellow.

**Comment by Pearson82** [comment]
@sammorrisdesign @robertberry

**Comment by sammorrisdesign** [comment]
I do think though, if we're going to signify that a video is a video with the icon. We should probably do that everywhere. Although I know here we do it twice because of the "– video" suffix.

**Comment by paperboyo** [comment]
> as they look a bit messy

Agreed. But with all the colours, they would look even messier :cry: This isn’t a proper argument, but I think they were all grey before the recent changes to icons architecture which caused this. Can’t check it in Time Machine, though. My, totally irrelevant, 2gr would be to have all icons grey, kickers in colour and remove instances of ‘- video’ ‘- live’ and ‘- in pictures’.

Regards
Mateusz

**Comment by robertberry** [comment]
@sammorrisdesign @Pearson82 Can you decide between you (or talk to Alex), then I'll fix it and close the issue.

**Comment by paperboyo** [comment]
Closing. Thanks.
