### ISSUE TITLE
Container's too tall when cut out involved

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#9065]
Hello,

I have seen it many times, but just now had it reported by Editorial and we've confirmed that editing in fronts tool can't really resolve it...

Also, sorry, but I do not know the terminology for differently sized tiles/cards/items...

When the cut out is displayed on very big tile, the adjacent boosted very big tile has an empty space below image, like so (Newtork Front, highlights, desktop BP, all browsers):

![empty space when cut out](https://cloud.githubusercontent.com/assets/6032869/7392222/64ea96da-ee7e-11e4-9f9f-3461875a1f89.jpg)

The **only** way to resolve it (bar removing the cut out) is to make sure that the tile with it has only three lines of text (including byline text) which is not a realistic solution.

One way to fix it would be to reduce the size of the cut out on this particular combination. Even better would be to make it dynamic depending on the amount of text.

As reported by Fergal A. and Nick D.

Loosely related to: https://github.com/guardian/frontend/issues/8935

Regards
Mateusz

**Comment by johnduffell** [comment]
since no-one has looked at this yet, it probably won't be looked at soon

**Comment by sndrs** [comment]
>Even better would be to make it dynamic depending on the amount of text.

not possible for many reasons, never admit this notion again :)

@sammorrisdesign what do you reckon? my feeling is we can do it, but every instance of the horizontal layout throws up issues like this, and it's not practicable to fix it on a case basis. that said, if 4 lines (inc byline) is extremely common, maybe this case is worth being the rule?
