### ISSUE TITLE
Hide "popular" component on fronts if query result has empty "most-viewed"

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#9068]
To help guard against issues such as https://github.com/guardian/frontend/issues/9034,
it is recommended that we hide the "popular" container in the case where CAPI is returning an empty "most-viewed" block, rather than displaying the "results" block instead.
The reasons for this are
1 - if we show the results block we are returning the most recently published articles, not the most popular
2 - if the container is hidden, it is really obvious to us that something has gone wrong, this is less obvious if we are showing the most recent.

**Comment by OliverJAsh** [comment]
@janua Is this possible?

**Comment by robertberry** [comment]
Given the current set up it's not trivial to do this, and I wouldn't like to add a bunch of spaghetti code to do so.

I think 1 is a valid concern, but 2 isn't. We ought to have an alarm set up in the correct place for when this happens, not rely on people seeing the container is missing on the front page.
