### ISSUE TITLE
Search bar z-index wrong and a tiny rant

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#9071]
Hello,

URL: http://www.theguardian.com/business/ng-interactive/2015/apr/29/the-austerity-delusion

Search bar is covered with an interactive like so:

![search bar zindex](https://cloud.githubusercontent.com/assets/6032869/7409275/dd7dd7c6-ef1c-11e4-90be-700f1aaca267.jpg)

Related to https://github.com/guardian/frontend/pull/9061 (where there are great ideas to use content, overlay, ui, notifications layers of stacking): https://github.com/guardian/frontend/pull/9061

The above article, produced (beautifully!) as an interactive, reminds me of a related but much more important point. We would better make interactives first class citizens!

Ophan reports 1 word and 0 expected reading time. The contents of an article is not indexed, so it's impossible to find it through site search by using its contents (sic!). But what I'm afraid of most is that one day it will just disappear as have other non-standard items, like embeds discussed https://github.com/guardian/frontend/issues/6872. I don't want it to disappear! :cry:

Regards
Mateusz

**Comment by paperboyo** [comment]
Ah! And, because of its non-standard nature, there are probably zylions of technical peculiarities. Could I ask you @sndrs if it would be able to use our font downgrading mechanism for PCs with font smoothing off, for example? (which I would like to know anyway for another reason...)

**Comment by mattandrews** [comment]
@wpf500 and @andymason might be interested here :)

**Comment by wpf500** [comment]
The article body has since been added to underlying article so it should get indexed. I think @sammorrisdesign made this interactive, is that right?

**Comment by phamann** [comment]
@paperboyo Thanks for the rant. We've been working closely with Composer, interactive team and CAPI on this issue (over the last 5 months) to come up with a new solution for this, and get raw HTML for interactives into the CAPI body response. You'll be happy to know this work has been scheduled for May and we will no longer have this issue.

**Comment by paperboyo** [comment]
@phamann Brilliant! :smiley:

**Comment by paperboyo** [comment]
Fixed, thanks @phamann!
