### ISSUE TITLE
Automated rich link overlap with social buttons

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#9090]
Reported by Central Production - this is on the following page only at the moment, but could potentially occur again?

http://www.theguardian.com/politics/2015/apr/23/the-triumph-of-nicola-sturgeon

![screen shot 2015-05-05 at 10 13 39](https://cloud.githubusercontent.com/assets/11922253/7469780/27a976b6-f30f-11e4-99d7-2170594f40dc.png)

**Comment by ScottPainterGNM** [comment]
This has now been found again by CP, this time with a manually-added rich link on a short piece.

![screen shot 2015-05-05 at 16 00 57](https://cloud.githubusercontent.com/assets/11922253/7475504/edb31ecc-f33f-11e4-98a9-e15e0cd8b895.png)

**Comment by sndrs** [comment]
also on articles with showcase format, e.g. http://preview.gutools.co.uk/global/2015/may/18/headline#

**Comment by johnduffell** [comment]
since no-one has looked at this yet, it probably won't be looked at soon - I have a feeling it might have been fixed anyway
