### ISSUE TITLE
IE11 - Most Popular text/image misalignment in prod

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#9091]
In IE11 the text for the most popular items appears slightly misaligned with the images, there is an extra blank line left above the text on each item when compared with Chrome/Firefox

![screen shot 2015-05-05 at 10 15 54](https://cloud.githubusercontent.com/assets/11922253/7469827/a1e8850c-f30f-11e4-9eca-d3c72c37856b.png)

**Comment by johnduffell** [comment]
since no-one has looked at this yet, it probably won't be looked at soon
