### ISSUE TITLE
Old US video playing in small window - video required

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#9098]
Central Production have contacted us as the video on the following below page only displays in a very small window:

http://www.theguardian.com/theguardian/video/2008/apr/04/guardianfilmsprimaries

The US team need to use the video again but the video faults team no longer have the master so cannot recode them so wanted to see whether this can be amended to display at the correct size and return the video functionality.

**Comment by ScottPainterGNM** [comment]
Sian Cain in Central Production emailed issue originally

**Comment by paperboyo** [comment]
Hi,

The video is 512x384 in Flash format (that is the only available source). I am not sure why it displays like that, though. I was under the impression that Flash videos display correctly.

Will try to notify the person who could maybe help with transcoding...

Regards
Mateusz

**Comment by ScottPainterGNM** [comment]
Closing as Patrick dealt with this already.
