### ISSUE TITLE
Buggy weather and expand icons on network front (mobile) 

### ISSUE THREAD

**Issue by theefer** [guardian/frontend#9121]
On the headlines container right below the elections one at the top of the page. 

![screenshot_2015-05-06-23-37-41](https://cloud.githubusercontent.com/assets/36964/7505319/3ea53e6e-f449-11e4-8efc-222475d6f678.png)

**Comment by davidrapson** [comment]
Just to add to this, not limited to mobile. Seems to be down to the fact that normally the first container is not toggle-able so causes some odd behaviour.

You get this behaviour on a large screen:

![toggle mov](https://cloud.githubusercontent.com/assets/123386/7515182/ad7857fe-f4bc-11e4-9912-68de75d1f0a0.gif)

@ScottPainterGNM

**Comment by ScottPainterGNM** [comment]
Thanks for the heads up @davidrapson I'll see if somebody can take a look

**Comment by davidrapson** [comment]
@ScottPainterGNM As the election container has been disabled this no longer happens on PROD.

**Comment by ScottPainterGNM** [comment]
Agreed, will close off for now but will feedback if we need to do something similar again.

**Comment by theefer** [comment]
This is broken again today, due to a top container for your queen being added above the headlines.

**Comment by paperboyo** [comment]
Yeah, best to assume that this container is going to be re(over-)used...

**Comment by crifmulholland** [comment]
We should use the canonical label to determine which is hideable and which isn't

**Comment by piuccio** [comment]
@crifmulholland however the canonical container is not always the one containing the weather, see #9274

**Comment by crifmulholland** [comment]
There was an email chain on https://github.com/guardian/frontend/pull/9274 saying it shouldn't happen (as the weather doesn't work on grey)

**Comment by theefer** [comment]
Update: Now still happening even without any container above it, it would seem.

**Comment by johnduffell** [comment]
looks weird, but things still work fundamentally - since no-one has looked at this yet, it probably won't be looked at soon

**Comment by theefer** [comment]
Seriously? It's on the front page of theguardian.com very often. Is it that hard to fix? :disappointed: 

cc @OliverJAsh @stephanfowler

**Comment by paperboyo** [comment]
So many similar, most probably simple to fix, ones have been closed today without a good reason... :disappointed:

**Comment by theefer** [comment]
I will do it.

**Comment by johnduffell** [comment]
@theefer thanks!

**Comment by paperboyo** [comment]
:100:

**Comment by davidrapson** [comment]
@theefer Thank you!

**Comment by crifmulholland** [comment]
Looks like this might have broken the weather ..

**Comment by theefer** [comment]
Where? Seems to be working for me now on the network front AFAICS and it
was working after the release.

On Thu, 9 Jul 2015 20:43 Chris Mulholland <notifications@github.com> wrote:

> Looks like this might have broken the weather ..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/9121#issuecomment-120123309>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by crifmulholland** [comment]
Hmm must have been slow connection or something. As you were... :)
