### ISSUE TITLE
Formatting error on Andriod

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#9125]
On the following page when first loading up the page and scrolling down the visual bug below occurs:

http://www.theguardian.com/commentisfree/2015/may/01/guardian-view-britain-needs-new-direction-needs-labour

![screen shot 2015-05-07 at 11 43 22](https://cloud.githubusercontent.com/assets/11922253/7513687/09deb268-f4ae-11e4-8918-c90d586ca920.png)

Reported on Nexus 5 and Samsung S3

**Comment by robertberry** [comment]
Ah yes ... this has been annoying me for months now. I'll pick this up.

**Comment by robertberry** [comment]
Update: This is a DFP ad slot when an iframe's inserted but for some reason no ad is loaded ...

**Comment by johnduffell** [comment]
it's been fixed
