### ISSUE TITLE
Gallery related content showing the viewed gallery within the container

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#9127]
Raised by CP and advised that CAPI isn't populating the related content. When viewing a gallery and scrolling down to the related content box the gallery you are viewing is displayed in the options:

example URL - http://www.theguardian.com/artanddesign/costume-and-culture/gallery/2015/may/05/what-frida-kahlo-wore-artists-wardrobe-locked-up-for-50-years

![screen shot 2015-05-07 at 12 38 57](https://cloud.githubusercontent.com/assets/11922253/7514502/cc22cdb2-f4b5-11e4-90aa-a4b18e4c5111.png)

![screen shot 2015-05-07 at 12 39 07](https://cloud.githubusercontent.com/assets/11922253/7514505/cef3fd0e-f4b5-11e4-8c12-b38aa929fc6d.png)

**Comment by johnduffell** [comment]
since no-one has looked at this yet, it probably won't be looked at soon
