### ISSUE TITLE
Direct jump to comment permalink broken in Firefox

### ISSUE THREAD

**Issue by JustinPinner** [guardian/frontend#9136]
Hi all,

The jump to comment feature is not working as it should in Firefox this morning. I've made a screen recording to demonstrate.

<video link removed>

When I click on a comment, the URL changes to the comment URL, but the screen does not jump to the comment itself. Pressing enter on the comment URL after it has finished loading takes you straight to the comment.

It is working consistently in Chrome.

Can someone please take a look? It has been flagged by two staff down on news this morning.

Thanks,

Sian

**Comment by JustinPinner** [comment]
This seems to be a weird issue in Firefox. It appears that on first loading an article, clicking one of the visible comment permalinks does work as expected, but afterwards it no longer works.

Still digging around in this one.

**Comment by JustinPinner** [comment]
On a video article (http://www.theguardian.com/politics/video/2015/may/08/boris-johnson-london-mayor-mp-prime-minister-general-election-video), clicking a comment's permalink fired the redirection and ended up with the correct comment highlighted but the page didn't scroll it in to view.

**Comment by JustinPinner** [comment]
Actually, the same thing happens on this non-video article too: http://www.theguardian.com/technology/2015/may/07/ad-injection-software-browser-extensions-google-malware

**Comment by JustinPinner** [comment]
This one seems to work fine (once the ads have finished loading): http://www.theguardian.com/technology/2015/may/08/pillars-of-eternity-does-it-matter-if-people-dont-finish-games-any-more

**Comment by JustinPinner** [comment]
(My tests have all been using FF 37.0.1)

**Comment by johnduffell** [comment]
since no-one has looked at this yet, it probably won't be looked at soon
