### ISSUE TITLE
An embed as main media set to showcase breaks the page

### ISSUE THREAD

**Issue by sammorrisdesign** [guardian/frontend#9171]
Just tried to add some embed code as the main media, it works until you set it to showcase. Then it looks like this...

![screen shot 2015-05-13 at 17 10 39](https://cloud.githubusercontent.com/assets/1607666/7615105/21134d42-f993-11e4-8362-11779a79ecaf.png)

**Comment by paperboyo** [comment]
Also: https://github.com/guardian/frontend/issues/9089.

**Comment by johnduffell** [comment]
since no-one has looked at this yet, it probably won't be looked at soon

**Comment by paperboyo** [comment]
Pls keep either that or https://github.com/guardian/frontend/issues/9089 open...
