### ISSUE TITLE
'Join us' form overlaps other components

### ISSUE THREAD

**Issue by Calanthe** [guardian/frontend#9173]
Like that:
![screen shot 2015-05-14 at 10 22 13](https://cloud.githubusercontent.com/assets/489567/7629374/dba0a598-fa23-11e4-8a0d-70fb2f3f9552.png)

Link: 
http://www.theguardian.com/news/2015/apr/08/can-world-economy-survive-without-fossil-fuels

**Comment by johnduffell** [comment]
since no-one has looked at this yet, it probably won't be looked at soon
