### ISSUE TITLE
New rule below social icons

### ISSUE THREAD

**Issue by Pearson82** [guardian/frontend#9188]
We seem to have gained a new rule below the social icons. Is appearing on all content pages, at all breakpoints from what I can see...

![screen shot 2015-05-15 at 10 14 27](https://cloud.githubusercontent.com/assets/3416696/7650135/6a837c1e-faeb-11e4-901b-a816c326b68a.png)

**Comment by Jholder112233** [comment]
@NathanielBennett pretty sure this is related to the save for later stuff. Class name on the extra div that has appeared is "meta__save-for-later".

**Comment by sndrs** [comment]
@Jholder112233 yeah i think you're right, spotted that this morning too.
