### ISSUE TITLE
Navigation bar toggling somewhat too aggressive 

### ISSUE THREAD

**Issue by jakub-** [guardian/frontend#9202]
So the international desktop version of The Guardian has this nice navigation bar that's only visible when scrolling up. This is great! However, I think there should be a threshold of scroll distance or time (probably the former) before the nav bar reappears as you scroll up.

I've gotta be honest, I am a bit compulsive when reading articles, scrolling up and down and selecting text as I read, so these little things get in the way by taking away my attention. This is probably not the case with the average reader but I don't think the threshold would hurt anyone.

Here's a screen cast pinpointing what I mean:
https://vid.me/x9TO

Thanks!

**Comment by robertberry** [comment]
I think this is an A/B test we're running, so might not be in its final state. If it is, you ought to be able to opt out if it's bugging you.

CC @Calanthe

**Comment by jakub-** [comment]
Thanks! I actually like this feature. Regardless, the lack of threshold may substantially affect the outcome of the A/B test.

**Comment by Calanthe** [comment]
Hi Jakub!

Thanks for your opinion, it's a really valuable idea!

We will probably make some changes soon.

Zosia

**Comment by jakub-** [comment]
@robertberry Could you clarify what the outcome of this is? Now I can't see the responsive navigation bar at all, is it coming back any time soon?

**Comment by jakub-** [comment]
@Calanthe Any news on this? Seems like this is live now?
