### ISSUE TITLE
iOS Video Bug

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#9211]
When you select a video to play on iOS the Guardian play button appears but once selected then the another play button appears while the video loads which looks like this:

![screen shot 2015-05-19 at 12 14 05](https://cloud.githubusercontent.com/assets/11922253/7701575/708f7580-fe20-11e4-9087-d85d64c56656.png)

Replicated on iPhone 5C on iOS 8.3 using Safari

**Comment by johnduffell** [comment]
since no-one has looked at this yet, it probably won't be looked at soon
