### ISSUE TITLE
Missing share icon on leftCol

### ISSUE THREAD

**Issue by Jholder112233** [guardian/frontend#9254]
![screen shot 2015-05-22 at 08 45 02](https://cloud.githubusercontent.com/assets/2236852/7766225/f1fba022-005e-11e5-9ac9-1e6ca0036fde.png)

Missing the LinkedIn button. Of arguable worth, but aesthetically at least it's better with four.

**Comment by paperboyo** [comment]
Can't reproduce on all browsers, all breakpoints, same URL: http://www.theguardian.com/uk-news/2015/may/21/network-rail-planning-for-strike-stopping-90-of-trains

**Comment by Jholder112233** [comment]
@paperboyo weird, on Firefox on Mac I see 4, on Chrome I see 3, on Opera I see 4...

**Comment by paperboyo** [comment]
Indeed, strange! The number varies by breakpoint, but it's never lower than 4 for me on FF 38.0.1, Chrome 40 on 10.9.3.

But! On that neglected, one-before-widest breakpoint, on Chrome 43 on 10.9.3, there are only 3! LinkedIn is missing.

**Comment by Jholder112233** [comment]
@paperboyo yep, I'm on Chrome 43. So this is reproducible on that browser. Strange...

**Comment by johnduffell** [comment]
since no-one has looked at this yet, it probably won't be looked at soon
