### ISSUE TITLE
Hard to close user profile drop down menu

### ISSUE THREAD

**Issue by davidrapson** [guardian/frontend#9255]
Raised by @Mullefa, https://github.com/guardian/membership-frontend/issues/551

"At the url `http://www.theguardian.com/membership#`, the drop down menu I get from clicking on my user profile (top left), can only be closed by re-clicking on my member profile (as opposed to anywhere off the drop down menu). I'm using Google Chrome on a MacBook."

This was raised on Membership but it looks like this applies here as you can click away to close the profile popup on membership.theguardian.com but not on theguardian.com

**Comment by sndrs** [comment]
yeah this long been the case, and it's really annoying. the whole menu thing could do with looking at. might try today actually

**Comment by davidrapson** [comment]
@sndrs Great, thanks Alex

**Comment by paperboyo** [comment]
Whoa! At last! The silent rest-of-interwebz has spoken.

Related: https://github.com/guardian/frontend/issues/3437, https://github.com/guardian/frontend/issues/7991#issuecomment-71533847 :stuck_out_tongue_winking_eye:

Thanks a lot, @sndrs!

**Comment by davidrapson** [comment]
Looks like this has been fixed in another PR, thanks @sndrs! 

![toggle mov](https://cloud.githubusercontent.com/assets/123386/8109527/1e126330-104f-11e5-89f7-96d56cd69f33.gif)
