### ISSUE TITLE
Images on fronts requested at too low a resolution

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#9278]
Hello,

It's hard to find all instances. The most offending occur in this new grey election special container that is being used sporadically for special events. Take a look, please, at the example from UK network front just now. Image resolution on widest BP is 700px at 100% zoom. Chrome 43 loads a low resolution 605px (sic!) image:

``
<img class="responsive-img" srcset="//i.guim.co.uk/static/w-445/h--/q-95/sys-images/Guardian/Pix/pictures/2015/5/27/1432712203406/5f19111d-2bd1-4c9b-a601-e5f394ebc72d-620x372.jpeg 445w, //i.guim.co.uk/static/w-605/h--/q-95/sys-images/Guardian/Pix/pictures/2015/5/27/1432712203406/5f19111d-2bd1-4c9b-a601-e5f394ebc72d-620x372.jpeg 605w" sizes="100%" src="//i.guim.co.uk/static/w-300/h--/q-95/sys-images/Guardian/Pix/pictures/2015/5/27/1432712203406/5f19111d-2bd1-4c9b-a601-e5f394ebc72d-620x372.jpeg">
``

But Firefox 38.0.1 loads a 445px wide image!

``
<img class="responsive-img" srcset="//i.guim.co.uk/static/w-445/h--/q-95/sys-images/Guardian/Pix/pictures/2015/5/27/1432712203406/5f19111d-2bd1-4c9b-a601-e5f394ebc72d-620x372.jpeg 445w, //i.guim.co.uk/static/w-605/h--/q-95/sys-images/Guardian/Pix/pictures/2015/5/27/1432712203406/5f19111d-2bd1-4c9b-a601-e5f394ebc72d-620x372.jpeg 605w" sizes="100%" src="//i.guim.co.uk/static/w-300/h--/q-95/sys-images/Guardian/Pix/pictures/2015/5/27/1432712203406/5f19111d-2bd1-4c9b-a601-e5f394ebc72d-620x372.jpeg">
``

Another instance was visible in Cannes uncovered series container (visible here http://www.theguardian.com/film/filmblog/2015/may/13/cannes-uncovered-day-1), when there wasn't much stories and the tiles were full-width. Now, they are fine...

Ideally, there would be a way to automatically look for images that are requested at the lower resolution than they are shown at 100% zoom.

Please note, that I moan about that only because, in time, I would like to load higher res images when the page is semi-permanently zoomed in (not when you _are zooming it in_!). Maybe using `window.devicePixelRatio` which reports zoom ratio in all browsers?

Regards
Mateusz

p.s. I've made no screenshots, but just imagine an **extremely blurry** image in the most prominent place on our front!

**Comment by Calanthe** [comment]
I can reproduce it now here: http://www.theguardian.com/media-network/2015/may/27/internet-of-things-automation-unemployment

![screen shot 2015-05-28 at 10 50 05](https://cloud.githubusercontent.com/assets/489567/7857317/665a9d2a-0527-11e5-9c49-ca0b6b277c05.png)

**Comment by robertberry** [comment]
@Calanthe That's due to that card being a 'standard' size yet it's been stretched for some reason. Bad choice of container for four items. I'll have a look at a fix for that. Not sure if that's what @paperboyo has been seeing

**Comment by paperboyo** [comment]
Hi,

Thanks, @robertberry! That's half of what's paperboyo's been seeing. The other half was low res images in elections-prince-charles-fifa-this-is-special container (lower res still in Firefox).

Ideally, images should always be requested at the resolution that they are shown at and their dimensions should not be hardcoded.

I can't be sure that series container and elections-prince-charles-fifa-this-is-special container are the only instances of that...

Regards
Mateusz

**Comment by robertberry** [comment]
A fix for the series container is rolling out now. I'll investigate the special container.

**Comment by paperboyo** [comment]
:beer:

**Comment by johnduffell** [comment]
maybe it's fixed, either that or it probably won't be looked at soon
