### ISSUE TITLE
Fronts tool - error message when I drag uncropped image is confusing

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#9328]
So if I am replacing an image on the front or if I am building a slideshow, we currently require that the image added is a crop of one of the images on "the grid" (https://media.gutools.co.uk) however if you forget to crop and drag in an uncropped image, the error message you get says
"Error: images must come from *.guim.co.uk"
a) This is not actually true - the url is different
B) there is no information that explains to the user how to get the image in correctly.

Recommend we update this error message so that it is more helpful to users.

![image](https://cloud.githubusercontent.com/assets/7239344/7912135/b5639402-085c-11e5-961f-8db5a367d745.png)

**Comment by johnduffell** [comment]
since no-one has looked at this yet, it probably won't be looked at soon
