### ISSUE TITLE
Container only gets 'first' class if first in tools, not first output

### ISSUE THREAD

**Issue by sammorrisdesign** [guardian/frontend#9378]
So the uk front looks like this:
![screen shot 2015-06-04 at 15 26 01](https://cloud.githubusercontent.com/assets/1607666/7986221/226f275a-0ace-11e5-805e-966130ecc951.png)

Because there is actually a container above:
![screen shot 2015-06-04 at 15 26 07](https://cloud.githubusercontent.com/assets/1607666/7986230/2a5b27ac-0ace-11e5-8a3a-a70e3420f013.png)

But the class of `fc-container--first` should get applied to the first visible container, not the first container in the tools, as it just handles visual changes. Basically it should look like this...
![screen shot 2015-06-04 at 15 26 17](https://cloud.githubusercontent.com/assets/1607666/7986242/45ebc42c-0ace-11e5-86b1-57e26ae38da2.png)

cc @stephanfowler

**Comment by crifmulholland** [comment]
Why can't we use the canonical parameter for this rather than the first on the page. Won't this still break if there is a special container above?

**Comment by sammorrisdesign** [comment]
@crifmulholland Not sure what you mean? This is just the way the container title wraps into the leftCol and the way the rule behaves.

**Comment by crifmulholland** [comment]
Oh, it seems to control whether 'hide' is visible or not too. I was looking on the right hand side...

**Comment by sammorrisdesign** [comment]
Oh yeah, we should fix that too. I was looking on the left hand side...

**Comment by stephanfowler** [comment]
Agreed. That class need to be applied to the first non-empty container.

On 4 June 2015 at 15:38, Sam Morris <notifications@github.com> wrote:

> Oh yeah, we should fix that too. I was looking on the left hand side...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/9378#issuecomment-108918606>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396
