### ISSUE TITLE
Posted comments cannot be seen by the poster

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#9446]
Easily reproduced in IE11 but has also been seen in google.

When I make a comment on IE11, upon pressing "post comment" the comment is not displayed for me in the list of comments and the overall impression is that the comment is lost.
In reality it is not - if I log in on another browser I can see the comment, so we are posting it, but giving the user the impression that it has been lost. 

Looks like it might be falling foul of cross origin resource sharing restrictions on the browser:

When we post a comment the url is appeded eg
http://www.theguardian.com/film/2015/jun/10/jurassic-world-review-chris-pratt-steven-spielberg-dinosaur-movie#comment-53586195

the debug console on posting of comments gives a number of Security warnings:
SEC7118: XMLHttpRequest for http://discussion.guardianapis.com/discussion-api/discussion//p/49k6q/comment required Cross Origin Resource Sharing (CORS)

SEC7119: XMLHttpRequest for http://discussion.guardianapis.com/discussion-api/discussion//p/49k6q/comment required CORS preflight.

SEC7118 XMLHttpRequest for http://api.nextgen.guardianapps.co.uk/discussion/comment-context/53586195.json?orderBy=newest&pagesSize=25&displayThreaded=true required Cross Origin Resource Sharing (CORS).
 
Refreshing the page did not display the comment but did add an extra error message:

"Potentially unhandled rejection [4] Error loading "http/pq-direct.revsci.net/pql?placementIdList=FLh9mM,c7Zrhu,Y1C40a,LtKGsC,MTLELH&cb=1433945769797!github:rich-nguyen/systemjs-script-plugin@0.1.9" at http://pq-direct.revsci.net/pql?placementIdList=FLh9mM,c7Zrhu,Y1C40a,LtKGsC,MTLELH&cb=1433945769797"

![image](https://cloud.githubusercontent.com/assets/7239344/8085150/8ab36c74-0f86-11e5-9a4a-338bb9334cb4.png)

![image](https://cloud.githubusercontent.com/assets/7239344/8085163/9be6a498-0f86-11e5-8e83-0153aaee4ea1.png)

**Comment by johnduffell** [comment]
#7164 duplicate
