### ISSUE TITLE
Trail text is not readable

### ISSUE THREAD

**Issue by piuccio** [guardian/frontend#9453]
Hi [this front](http://www.theguardian.com/university-sussex-partner-zone) has trail with comment tone at the bottom. The trail text is dark and hard to read, should be white.

![screen shot 2015-06-11 at 15 28 16](https://cloud.githubusercontent.com/assets/680284/8109409/66ad91c4-104e-11e5-9fd2-e8215a3af428.png)

Bonus issue, two trails touch

**Comment by johnduffell** [comment]
since no-one has looked at this yet, it probably won't be looked at soon
