### ISSUE TITLE
Images in liveblogs requested at too low a resolution

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#9482]
Hello,

Seen on FF, Chrome, IE11 on Win 8.1. On two breakpoints, liveblogs pages request images at lower resolution than they are shown (at 100% zoom).

On BP 740px-980px - they are shown at 700px but are requested at 620px.

On BP 1140px-1300px - they are shown at 780px but are requested at 620px!

This results in unnecessarily blurry images.

Loosely related to https://github.com/guardian/frontend/issues/9278.

BTW, since this problem manifests in different places, is there a _simple_ way to test the whole site for occurrences of imagery being requested at lower resolution than they are shown at 100% zoom? Then, we could catch them all.

And this is needed before we start to think about showing them at higher resolutions if the (desktop) browsers are zoomed in ~~(maybe by sniffing ``window.devicePixelRatio``?) :wink:~~

@robertberry 

Regards
Mateusz

**Comment by ScottPainterGNM** [comment]
Is this still an issue or sorted by #10751 ??

**Comment by paperboyo** [comment]
Yep, @ScottPainterGNM.

**Comment by JonnyWeeks** [comment]
@OliverJAsh @paperboyo hey oliver and mateusz, it looks to my eyes as if the liveblog break-point issue is now fixed.... is that the case?? If so, thank you v much. jonny

**Comment by OliverJAsh** [comment]
Yes, this is fixed now. Thanks

**Comment by JonnyWeeks** [comment]
@OliverJAsh @paperboyo thanks for fixing the liveblog issue guys, hugely appreciated.

You know how i also mentioned that sometimes entire containers appear to be low res, well that issue has popped up again. I screengrabbed it for you and immediately tried to inspect element to get the specific deets for you, but as soon as i went to inspect element the site rejigged itself, an advert appeared alongside it and the content in the container suddenly appeared sharp. I don'y really understand it but to my ill-educated eye it does seem to be some kind of responsive issue. I've seen it over recent months and it always afflicts all of the images in one container at a time (somehow the images in neighbouring containers are fine). Here's the only screengrab I have:
![picture 604](https://cloud.githubusercontent.com/assets/11023438/10679851/e70b0064-7966-11e5-8e38-fc6b788d852f.png)

lemme know what you think
cheers
jonny
p.s. my browser is chrome and i was deffo viewing it at 100% when it looked wrong.

**Comment by paperboyo** [comment]
@JonnyWeeks Thanks should go entirely to Oliver!

I have noticed that as well. But, as you also observed, it does happen _only_ when the ad has not loaded yet/fails to load. My hunch is that this does not constitute a bug as such.
