### ISSUE TITLE
Peek-a-boo adverts

### ISSUE THREAD

**Issue by davidrapson** [guardian/frontend#9506]
Some jumping going on with adverts at the moment, opposite add slot shows briefly depending on if the top add is above or below the header.

![peek-a-boo mov](https://cloud.githubusercontent.com/assets/123386/8203570/a803e868-14da-11e5-8d9e-51acf42c9b5c.gif)

![reverse-peek-a-boo mov](https://cloud.githubusercontent.com/assets/123386/8203572/aac2e14e-14da-11e5-893b-63e58e45c9a2.gif)

This is on Chrome 43 / OS X 10.10
 
@Calanthe

**Comment by johnduffell** [comment]
presumably these adverts have been removed, must have been a badly behaved one

**Comment by davidrapson** [comment]
@johnduffell Wasn't a specific advert this was happening for all header adds. I've spotted a few PRs go through related to this so I think this has been resolved as part of other work.

**Comment by johnduffell** [comment]
Thanks @davidrapson for the update.
