### ISSUE TITLE
html in bylines shows up on fronts

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#9528]
reported by Katherine Le Ruez
HTML in bylines eg like the one on this page: http://www.theguardian.com/lifeandstyle/2015/jun/16/two-bars-chocolate-day-help-heart-disease.
I saw something similar on the weekend when looking at a front with chrome on Windows 8.1

shows up on the fronts.
![image](https://cloud.githubusercontent.com/assets/7239344/8229667/e42056fc-15b0-11e5-9455-a119d97c9630.png)

**Comment by paperboyo** [comment]
Reproduced on FF 38.0.5 on 10.9.3.

**Comment by fredericksilva** [comment]
![bug-firefox-developer](https://cloud.githubusercontent.com/assets/410689/8254371/44b49fa6-166e-11e5-9951-ca815b4b38d9.png)

**Comment by johnduffell** [comment]
that has been fixed now

**Comment by fredericksilva** [comment]
:facepunch:
