### ISSUE TITLE
Do not show SFL twice on Picture content type pages

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#9701]
Hello,

This seems redundant:

![save twice](https://cloud.githubusercontent.com/assets/6032869/8507761/bf7aa0d8-2248-11e5-82da-858f2625dd58.jpg)

Have a nice weekend!

Regards
Mateusz

**Comment by paperboyo** [comment]
...and video pages...

**Comment by sndrs** [comment]
i think this is expected, @crifmulholland?

**Comment by crifmulholland** [comment]
I don't think we looked into this case specifically. I agree it is redundant. Particularly on mobile! We should get rid on these that only have one image.

![image](https://cloud.githubusercontent.com/assets/796176/8593477/ffa2df8c-262f-11e5-8dd2-51252c2eaad2.png)

**Comment by OliverJAsh** [comment]
Closing because this is not an issue, just an area for improvement. If it's important enough we'll get round to it.

**Comment by ScottPainterGNM** [comment]
This has been reported by the multimedia team, how much work would it take to fix it on these content types as it looks a bit messy on mobile especially

**Comment by ScottPainterGNM** [comment]
Didn't mean to reopen that
