### ISSUE TITLE
Sticky situation brakes comment tone design

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#9702]
Hello,

One of the recent changes to navigation does not play well with our design where comment tone byline cutouts ought to overlap navigation:

![nav cut out](https://cloud.githubusercontent.com/assets/6032869/8508631/c4a19ba8-226f-11e5-9a10-12af1c9b5665.gif)
[apologies for the long GIF, but ads make my quadcore 18GB machine unresponsive, plugins crash and so on...]

Regards
Mateusz

**Comment by ScottPainterGNM** [comment]
@uplne Some feedback on the viewability feature for you
