### ISSUE TITLE
Font whitelist for signup.theguardian.com 

### ISSUE THREAD

**Issue by stephanfowler** [guardian/frontend#9709]
Egyptian font needs whitelisting for signup.theguardian.com

Sample page:
https://signup.theguardian.com/page.aspx?QS=5c591a8916642e73dcfb86657e3a4f2cb3cd3889df5fd4a3b7a734ac3d002701

Reply to shane.hoyle@theguardian.com when complete

**Comment by JustinPinner** [comment]
I've added high priority and severity labels to this as I think the lack of consistency between the sign up page and our official appearance may put people off.

**Comment by stephanfowler** [comment]
I fixed this already - but forgot to close.
