### ISSUE TITLE
video shows the first frame just before the ad comes in

### ISSUE THREAD

**Issue by johnduffell** [guardian/frontend#9726]
test url: http://www.theguardian.com/artanddesign/video/2015/jun/25/damien-hirst-paintings-john-hoyland-newport-street-gallery-london-video?adtest=tom
Raised and in progress with google at:
https://groups.google.com/forum/?place=forum%2Fima-sdk&showsearch=true&showpopout=true&parenturl=https%3A%2F%2Fdevelopers.google.com%2Finteractive-media-ads%2Fdocs%2Fsdks%2Fhtml5%2Fcommunity#!topic/ima-sdk/ybmD6E9Szo4

libraries that we use on top of the ima sdk:
https://github.com/googleads/videojs-ima
https://github.com/videojs/videojs-contrib-ads
IME SDK quickstart docs:
https://developers.google.com/interactive-media-ads/docs/sdks/html5/quickstart

**Comment by paperboyo** [comment]
_Possibly_ related to https://github.com/guardian/frontend/issues/8118. Just sayin’ :wink:

**Comment by johnduffell** [comment]
could be! apparently we're waiting for the ads to timeout before we load them in

**Comment by ScottPainterGNM** [comment]
@jamesgorrie can this old issue be shut down now?

**Comment by jamesgorrie** [comment]
Nope - there is still some work / testing to be done around this.
Unfortunately I am stuck in videojs dependency hell, so it's hard to test.

**Comment by jamesgorrie** [comment]
@ScottPainterGNM ^

**Comment by ScottPainterGNM** [comment]
Aboo, let me know if I can help anyway!

**Comment by ScottPainterGNM** [comment]
@jamesgorrie totally just did the same thing ^
