### ISSUE TITLE
Getting loads of JS errors from ads

### ISSUE THREAD

**Issue by kaelig** [guardian/frontend#9760]
In Safari 9

![screenshot 2015-07-13 10 05 42](https://cloud.githubusercontent.com/assets/85783/8655580/efecfbe4-2946-11e5-8c33-b242698c3301.png)

Here is a log: https://gist.github.com/kaelig/b34b3c04ce9f43c76b5b

**Comment by janua** [comment]
@kaelig Thanks!
Do you know if it was a specific ad or all ads? Seems very specific to me.

Is it reproducible?

**Comment by kaelig** [comment]
It happens with most ads but I guess it could be an ad issue, not a guardian issue. Closing it.
