### ISSUE TITLE
Extra whitespace in article body

### ISSUE THREAD

**Issue by JustinPinner** [guardian/frontend#9761]
Reported by: Shraddha

Prerequisites: Sticky nav A/B opted in. Ads enabled.

URL: http://www.theguardian.com/sport/2015/jul/13/serena-williams-and-novak-djokovic-dancing

Screenshot:
![screen shot 2015-07-13 at 16 49 13](https://cloud.githubusercontent.com/assets/690395/8655528/aa4c132a-2989-11e5-8d72-b668c5469f85.png)

It looks as though the combination of having sticky nav enabled and lazy loading of an ad taking longer than expected may have produced this condition. When sticky nav was disabled the left-column rich link moved higher up the page, and away from the ad container. This may or may not be significant as we couldn't reproduce the problem again regardless of nav / ad settings.

**Comment by OliverJAsh** [comment]
Surely this is one for commericla?

**Comment by Calanthe** [comment]
I cant reproduce it now.

**Comment by OliverJAsh** [comment]
Will re-open if we can reproduce.
