### ISSUE TITLE
Tracking is not working in IE 9 (and IE 8)

### ISSUE THREAD

**Issue by janua** [guardian/frontend#9767]
Ophan and Omniture tracking does not seem to be working in IE 8 or 9 correctly.

In Ophan, IE 8 seems OK, but IE 9 is missing.

In Omniture, they are both missing.

**Comment by OliverJAsh** [comment]
Looks like we broke it around June 29, same time we broke comments et al:

![image](https://cloud.githubusercontent.com/assets/921609/8676862/d0c4c30c-2a43-11e5-843f-a4644e8f7ae8.png)

Could it be the switch of ajax/assets to HTTPS, i.e. https://github.com/guardian/frontend/issues/9736#issuecomment-121193214? This occurred around the same time. I doubt it, though.

**Comment by janua** [comment]
This has been fixed by the changes in `javascriptFirstSteps`.

See https://github.com/guardian/frontend/pull/9779

**Comment by janua** [comment]
See https://github.com/guardian/frontend/pull/9797 as to why the `common.js` changes fixed tracking.
