### ISSUE TITLE
Membership container broken on narrow viewports

### ISSUE THREAD

**Issue by OliverJAsh** [guardian/frontend#9777]
Not sure who is the right person to talk to about this. @davidrapson?

![image](https://cloud.githubusercontent.com/assets/921609/8695641/2e0f19e6-2ade-11e5-95cd-74a5ff0e7b0c.png)

**Comment by davidrapson** [comment]
I'm not sure actually. I've not worked on these commercial components, perhaps @uplne or @Calanthe?

If it makes more sense for someone on Membership to own this then let me know and I can pick this up.

**Comment by uplne** [comment]
This is us. We will look at it.

**Comment by tijanamiletic** [comment]
Do we know who created this component? Is it a manual one? Is there a URL we could see? 

I vaguely remember seeing a similar problem a few months ago and it was a problem with a manual component, i.e. a content issue.

**Comment by ScottPainterGNM** [comment]
@uplne Can we close this one off now? Are we still using these components?

**Comment by uplne** [comment]
@ScottPainterGNM I've looked at it and couldn't replicate the issue. I've then had to move to some other tasks and totally forgot about it.

However we did so many changes (and a new major refactor is almost done) to the commercial components in the last few weeks that I can confidently say that we can close this one

**Comment by ScottPainterGNM** [comment]
Bueno :+1:

**Comment by davidrapson** [comment]
:wave: Bye little issue.
