### ISSUE TITLE
Pintrest button looks broken in IE with javascript turned off

### ISSUE THREAD

**Issue by janua** [guardian/frontend#9792]
When in `IE` without `javascript`, the `pintrest` button is completely broken. It looks like a red circle with 3 little dots on the top left.

It looks like the `P` image/svg is not aligning properly to the centre of the red circle.

To turn off `javascript` in `IE`, go to:

    Internet Options -> Security -> Custom Level -> Scripting -> Active Scripting -> Disable

**Comment by NataliaLKB** [comment]
This should now be fixed :smile: .
