### ISSUE TITLE
Contributor pic cropped by nav

### ISSUE THREAD

**Issue by OliverJAsh** [guardian/frontend#9811]
![image](https://cloud.githubusercontent.com/assets/921609/8727258/a6506916-2bd6-11e5-8d7c-8a1eb6f0f280.png)

http://www.theguardian.com/commentisfree/2015/jul/16/tim-farron-lib-dem-leader

The contributor pic is cut off from the top when the user starts to scroll.

Is this because of the sticky nav? /cc @uplne @Calanthe (anyone else I should cc?) @mattosborn

**Comment by paperboyo** [comment]
Duplicate: https://github.com/guardian/frontend/issues/9702
