### ISSUE TITLE
Search box z-index broken

### ISSUE THREAD

**Issue by JustinPinner** [guardian/frontend#9812]
Raised by: Chris King via Mariana Pereira

Screenshot:
![searchzindex](https://cloud.githubusercontent.com/assets/690395/8727900/2cb0fb62-2bda-11e5-9a84-a6972d366c10.jpg)

So far I haven't been able to reproduce this but there was a zindex-related PR merged earlier today: https://github.com/guardian/frontend/pull/9769

**Comment by uplne** [comment]
The z-index PR shouldn't affect this. So far I was unable to reproduce this bug either. We will find Chris today and try to find out what is happening on his machine.

**Comment by OliverJAsh** [comment]
Any updates @uplne?

**Comment by OliverJAsh** [comment]
Cannot reproduce.
