### ISSUE TITLE
meta element style broken on interactive template

### ISSUE THREAD

**Issue by mattosborn** [guardian/frontend#9821]
broken style at <= leftCol breakpoint on interactive template

![image](https://cloud.githubusercontent.com/assets/960919/8744777/df52e0f4-2c71-11e5-8302-fa8472b0d63b.png)

http://www.theguardian.com/news/datablog/ng-interactive/2015/jul/17/interactive-whats-the-world-scared-of

**Comment by JustinPinner** [comment]
Added high priority and severity labels as this potentially interferes with user interaction.

**Comment by sndrs** [comment]
this is really current work for loyalty team
