### ISSUE TITLE
byline hidden at <= leftCol on interactive template

### ISSUE THREAD

**Issue by mattosborn** [guardian/frontend#9822]
byline hidden at <= leftCol on interactive template

http://www.theguardian.com/news/datablog/ng-interactive/2015/jul/17/interactive-whats-the-world-scared-of

wide
====
![image](https://cloud.githubusercontent.com/assets/960919/8744851/6f9bb62c-2c72-11e5-9987-90a5cd5e85ba.png)
leftCol
====
![image](https://cloud.githubusercontent.com/assets/960919/8744844/687470e6-2c72-11e5-980b-1789ee1d4303.png)

**Comment by gtrufitt** [comment]
Hi @mattosborn - It looks as if the byline is shown at the leftCol (1140) breakpoint now? Is the behaviour correct now or do you need it to show at different breakpoints to current?

**Comment by mattosborn** [comment]
hmm still getting hidden below 1140px for me.

**Comment by gtrufitt** [comment]
Ah, yes, no problem, I'll update it.

**Comment by gtrufitt** [comment]
Updated on prod.
