### ISSUE TITLE
Sticky situation makes page jumpy with ad blockers/privacy extensions

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#9841]
Hello,

Even after https://github.com/guardian/frontend/pull/9789, the experience is dreadful. In between normal and sticky nav states the page jumps considerably like so:

![ad-jump_2](https://cloud.githubusercontent.com/assets/6032869/8766088/888b9bc8-2e22-11e5-9999-9bc746c5bb7b.gif)

We have enough jumpiness on the page without that, thank you very much (e.g. https://github.com/guardian/frontend/issues/8444#issuecomment-76284160).

Regards
Mateusz

**Comment by paperboyo** [comment]
Also, when the page is short (like e.g. http://www.theguardian.com/help/accessibility-help), CH displays empty space below footer and FF lets you scroll indefinitely in place...

**Comment by ScottPainterGNM** [comment]
@Calanthe @uplne not sure who is looking at the sticky nav issues at the moment but this is the one generating the most complaints currently. Would you be able to assign and pick up as a priority possibly?

**Comment by Calanthe** [comment]
We plan to make a special banner for adblock users, so I am not sure if it is worth fixing any bugs right now (because it will be rewritten anyway). Currently I am waiting for designs and don't know how long it will take, so maybe it will be better to look at those issues now and see if there is any fast and easy, temporary fix. I will look at it.

**Comment by OliverJAsh** [comment]
It would be great if we could turn it off until it's fixed :-)

On Thu, 30 Jul 2015 at 15:27 Zofia Korcz <notifications@github.com> wrote:

> We plan to make a special banner for adblock users, so I am not sure if it
> is worth fixing any bugs right now (because it will be rewritten anyway).
> Currently I am waiting for designs and don't know how long it will take, so
> maybe it will be better to look at those issues now and see if there is any
> fast and easy, temporary fix. I will look at it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/9841#issuecomment-126347736>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by Calanthe** [comment]
It would be great if we could turn it off completely ;)

**Comment by ScottPainterGNM** [comment]
I saw the designs for this but the only worry I had was that until we can work out who are subs/members from identity then they could get annoyed seeing a message. Some of the adblock users who have reported a bug say they have it on for privacy/performance but they support us so we don't miss out. 

Temp fix is grand though, think that will stop alot of the negative feedback!

**Comment by OliverJAsh** [comment]
Manually closing, re. https://github.com/guardian/frontend/pull/10011
