### ISSUE TITLE
Sticky situation hides almost all the content from me

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#9843]
Hello,

I invite you to the game of Spot-the-Content™. Also, one has to be __really__ careful when choosing a correct space to be able to actually scroll to see more of it. Not that the sticky stuff won’t be following one when one tries...

![screenshot_2015-06-29-16-53-02](https://cloud.githubusercontent.com/assets/6032869/8766289/7a84d032-2e2a-11e5-88be-3b936b94d794.png)
[Samsung Galaxy SII]

Regards
Mateusz

**Comment by OliverJAsh** [comment]
This would be even worse for smaller devices, i.e. iPhone 4.

**Comment by sndrs** [comment]
this is a design decision. i agree it's a sub-optimal experience, but it's not a source code issue...sorry!

**Comment by davidrapson** [comment]
@sndrs Is there another place to document this kind of thing then? Seems worth a discussion at least.

**Comment by OliverJAsh** [comment]
I think it's fine to file UX issues her? Just label them…

**Comment by paperboyo** [comment]
> I think it's fine to file UX issues her[e]?

Yes, please! Paperboyo redundant otherwise :sob: Can't label things on me own, though...

**Comment by OliverJAsh** [comment]
@paperboyo After talking to @sndrs, we think the best place for these things is probably email. Or, we could setup a Google group forum thingamajig for it.

Do you want to forward the contents of these issues to commercial.dev@theguardian.com?

**Comment by paperboyo** [comment]
@OliverJAsh @sndrs Alrighty then! We are loosing on some great conversations, but I will _try_ to keep all bad "design decisions" out of developer's playground. So will forward this issue (a link to it) to the email above.

I will keep pestering you with issues that I think (and, remember, I can't code so can be wrong) are strictly code related here (like https://github.com/guardian/frontend/issues/9841), though.

But I must say I do have a problem with your reasoning, Gentlemen. Why would I be the one who have to think if something is a bad "design decision", a "design glitch" (clearly a bug, will still be putting them here), bad UX decision, clear UX glitch or code-related... I'm both badly qualified to do this and also, pardon me, it's not my job.

By "me" I mean, obviously, all of our readers - in line with my megalomania :wink:

Developing in the open may mean some mean things. Like interacting. I know that the team is short-staffed. But agreeing on a label that will put your mind at rest (like "won't fix") and labelling new issues should not be that hard (maybe you can even set a filter and label all my issues "won't fix" a priori :stuck_out_tongue:).

I hope you reconsider. And that you'll get some great people soon. And that you well know that nothing above is in any way personal.

I'll let myself cc/ @gklopper...

Regards
Mateusz

**Comment by paperboyo** [comment]
@OliverJAsh BTW, is commercial.dev@theguardian.com the right email anyway? Doesn't it say "dev", meaning: not where the bad design decisions are made? Just executed? And I will get routed to another email and another, and not only there will be no conversation at all but everyone's gonna hate me even more?

**Comment by sndrs** [comment]
added the 'discussion' tag, hopefully sufficient to disambiguate and not pollute the list of actual bugs

**Comment by paperboyo** [comment]
Thanks, @sndrs! While I'm well known for discussions with myself, I do hope someone will chime in :laughing:. I will be sure to close it, if nothing happens for some time (the most probable outcome...).

**Comment by OliverJAsh** [comment]
Also see https://twitter.com/grumpyuxman/status/623181043714158592

**Comment by Calanthe** [comment]
We will probably remove sticky nav from mobile (at least horizontal view). The final decision is planned to be made tomorrow.

**Comment by paperboyo** [comment]
Hello.

Thanks all for participating! And for the work to make sticky situation less sticky! Some good discussion happened (I think), time to close.

Regards
Mateusz

**Comment by heralder99** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

heralder@naver.com 님께 보내신 메일 <Re: [frontend] Sticky situation hides almost all the content from me (#9843)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
