### ISSUE TITLE
IE 8: no JS (thus no ads, no images)

### ISSUE THREAD

**Issue by OliverJAsh** [guardian/frontend#9844]
Due to an error: https://app.getsentry.com/the-guardian/client-side-prod/group/55246354/

When debugging using IE11 emulation mode, you get a nicer error:

![image](https://cloud.githubusercontent.com/assets/921609/8773103/880da6bc-2ec9-11e5-9979-a02fc2f81259.png)

**Comment by NataliaLKB** [comment]
This is related to an issue that I am assigned to on Trello. Will pick up this task tomorrow!

**Comment by NataliaLKB** [comment]
The issue to why images weren't loading, and why ads aren't loading are slightly different. Closing this issue and I would suggest opening a different one that is ad specific.

**Comment by OliverJAsh** [comment]
@NataliaLKB So images are fixed by #10431, but ads are still broken? Do you know if it's because of this error? (Just so we can document in the issue)

**Comment by NataliaLKB** [comment]
@OliverJAsh it seems to be a deeper issue (but again haven't investigated quite deep enough to know why).

It seems that the config is undefined:

![image](https://cloud.githubusercontent.com/assets/8774970/9741432/5d94223e-5652-11e5-809f-48f8e5bd65d2.png)

![image](https://cloud.githubusercontent.com/assets/8774970/9741442/669a5fc4-5652-11e5-8c22-a2cb74860194.png)
