### ISSUE TITLE
Sticky ad never loads in less than 6s after page load on mobile (even on WiFi+broadband)

### ISSUE THREAD

**Issue by theefer** [guardian/frontend#9852]
The ad in the sticky slot under the nav never loads in less than 6s (often up to 10s, sometimes more) after the initial page load on my phone (Nexus 5 / Chrome), even on 4G or on broadband (via Wi-Fi) at home or in the office.

That means that the viewport is obstructed by an unexplained and empty grey slot for 6+ seconds.

![screenshot_2015-07-20-14-03-09](https://cloud.githubusercontent.com/assets/36964/8776398/af4b7136-2ee8-11e5-9f0f-3873cfd6185b.png)

Are there any metrics on how many people see the empty sicky ad slot vs the slot with an ad in it? And respectively how long for?

Intuitively, it doesn't seem to make sense to obstruct the user's viewport if they will scroll past the sticky ad before it loads anyway?

I know @OliverJAsh briefly investigated the loading sequence of the ad; it seems that anything that could speed it up would benefit viewability and make the current sticky ad slot less wasteful and confusing.

**Comment by theefer** [comment]
Would be good to reproduce and measure, even empirically, on a wider array of devices.

**Comment by ScottPainterGNM** [comment]
The ad slot for mobile has now been removed completely so this should no longer be an issue, huzzah!

**Comment by theefer** [comment]
\o/

**Comment by paperboyo** [comment]
\o/\o/
