### ISSUE TITLE
Sticky situation makes pinch to zoom unusable

### ISSUE THREAD

**Issue by OliverJAsh** [guardian/frontend#9875]
This happens when I scroll down:

![screenshot_2015-07-21-10-51-15](https://cloud.githubusercontent.com/assets/921609/8798149/1877210a-2f98-11e5-8e95-e5041e95044d.png)

**Comment by OliverJAsh** [comment]
Good example: this is completely unusable on mobile because you need to zoom in, but you can't: http://www.theguardian.com/technology/picture/2015/may/04/take-the-test-could-you-get-a-job-at-google

**Comment by ScottPainterGNM** [comment]
Having discussed with @stephanfowler - as we will reimplement mobile before it coming back on, this bug is closed for now but needs to be considered for when we revisit this.
