### ISSUE TITLE
Windows phone - /help/contact-us page sticky header - subsection dropdown does not collapse

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#9883]
Windows8 phone
When I scroll down on a page, the subsection dropdown on the sticky nav should collapse as it does on other phones, however it does not.
This messes with the positioning when you have a jump-to-text link in a page, also it means the dropdown uses more real estate than it should

**Comment by ScottPainterGNM** [comment]
Having discussed with @stephanfowler - as we will reimplement mobile before it coming back on, this bug is closed for now but needs to be considered for when we revisit this.
