### ISSUE TITLE
Discussion Abuse Reports: Indicate success or failure of submission to user

### ISSUE THREAD

**Issue by gidsg** [guardian/frontend#9898]
We had some reports from legal of abuse reports not being received, this may be because the success or failure of the submission is not indicated to the user, so the report may 'silently fail.'

Steps to reproduce
================
Go to: http://www.theguardian.com/science/grrlscientist/2012/aug/07/3#comment-56181127
Turn off Wifi/Ethernet
Click report abuse on a comment and submit form.

Actual Results
============
Dialog closes with no indication of success or failure to the user

Expected Results
=============
Indicate the success or failure of an abuse report, as per posting a comment:

![screen shot 2015-07-22 at 12 39 04](https://cloud.githubusercontent.com/assets/1764158/8825698/f031010c-3078-11e5-8371-e3823a0ce66b.png)

CC @guardian/discussion @JustinPinner @OliverJAsh

**Comment by JustinPinner** [comment]
@gidsg is this still an issue? @OliverJAsh referenced this issue in a PR merge in July.

**Comment by gidsg** [comment]
Yes, @JustinPinner this is still an issue, happy to discuss in person if that'd be easier.

**Comment by nicl** [comment]
@JustinPinner @gidsg yes, would be great to improve the UX here.

**Comment by ScottPainterGNM** [comment]
@gtrufitt This was the one I mentioned earlier if you do look at discussion soon, bug is still reproduceable

**Comment by NathanielBennett** [comment]
https://github.com/guardian/frontend/pull/13718
Done
