### ISSUE TITLE
Prevent Adblocker message from appearing when user whitelists theguardian.com

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#9899]
Raised a little while ago but just adding a formalised issue for you to pick up, as per the subject if a user has whitelisted our site then they shouldn't see the banner message but currently do.

@Calanthe @uplne

**Comment by ScottPainterGNM** [comment]
@jbreckmckye I know you were looking into adblock, is this still an issue or did you guys pick up?

**Comment by jbreckmckye** [comment]
@ScottPainterGNM - this shouldn't be happening any more; we made a change to stop Firefox AdblockPlus users getting false positives when whitelist as part of [this](https://github.com/guardian/frontend/pull/10152) pull request.

**Comment by ScottPainterGNM** [comment]
Awesome, I will shut this one down in that case.
