### ISSUE TITLE
Omniture events misfiring

### ISSUE THREAD

**Issue by OliverJAsh** [guardian/frontend#9901]
In our custom link calls we can see multiple instances of s.events being passed, where we would only have one passed normally.

Example
events:event37,event37,event37,event37,event37,event37,event51,event37,event37,event37,event51

This has inflated some of our stats, i.e. comment submissions (event51).

This was introduced by https://github.com/guardian/frontend/pull/9568, probably because we [no longer reset the event list](https://github.com/guardian/frontend/commit/bfdd7051d786cae36631185bb8de0648b3b6c6e6). I had to make this change because an event was being set in the Omniture vendor code, which we would have otherwise stripped accidentally.

/cc @mkopka

**Comment by mkopka** [comment]
Thanks all for sorting

On 23 July 2015 at 10:13, Oliver Joseph Ash <notifications@github.com>
wrote:

> Closed #9901 <https://github.com/guardian/frontend/issues/9901> via #9904
> <https://github.com/guardian/frontend/pull/9904>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/9901#event-363194981>.
>



-- 



Sent from Gmail Mobile

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396
