### ISSUE TITLE
Potential race condition in Firefox A/B tests

### ISSUE THREAD

**Issue by mattandrews** [guardian/frontend#9927]
Hello Guardian!

I've had this error for months and emailed about it back in the days when @guardian was my employer... think I've got a lead on it now.

At least half of the time when I load Guardian pages, I see things like this:

![screen shot 2015-07-24 at 2 44 36 pm](https://cloud.githubusercontent.com/assets/394376/8875617/6938deea-3212-11e5-8b80-ea2bbea90219.png)

... or on article pages, no comments display. A page refresh almost always fixes this.

Looking into that JS error, the (minified) source has this code on line `6:17802`:

`r=n.page.shouldHideAdverts;return(r?e.showForSensitive:!0)`

A bit of source searching suggests it's [this line](https://github.com/guardian/frontend/blob/3a178b1cc8fd1753b756ba82773d170f82aa9e75/static/src/javascripts/projects/common/modules/experiments/ab.js#L112) in `ab.js`. The error, in short, translates that `config` is undefined.

Not sure why this would happen but it's been consistently happening for me on desktop Firefox across at least three different machines/installs of Firefox (v39 at the time of writing).

Could someone have a look at this? Thanks!

**Comment by OliverJAsh** [comment]
Hey @mattandrews! :smile:

No images appear to be loading either?

Can you check if `window.guardian.config` exists?

**Comment by jennysivapalan** [comment]
@mattandrews :wave:

**Comment by mattandrews** [comment]
Hi! Just managed to reproduce it (it's sporadic) and on a page where comments didn't load, `window.guardian.config` is defined (and has the `page.shouldHideAdverts` flag):

![screen shot 2015-07-27 at 11 16 08 am](https://cloud.githubusercontent.com/assets/394376/8903541/be60282a-3450-11e5-9cf7-ae18c01c981e.png)

When I reload the page comments appear and it's fine, although I did get a 404 for [this JSON file](https://api.nextgen.guardianapps.co.uk/most-read-null.json) being called from [this article](http://www.theguardian.com/education/2015/jul/27/my-aspergers-makes-living-with-other-students-a-struggle).

**Comment by OliverJAsh** [comment]
Strange, it looks like your config is set but Firefox can't read it for some reason.

**Comment by mattandrews** [comment]
Seeing this more frequently now :( still the same error.

**Comment by mattandrews** [comment]
... one thing which sounds weird but testing, seems to be reproducable: it only seems to happen when I open things in new tabs (either from bookmarks or Cmd+clicking a link). Could this be a thing?!

**Comment by paperboyo** [comment]
Reproduced on 41.0b8 on Win 10:

![new-tab_1](https://cloud.githubusercontent.com/assets/6032869/9786651/a753c034-57b3-11e5-8a54-48277bd0a5fc.gif)

**Comment by paperboyo** [comment]
Can’t reproduce any more. Possibly fixed by #10829? Safe to close?

**Comment by mattandrews** [comment]
Yes! All fixed – thanks very much all.
