### ISSUE TITLE
Supporting membership event clearing rest of content and not interactive

### ISSUE THREAD

**Issue by rcrphillips** [guardian/frontend#9930]
http://www.theguardian.com/politics/2015/jul/24/did-you-hear-the-one-about-jeremy-corbyn-twitter-corbynjokes

Also, the links in the element are not working.

Apols if this is for the Membership team?

<img width="905" alt="screen shot 2015-07-24 at 17 13 13" src="https://cloud.githubusercontent.com/assets/2051501/8879126/5035fa80-3227-11e5-8c26-44528f26ce93.png">

**Comment by OliverJAsh** [comment]
Is this an embedded piece of content?

**Comment by OliverJAsh** [comment]
Could be one for @uplne or @Calanthe.

**Comment by davidrapson** [comment]
@OliverJAsh The Membership event embed comes from us, but it looks like this is more down to the tweets not clearing:

![screen shot 2015-07-24 at 17 18 58](https://cloud.githubusercontent.com/assets/123386/8902836/a4c79ef2-344b-11e5-8f00-cba89809784b.png)

**Comment by OliverJAsh** [comment]
If I add clearing to it using DevTools, it doesn't fix the problem.

On Mon, 27 Jul 2015 at 10:39 David Rapson <notifications@github.com> wrote:

> @OliverJAsh <https://github.com/OliverJAsh> The Membership event embed
> comes from us, but it looks like this is more down to the tweets not
> clearing:
>
> [image: screen shot 2015-07-24 at 17 18 58]
> <https://cloud.githubusercontent.com/assets/123386/8902836/a4c79ef2-344b-11e5-8f00-cba89809784b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/9930#issuecomment-125146910>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by ScottPainterGNM** [comment]
@uplne @Calanthe - is this a commercial job or one for sustain?

**Comment by davidrapson** [comment]
@ScottPainterGNM I'll pick this one up, save it sitting stale.

**Comment by ScottPainterGNM** [comment]
Cheers @davidrapson - you get a :gem: !

**Comment by davidrapson** [comment]
Had a bit of a look into this. In the reported case the embed has been removed ,however we are planning on removing that particular embed completely as in practice we are using a different and preferred embed via merchandising components. So I'm going to close this issue as the embed itself it going soon. Hope that made some sense.
