### ISSUE TITLE
Banner ads on us front are displayed in front of dropdown lists - dfp-ad--top shows z-index of 1010

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#9936]
Banner ads on us front are getting z-index of 1010 on mobile chrome. as a result they are showing in front of dropdown lists.
Seen on multiple ads on android devices.
Reproduceable on desktop browser if you shrink window to mobile breakpoint and select US front from edition selector.

Debugger shows
banner ad itself shows z-index of 1 but dfp-ad--top shows z-index of 1010

![image](https://cloud.githubusercontent.com/assets/7239344/8904365/ab8efb6c-3456-11e5-9183-2e1000715bbe.png)

**Comment by uplne** [comment]
Fixed by https://github.com/guardian/frontend/pull/10017
