### ISSUE TITLE
Sticky nav breaks page down

### ISSUE THREAD

**Issue by OliverJAsh** [guardian/frontend#9937]
The sticky nav obscures the content at the top of the page.

See video supplied by user in https://groups.google.com/a/guardian.co.uk/d/msg/dotcom.feedback/jAqPTPEx7R4/M4eKQRXvFLgJ.

**Comment by OliverJAsh** [comment]
We've had two complaints about this now.

**Comment by ScottPainterGNM** [comment]
And more today
