### ISSUE TITLE
Frustrating scrolling behaviour with fast click on fronts

### ISSUE THREAD

**Issue by alastairjardine** [guardian/frontend#9947]
When strolling a front on an iPad, it's really easy to accidentally click to go into an article. The problem is particularly annoying if a *flick*–*scroll*–*tap-to-stop* action is performed, as Fast Click (http://labs.ft.com/2011/08/fastclick-native-like-tapping-for-touch-apps/) interprets the *tap-to-stop* as a click on an article, which it isn't.

Please consider switching off Fast Click on fronts (https://github.com/guardian/frontend/blob/8053d50a1bb4287625d5d139139ad1452c445677/static/src/javascripts/bootstraps/common.js#L106)

Very happy to demo. I could even video the frustration when I enter an unexpected article for the 4th time over my morning granola.

**Comment by rich-nguyen** [comment]
Thanks @alastairjardine, I agree wholeheartedly with the diagnosis and the proposed fix.

**Comment by alastairjardine** [comment]
Thanks @rich-nguyen. It would make for a much less frustrating experience.

**Comment by kaelig** [comment]
FYI, I experienced the same thing with videos on front on my iPhone, even before FastClick was implemented. Videos would start playing while I was scrolling down the homepage.

**Comment by alastairjardine** [comment]
First person to fix this gets my homemade granola recipe.

**Comment by OliverJAsh** [comment]
> Videos would start playing while I was scrolling down the homepage.

Hmm, sounds like a separate issue from Fast Click.

**Comment by kaelig** [comment]
I don't know, the video player itself captures touch / click events if I recall correctly.

**Comment by OliverJAsh** [comment]
The issue described by @alastairjardine sounds like https://github.com/ftlabs/fastclick/issues/178, or a variety of it.

I like having it, so I might try and debug the problem.

**Comment by alastairjardine** [comment]
@OliverJAsh What functionality does fast click give us? (sorry, n00b question)

**Comment by OliverJAsh** [comment]
> ... [in some mobile browsers, i.e. iOS, there is a] 300ms delay between a tap and the firing of a click event, which can make your apps feel laggy and unresponsive even when it’s not technically so.

> The technique we use to get around this problem is to track all TouchStart events in our app and fire a click event as soon as we receive a TouchEnd event (unless some application-specific exception is satisfied).

http://labs.ft.com/articles/ft-fastclick/

We aim to respond to all user interactions in 100ms (for cognitive reasons)

**Comment by alastairjardine** [comment]
@OliverJAsh Thanks – makes sense. Shame about the bugginess :/

**Comment by OliverJAsh** [comment]
I might be able to configure it to be less sensitive.

**Comment by alastairjardine** [comment]
@OliverJAsh Can you spin up a branch without FastClick to test the delay theory? Would like to experience it first hand

**Comment by OliverJAsh** [comment]
Try going to a website that doesn't use FastClick (or there own solution),
i.e. Google.

On Thu, 30 Jul 2015 at 12:12 Alastair Jardine <notifications@github.com>
wrote:

> @OliverJAsh <https://github.com/OliverJAsh> Can you spin up a branch
> without FastClick to test the delay theory? Would like to experience it
> first hand
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/9947#issuecomment-126275677>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by alastairjardine** [comment]
Seems fine to me… (iPhone 6)

**Comment by rich-nguyen** [comment]
I think a good balanced solution here is to keep fastclick for internal page interactions, eg. open nav, expand container, but prevent fastclick from interfering with `<a>` links.

**Comment by OliverJAsh** [comment]
Think I agree @rich-nguyen, but might require a fork. Even better if we could keep Fast Click for all types of interaction but just make it less sensitive.

**Comment by piuccio** [comment]
Maybe [needsclick](https://github.com/ftlabs/fastclick#ignore-certain-elements-with-needsclick) is the solution.

**Comment by OliverJAsh** [comment]
This is actually a well known issue: https://github.com/ftlabs/fastclick/issues/227

**Comment by OliverJAsh** [comment]
I came up with a workaround: https://github.com/ftlabs/fastclick/issues/227#issuecomment-127676180

I think this won't have much of a performance hit on the scroll event. Safari Dev Tools don't expose detailed frame information like Chrome’s DevTools do, so I can't speak specifically for that. We have a bit of a crashing problem on iPads right now, so I'm slightly hesitant to add more (especially iOS specific) JS. Will revisit once we hopefully solving the crashing.

**Comment by piuccio** [comment]
How about removing fastclick?

https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away?hl=en
The 300ms delay is gone in Chrome and Firefox and it can be removed in IE with CSS. As for IOS, well maybe it's better a click delay than horrible gesture experience.

It's also bites and JS execution saved.

**Comment by OliverJAsh** [comment]
@piuccio That would mean the interaction time going from 0ms to 300ms for iOS users. We aim to keep it under 100ms. But I like the idea of removing JS… :smile:

**Comment by alastairjardine** [comment]
@OliverJAsh @piuccio I've never 'felt' that as a user, so I wouldn't worry too much. Certainly test it.

**Comment by piuccio** [comment]
I think it's enough if the trail reacts on tap. If you highlight the touch target in <100ms it doesn't matter if the click happens in 300ms

**Comment by OliverJAsh** [comment]
Here's an example if you want to compare the difference:
http://ftlabs.github.io/fastclick/examples/layer.html. I'm just quoting
user research: https://youtu.be/CceyqktMoRw?t=13m9s

Unfortunately we don't provide any feedback when the user taps:
https://github.com/guardian/frontend/issues/9960. If we did have feedback
on tap, you would still need FastClick to emit the "click" event instantly,
in order for the feedback to appear.

On Wed, 5 Aug 2015 at 16:15 Alastair Jardine <notifications@github.com>
wrote:

> @OliverJAsh <https://github.com/OliverJAsh> @piuccio
> <https://github.com/piuccio> I've never 'felt' that as a user, so I
> wouldn't worry too much. Certainly test it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/9947#issuecomment-128033240>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by piuccio** [comment]
feedback should be on `pointerdown` or `mousedown` or whatever.
For instance, material design button start the ripple effect when you touch it, not when you click http://www.google.com/design/spec/components/buttons.html

**Comment by OliverJAsh** [comment]
@piuccio Good point, see #10046
