### ISSUE TITLE
Sticky nav breaks live blog block anchor links

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#9963]
In a liveblog, select one of the key events to jump to that location.
Result:
You are taken to that location, but scroll is not offset to allow for sticky nav, so title of key event block is hidden beneath sticky-nav

This is similar to #9776 - probably a manifestation of the same issue that we missed first time around. Hopefully it can be fixed by a similar change to that made in #9867 

![image](https://cloud.githubusercontent.com/assets/7239344/8956113/9f9659c8-35ea-11e5-985c-b3b5752d7184.png)

**Comment by OliverJAsh** [comment]
Related to https://github.com/guardian/frontend/issues/9776

**Comment by ScottPainterGNM** [comment]
Related issues #9917 - same behaviour when scrolling up on a live blog and the top of the key events are obscured.
