### ISSUE TITLE
Sticky Nav - When adblock is on the page jumps

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#9967]
Just to make sure this issue is documented but when adblocker is switched on the scroll animation jumps considerably when you scroll down the page on all browsers.

This is causing numerous complaints from users.

**Comment by paperboyo** [comment]
Duplicate of https://github.com/guardian/frontend/issues/9841 (there is a GIF there).

There is another bug with adblocking/privacy extensions active, though. Scroll down the page, reload and scroll to the top to see a huge empty space just below the navigation like so:

![przechwytywanie](https://cloud.githubusercontent.com/assets/6032869/8980437/f0483f46-36b0-11e5-9a11-c1671f9c03d1.PNG)

**Comment by ScottPainterGNM** [comment]
@paperboyo true, will close this one down. Could you raise a separate issue for the one you've reported above please?

**Comment by paperboyo** [comment]
Thanks, @ScottPainterGNM. Done in https://github.com/guardian/frontend/issues/9990.

**Comment by OliverJAsh** [comment]
This looks like it's still an issue, re. #10025? /cc @ScottPainterGNM

**Comment by ScottPainterGNM** [comment]
I closed this down as it was already raised in #9841 so didn't want to duplicate bugs, Zofia was going to fix that but referencing that issue number rather than this one.

**Comment by OliverJAsh** [comment]
Ah, didn't see that, thanks!
