### ISSUE TITLE
Search - not working in Safari

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#9968]
A user has pointed this out but the Search button isn't functioning in Safari

![image](https://cloud.githubusercontent.com/assets/11922253/8979355/f56852c8-36a0-11e5-8226-aed57f6087a3.png)

**Comment by jennysivapalan** [comment]
I've just tried this out and it works fine for me on Safari (on desktop). Has anyone else reported it or do we have more details of where this isn't working (e.g. mobile)?
![screen shot 2015-08-03 at 16 37 04](https://cloud.githubusercontent.com/assets/944375/9041084/065101d8-39fe-11e5-8166-fbcc316dedf9.png)

**Comment by paperboyo** [comment]
Maybe the original reporter wasn't patient enough? Our site search requires the patience of up to 30 seconds at times :smile:

**Comment by ScottPainterGNM** [comment]
Hmm this does seem to be working pretty speedily now, when I replicated before it just sat as a white box for a while (maybe though not even 30 seconds)....I blame the internet generation. 

Closing off anyway
