### ISSUE TITLE
Football - Tabbed Navigation Missing

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#9974]
On football pages there should be tabbed navigation across the tops of live blogs and articles, this is currently absent across all football pages (old and new).

**Comment by ScottPainterGNM** [comment]
Old example of what the tabs looked like before:

![screen shot 2015-07-30 at 11 49 24](https://cloud.githubusercontent.com/assets/11922253/8981533/0ee6a2ee-36b1-11e5-93c1-f5559276cca4.png)

**Comment by jennysivapalan** [comment]
I've been getting my head full of Javascript, Akka agents and football.

There are a couple rules for getting this information to load:
- Both teams have to be tagged with with a pa-football-team reference in the Content API. The above example meets that criteria but a few games I was testing with locally don't match this condition.
- We fetch competitions from PA and filter out to competitions a subset listed here:
https://github.com/guardian/frontend/blob/master/sport/app/football/feed/Competitions.scala#L100-L123
- When calling to get a refresh of competition results to PA we have to send through a start date. This start date for initial call is 30 days ago. Once we have the competition date in memory we use the start date of the competition. Most competitions have been updated to the new season (e.g. Premier league starts 1st August). The above example would never be fetched as it was more than 30 days ago and is not in the current season being returned. 

Essentially this issue will occur during the off-season, we could extend the days ago to 90 days to cover the gap or do something more clever around fetching the previous season if the current season has no results.

**Comment by jennysivapalan** [comment]
@ScottPainterGNM Just checked the game over the weekend and all the navigation tab showed. 
http://www.theguardian.com/football/2015/aug/02/community-shield-arsenal-chelsea-oxlade-chamberlain

![screen shot 2015-08-03 at 10 50 25](https://cloud.githubusercontent.com/assets/944375/9035171/795fa318-39cd-11e5-8ee7-54832bc77a16.png)


I think for now we can close this but should let the editorial team about the rules for showing the tabbed nav and stats?

**Comment by jennysivapalan** [comment]
Closing as confirmed with football editorial team that data is showing up fine.
