### ISSUE TITLE
Football - Incorrect Match Stats Displaying

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#9977]
On the football pages (live and match reports) there have been reports that the possession match stats that are provided aren't being displayed and just show 50% / 50% between the two teams as this is the default. 

For this URL the match stats were reported as showing the above issue but we are receiving a data feed through:

http://www.theguardian.com/football/2015/jun/06/barcelona-juventus-luis-suarez
http://www.theguardian.com/football/live/2015/jun/06/juventus-v-barcelona-champions-league-final-2015-live

Data - http://www.uefa.com/uefachampionsleague/season=2015/matches/round=2000552/match=2015227/postmatch/report/index.html

**Comment by jennysivapalan** [comment]
@ScottPainterGNM Similar to https://github.com/guardian/frontend/issues/9978 I haven't seen this issue. I've only looked post match though and not during a game. Just to clarify we don't get the data from the link posted in the issue, we get the data from PA.

**Comment by jennysivapalan** [comment]
Closing as confirmed with football editorial team that data is showing up fine.
