### ISSUE TITLE
Football - Default Match Data Displaying

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#9978]
When we don't receive a data feed for certain information (Lingua 1 for example only provides scores) we should only display what is received. In the example of possession the default displays 50% / 50% but this shouldn't be displayed at all if no data received.

http://www.theguardian.com/football/2015/apr/05/marseille-psg-ligue-1-match-report

**Comment by ScottPainterGNM** [comment]
Related issue #9977

**Comment by jennysivapalan** [comment]
@ScottPainterGNM I've checked over a few games over the weekend and have not seen this issue. Either we show the stats or not at all (based on the rules https://github.com/guardian/frontend/issues/9974#issuecomment-126729628)

**Comment by jennysivapalan** [comment]
Closing as confirmed with football editorial team that data is showing up fine.
