### ISSUE TITLE
Sticky nav breaks live blog block anchor links

### ISSUE THREAD

**Issue by Jholder112233** [guardian/frontend#9988]
For example: http://www.theguardian.com/sport/live/2015/jul/30/ashes-2015-england-v-australia-third-test-day-two-live#block-55ba45b8e4b03fc4744e11cc

![screen shot 2015-07-30 at 17 19 27](https://cloud.githubusercontent.com/assets/2236852/8988624/29395f96-36df-11e5-8cc5-66dbdcb66ecf.png)

**Comment by OliverJAsh** [comment]
Thanks!

**Comment by OliverJAsh** [comment]
Making a mess, sorry. This is a duplicate of #9963.
