### ISSUE TITLE
Sticky nav breaks comment anchor links

### ISSUE THREAD

**Issue by Jholder112233** [guardian/frontend#9989]
For example, individual comment links: http://www.theguardian.com/business/blog/live/2015/jul/30/uk-job-losses-dominate-bumper-results-day-shell-centrica-live#comment-56656031

And just linking directly to the comments: http://www.theguardian.com/football/2015/jul/30/mls-all-stars-tottenham-hotspur-match-report#comments

![screen shot 2015-07-30 at 17 14 04](https://cloud.githubusercontent.com/assets/2236852/8988658/5d461356-36df-11e5-8f87-9dc5e4b45c90.png)

**Comment by OliverJAsh** [comment]
Duplicate of #9963

**Comment by Jholder112233** [comment]
This doesn't feel like a duplicate to #9963?
