### ISSUE TITLE
Sticky nav leaves huge white space under main nav with ad blockers active

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#9990]
Hello,

Multiple OSes/browsers. Tested with AdBlock Plus. Steps:

1. Scroll down the page.
2. Reload.
3. Scroll to the top.

There is a huge block of white empty space below the main navigation, like so:

![przechwytywanie](https://cloud.githubusercontent.com/assets/6032869/8996249/d90948be-3716-11e5-905d-8f4bdfd374a4.PNG)

Regards
Mateusz

**Comment by Calanthe** [comment]
I can't reproduce it now. @paperboyo can you reproduce it?

**Comment by paperboyo** [comment]
Hi, @Calanthe! Yes, I can. Chrome 44 on Win 7, AdBlock Plus default install. But I've encountered it on different browsers/OSes as well. This is easiest to repro if you soft-refresh when the page is scrolled down to almost the very bottom. And then, scroll up after the refresh is done.

**Comment by Calanthe** [comment]
This has been fixed.
