### ISSUE TITLE
Ad and rich link conflicting

### ISSUE THREAD

**Issue by OliverJAsh** [guardian/frontend#9991]
Is this a bug in Spacefinder or something in commercial? @uplne @mattosborn 

![image1](https://cloud.githubusercontent.com/assets/921609/9004364/46e320ca-376d-11e5-941d-1a1206bd43bc.PNG)

**Comment by mattosborn** [comment]
Not sure why this would be happening. Either it is a bug with spacefinder or possibly both modules are searching for space before the other has inserted anything, so spacefinder is returning the same paragraph to both of them. If that's the case insertion should be done synchronously or there should be a blocking mechanism until it is complete.

**Comment by rich-nguyen** [comment]
I cannot reproduce. Feel free to reopen if you can repro it.
