### ISSUE TITLE
Microsoft Edge Browser does not serve Guardian Fonts

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#9992]
The new Microsoft Browser being shipped with Windows 10 is currently not displaying the Guardian fonts on the site, the version of IE being shipped with it does however do so.

**Comment by OliverJAsh** [comment]
;o

**Comment by ScottPainterGNM** [comment]
Microsofttttt!!!! *shakes fist*

**Comment by paperboyo** [comment]
:-( Told them half a year ago... I'm surprised only IE11 got fixed... 

http://answers.microsoft.com/en-us/insider/forum/insider_internet-insider_ie/fonts-embedded-as-data-uri-do-not-display-in-ie11/a6fa26a8-2e83-4347-a192-94c80973d63d?auth=1

**Comment by OliverJAsh** [comment]
Is it just our fonts or all web fonts? If it is just ours, what's special about our fonts?

**Comment by paperboyo** [comment]
When I first encountered it, both IE11 and Spartan (later Edge) wouldn't display any webfonts embedded as data URIs (eg. https://robert.accettura.com/wp-content/uploads/2009/07/embedded-font-face.html). I have no way of checking it at the moment...

**Comment by ScottPainterGNM** [comment]
We have a Windows 10 box built next to me if you want to have a play, weird to only fix IE11 though

**Comment by paperboyo** [comment]
Unfortunately, I'm on holidays currently playing in http://www.polin.pl/en (great!):

![mk2](https://cloud.githubusercontent.com/assets/6032869/9035224/4af87d0c-39d6-11e5-9814-e6c8fde234c1.jpg)

Back in two weeks... :sunglasses:

**Comment by ScottPainterGNM** [comment]
@sndrs This was the GitHub issue raised for Edge fonts

**Comment by paperboyo** [comment]
Unfortunately, the fonts are not working in Edge. See https://github.com/guardian/frontend/pull/10395#issuecomment-153706458. Reopen?

**Comment by OliverJAsh** [comment]
This is still an issue? Raised by @theefer

![image](https://cloud.githubusercontent.com/assets/921609/13078725/a08bcb84-d4b8-11e5-976b-2367ed80a607.png)

**Comment by paperboyo** [comment]
> This is still an issue?

Yep. Many machines, many Edges. If our Win10 testing is on RTM - easy to see. Thanks for reopening!

**Comment by rich-nguyen** [comment]
Yeah, let's sniff the sniffing, and see what's sniffing.
